'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.SHUTTLE_PLAYWRIGHT_PATH||'playwright'),Model=require('../src/model');
const base=path.resolve(__dirname,'..'),qa=path.join(base,'qa'),url=pathToFileURL(path.resolve(base,'../셔틀_실행.html')).href,checks=[],errors=[],requests=[];let browser,page;
async function test(name,fn){try{await fn();checks.push(name);console.log('PASS '+name);}catch(e){console.error('FAIL '+name);throw e;}}
async function tab(name,p=page){await p.locator('[data-tab="'+name+'"]').click();}
async function field(id,value,p=page){await p.locator('#'+id).evaluate(el=>{const d=el.closest('details');if(d)d.open=true;});await p.locator('#'+id).fill(String(value));}
async function download(id,p=page){const event=p.waitForEvent('download');await p.locator('#'+id).click();const d=await event,stream=await d.createReadStream(),parts=[];for await(const chunk of stream)parts.push(chunk);return Buffer.concat(parts).toString('utf8');}
async function applyConfig(c,p=page){const name=c.name+' QA '+Date.now();c={...c,name};await p.locator('#projectFile').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(Model.pack(c)))});await p.waitForFunction(name=>document.getElementById('projectSummary').textContent.startsWith(name)&&document.body.dataset.dirty==='false',name);return c;}
async function range(id,value,p=page,event='change'){await p.locator('#'+id).evaluate((el,{value,event})=>{el.value=value;el.dispatchEvent(new Event(event,{bubbles:true}));},{value:String(value),event});}
async function finish(p=page){await p.locator('#simFinish').click();await p.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'));await p.waitForFunction(()=>!document.getElementById('simFinish').disabled);}
async function snapshot(p=page){return p.evaluate(()=>window.__shuttleScene.engine.snapshot());}
async function instrument(p){await p.evaluate(()=>{const Original=ShuttleScene.Scene;ShuttleScene.Scene=class extends Original{constructor(...args){super(...args);window.__shuttleScene=this;}};});}
(async()=>{
browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1600,height:1050},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(url);await instrument(page);
await test('offline opening, four KPIs and Worker ready',async()=>{await page.waitForFunction(()=>document.getElementById('runtime').textContent.includes('Worker OK'));assert.equal(await page.locator('#analysisKpis .kpi').count(),4);assert.equal(await page.locator('#error').isVisible(),false);await page.screenshot({path:path.join(qa,'01_overview.png')});});
let original=await page.locator('#analysisKpis').textContent();
await test('distance and speed display conversion preserves SI calculations',async()=>{await page.locator('#distanceUnit').selectOption('mm');await page.locator('#speedUnit').selectOption('m/s');assert.equal(await page.locator('#bayPitch').inputValue(),'1400');assert.equal(await page.locator('#xLoadedV').inputValue(),'2');await page.locator('#calculate').click();assert.equal(await page.locator('#analysisKpis').textContent(),original);const doc=JSON.parse(await download('saveProject'));assert.equal(doc.config.bayPitch,1.4);assert.equal(doc.config.xLoadedV,2);});
await test('field help displays description and converted ranges',async()=>{await page.locator('[data-help="bayPitch"]').click();assert.ok((await page.locator('#helpDialog').textContent()).includes('mm'));await page.locator('#helpDialog button').click();});
await test('layer count resizes editable layer rows',async()=>{await field('levels',5);await page.locator('#levels').dispatchEvent('change');await tab('layout');assert.equal(await page.locator('#layersEditor tbody tr').count(),5);await page.locator('#calculate').click();assert.ok((await page.locator('#projectSummary').textContent()).includes('5층'));});
await test('overweight validation and dirty-state execution guard',async()=>{await field('cargoMass',2500);await page.locator('#calculate').click();assert.ok((await page.locator('#error').textContent()).includes('정격'));assert.equal(await page.locator('body').getAttribute('data-dirty'),'true');await tab('simulation');assert.equal(await page.locator('#simPlay').evaluate(el=>getComputedStyle(el).pointerEvents),'none');await page.locator('#simPlay').evaluate(el=>el.click());assert.ok((await page.locator('#toast').textContent()).includes('설정 적용'));await applyConfig(Model.preset('default'));});
await test('JSON import resets to verified project and rejects unrelated schema',async()=>{await page.locator('#projectFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":"wrong"}')});await page.waitForFunction(()=>!document.getElementById('error').hidden);assert.ok((await page.locator('#error').textContent()).includes('프로젝트'));await applyConfig(Model.preset('default'));});
await test('Three.js renders four rack tiers, shuttle actors and independent lift',async()=>{await tab('simulation');await page.waitForFunction(()=>window.__shuttleScene?.engine&&!window.__shuttleScene.fallback);const r=await page.evaluate(()=>({renderer:document.getElementById('simScene').dataset.renderer,levels:__shuttleScene.levels.length,actors:__shuttleScene.actors.size,stocks:__shuttleScene.stock.map(s=>s.rows.length)}));assert.equal(r.renderer,'webgl');assert.equal(r.levels,4);assert.equal(r.actors,5);assert.deepEqual(r.stocks,[120,120,120,120]);await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'02_all_floors.png')});});
await test('floor filter changes rack and shuttle visibility; actor selector changes floor',async()=>{await page.locator('#sceneLevel').selectOption('1');await page.waitForFunction(()=>__shuttleScene.actors.get('S1-1').body.visible===false);assert.deepEqual(await page.evaluate(()=>__shuttleScene.levels.map(f=>f.group.visible)),[false,true,false,false]);await page.locator('#sceneActor').selectOption('S3-1');assert.equal(await page.locator('#sceneLevel').inputValue(),'2');await page.waitForFunction(()=>__shuttleScene.actors.get('S3-1').body.visible);});
await test('top/front/isometric controls and label toggle',async()=>{for(const [id,mode]of [['viewTop','top'],['viewFront','front'],['viewIso','iso']]){await page.locator('#'+id).click();assert.equal(await page.evaluate(()=>__shuttleScene.mode),mode);}await page.locator('#sceneLabels').uncheck();await page.waitForFunction(()=>__shuttleScene.labels.every(l=>!l.visible));await page.locator('#sceneLabels').check();});
await test('click picks actual shuttle body in plan view',async()=>{await page.locator('#sceneLevel').selectOption('0');await page.locator('#sceneActor').selectOption('L1');await page.locator('#viewTop').click();await page.locator('#simScene canvas').scrollIntoViewIfNeeded();await page.waitForTimeout(180);const pos=await page.evaluate(()=>{const s=__shuttleScene,m=s.actors.get('S1-1'),r=s.renderer.domElement.getBoundingClientRect(),p=m.body.position.clone().add(new THREE.Vector3(0,.15,0)).project(s.camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};});await page.mouse.click(pos.x,pos.y);assert.equal(await page.locator('#sceneActor').inputValue(),'S1-1');});
await test('next event advances DES and continuous 3D pose matches every actor',async()=>{await page.locator('#simStep').click();assert.ok((await snapshot()).time>0);await range('simSeek',200);await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>__shuttleScene.engine.actors.every(a=>{const p=__shuttleScene.engine.actorPose(a),b=__shuttleScene.actors.get(a.id).body.position;return Math.hypot(p.x-b.x,p.y-b.y,p.z-b.z)<1e-7;})));});
await test('stock instances match stored TU except active transfer cargo',async()=>{assert.ok(await page.evaluate(()=>{const s=__shuttleScene,handling=new Set(s.engine.actors.map(a=>s.engine.actorPose(a)).filter(p=>['store','retrieve'].includes(p.phase?.action?.kind)).map(p=>p.tu));return s.stock.every(stock=>stock.rows.every((row,i)=>stock.shown[i]===(s.engine.slotById.get(row.id).tu&&!handling.has(s.engine.slotById.get(row.id).tu)?s.engine.slotById.get(row.id).tu:null)));}));});
await test('lift focus follows vertical movement in three dimensions',async()=>{await page.locator('#simReset').click();await page.locator('#sceneLevel').selectOption('all');await page.locator('#sceneActor').selectOption('L1');await page.locator('#sceneFollow').check();const before=await page.evaluate(()=>__shuttleScene.controls.target.y);await page.locator('#simStep').click();const seek=await page.evaluate(()=>{const s=__shuttleScene,e=s.engine,p=e.lifts[0].current,m=p.phases.find(p=>p.axis==='y'&&p.profile);return Math.round((p.start+m.start+m.duration*.5)/e.horizon*1000);});await range('simSeek',seek);await page.waitForTimeout(200);const state=await page.evaluate(()=>({pose:__shuttleScene.engine.actorPose(__shuttleScene.engine.lifts[0]),y:__shuttleScene.controls.target.y}));assert.ok(state.pose.y>0&&state.y>before);await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'03_lift_follow.png')});await page.locator('#sceneFollow').uncheck();});
await test('play/pause advances simulation and stops on request',async()=>{await page.locator('#simSpeed').selectOption('1');const t=(await snapshot()).time;await page.locator('#simPlay').click();await page.waitForTimeout(400);await page.locator('#simPlay').click();const stopped=(await snapshot()).time;assert.ok(stopped>t);await page.waitForTimeout(120);assert.equal((await snapshot()).time,stopped);});
await test('finish, per-layer metrics, finite buffers and conservation',async()=>{await finish();const s=await snapshot();assert.equal(s.complete,true);assert.equal(s.conserved,true);assert.equal(s.throughput,252);assert.equal(await page.locator('#observedLayers tbody tr').count(),4);assert.ok((await page.locator('#conservation').textContent()).includes('✓ 정상'));assert.ok(await page.evaluate(()=>__shuttleScene.engine.calendar.audit()));await page.locator('#sceneLevel').selectOption('0');await page.locator('#viewIso').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'04_floor_detail.png')});});
let finalLogs;
await test('completed job CSV records one row per actual completion',async()=>{finalLogs=await download('exportJobs');assert.ok(finalLogs.includes('measurement_window'));assert.equal(finalLogs.trim().split('\n').length-1,(await snapshot()).completedIn+(await snapshot()).completedOut);fs.writeFileSync(path.join(qa,'browser-completed-jobs.csv'),finalLogs);});
await test('seeking backward then recompleting reproduces all completion records',async()=>{await range('simSeek',100);assert.equal((await snapshot()).complete,false);await finish();assert.equal(await download('exportJobs'),finalLogs);});
await test('motion DC includes X/Z graphs and animated coordinate marker',async()=>{await tab('motion');await page.locator('#motionType').selectOption('dual');await field('motionAisle',1);await field('motionOutAisle',3);await page.locator('#applyMotion').click();assert.ok((await page.locator('#motionDescription').textContent()).includes('DUAL'));for(const id of ['speedGraph','positionGraph','accelGraph'])assert.equal(await page.locator('#'+id+' svg').count(),1);const text=await page.locator('#motionValues').textContent();await range('motionSeek',500,page,'input');assert.notEqual(await page.locator('#motionValues').textContent(),text);await page.locator('[data-panel="motion"] .card').first().screenshot({path:path.join(qa,'05_motion.png')});});
await test('markdown exports full SI input and observed result',async()=>{const md=await download('exportReport');assert.ok(md.includes('shuttle-4way/project@1')&&md.includes('관측 입고'));fs.writeFileSync(path.join(qa,'browser-report.md'),md);});
await test('print report popup includes metadata and analysis/observed sections',async()=>{await page.locator('#pdfReport').click();await field('documentNo','SH-QA-001');await field('author','검증 담당');const event=page.waitForEvent('popup');await page.locator('#pdfForm button[type="submit"]').click();const popup=await event;await popup.waitForLoadState();assert.ok((await popup.locator('body').textContent()).includes('SH-QA-001'));assert.ok(await popup.locator('#printPdf').isVisible());assert.ok((await popup.locator('h2').count())>=6);await popup.screenshot({path:path.join(qa,'06_report_preview.png'),fullPage:true});await popup.close();});
await test('Worker combination experiment runs 12 common-seed trials',async()=>{await tab('experiments');await field('shuttleMax',2);await field('liftMax',2);await page.locator('#repCount').selectOption('3');await page.locator('#runExperiments').click();await page.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('12회 완료'),null,{timeout:60000});const data=JSON.parse(await download('exportExperiments'));assert.equal(data.runs.length,12);assert.ok(data.runs.every(r=>r.conserved&&r.reservationOK));for(const n of [1,2,3])assert.equal(new Set(data.runs.filter(r=>r.repetition===n).map(r=>r.seed)).size,1);fs.writeFileSync(path.join(qa,'browser-experiment.json'),JSON.stringify(data,null,2));await page.locator('[data-panel="experiments"]').screenshot({path:path.join(qa,'07_experiments.png')});});
await test('experiment cancel releases interface and preserves completed trials',async()=>{await field('shuttleMax',6);await field('liftMax',4);await page.locator('#repCount').selectOption('5');await page.locator('#runExperiments').click();await page.locator('#cancelExperiments').click();assert.equal(await page.locator('#runExperiments').isEnabled(),true);assert.ok((await page.locator('#experimentStatus').textContent()).includes('중단'));});
await test('demand skew visibly leaves top-floor shortfall',async()=>{await applyConfig(Model.preset('skew'));await tab('simulation');await finish();const s=await snapshot();assert.ok(s.floors[3].inbound<120||s.floors[3].outbound<120);assert.ok((await page.locator('#observedLayers').textContent()).includes('F4'));});
await test('blocked output scenario respects two-place buffer and 60/h takeaway',async()=>{await applyConfig(Model.preset('blocked'));await finish();const s=await snapshot();assert.ok(s.output.max<=2);assert.ok(s.shippingRate<=62);assert.ok(s.backlog>0);assert.equal(s.conserved,true);});
await test('TOTE and BOX presets apply dimensions, speeds and ratings',async()=>{for(const name of ['tote','box']){await page.locator('#preset').selectOption(name);await page.locator('#loadPreset').click();const doc=JSON.parse(await download('saveProject'));assert.equal(doc.config.cargoType,name);assert.equal(doc.config.cargoMass,Model.preset(name).cargoMass);assert.equal(await page.locator('#error').isVisible(),false);}});
await test('history CSV import runs exact four requested jobs without extra demand',async()=>{await applyConfig(Model.preset('default'));await tab('demand');await page.locator('#historyFile').setInputFiles(path.join(base,'examples/history.csv'));await page.waitForFunction(()=>document.getElementById('historyStatus').textContent.includes('4건'));await field('warmup',0);await page.locator('#calculate').click();await tab('simulation');await finish();const s=await snapshot();assert.equal(s.arrivedIn,2);assert.equal(s.arrivedOut,2);assert.equal(s.completedIn+s.completedOut,4);assert.equal(s.throughput,8);});
await test('invalid history floor rejected with clear error',async()=>{await page.locator('#historyFile').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('time_s,type,level\n0,out,99')});await page.waitForFunction(()=>!document.getElementById('error').hidden);assert.ok((await page.locator('#error').textContent()).includes('층 번호'));await applyConfig(Model.preset('default'));});
await test('wide cargo and six parking stalls with four lifts fit top camera',async()=>{const c=Model.preset('default');Object.assign(c,{levels:2,bays:4,aisles:2,numLifts:4,cargoLength:3,cargoWidth:3,bayPitch:3.2,firstBay:3.2,aislePitch:9.4,hours:.05,warmup:0,layers:[{id:'F1',shuttles:6,inbound:0,outbound:0},{id:'F2',shuttles:6,inbound:0,outbound:0}]});await applyConfig(c);await page.locator('#viewTop').click();await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>{const s=__shuttleScene,e=s.extent;return[e.minX,e.maxX].every(x=>[e.minZ,e.maxZ].every(z=>{const p=new THREE.Vector3(x,0,z).project(s.camera);return Math.abs(p.x)<1&&Math.abs(p.y)<1;}));}));assert.equal(await page.locator('#sceneActor option').count(),16);await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'10_wide_layout.png')});await applyConfig(Model.preset('default'));});
await test('mobile layout fits viewport with usable canvas and scrollable tables',async()=>{await page.setViewportSize({width:390,height:844});await tab('simulation');await page.waitForTimeout(200);const sizes=await page.evaluate(()=>({doc:document.documentElement.scrollWidth,w:innerWidth,canvas:document.querySelector('#simScene canvas').getBoundingClientRect().width,box:document.getElementById('simScene').clientWidth}));assert.ok(sizes.doc<=sizes.w+1);assert.ok(sizes.canvas<=sizes.box+1);await page.screenshot({path:path.join(qa,'08_mobile.png')});await page.setViewportSize({width:1600,height:1050});});
await test('context loss switches live scene to functional 2D',async()=>{await page.evaluate(()=>__shuttleScene.renderer.domElement.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await page.waitForFunction(()=>document.getElementById('simScene').dataset.renderer==='fallback');assert.equal(await page.locator('#simScene svg').count(),1);await page.locator('#simStep').click();assert.equal(await page.locator('#viewTop').isDisabled(),true);});
const fallback=await browser.newPage({viewport:{width:1500,height:950},acceptDownloads:true});fallback.on('pageerror',e=>errors.push(e.message));fallback.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};window.Worker=class{constructor(){throw Error('disabled for QA');}};});await fallback.goto(url);await instrument(fallback);
await test('no-WebGL / no-Worker opens with 2D simulation fallback',async()=>{await tab('simulation',fallback);assert.equal(await fallback.locator('#simScene').getAttribute('data-renderer'),'fallback');assert.ok((await fallback.locator('#runtime').textContent()).includes('분할 계산'));assert.equal(await fallback.locator('#viewSelected').isDisabled(),true);await fallback.locator('#sceneLevel').selectOption('2');assert.ok((await fallback.locator('#simScene').textContent()).includes('F3'));await fallback.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'09_fallback.png')});});
await test('fallback DES finish retains identical default throughput',async()=>{await finish(fallback);assert.equal((await snapshot(fallback)).throughput,252);assert.equal((await snapshot(fallback)).conserved,true);});
await test('fallback chunked experiments finish and export without Worker',async()=>{await tab('experiments',fallback);await field('shuttleMax',2,fallback);await field('liftMax',1,fallback);await fallback.locator('#repCount').selectOption('1');await fallback.locator('#runExperiments').click();await fallback.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('2회 완료'));const r=JSON.parse(await download('exportExperiments',fallback));assert.equal(r.runs.length,2);assert.ok(r.runs.every(r=>r.conserved&&r.reservationOK));});
await test('no uncaught JavaScript errors or external HTTP requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
fs.writeFileSync(path.join(qa,'browser-results.json'),JSON.stringify({browser:await browser.version(),passed:checks.length,errors,externalRequests:requests,checks},null,2));console.log(checks.length+' browser groups passed.');await browser.close();
})().catch(async e=>{console.error(e);if(page)await page.screenshot({path:path.join(qa,'failure.png')}).catch(()=>{});if(browser)await browser.close();process.exitCode=1;});


