const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict'),{chromium}=require(process.env.BLENDER_PLAYWRIGHT_PATH||process.env.SHUTTLE_PLAYWRIGHT_PATH||'playwright');
const base=path.resolve(__dirname,'..'),root=path.resolve(base,'..'),apps=[['stacker','스태커크레인_실행.html','STCScene','scene'],['linear','직선RGV_실행.html','RGVScene','simScene'],['loop','LoopRGV_실행.html','LoopScene','simScene'],['shuttle','셔틀_실행.html','ShuttleScene','simScene']];
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']}),results=[];try{for(const[id,file,api,host]of apps){const page=await browser.newPage({viewport:{width:1600,height:1080}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(pathToFileURL(path.join(root,file)).href);await page.evaluate(api=>{const Old=globalThis[api].Scene;globalThis[api].Scene=class extends Old{constructor(...a){super(...a);window.__view=this;}};},api);await page.locator('[data-tab="simulation"]').click();await page.locator('#'+host+' .blender-model-badge').waitFor();await page.waitForFunction(()=>window.__view);
const meshes=await page.evaluate(()=>{const v=window.__view,assets=[];v.scene.traverse(o=>{if(o.userData.blenderAsset)assets.push(o.userData.blenderAsset);});return{source:v.container.dataset.modelSource,assets,drawCalls:v.renderer.info.render.calls};});assert.ok(meshes.source.startsWith('Blender'));assert.ok(meshes.assets.length>0);
await page.locator('#'+host).scrollIntoViewIfNeeded();await page.locator('#'+host).screenshot({path:path.join(base,'qa',id+'_overview.png')});
await page.locator('#'+host+' .blender-model-badge button').click();
await page.waitForTimeout(180);await page.locator('#'+host).screenshot({path:path.join(base,'qa',id+'_detail.png')});
await page.locator('#simSeek').evaluate(el=>{el.value=200;el.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(180);
const state=await page.evaluate(id=>{const v=__view;let aligned=true;if(id==='stacker'){for(const [i,a]of v.aisles.entries()){const p=v.latestFleet.engines[i].pose();aligned&&=Math.abs(a.crane.position.x-p.x.p)<1e-7&&Math.abs(a.carriage.position.y-p.y.p)<1e-7&&Math.abs(a.fork.position.z-p.f.p)<1e-7;}}else if(id==='shuttle'){for(const a of v.engine.actors){const p=v.engine.actorPose(a),b=v.actors.get(a.id).body.position;aligned&&=Math.hypot(b.x-p.x,b.y-p.y,b.z-p.z)<1e-7;}}else{for(const[i,a]of v.cars.entries()){const p=v.engine.pose(v.engine.cars[i]);aligned&&=Math.abs(a.body.position.x-p.x)<1e-7;}}return{aligned,materials:v.materials.length,geometries:v.geometries.length};},id);assert.equal(state.aligned,true);
await page.locator('#simFinish').click();await page.waitForFunction(()=>!document.getElementById('simFinish').disabled,null,{timeout:60000});await page.waitForTimeout(100);
const finish=await page.evaluate(id=>{const v=__view,e=id==='stacker'?v.latestFleet:v.engine;return{clock:document.getElementById('simClock').textContent,kpis:document.getElementById('simKpis')?.textContent||'',time:e.time};},id);
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);results.push({id,...meshes,...state,finish,errors,requests});console.log('PASS '+id+' Blender model, animated coordinates, offline UI');await page.close();}
fs.writeFileSync(path.join(base,'qa/browser-smoke.json'),JSON.stringify(results,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});



