(function(){'use strict';
const M=CvModel,E=CvEngine,IO=CvIO,$=id=>document.getElementById(id),esc=IO.escape,fmt=(x,n=1)=>x===null||x===undefined?'—':Number.isFinite(x)?x.toLocaleString('ko-KR',{maximumFractionDigits:n}):'제약 없음',clock=t=>[Math.floor(t/3600),Math.floor(t%3600/60),Math.floor(t%60)].map(x=>String(x).padStart(2,'0')).join(':');
let p=M.preset('h'),run=null,analysis=null,worker=null,playing=false,time=0,previousFrame=0,lastInfo=-1,selectedPreset='h',selectedEdge='',sensitivityRows=[],comparisons=[];
try{const saved=localStorage.getItem('conveyor.project.v1');if(saved){p=M.unpack(JSON.parse(saved));selectedPreset='';}comparisons=JSON.parse(localStorage.getItem('conveyor.compare.v1')||'[]');if(!Array.isArray(comparisons))comparisons=[];}catch(e){p=M.preset('h');comparisons=[];}
const scene=new CvScene.Scene($('scene'),id=>{selectedEdge=id;showTab('layout');renderTables();document.querySelector('#edgesTable tr.selected-row')?.scrollIntoView({block:'center',behavior:'smooth'});}),plan=new CvScene.Plan($('layoutCanvas'),()=>{markDirty();renderTables();});
function message(text,good=false){$('message').hidden=!text;$('message').textContent=text||'';$('message').classList.toggle('success',good);}
function busy(on){document.body.classList.toggle('busy',on);$('run').disabled=on;$('cancel').hidden=!on;$('progress').hidden=!on;document.querySelectorAll('[data-result-action]').forEach(b=>b.disabled=on||!run||M.hash(p)!==run.configHash);}
function markDirty(){const dirty=!run||M.hash(p)!==run.configHash;if(dirty){selectedPreset='';document.querySelectorAll('.preset').forEach(b=>b.classList.remove('active'));}$('stale').hidden=!dirty||!run;document.querySelectorAll('[data-result-action]').forEach(b=>b.disabled=dirty||!!worker);$('runStatus').textContent=dirty?'입력 변경 · 다시 계산해 주세요.':'계산 완료 · 운전 기록 재생 가능';}
function showTab(id){renderTables();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(el=>el.classList.toggle('active',el.id==='panel-'+id));if(id==='layout')plan.draw(p);if(id==='simulation'){scene.resize();drawChart();}if(id==='analysis')renderAnalysis();}
const typeOptions=[['source','입구'],['junction','이재/합류'],['sink','출구']],policyOptions=[['fifo','FIFO'],['roundRobin','교대 합류'],['priority','고정 우선순위']],peerOptions=[['none','미연결'],['stacker-crane','스태커 크레인'],['rgv_linear','직선 RGV'],['rgv_loop','LOOP RGV'],['shuttle_4way','셔틀'],['agv_amr','AGV & AMR']];
const col=(key,label,extra={})=>({key,label,...extra}),options=(key,filter=()=>true)=>p[key].filter(filter).map(x=>[x.id,x.id]);
function table(key,cols,{filter=()=>true,del=true}={}){return '<table><thead><tr>'+cols.map(c=>'<th>'+esc(c.label)+'</th>').join('')+(del?'<th></th>':'')+'</tr></thead><tbody>'+p[key].map((r,i)=>({r,i})).filter(({r})=>filter(r)).map(({r,i})=>'<tr class="'+(key==='edges'&&r.id===selectedEdge?'selected-row':'')+'">'+cols.map(c=>{let v=r[c.key];if(c.render)return '<td>'+c.render(r,i)+'</td>';if(c.read)return '<td><strong>'+esc(v)+'</strong></td>';const attrs=' data-list="'+key+'" data-index="'+i+'" data-key="'+c.key+'"'+(c.scale?' data-scale="'+c.scale+'"':'')+' aria-label="'+esc(r.id||'행 '+(i+1))+' '+esc(c.label)+'"';if(c.options)return '<td><select'+attrs+'>'+c.options.map(([value,label])=>'<option value="'+esc(value)+'"'+(v===value?' selected':'')+'>'+esc(label)+'</option>').join('')+'</select></td>';return '<td><input'+attrs+' type="'+(c.type||'text')+'" value="'+esc(typeof v==='number'&&c.scale?Number((v/c.scale).toFixed(6)):v)+'"'+(c.type==='number'?' step="'+(c.step||'any')+'"':'')+'></td>';}).join('')+(del?'<td><button class="delete" data-delete="'+key+'" data-index="'+i+'" aria-label="'+esc(r.id||i+1)+' 삭제">×</button></td>':'')+'</tr>').join('')+'</tbody></table>'+(!p[key].filter(filter).length?'<div class="empty">등록된 항목이 없습니다.</div>':'');}
function renderTables(){
 $('nodesTable').innerHTML=table('nodes',[col('id','노드 ID',{read:true}),col('type','유형',{options:typeOptions}),col('x','X (m)',{type:'number'}),col('z','Z (m)',{type:'number'}),col('height','상면 높이 (m)',{type:'number'}),col('cycle','이재/인계 주기 (s)',{type:'number'}),col('policy','합류 정책',{options:policyOptions}),col('resourceId','공유 자원 ID')]);
 $('edgesTable').innerHTML=table('edges',[col('id','구간 ID',{read:true}),col('from','시작',{options:options('nodes')}),col('to','끝',{options:options('nodes')}),col('length','길이 (m)',{render:e=>{const a=p.nodes.find(n=>n.id===e.from),b=p.nodes.find(n=>n.id===e.to);return '<span data-edge-length="'+esc(e.id)+'">'+(a&&b?fmt(Math.hypot(a.x-b.x,a.z-b.z,a.height-b.height),2):'—')+'</span>';}}),col('speed','속도 (m/min)',{type:'number',scale:1/60}),col('pitch','존 피치 (mm)',{type:'number',scale:.001}),col('width','폭 (mm)',{type:'number',scale:.001}),col('gap','최소 간격 (mm)',{type:'number',scale:.001}),col('payload','허용하중 (kg)',{type:'number'}),col('mechanism','기계 형식',{options:[['roller','롤러'],['belt','벨트'],['chain','체인']]})]);
 $('cargoTable').innerHTML=table('cargo',[col('id','ID',{read:true}),col('name','이름'),col('kind','화물 유형',{options:[['pallet','팔레트'],['box','박스'],['tote','토트']]}),col('length','길이 (mm)',{type:'number',scale:.001}),col('width','폭 (mm)',{type:'number',scale:.001}),col('height','높이 (mm)',{type:'number',scale:.001}),col('weight','중량 (kg)',{type:'number'}),col('color','색상',{type:'color'})]);
 $('flowsTable').innerHTML=table('flows',[col('id','OD ID',{read:true}),col('from','출발 입구',{options:options('nodes',n=>n.type==='source')}),col('to','도착 출구',{options:options('nodes',n=>n.type==='sink')}),col('cargoId','운반물',{options:p.cargo.map(c=>[c.id,c.name])}),col('rate','수요 (개/h)',{type:'number'}),col('ratio','분기 비율',{render:f=>{const sum=p.flows.filter(x=>x.from===f.from).reduce((a,x)=>a+x.rate,0);return '<span data-flow-ratio="'+esc(f.id)+'">'+(p.demandMode==='history'?'이력 기준':sum?fmt(f.rate/sum*100)+'%':'—')+'</span>';}}),col('priority','우선순위',{type:'number',step:1})]);
 $('operationsTable').innerHTML=table('edges',[col('id','구간',{read:true}),col('mode','운전 방식',{options:[['continuous','연속 이송'],['zpa','ZPA · 정지 존']]}),col('accel','가속 (m/s²)',{type:'number'}),col('decel','감속 (m/s²)',{type:'number'}),col('dwell','존 정지 (s)',{type:'number'}),col('initial','초기 점유 (개)',{type:'number',step:1}),col('initialCargo','초기 화물',{options:p.cargo.map(c=>[c.id,c.name])}),col('initialSink','초기 화물 출구',{options:options('nodes',n=>n.type==='sink')})],{del:false});
 $('stopsTable').innerHTML=table('stops',[col('edgeId','정지 구간',{options:options('edges')}),col('start','시작 (min)',{type:'number',scale:60}),col('end','종료 (min)',{type:'number',scale:60})]);
 $('portsTable').innerHTML=table('nodes',[col('id','입출력 노드',{read:true}),col('port','고유 포트',{render:n=>esc(p.moduleId+':'+n.id)}),col('peerType','연결 설비',{options:peerOptions}),col('peerId','연결 모듈 ID'),col('cycle','인계주기 (s)',{type:'number'})],{filter:n=>n.type!=='junction',del:false});
 $('historyInfo').textContent=p.history.length?fmt(p.history.length,0)+'개 작업 이력 등록 · 수요 발생 기준을 이력 모드로 선택하세요.':'작업 이력이 없습니다. 일정한 수요는 위 표만 입력하면 됩니다.';
 $('portSummary').innerHTML=IO.getPorts(p).map(port=>'<span class="port-chip">'+esc(port.direction.toUpperCase()+' · '+port.portId)+'</span>').join('');
}
function refreshDerived(){document.querySelectorAll('[data-edge-length]').forEach(el=>{const e=p.edges.find(e=>e.id===el.dataset.edgeLength),a=p.nodes.find(n=>n.id===e?.from),b=p.nodes.find(n=>n.id===e?.to);el.textContent=a&&b?fmt(Math.hypot(a.x-b.x,a.z-b.z,a.height-b.height),2):'—';});document.querySelectorAll('[data-flow-ratio]').forEach(el=>{const f=p.flows.find(f=>f.id===el.dataset.flowRatio),sum=p.flows.filter(x=>x.from===f.from).reduce((a,x)=>a+x.rate,0);el.textContent=p.demandMode==='history'?'이력 기준':sum?fmt(f.rate/sum*100)+'%':'—';});}
function renderForms(){document.querySelectorAll('[data-field]').forEach(el=>{const value=p[el.dataset.field];el.value=el.dataset.scale?Number((value/Number(el.dataset.scale)).toFixed(6)):value;});$('moduleTag').textContent=p.moduleId;renderTables();plan.draw(p);document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===selectedPreset));}
function renderKpis(){if(!run)return;const m=run.metrics,util=analysis.resources.find(r=>r.id===analysis.bottleneck)?.util||0;const kpis=[['측정 처리량',fmt(m.throughput),'HU/h',m.byCargo.filter(c=>c.completed).map(c=>esc(c.name)+' '+fmt(c.rate,0)).join(' · '),'primary-kpi teal'],['해석 처리능력 상한',fmt(analysis.upper),'HU/h','현재 물량 구성 고정 · 정지·정체 적용 전',''],['병목 자원',esc(analysis.bottleneck),'', '요구 부하율 '+fmt(util*100)+'% · 목표 '+fmt(run.config.target*100,0)+'%',util>1?'red':'amber'],['미투입 / 재공',fmt(m.backlog,0)+' <small>/</small> '+fmt(m.wip,0),'개','운전 종료 시점 · 모든 화물 유형 합계','']];$('kpis').innerHTML=kpis.map(([label,value,unit,note,cls])=>'<div class="kpi '+cls+'"><div class="kpi-label">'+label+'</div><div class="kpi-value">'+value+'<small>'+unit+'</small></div><div class="kpi-note">'+note+'</div></div>').join('');$('summary').innerHTML=[['투입 + 초기 재고',fmt(m.generated,0)+' + '+fmt(m.initial,0)+' 개'],['총 완료',fmt(m.totalCompleted,0)+' 개'],['평균 / P95 리드타임',fmt(m.meanLead)+' / '+fmt(m.p95Lead)+' s'],['평균 재공 / 미투입 대기',fmt(m.meanWip)+' / '+fmt(m.meanBacklog)+' 개'],['처리량 측정 구간',clock(run.config.warmup)+' – '+clock(run.config.horizon)]].map(([k,v])=>'<div class="summary-row"><span>'+k+'</span><strong>'+v+'</strong></div>').join('');$('balance').textContent=m.conservation?'화물 보존 일치':'화물 보존 오류';$('sceneName').textContent='· '+run.config.name;}
const plainTable=(heads,rows)=>'<table><thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
function renderAnalysis(){if(!run)return;const m=run.metrics;$('resultDetail').innerHTML='<article class="card"><div class="result-stat-grid"><div class="mini-stat"><span>시간가중 평균 재공</span><strong>'+fmt(m.meanWip)+' <small>개</small></strong></div><div class="mini-stat"><span>평균 / P95 리드타임</span><strong>'+fmt(m.meanLead)+' / '+fmt(m.p95Lead)+' <small>s</small></strong></div><div class="mini-stat"><span>실제 측정시간</span><strong>'+fmt(m.measuredSeconds/60)+' <small>min</small></strong></div></div>'+plainTable(['화물 유형','측정 완료','달성 처리량'],m.byCargo.map(c=>[esc(c.name),fmt(c.completed,0)+' 개',fmt(c.rate)+' '+(c.kind==='pallet'?'PLT/h':c.kind==='box'?'box/h':'tote/h')]))+'<p class="subtext">HU/h는 혼합 화물 개수의 합입니다. 초기 재고도 완료량에 포함됩니다. 초기 재고를 제외한 완료 작업의 리드타임을 집계합니다. 낮은 투입 수요는 설비의 최대 처리능력을 입증하지 않습니다.</p></article><div class="table-card"><div class="card-heading"><h2>자원별 정상상태 능력</h2><span class="soft">요구 부하율 = 요청량 / 자원 능력</span></div><div class="table-scroll">'+plainTable(['자원','유형','요구량 개/h','능력 개/h','Headway s','요구 부하율','판정'],analysis.resources.map(r=>[esc(r.id),r.type,fmt(r.load),fmt(r.capacity),fmt(r.headway,2),'<span class="bar"><i style="width:'+Math.min(100,r.util*100)+'%;background:'+(r.util>1?'#c76660':'#3c9d99')+'"></i></span>'+fmt(r.util*100)+'%','<span class="'+(r.util>1?'red':r.util>run.config.target?'amber':'teal')+'">'+r.status+'</span>']))+'</div></div><div class="table-card"><div class="card-heading"><h2>구간 점유 · 차단</h2></div><div class="table-scroll">'+plainTable(['구간','존 용량','평균 점유·예약','최대 점유·예약','출구 대기비율','정지시간'],m.edgeRows.map(e=>[esc(e.id),e.capacity,fmt(e.meanOccupancy,2),e.maxOccupancy,fmt(e.blockedRatio*100)+'%',fmt(e.stopSeconds)+' s']))+'</div></div><div class="table-card"><div class="card-heading"><h2>이재 장치 가동률</h2></div><div class="table-scroll">'+plainTable(['공유 자원 ID','실제 가동률','측정 구간 이재 횟수'],m.nodeRows.map(n=>[esc(n.id),fmt(n.busyRatio*100)+'%',n.handled]))+'</div></div><article class="card"><h2>경로와 계산 가정</h2><div class="table-scroll">'+plainTable(['수요','적용 경로','무대기 소요시간'],analysis.flows.map(f=>[esc(f.id),esc(f.path.join(' → ')),fmt(f.lead)+' s']))+'</div><ul class="warn-list">'+analysis.warnings.map(s=>'<li>'+esc(s)+'</li>').join('')+'<li>3D는 구간 이동의 평균 속도와 화물 대기 위치를 표시합니다. 기계 동작의 상세 가감속 궤적은 표시하지 않습니다.</li><li>전체 운전 동안의 요청 수·초기 재고·완료·재공·미투입이 보존됩니다. 평균 지표는 준비운전 이후 시간가중 값입니다.</li></ul></article>';
 $('sensitivityResults').innerHTML=sensitivityRows.length?plainTable(['조건','처리량 HU/h','기준 대비','미투입 개','P95 s','해석 상한 HU/h'],sensitivityRows.map((r,i)=>[esc(r.name),fmt(r.throughput),i?fmt(r.throughput-sensitivityRows[0].throughput):'기준',r.backlog,fmt(r.p95),fmt(r.upper)])):'<div class="empty">5가지 조건 비교를 실행하면 개선 효과를 확인할 수 있습니다.</div>';
 $('comparisons').innerHTML=comparisons.length?plainTable(['시나리오','입력 해시','측정 min','시드','처리량 HU/h','미투입 / 재공','P95 s'],comparisons.map(c=>[esc(c.name),esc(c.hash),fmt(c.measured/60),esc(c.seed),fmt(c.throughput),c.backlog+' / '+c.wip,fmt(c.p95)])):'<div class="empty">설정을 바꾸기 전에 현재 결과를 추가하세요. 최대 8개까지 이 기기에 저장됩니다.</div>';
}
function drawChart(){if(!run)return;const c=$('flowChart'),rect=c.getBoundingClientRect();if(!rect.width)return;const dpr=Math.min(devicePixelRatio||1,2);c.width=rect.width*dpr;c.height=167*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=167,left=42,top=19,right=12,bottom=25,max=Math.max(10,run.generated+run.initial);ctx.font='9px Segoe UI';for(let i=0;i<=4;i++){const y=top+(h-top-bottom)*i/4;ctx.strokeStyle='#e9eff3';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke();ctx.fillStyle='#91a4ae';ctx.textAlign='right';ctx.fillText(fmt(max*(4-i)/4,0),left-8,y+3);}for(const [key,color]of [['generated','#a5b8c5'],['completed','#158c86']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();run.samples.forEach((s,i)=>{const x=left+(w-left-right)*s.time/run.config.horizon,y=top+(h-top-bottom)*(1-(s[key]+(key==='generated'?run.initial:0))/max);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}ctx.fillStyle='#93a5ae';ctx.textAlign='left';ctx.fillText('0 min',left,h-5);ctx.textAlign='right';ctx.fillText(fmt(run.config.horizon/60,0)+' min',w-right,h-5);ctx.fillStyle='#93aab9';ctx.fillText('투입 + 초기',w-83,10);ctx.fillStyle='#158c86';ctx.fillText('완료',w-12,10);}
function setTime(t){if(!run)return;time=Math.max(0,Math.min(run.config.horizon,t));scene.render(time);$('seek').value=time;$('clock').textContent=clock(time);if(Math.abs(time-lastInfo)>.3||lastInfo<0){lastInfo=time;const started=run.items.filter(i=>i.acceptedAt!==null&&i.acceptedAt<=time).length,done=run.items.filter(i=>i.completedAt!==null&&i.completedAt<=time).length;$('sceneStatus').textContent=(scene.fallback?'2D 대체 화면 · ':'')+'재생 시점 완료 '+done+' · 재공 '+(started-done)+(scene.poses?.length>600?' · 표시 최대 600개':'');}}
function saveBlob(name,data,type='application/json'){const blob=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(s){return s.replace(/[<>:"/\\|?*]/g,'_').slice(0,80);}
function stopWorker(){if(worker){worker.terminate();worker=null;}busy(false);}
function applied(result){run=result;analysis=M.calculate(run.config);sensitivityRows=[];playing=false;$('play').textContent='▶';scene.build(run);$('seek').max=run.config.horizon;$('duration').textContent=clock(run.config.horizon);lastInfo=-1;setTime(Math.min(60,run.config.horizon));renderKpis();renderAnalysis();drawChart();markDirty();$('runStatus').textContent='계산 완료 · '+fmt(run.eventCount,0)+'개 이벤트';try{localStorage.setItem('conveyor.project.v1',JSON.stringify(M.pack(run.config)));}catch(e){$('runStatus').textContent+=' · 자동 복구 저장 실패, JSON 저장 권장';}if(scene.fallback)message('이 환경에서는 3D를 초기화할 수 없어 2D 운전 재생으로 표시합니다. WebGL을 사용할 수 있는 Edge 또는 Chrome에서 3D를 이용하세요.');}
function calculate(type='run'){message('');const check=M.validate(p);if(check.errors.length){message(check.errors.slice(0,30).join('\n'));return;}stopWorker();playing=false;$('play').textContent='▶';busy(true);$('progress').value=0;$('runStatus').textContent=type==='run'?'물동량과 운전 기록을 계산하고 있습니다.':'5가지 개선 조건을 비교하고 있습니다.';const input=M.clone(p),hash=M.hash(input);try{const url=URL.createObjectURL(new Blob([CV_WORKER_SOURCE],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=({data})=>{if(data.type==='progress'){$('progress').value=data.value;return;}stopWorker();if(data.type==='error'){message(data.message);$('runStatus').textContent='계산 실패 · 입력 조건을 확인하세요.';}else if(data.type==='result')applied(data.run);else if(data.type==='sensitivity'){if(M.hash(p)!==hash||run?.configHash!==hash){message('조건이 변경되어 비교 결과를 적용하지 않았습니다. 다시 계산해 주세요.');return;}sensitivityRows=data.rows;renderAnalysis();$('runStatus').textContent='개선 조건 비교 완료';}};worker.onerror=ev=>{stopWorker();message('계산 중 오류: '+ev.message);$('runStatus').textContent='계산 중단';};worker.postMessage({type,config:input});}catch(e){stopWorker();if(type==='run'&&input.horizon*input.flows.reduce((a,f)=>a+f.rate,0)/3600<5000){$('runStatus').textContent='기본 계산 방식으로 실행 중';setTimeout(()=>{try{applied(E.run(input));}catch(err){message(err.message);}},30);}else message('이 브라우저에서 병렬 계산을 시작할 수 없습니다. Edge 또는 Chrome에서 실행해 주세요.');}}
function unique(key,prefix){let i=1;while(p[key].some(x=>x.id===prefix+i)||p.nodes.some(x=>x.id===prefix+i)||p.edges.some(x=>x.id===prefix+i))i++;return prefix+i;}
function add(key){if(key==='nodes'){const id=unique('nodes','N');p.nodes.push(M.node(id,0,Math.max(...p.nodes.map(n=>n.z),0)+5));}if(key==='edges'){const from=p.nodes.find(n=>n.type==='source')||p.nodes[0],to=p.nodes.find(n=>n.type==='sink')||p.nodes[1];if(!from||!to){message('구간을 추가하려면 노드 2개가 필요합니다.');return;}p.edges.push(M.edge(unique('edges','CV'),from.id,to.id,{initialCargo:p.cargo[0]?.id||'',initialSink:to.id}));}if(key==='cargo')p.cargo.push({...M.clone(M.cargoDefaults[1]),id:unique('cargo','CARGO'),name:'신규 박스'});if(key==='flows'){const from=p.nodes.find(n=>n.type==='source'),to=p.nodes.find(n=>n.type==='sink');if(!from||!to||!p.cargo.length){message('입구·출구·운반물을 먼저 추가하세요.');return;}p.flows.push({id:unique('flows','OD'),from:from.id,to:to.id,cargoId:p.cargo[0].id,rate:100,priority:1});}if(key==='stops'){if(!p.edges.length)return;p.stops.push({edgeId:p.edges[0].id,start:Math.min(600,p.horizon*.3),end:Math.min(900,p.horizon*.5)});}renderForms();markDirty();}
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.field){p[el.dataset.field]=el.type==='number'?el.value===''?NaN:Number(el.value)*(Number(el.dataset.scale)||1):el.value;markDirty();if(el.dataset.field==='moduleId')renderTables();refreshDerived();}else if(el.dataset.list){const row=p[el.dataset.list][Number(el.dataset.index)];row[el.dataset.key]=el.type==='number'?el.value===''?NaN:Number(el.value)*(Number(el.dataset.scale)||1):el.value;markDirty();document.querySelectorAll('[data-list="'+el.dataset.list+'"][data-index="'+el.dataset.index+'"][data-key="'+el.dataset.key+'"]').forEach(other=>{if(other!==el)other.value=el.value;});refreshDerived();if(['nodes','edges'].includes(el.dataset.list))plan.draw(p);}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)showTab(b.dataset.tab);if(b.dataset.preset){stopWorker();p=M.preset(b.dataset.preset);selectedPreset=b.dataset.preset;renderForms();calculate();}if(b.dataset.delete){const key=b.dataset.delete,i=Number(b.dataset.index),r=p[key][i];if(key==='nodes'&&(p.edges.some(e=>e.from===r.id||e.to===r.id)||p.flows.some(f=>f.from===r.id||f.to===r.id))){message('이 노드를 참조하는 구간과 수요를 먼저 삭제하세요.');return;}if(key==='cargo'&&(p.flows.some(f=>f.cargoId===r.id)||p.edges.some(e=>e.initialCargo===r.id))){message('이 운반물을 참조하는 수요와 초기 점유 화물 설정을 먼저 변경하세요.');return;}if(key==='edges'&&p.stops.some(s=>s.edgeId===r.id)){message('이 구간의 계획 정지를 먼저 삭제하세요.');return;}if(key==='flows'&&p.history.some(h=>h.flowId===r.id)){message('작업 이력에서 사용하는 수요입니다. 작업 이력을 교체한 후 삭제하세요.');return;}p[key].splice(i,1);renderForms();markDirty();message('');}});
const glyphs={straight:'━',merge:'┳',split:'┫',cross:'╋',h:'H',u:'∪',loop:'▱'};$('presets').innerHTML=Object.entries(M.kinds).map(([id,label])=>'<button class="preset" data-preset="'+id+'"><span class="glyph">'+glyphs[id]+'</span>'+esc(label)+'</button>').join('');
for(const [id,key]of [['addNode','nodes'],['addEdge','edges'],['addCargo','cargo'],['addFlow','flows'],['addStop','stops']])$(id).onclick=()=>add(key);
 $('run').onclick=()=>calculate();$('cancel').onclick=()=>{stopWorker();$('runStatus').textContent='계산이 취소되었습니다.';};$('sensitivity').onclick=()=>calculate('sensitivity');$('play').onclick=()=>{if(!run)return;if(time>=run.config.horizon)setTime(0);playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'시뮬레이션 일시정지':'시뮬레이션 재생');};$('rewind').onclick=()=>{playing=false;$('play').textContent='▶';setTime(0);};$('seek').oninput=e=>{playing=false;$('play').textContent='▶';setTime(Number(e.target.value));};$('iso').onclick=()=>{scene.setCamera('iso');$('iso').classList.add('active');$('top').classList.remove('active');};$('top').onclick=()=>{scene.setCamera('top');$('top').classList.add('active');$('iso').classList.remove('active');};$('resetCamera').onclick=()=>scene.setCamera(scene.mode||'iso');$('capture').onclick=()=>{if(!run)return;const a=document.createElement('a');a.download='컨베이어_3D_'+Math.floor(time)+'s.png';a.href=scene.capture();a.click();};
 $('saveProject').onclick=()=>{try{saveBlob(filename(p.name)+'.json',JSON.stringify(M.pack(p),null,2));message('프로젝트 JSON을 다운로드했습니다.',true);}catch(e){message(e.message);}};$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('프로젝트 파일은 5 MB 이하로 선택하세요.');const next=M.unpack(JSON.parse(await file.text()));stopWorker();p=next;selectedPreset='';renderForms();calculate();}catch(err){message('불러오기 실패: '+err.message);}e.target.value='';};
 $('historyTemplate').onclick=()=>saveBlob('컨베이어_작업이력_양식.csv',IO.csv([['id','release_s','flowId'],['TASK-001',0,p.flows[0]?.id||'OD1'],['TASK-002',12,p.flows[0]?.id||'OD1']]),'text/csv;charset=utf-8');$('loadHistory').onclick=()=>$('historyFile').click();$('historyFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('CSV는 3 MB 이하로 선택하세요.');p=IO.importHistory(await file.text(),p);renderForms();markDirty();message(p.history.length+'개 작업을 불러왔습니다. 설정 적용 · 계산을 누르세요.',true);}catch(err){message(err.message);}e.target.value='';};
 $('csvResults').onclick=()=>saveBlob(filename(run.config.name)+'_결과.csv',IO.resultCSV(run,analysis),'text/csv;charset=utf-8');$('report').onclick=()=>saveBlob(filename(run.config.name)+'_보고서.html',IO.report(run,analysis),'text/html;charset=utf-8');$('exportInterface').onclick=()=>saveBlob(filename(run.config.moduleId)+'_연동데이터.json',JSON.stringify(IO.interfaceData(run),null,2));$('pin').onclick=()=>{const m=run.metrics;comparisons.push({name:run.config.name,hash:run.configHash,measured:m.measuredSeconds,seed:run.config.seed,throughput:m.throughput,backlog:m.backlog,wip:m.wip,p95:m.p95Lead});comparisons=comparisons.slice(-8);try{localStorage.setItem('conveyor.compare.v1',JSON.stringify(comparisons));}catch(e){}renderAnalysis();message('현재 시나리오를 비교 목록에 추가했습니다.',true);};$('clearCompare').onclick=()=>{comparisons=[];try{localStorage.removeItem('conveyor.compare.v1');}catch(e){}renderAnalysis();};$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
function frame(now){const delta=previousFrame?Math.min(.2,(now-previousFrame)/1000):0;previousFrame=now;if(playing&&run){setTime(time+delta*Number($('speed').value));if(time>=run.config.horizon){playing=false;$('play').textContent='▶';}}else if(!scene.fallback)scene.controls.update();requestAnimationFrame(frame);}
window.addEventListener('resize',drawChart);window.CvApp={getConfig:()=>M.clone(p),getResult:()=>run,plugin:IO.plugin};renderForms();calculate();requestAnimationFrame(frame);
})();
