(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model'):root.CvModel);if(typeof module==='object'&&module.exports)module.exports=api;root.CvEngine=api;})(globalThis,function(M){
'use strict';const EPS=1e-7;
class Heap{constructor(){this.a=[];this.seq=0;}push(t,kind,data){if(!Number.isFinite(t))return;const x={t,kind,data,seq:this.seq++};let i=this.a.length;this.a.push(x);while(i){const j=(i-1)>>1;if(!this.less(x,this.a[j]))break;this.a[i]=this.a[j];i=j;this.a[i]=x;}}less(a,b){return a.t<b.t||(a.t===b.t&&a.seq<b.seq);}pop(){const top=this.a[0],tail=this.a.pop();if(this.a.length){let i=0;this.a[0]=tail;while(true){let j=i*2+1;if(j>=this.a.length)break;if(j+1<this.a.length&&this.less(this.a[j+1],this.a[j]))j++;if(!this.less(this.a[j],tail))break;this.a[i]=this.a[j];i=j;this.a[i]=tail;}}return top;}get peek(){return this.a[0];}}
function rng(seed){return ()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function intervals(rows){const out=[];for(const x of [...rows].sort((a,b)=>a.start-b.start)){const last=out.at(-1);if(last&&x.start<=last.end)last.end=Math.max(last.end,x.end);else out.push({start:x.start,end:x.end});}return out;}
function activeAt(t,stops){for(const s of stops)if(t>=s.start-EPS&&t<s.end-EPS)t=s.end;return t;}
function activeAdd(start,duration,stops){if(!Number.isFinite(start))return start;let t=activeAt(start,stops),left=duration;for(const s of stops){if(s.end<=t+EPS)continue;if(s.start>t&&t+left<=s.start+EPS)return t+left;if(s.start>=t){left-=s.start-t;t=s.end;}}return t+left;}
function activeElapsed(start,end,stops){if(end<=start)return 0;let n=end-start;for(const s of stops)n-=Math.max(0,Math.min(end,s.end)-Math.max(start,s.start));return Math.max(0,n);}
const overlap=(a,b,w,h)=>Math.max(0,Math.min(b,h)-Math.max(a,w));
class Simulation{
 constructor(config){const checked=M.validate(config);if(checked.errors.length)throw Error(checked.errors.join('\n'));this.p=M.clone(config);this.g=M.graph(this.p);this.time=0;this.heap=new Heap();this.items=[];this.events=[];this.wakes=new Set();this.counter=0;this.eventCount=0;this.generated=0;this.initial=0;this.accepted=0;this.completed=0;this.resources=new Map();this.nodes=new Map();this.edges=new Map();this.samples=[];
  for(const n of this.p.nodes){this.nodes.set(n.id,{...n,queue:[],lastInput:''});if(!this.resources.has(n.resourceId))this.resources.set(n.resourceId,{id:n.resourceId,busy:null});}
  for(const e of this.g.edges.values())this.edges.set(e.id,{...e,queue:[],reserved:0,lastEntry:-Infinity,lastExit:-Infinity,stops:intervals(this.p.stops.filter(s=>s.edgeId===e.id))});
  for(const e of this.edges.values())for(let i=0;i<e.initial;i++){const item=this.makeItem({id:'INITIAL-'+e.id+'-'+(i+1),from:e.from,to:e.initialSink,cargoId:e.initialCargo,priority:1},0,true);item.path=[e.id,...M.route(this.g,e.to,e.initialSink)];item.cursor=1;item.acceptedAt=0;item.ready=activeAdd(0,(i+1)*e.headway,e.stops);item.stays.push({type:'edge',id:e.id,start:0,end:null,offset:Math.max(0,e.length-(i+1)*e.pitch),initial:true});e.queue.push(item);this.initial++;}
  const flows=new Map(this.p.flows.map(f=>[f.id,f]));if(this.p.demandMode==='history'){for(const h of this.p.history)this.heap.push(h.release,'arrival',{flow:flows.get(h.flowId),id:h.id});}else for(const f of this.p.flows){if(!f.rate)continue;const random=rng((this.p.seed^parseInt(M.hash(f.id),16))>>>0),gap=3600/f.rate;let t=this.p.arrival==='periodic'?0:-Math.log(Math.max(1e-12,1-random()))*gap;let i=0;while(t<this.p.horizon-EPS){if(++i>60000)throw Error('확률 도착 60,000건 초과');this.heap.push(t,'arrival',{flow:f,id:f.id+'-'+i});t+=this.p.arrival==='periodic'?gap:-Math.log(Math.max(1e-12,1-random()))*gap;}}
  for(const s of this.p.stops){this.wake(s.start);this.wake(s.end);}this.wake(0);this.wake(this.p.warmup);this.wake(this.p.horizon);for(let t=0;t<=this.p.horizon;t+=Math.max(10,this.p.horizon/360))this.heap.push(t,'sample');
 }
 wake(t){if(!Number.isFinite(t)||t>this.p.horizon+EPS)return;const key=t.toFixed(7);if(this.wakes.has(key))return;this.wakes.add(key);this.heap.push(t,'wake',key);}
 makeItem(f,t,initial=false,id){const item={id:id||'C'+(++this.counter),flowId:initial?'INITIAL':f.id,from:f.from,to:f.to,cargoId:f.cargoId,priority:f.priority,release:t,acceptedAt:null,completedAt:null,path:initial?[]:M.route(this.g,f.from,f.to),cursor:0,stays:[],initial,order:this.items.length};this.items.push(item);return item;}
 process(ev){if(ev.kind==='wake')this.wakes.delete(ev.data);else if(ev.kind==='arrival'){const item=this.makeItem(ev.data.flow,ev.t,false,ev.data.id);this.nodes.get(item.from).queue.push(item);this.generated++;this.events.push({time:ev.t,type:'REQUEST',cargoId:item.id,flowId:item.flowId,nodeId:item.from});}
  else if(ev.kind==='finish'){const {item,node,out,resource,stay}=ev.data;stay.end=ev.t;resource.busy=null;if(out){out.reserved--;out.queue.push(item);out.lastEntry=ev.t;item.ready=activeAdd(ev.t,out.travel,out.stops);item.cursor++;item.stays.push({type:'edge',id:out.id,start:ev.t,end:null,offset:0});this.wake(item.ready);this.events.push({time:ev.t,type:'ENTER_EDGE',cargoId:item.id,nodeId:node.id,edgeId:out.id});}else{item.completedAt=ev.t;this.completed++;this.events.push({time:ev.t,type:'HANDOFF_COMPLETE',cargoId:item.id,cargoType:item.cargoId,flowId:item.flowId,nodeId:node.id,peerType:node.peerType,peerId:node.peerId});}}
 }
 candidate(node,item,incoming,t){let earliest=t;if(incoming){earliest=Math.max(earliest,item.ready,activeAdd(incoming.lastExit,incoming.headway,incoming.stops));earliest=activeAt(earliest,incoming.stops);}const out=item.cursor<item.path.length?this.edges.get(item.path[item.cursor]):null;if(out){if(out.queue.length+out.reserved>=out.capacity)return null;const enter=activeAt(Math.max(earliest+node.cycle,activeAdd(out.lastEntry,out.headway,out.stops)),out.stops);earliest=Math.max(earliest,enter-node.cycle);if(incoming)earliest=activeAt(earliest,incoming.stops);const revised=activeAt(earliest+node.cycle,out.stops);earliest=revised-node.cycle;if(incoming&&activeAt(earliest,incoming.stops)>earliest+EPS){this.wake(activeAt(earliest,incoming.stops));return null;}}
  if(earliest>t+EPS){this.wake(earliest);return null;}return {node,item,incoming,out,input:incoming?.id||node.id};
 }
 pump(t){let changed=true,loops=0;while(changed){changed=false;if(++loops>this.p.nodes.length+5)throw Error('동일시각 처리 순환 오류');for(const resource of this.resources.values()){if(resource.busy)continue;const candidates=[];for(const node of this.nodes.values()){if(node.resourceId!==resource.id)continue;if(node.type==='source'){const item=node.queue[0];if(item){const c=this.candidate(node,item,null,t);if(c)candidates.push(c);}}else for(const incoming of this.edges.values()){if(incoming.to!==node.id||!incoming.queue.length)continue;const c=this.candidate(node,incoming.queue[0],incoming,t);if(c)candidates.push(c);}}
    if(!candidates.length)continue;candidates.sort((a,b)=>{if(a.node.id!==b.node.id)return a.item.release-b.item.release||a.item.order-b.item.order;const policy=a.node.policy;if(policy==='priority'&&a.item.priority!==b.item.priority)return b.item.priority-a.item.priority;if(policy==='roundRobin'){const ids=[...new Set(candidates.filter(c=>c.node.id===a.node.id).map(c=>c.input))].sort();const last=ids.indexOf(a.node.lastInput),rank=x=>(ids.indexOf(x)-last-1+ids.length)%ids.length;const delta=rank(a.input)-rank(b.input);if(delta)return delta;}return a.item.release-b.item.release||a.item.order-b.item.order;});
    const {node,item,incoming,out,input}=candidates[0];if(incoming){incoming.queue.shift();incoming.lastExit=t;item.stays.at(-1).end=t;this.wake(activeAdd(t,incoming.headway,incoming.stops));}else{node.queue.shift();item.acceptedAt=t;this.accepted++;this.events.push({time:t,type:'ACCEPT',cargoId:item.id,nodeId:node.id});}if(out)out.reserved++;node.lastInput=input;const stay={type:'node',id:node.id,resourceId:node.resourceId,start:t,end:null,plannedEnd:t+node.cycle};item.stays.push(stay);resource.busy=item.id;this.events.push({time:t,type:'TRANSFER_START',cargoId:item.id,nodeId:node.id,resourceId:node.resourceId});this.heap.push(t+node.cycle,'finish',{item,node,out,resource,stay});changed=true;
   }}
 }
 advanceTo(until){if(until<this.time-EPS||until>this.p.horizon+EPS)throw Error('시뮬레이션 시각은 현재 이상, 운전 종료 이하이어야 합니다.');while(this.heap.peek&&this.heap.peek.t<=until+EPS){const t=this.heap.peek.t;let sample=false;while(this.heap.peek&&this.heap.peek.t<=t+EPS){const ev=this.heap.pop();if(++this.eventCount>1500000)throw Error('이벤트 1,500,000건 초과. 시간 또는 수요를 줄이세요.');if(ev.kind==='sample')sample=true;else this.process(ev);}this.time=t;this.pump(t);if(sample)this.samples.push({time:t,generated:this.generated,completed:this.completed,backlog:this.generated-this.accepted,wip:this.initial+this.accepted-this.completed});}this.time=until;return this;}
 result(){return {version:M.VERSION,configHash:M.hash(this.p),config:M.clone(this.p),time:this.time,initial:this.initial,generated:this.generated,accepted:this.accepted,completed:this.completed,items:this.items,events:this.events,samples:this.samples,eventCount:this.eventCount};}
}
function run(p,progress){const s=new Simulation(p);const chunk=Math.max(60,p.horizon/20);for(let t=chunk;t<p.horizon;t+=chunk){s.advanceTo(t);if(progress)progress(t/p.horizon);}s.advanceTo(p.horizon);const r=s.result();r.metrics=metrics(r);return r;}
function metrics(run,t=run.time){const p=run.config,w=Math.min(p.warmup,t),span=Math.max(0,t-w),end=x=>x??t,items=run.items.filter(i=>i.release<=t+EPS),generated=items.filter(i=>!i.initial).length,initial=items.filter(i=>i.initial).length,accepted=items.filter(i=>!i.initial&&i.acceptedAt!==null&&i.acceptedAt<=t+EPS).length,done=items.filter(i=>i.completedAt!==null&&i.completedAt<=t+EPS),measured=done.filter(i=>i.completedAt>=w-EPS&&i.completedAt<t-EPS),lead=measured.filter(i=>!i.initial).map(i=>i.completedAt-i.release).sort((a,b)=>a-b),byCargo=p.cargo.map(c=>({id:c.id,name:c.name,kind:c.kind,completed:measured.filter(i=>i.cargoId===c.id).length,rate:span?measured.filter(i=>i.cargoId===c.id).length*3600/span:0}));
 const g=M.graph(p),edgeRows=[],nodeRows=[];for(const e of g.edges.values()){const stays=items.flatMap(i=>i.stays.filter(s=>s.type==='edge'&&s.id===e.id&&s.start<=t).map(s=>({...s,item:i}))).sort((a,b)=>a.start-b.start||a.item.order-b.item.order),stops=intervals(p.stops.filter(s=>s.edgeId===e.id));let blocked=0,area=0,lastExit=-Infinity;for(const s of stays){const finish=Math.min(end(s.end),t),free=s.initial?activeAdd(0,(e.length-s.offset)/e.length*e.travel,stops):activeAdd(s.start,e.travel,stops),ready=Math.max(free,activeAdd(lastExit,e.headway,stops));blocked+=activeElapsed(Math.max(ready,w),finish,stops);area+=overlap(s.start,finish,w,t);if(s.end!==null)lastExit=s.end;}
  const reservations=items.flatMap(i=>i.stays.filter(s=>s.type==='node'&&s.start<=t&&s.plannedEnd>s.start).map(s=>{const idx=i.stays.indexOf(s),next=i.stays[idx+1];const pathIndex=i.stays.slice(0,idx).filter(q=>q.type==='edge').length;const outId=next?.type==='edge'?next.id:i.path[pathIndex];return outId===e.id?s:null;}).filter(Boolean));for(const s of reservations)area+=overlap(s.start,Math.min(end(s.end),t),w,t);
  const deltas=[[w,0]];for(const s of stays){deltas.push([s.start,1]);if(s.end!==null&&s.end<=t)deltas.push([s.end,-1]);}for(const s of reservations){deltas.push([s.start,1]);if(s.end!==null&&s.end<=t)deltas.push([s.end,-1]);}deltas.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let count=0,max=0;for(const [at,d]of deltas){count+=d;if(at>=w-EPS)max=Math.max(max,count);}edgeRows.push({id:e.id,capacity:e.capacity,meanOccupancy:span?area/span:0,maxOccupancy:max,blockedRatio:span?Math.min(1,blocked/span):0,stopSeconds:span-activeElapsed(w,t,stops)});
 }
 for(const id of new Set(p.nodes.map(n=>n.resourceId))){const busy=items.flatMap(i=>i.stays.filter(s=>s.type==='node'&&s.resourceId===id));nodeRows.push({id,busyRatio:span?busy.reduce((a,s)=>a+overlap(s.start,end(s.end),w,t),0)/span:0,handled:busy.filter(s=>s.end!==null&&s.end>=w&&s.end<=t).length});}
 const wipArea=items.filter(i=>i.acceptedAt!==null).reduce((a,i)=>a+overlap(i.acceptedAt,end(i.completedAt),w,t),0),backlogArea=items.filter(i=>!i.initial).reduce((a,i)=>a+overlap(i.release,end(i.acceptedAt),w,t),0),wip=initial+accepted-done.length,backlog=generated-accepted;
 return {time:t,measuredSeconds:span,generated,initial,accepted,totalCompleted:done.length,completed:measured.length,throughput:span?measured.length*3600/span:0,byCargo,wip,backlog,meanWip:span?wipArea/span:0,meanBacklog:span?backlogArea/span:0,meanLead:lead.length?lead.reduce((a,b)=>a+b,0)/lead.length:null,p95Lead:lead.length?lead[Math.ceil(.95*lead.length)-1]:null,maxLead:lead.at(-1)??null,edgeRows,nodeRows,conservation:initial+generated===done.length+wip+backlog};
}
function snapshot(run,t){const p=run.config,g=M.graph(p),poses=[],edgeItems=new Map(p.edges.map(e=>[e.id,[]]));for(const item of run.items){if(item.acceptedAt===null||item.acceptedAt>t||item.completedAt!==null&&item.completedAt<=t)continue;const stay=item.stays.find(s=>s.start<=t&&(s.end===null||s.end>t));if(!stay)continue;if(stay.type==='node'){const n=g.nodes.get(stay.id);poses.push({id:item.id,cargoId:item.cargoId,x:n.x,z:n.z,y:n.height,heading:0,state:'transfer',resourceId:n.resourceId});}else edgeItems.get(stay.id).push({item,stay});}
 for(const [id,current]of edgeItems){if(!current.length)continue;const e=g.edges.get(id),stops=intervals(p.stops.filter(s=>s.edgeId===id)),a=g.nodes.get(e.from),b=g.nodes.get(e.to);current.sort((x,y)=>x.stay.start-y.stay.start||x.item.order-y.item.order);const previous=run.items.flatMap(i=>i.stays.filter(s=>s.type==='edge'&&s.id===id&&s.end!==null&&s.end<=t)).sort((x,y)=>y.end-x.end)[0];let front=previous?e.length+activeElapsed(previous.end,t,stops)*(e.length/e.travel):Infinity;for(const {item,stay}of current){const elapsed=activeElapsed(stay.start,t,stops),distance=stay.offset+elapsed*(e.length/e.travel),d=Math.max(0,Math.min(e.length,distance,front-e.pitch));front=d;const ratio=d/e.length,stopped=activeAt(t,stops)>t+EPS;poses.push({id:item.id,cargoId:item.cargoId,x:a.x+(b.x-a.x)*ratio,z:a.z+(b.z-a.z)*ratio,y:a.height+(b.height-a.height)*ratio,heading:Math.atan2(b.z-a.z,b.x-a.x),state:stopped?'stopped':d>=e.length-1e-6||d+1e-6<Math.min(e.length,distance)?'waiting':'moving',edgeId:id});}}
 return {time:t,poses};
}
return {Heap,rng,intervals,activeAt,activeAdd,activeElapsed,Simulation,run,metrics,snapshot};
});
