(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.CvModel=api;})(globalThis,function(){
'use strict';
const VERSION='1.0.0',SCHEMA='conveyor/project@1',clone=x=>JSON.parse(JSON.stringify(x));
const kinds={straight:'직선',merge:'T · 합류',split:'T · 분기',cross:'+ · 교차',h:'H · 연결',u:'U · 회송',loop:'우회 루프'};
const cargoDefaults=[{id:'PLT',name:'팔레트',kind:'pallet',length:1.2,width:1,height:1,weight:700,color:'#c7955c'},{id:'BOX',name:'박스',kind:'box',length:.6,width:.4,height:.4,weight:20,color:'#deaa6c'},{id:'TOTE',name:'토트',kind:'tote',length:.6,width:.4,height:.32,weight:30,color:'#5b9dbe'}];
const node=(id,x,z,type='junction',extra={})=>({id,name:id,x,z,height:.8,type,cycle:type==='junction'?3:type==='sink'?4:1,policy:'fifo',resourceId:id,peerType:'none',peerId:'',...extra});
const edge=(id,from,to,extra={})=>({id,from,to,speed:.4,pitch:1.5,gap:.2,width:1.2,payload:1000,mode:'continuous',mechanism:'roller',accel:.5,decel:.5,dwell:.3,initial:0,initialCargo:'PLT',initialSink:'OUT1',...extra});
function preset(kind='h'){
 const p={schemaVersion:SCHEMA,moduleId:'CV-01',name:kinds[kind]+' 컨베이어 물동량 검토',horizon:3600,warmup:300,seed:20260915,arrival:'periodic',demandMode:'rates',target:.85,cargo:clone(cargoDefaults),nodes:[],edges:[],flows:[],stops:[],history:[]};
 const n=(...args)=>p.nodes.push(node(...args)),e=(a,b,x={})=>p.edges.push(edge('CV'+String(p.edges.length+1).padStart(2,'0'),a,b,x)),f=(a,b,r,c='PLT',priority=1)=>p.flows.push({id:'OD'+(p.flows.length+1),from:a,to:b,cargoId:c,rate:r,priority});
 if(kind==='straight'){n('IN1',-12,0,'source');n('OUT1',12,0,'sink');e('IN1','OUT1');f('IN1','OUT1',600);}
 if(kind==='merge'){n('IN1',-12,0,'source');n('IN2',0,10,'source');n('J1',0,0);n('OUT1',12,0,'sink');e('IN1','J1');e('IN2','J1');e('J1','OUT1');f('IN1','OUT1',400);f('IN2','OUT1',300,'BOX');}
 if(kind==='split'){n('IN1',-12,0,'source');n('J1',0,0);n('OUT1',12,0,'sink');n('OUT2',0,10,'sink');e('IN1','J1');e('J1','OUT1');e('J1','OUT2');f('IN1','OUT1',420);f('IN1','OUT2',280,'TOTE');}
 if(kind==='cross'){n('IN1',-12,0,'source');n('IN2',0,-10,'source');n('X1',0,0,'junction',{cycle:4});n('OUT1',12,0,'sink');n('OUT2',0,10,'sink');e('IN1','X1');e('IN2','X1');e('X1','OUT1');e('X1','OUT2');f('IN1','OUT1',320);f('IN1','OUT2',160,'BOX');f('IN2','OUT1',160,'TOTE');f('IN2','OUT2',240);}
 if(kind==='h'){n('IN1',-12,-6,'source');n('IN2',-12,6,'source');n('J1',0,-6,'junction',{cycle:4,policy:'roundRobin'});n('J2',0,6,'junction',{cycle:4,policy:'roundRobin'});n('OUT1',12,-6,'sink',{cycle:6,peerType:'stacker-crane',peerId:'STC-01'});n('OUT2',12,6,'sink',{cycle:6,peerType:'rgv_linear',peerId:'RGV-01'});e('IN1','J1');e('IN2','J2');e('J1','J2');e('J1','OUT1');e('J2','OUT2');f('IN1','OUT1',280);f('IN1','OUT2',220,'BOX');f('IN2','OUT2',300,'TOTE');}
 if(kind==='u'){n('IN1',-12,-5,'source');n('J1',10,-5);n('J2',10,5);n('OUT1',-12,5,'sink');e('IN1','J1');e('J1','J2');e('J2','OUT1');f('IN1','OUT1',600);}
 if(kind==='loop'){n('IN1',-16,0,'source');n('J1',-8,0);n('J2',8,0);n('B1',-8,8);n('B2',8,8);n('OUT1',16,0,'sink');e('IN1','J1');e('J1','J2',{speed:.06});e('J1','B1');e('B1','B2');e('B2','J2');e('J2','OUT1');f('IN1','OUT1',500);}
 if(!p.nodes.length)throw Error('알 수 없는 배치');return p;
}
function hash(x){const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);let h=2166136261;for(const c of canonical(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function profile(length,v,a,d){const peak=Math.min(v,Math.sqrt(2*length/(1/a+1/d))),ta=peak/a,td=peak/d,cruise=Math.max(0,(length-peak*peak/2*(1/a+1/d))/peak);return {length,v:peak,a,d,ta,td,cruise,duration:ta+cruise+td};}
function position(q,t){t=Math.max(0,Math.min(t,q.duration));if(t<=q.ta)return .5*q.a*t*t;const sa=.5*q.a*q.ta*q.ta;if(t<=q.ta+q.cruise)return sa+q.v*(t-q.ta);const u=t-q.ta-q.cruise;return Math.min(q.length,sa+q.v*q.cruise+q.v*u-.5*q.d*u*u);}
function graph(p){const nodes=new Map(p.nodes.map(n=>[n.id,n])),edges=new Map(),adj=new Map(p.nodes.map(n=>[n.id,[]]));for(const e of p.edges){const a=nodes.get(e.from),b=nodes.get(e.to);if(!a||!b)continue;const length=Math.hypot(a.x-b.x,a.z-b.z,a.height-b.height),capacity=Math.floor((length+1e-8)/e.pitch),zone=length/Math.max(capacity,1),motion=profile(zone,e.speed,e.accel,e.decel),headway=e.mode==='zpa'?motion.duration+e.dwell:e.pitch/e.speed,travel=e.mode==='zpa'?capacity*headway:length/e.speed;const q={...e,length,capacity,zone,motion,headway,travel};edges.set(e.id,q);adj.get(e.from).push(q);}return {nodes,edges,adj};}
function route(g,from,to){const dist=new Map([[from,0]]),prev=new Map(),done=new Set();while(true){let cur=null,best=Infinity;for(const [k,v]of dist)if(!done.has(k)&&v<best){cur=k;best=v;}if(cur===null)return null;if(cur===to)break;done.add(cur);if(cur!==from&&g.nodes.get(cur)?.type!=='junction')continue;for(const e of g.adj.get(cur)||[]){const cost=best+e.travel+g.nodes.get(e.to).cycle;if(cost<(dist.get(e.to)??Infinity)){dist.set(e.to,cost);prev.set(e.to,e);}}}const ids=[];let id=to;while(id!==from){const e=prev.get(id);if(!e)return null;ids.unshift(e.id);id=e.from;}return ids;}
function validate(p){
 const errors=[],warnings=[],err=s=>errors.push(s),num=(v,min,max,label,int=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max||(int&&!Number.isInteger(v)))err(label+': '+min+'~'+max+(int?' 정수':'')+' 필요');},id=(v,label)=>{if(typeof v!=='string'||!/^[-A-Za-z0-9_가-힣]{1,60}$/.test(v))err(label+': 영문·숫자·한글·밑줄·하이픈 1~60자 필요');};
 if(!p||p.schemaVersion!==SCHEMA)return {errors:['컨베이어 프로젝트 '+SCHEMA+' 형식이 필요합니다.'],warnings};
 for(const k of ['nodes','edges','flows','cargo','stops','history'])if(!Array.isArray(p[k]))err(k+' 목록 누락');if(errors.length)return {errors,warnings};
 if(typeof p.name!=='string'||p.name.length>200)err('프로젝트 이름: 200자 이하 문자열 필요');id(p.moduleId,'모듈 ID');num(p.horizon,60,86400,'운전시간 s');num(p.warmup,0,p.horizon-1,'준비운전 s');num(p.seed,0,4294967295,'난수 시드',true);num(p.target,.1,.95,'목표 부하율');
 if(!['periodic','poisson'].includes(p.arrival))err('도착 방식 오류');if(!['rates','history'].includes(p.demandMode))err('수요 모드 오류');
 if(p.nodes.length<2||p.nodes.length>100||p.edges.length<1||p.edges.length>180||p.flows.length>150||p.cargo.length<1||p.cargo.length>12||p.stops.length>100||p.history.length>30000)err('입력 상한: 노드 100, 구간 180, OD 150, 화물 12, 정지 100, 작업 30,000');
 const ns=new Set(),es=new Set(),cs=new Set(),fs=new Set(),all=new Set();
 for(const c of p.cargo){if(!c||typeof c!=='object'){err('화물 행 오류');continue;}id(c.id,'화물 ID');if(cs.has(c.id))err('화물 ID 중복: '+c.id);cs.add(c.id);if(!['pallet','box','tote'].includes(c.kind))err(c.id+': 화물 유형 오류');for(const k of ['length','width','height'])num(c[k],.05,10,c.id+' '+k);num(c.weight,.01,100000,c.id+' 중량');if(typeof c.name!=='string'||c.name.length>100)err('화물 이름 오류');if(!/^#[0-9a-f]{6}$/i.test(c.color))err('화물 색상 오류');}
 for(const n of p.nodes){if(!n||typeof n!=='object'){err('노드 행 오류');continue;}id(n.id,'노드 ID');if(ns.has(n.id))err('노드 ID 중복: '+n.id);ns.add(n.id);all.add(n.id);num(n.x,-500,500,n.id+' X');num(n.z,-500,500,n.id+' Z');num(n.height,.1,30,n.id+' 높이');num(n.cycle,0,600,n.id+' 이재주기');if(!['source','junction','sink'].includes(n.type))err(n.id+': 노드 유형 오류');if(!['fifo','roundRobin','priority'].includes(n.policy))err(n.id+': 합류 정책 오류');id(n.resourceId,n.id+' 자원 ID');if(!['none','stacker-crane','rgv_linear','rgv_loop','shuttle_4way','agv_amr'].includes(n.peerType))err(n.id+': 연결 설비 유형 오류');if(typeof n.peerId!=='string'||n.peerId.length>100)err(n.id+': 연결 설비 ID 오류');}
 for(const e of p.edges){if(!e||typeof e!=='object'){err('구간 행 오류');continue;}id(e.id,'구간 ID');if(es.has(e.id)||all.has(e.id))err('구간/노드 ID 중복: '+e.id);es.add(e.id);if(!ns.has(e.from)||!ns.has(e.to)||e.from===e.to)err(e.id+': 시작/끝 노드 오류');for(const [k,min,max]of [['speed',.01,5],['pitch',.1,20],['gap',0,5],['width',.1,20],['payload',1,100000],['accel',.01,10],['decel',.01,10],['dwell',0,600]])num(e[k],min,max,e.id+' '+k);num(e.initial,0,1000,e.id+' 초기 점유',true);if(!['continuous','zpa'].includes(e.mode)||!['roller','belt','chain'].includes(e.mechanism))err(e.id+': 운전/기계 형식 오류');if(!cs.has(e.initialCargo))err(e.id+': 초기 화물 유형 없음');}
 for(const f of p.flows){if(!f||typeof f!=='object'){err('OD 행 오류');continue;}id(f.id,'OD ID');if(fs.has(f.id))err('OD ID 중복: '+f.id);fs.add(f.id);num(f.rate,0,30000,f.id+' 수요');num(f.priority,0,100,f.id+' 우선순위',true);if(!cs.has(f.cargoId))err(f.id+': 화물 유형 없음');}
 if(errors.length)return {errors,warnings};const g=graph(p),paths=new Map();
 for(const n of p.nodes){if(n.type==='source'&&p.edges.some(e=>e.to===n.id))err(n.id+': 입구로 들어오는 구간은 연결할 수 없습니다.');if(n.type==='sink'&&(g.adj.get(n.id)||[]).length)err(n.id+': 출구에서 나가는 구간은 연결할 수 없습니다.');}
 for(const f of p.flows){if(g.nodes.get(f.from)?.type!=='source'||g.nodes.get(f.to)?.type!=='sink'){err(f.id+': 입구 → 출구 연결 필요');continue;}const path=route(g,f.from,f.to);if(!path?.length)err(f.id+': 연결 경로 없음');else paths.set(f.id,path);}
 const used=new Map(p.edges.map(e=>[e.id,new Set()]));for(const f of p.flows)if(f.rate>0||p.demandMode==='history')for(const eid of paths.get(f.id)||[])used.get(eid).add(f.cargoId);
 for(const e of g.edges.values())if(e.initial){used.get(e.id).add(e.initialCargo);const tail=route(g,e.to,e.initialSink);if(g.nodes.get(e.initialSink)?.type!=='sink'||!tail)err(e.id+': 초기 화물 출구 경로 없음');else for(const eid of tail)used.get(eid).add(e.initialCargo);}
 for(const e of g.edges.values()){if(e.capacity<1)err(e.id+': 구간 길이가 존 피치보다 짧습니다.');if(e.capacity>600)err(e.id+': 존 수 600 초과');if(e.initial>e.capacity)err(e.id+': 초기 점유가 물리 용량을 초과합니다.');for(const cid of used.get(e.id)){const c=p.cargo.find(c=>c.id===cid);if(e.pitch+1e-9<c.length+e.gap)err(e.id+': '+c.name+' 길이 + 간격 ≤ 피치 조건 필요');if(e.width+1e-9<c.width+.1)err(e.id+': '+c.name+' 폭 + 100 mm ≤ 컨베이어 폭 조건 필요');if(e.payload<c.weight)err(e.id+': '+c.name+' 중량이 허용하중을 초과합니다.');}if(g.nodes.get(e.from).height!==g.nodes.get(e.to).height)warnings.push(e.id+': 경사 구간은 3차원 거리로 계산하며 미끄럼·경사 동력은 계산하지 않습니다.');}
 for(let i=0;i<p.nodes.length;i++)for(let j=0;j<i;j++){const a=p.nodes[i],b=p.nodes[j];if(Math.hypot(a.x-b.x,a.z-b.z,a.height-b.height)<.01)err(a.id+'/'+b.id+': 같은 위치의 노드는 하나의 공통 노드로 합치세요.');}
 for(let i=0;i<p.edges.length;i++)for(let j=0;j<i;j++){const a=p.edges[i],b=p.edges[j];if(a.from===b.from&&a.to===b.to||a.from===b.to&&a.to===b.from)err(a.id+'/'+b.id+': 같은 위치에 중복/반대방향 컨베이어를 배치할 수 없습니다. 별도 좌표로 분리하세요.');}
 // At-grade crossings must be explicitly connected to a mutually exclusive junction.
 const cross=(a,b)=>a.x*b.z-a.z*b.x,sub=(a,b)=>({x:a.x-b.x,z:a.z-b.z});
 for(let i=0;i<p.edges.length;i++)for(let j=0;j<i;j++){const e=p.edges[i],f=p.edges[j];if([e.from,e.to].some(n=>n===f.from||n===f.to))continue;const a=g.nodes.get(e.from),b=g.nodes.get(e.to),c=g.nodes.get(f.from),d=g.nodes.get(f.to),r=sub(b,a),s=sub(d,c),den=cross(r,s);if(Math.abs(den)<1e-8)continue;const t=cross(sub(c,a),s)/den,u=cross(sub(c,a),r)/den;if(t>1e-6&&t<1-1e-6&&u>1e-6&&u<1-1e-6&&Math.abs(a.height+t*(b.height-a.height)-c.height-u*(d.height-c.height))<Math.max(...p.cargo.map(c=>c.height))+.3)err(e.id+'/'+f.id+': 평면 교차점에 공통 이재 노드를 추가하세요.');}
 for(const s of p.stops){if(!s||!es.has(s.edgeId)){err('정지 구간 ID 오류');continue;}num(s.start,0,p.horizon,'정지 시작');num(s.end,s.start+.001,p.horizon,'정지 종료');}
 const hs=new Set();for(const h of p.history){if(!h||!fs.has(h.flowId)){err('작업 이력 OD 없음');continue;}id(h.id,'작업 ID');if(hs.has(h.id))err('작업 ID 중복: '+h.id);hs.add(h.id);num(h.release,0,p.horizon-.000001,'작업 발생 s');}
 const expected=p.flows.reduce((a,f)=>a+f.rate,0)*p.horizon/3600;if(p.demandMode==='rates'&&expected>30000)err('예상 투입 30,000개 초과: 운전시간 또는 수요를 줄이세요.');
 if(p.edges.reduce((a,e)=>a+e.initial,0)>3000)err('초기 화물 3,000개 초과');if(p.demandMode==='history'&&!p.history.length)warnings.push('작업 이력이 비어 있어 신규 화물이 투입되지 않습니다.');
 warnings.push('고정 경로 · 유한 버퍼 모델. 혼합 화물도 구간에 설정한 단일 존 피치를 사용합니다.','연속 구간은 가감속 없이 이송하고, ZPA 구간은 존마다 정지·재출발합니다.','후단 인계는 입력한 주기로 모사합니다. 연결 설비의 실제 동시 운전은 후속 통합 대상입니다.');return {errors:[...new Set(errors)],warnings:[...new Set(warnings)]};
}
function calculate(p){const check=validate(p);if(check.errors.length)throw Error(check.errors.join('\n'));const g=graph(p),resources=new Map(),flows=[];for(const e of g.edges.values())resources.set('edge:'+e.id,{id:e.id,type:'구간',capacity:3600/e.headway,headway:e.headway,travel:e.travel,slots:e.capacity,load:0});for(const n of p.nodes)if(!resources.has('node:'+n.resourceId))resources.set('node:'+n.resourceId,{id:n.resourceId,type:'이재/인계',capacity:Infinity,headway:0,load:0,work:0});
 let demand=0;for(const f of p.flows){const rate=p.demandMode==='history'?p.history.filter(h=>h.flowId===f.id).length*3600/p.horizon:f.rate,path=route(g,f.from,f.to),nodes=[f.from,...path.map(id=>g.edges.get(id).to)];demand+=rate;for(const id of path)resources.get('edge:'+id).load+=rate;for(const id of nodes){const n=g.nodes.get(id),r=resources.get('node:'+n.resourceId);r.load+=rate;r.work+=rate*n.cycle;}flows.push({...f,rate,path,lead: path.reduce((a,id)=>a+g.edges.get(id).travel,0)+nodes.reduce((a,id)=>a+g.nodes.get(id).cycle,0)});}
 const rows=[...resources.values()];for(const r of rows){if(r.type!=='구간'){r.headway=r.load?r.work/r.load:0;r.capacity=r.headway?3600/r.headway:Infinity;}r.util=r.capacity===Infinity?0:r.load/r.capacity;r.status=r.util<=p.target?'적정':r.util<=.95?'주의':r.util<=1?'위험':'처리불가';}const limiting=rows.filter(r=>r.load>0).sort((a,b)=>b.util-a.util)[0];const upper=demand&&limiting?.util?demand/limiting.util:null;return {demand,upper,targetCapacity:upper===null?null:upper*p.target,resources:rows,flows,bottleneck:limiting?.id??'—',warnings:check.warnings,totalSlots:[...g.edges.values()].reduce((a,e)=>a+e.capacity,0)};
}
function pack(p){const v=validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));return {schemaVersion:SCHEMA,deviceType:'conveyor',moduleVersion:VERSION,units:{distance:'m',speed:'m/s',acceleration:'m/s2',time:'s',weight:'kg',quantity:'handling-unit'},config:clone(p)};}
function unpack(doc){if(doc?.schemaVersion!==SCHEMA||doc.deviceType!=='conveyor'||doc.moduleVersion?.split('.')[0]!=='1'||doc.units?.distance!=='m'||doc.units?.speed!=='m/s'||doc.units?.time!=='s'||doc.units?.weight!=='kg'||doc.units?.acceleration!=='m/s2'||doc.units?.quantity!=='handling-unit')throw Error('지원하는 컨베이어 프로젝트 JSON과 SI 단위 규격이 아닙니다.');const p=clone(doc.config),v=validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));return p;}
return {VERSION,SCHEMA,kinds,cargoDefaults,node,edge,preset,hash,clone,profile,position,graph,route,validate,calculate,pack,unpack};
});
