const test=require('node:test'),assert=require('node:assert/strict');
const Model=require('../src/model'),Excel=require('../src/excel'),Xlsx=require('../src/xlsx');
const rows=(c=Model.defaults,e)=>Object.fromEntries(Object.entries(Excel.sheets(c,e)).map(([name,s])=>[name,s.rows]));
const basic=(b,key)=>b.기본조건.find(r=>r[0]===key);
function same(a,b){if(typeof a==='number')assert.ok(Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(a)),`${a} != ${b}`);else if(Array.isArray(a)){assert.equal(a.length,b.length);a.forEach((v,i)=>same(v,b[i]));}else if(a&&typeof a==='object'){assert.deepEqual(Object.keys(a).sort(),Object.keys(b).sort());for(const k of Object.keys(a))same(a[k],b[k]);}else assert.equal(a,b);}
test('Every design field and all five tables are exported, with experiment controls',()=>{const b=rows();assert.equal(b.기본조건.length-1,Object.values(Model.defaults).filter(v=>!Array.isArray(v)).length);assert.equal(Object.keys(b).length,8);assert.equal(b.설비스테이션.length,5);assert.equal(b.OD물동량.length,5);same(Model.defaults,Excel.fromSheets(b).config);});
test('All five supplied scenarios round-trip',()=>{for(const k of ['default','single','congested','block','history'])same(Model.preset(k),Excel.fromSheets(rows(Model.preset(k))).config);});
test('Nondefault units, pure handling display, profile, speed zones, history and experiments survive',()=>{const c=Model.clone(Model.defaults);Object.assign(c,{distanceUnit:'mm',speedUnit:'m/s',handlingMode:'detail',unit:'TOTE',direction:'reverse',batchSize:2,arrival:'poisson',basis:'',basisNote:'한글 <&> _x0041_ =1+1',name:'비율과 단위 검토'});c.stations[0].name='A & B <입고>';c.profile=[{start:0,end:15,multiplier:1.2},{start:15,end:33,multiplier:.8}];c.zones=[{from:5,to:8,v:.8}];c.history=[{time:12,from:'P1',to:'D1',quantity:2}];const e={fleetMin:6,fleetMax:10,fleetStep:2,repCount:5},b=rows(c,e),out=Excel.fromSheets(b);assert.equal(basic(b,'horizontal')[2],60);assert.equal(basic(b,'emptyV')[2],120);assert.equal(b.설비스테이션[1][3],6);assert.equal(b.시간대비율[1][2],1.2);assert.equal(b.제한속도[1][2],48);same(c,out.config);assert.deepEqual(out.experiment,e);});
test('Edited workbook cells are authoritative and affect calculated demand',()=>{const b=rows();basic(b,'vehicles')[2]=10;b.OD물동량[1][3]=60;b.시간대비율.push([0,33,1.5]);b.설비스테이션[3][6]=12;const c=Excel.fromSheets(b).config;assert.equal(c.vehicles,10);same(Model.calculate(c).total,270);assert.equal(c.stations[2].takeaway,12);});
test('Empty optional sheets clear prior data, basic rows and table columns can be reordered',()=>{const b=rows();b.기본조건=[b.기본조건[0],...b.기본조건.slice(1).reverse()];b.OD물동량=b.OD물동량.map(r=>[r[3],r[0],r[2],r[1]]);const c=Excel.fromSheets(b).config;same(c,Model.defaults);assert.deepEqual(c.profile,[]);});
test('Blank numeric value is rejected rather than converted to zero',()=>{const b=rows();basic(b,'horizontal')[2]='';assert.throws(()=>Excel.fromSheets(b),/기본조건.*수평 직선 길이/);b.설비스테이션[1][5]=' ';assert.throws(()=>Excel.fromSheets(b),/설비스테이션 2행.*출고 버퍼/);});
test('Missing, duplicate and unknown fields or sheets cannot silently reset conditions',()=>{let b=rows();b.기본조건.splice(2,1);assert.throws(()=>Excel.fromSheets(b),/필수 항목 누락/);b=rows();b.기본조건[2]=[...b.기본조건[1]];assert.throws(()=>Excel.fromSheets(b),/중복/);b=rows();delete b.시간대비율;assert.throws(()=>Excel.fromSheets(b),/시간대비율.*시트/);b=rows();b.Other=[['a']];assert.throws(()=>Excel.fromSheets(b),/지원하지 않는 시트/);});
test('Station references and actual worksheet row numbers appear in errors',()=>{const b=rows();b.OD물동량.splice(1,0,[],[]);b.OD물동량[3][1]='MISSING';assert.throws(()=>Excel.fromSheets(b),/MISSING \(OD물동량 4행 출발 ID\)/);});
test('Overlapping time bands and 120 entered instead of 120% are rejected',()=>{const b=rows();b.시간대비율.push([0,20,1.2],[15,33,1]);assert.throws(()=>Excel.fromSheets(b),/시간대비율 3행/);b.시간대비율=[[...b.시간대비율[0]],[0,33,120]];assert.throws(()=>Excel.fromSheets(b),/비율.*0~10/);});
test('Units, total handling, batch sizes and fleet geometry are validated',()=>{let b=rows();basic(b,'horizontal')[3]='mm';assert.throws(()=>Excel.fromSheets(b),/단위는 m/);b=rows();b.설비스테이션[1][3]=.5;assert.throws(()=>Excel.fromSheets(b),/총 상차시간/);b=rows();b.작업이력.push([0,'P1','D1',2]);assert.throws(()=>Excel.fromSheets(b),/작업이력 2행 수량/);b=rows();basic(b,'horizontal')[2]=.1;basic(b,'vertical')[2]=.1;assert.throws(()=>Excel.fromSheets(b));});
test('Experiment constraints and non-LOOP workbooks are rejected',()=>{let b=rows();b.실험조건[4][2]=2;assert.throws(()=>Excel.fromSheets(b),/반복 횟수/);b=rows();b.안내[1][1]='other@1';assert.throws(()=>Excel.fromSheets(b),/LOOP RGV 엑셀 양식/);});
test('XLSX package contains typed numbers, literal text, percent formats and drop-downs',async()=>{const c=Model.clone(Model.defaults);c.name='=1+1';c.basisNote='_x0041_ & <한글>';const files=await Xlsx.unzip(await Excel.write(c).arrayBuffer());assert.match(files['xl/worksheets/sheet2.xml'],/t="inlineStr"[^]*=1\+1/);assert.match(files['xl/worksheets/sheet2.xml'],/_x005F_x0041_/);assert.match(files['xl/worksheets/sheet2.xml'],/<dataValidations/);assert.match(files['xl/worksheets/sheet3.xml'],/<v>10\.652<\/v>/);assert.match(files['xl/styles.xml'],/numFmtId="10"/);assert.equal(Object.keys(files).filter(n=>n.startsWith('xl/worksheets/')).length,8);});
test('Corrupted, truncated and oversized ZIP inputs fail safely',async()=>{const buffer=await Excel.write(Model.defaults).arrayBuffer(),broken=buffer.slice(0);new Uint8Array(broken)[80]^=1;await assert.rejects(Xlsx.unzip(broken));await assert.rejects(Xlsx.unzip(buffer.slice(0,100)),/xlsx/);await assert.rejects(Xlsx.unzip(new ArrayBuffer(Xlsx.MAX_FILE+1)),/10 MB/);});
test('20,000 history rows remain typed and within supported file limits',async()=>{const c=Model.clone(Model.defaults);c.history=Array.from({length:20000},(_,i)=>({time:i/20,from:'P1',to:'D1',quantity:1}));c.demandMode='history';same(c,Excel.fromSheets(rows(c)).config);const blob=Excel.write(c);assert.ok(blob.size<Xlsx.MAX_FILE);});
