const test=require('node:test'),assert=require('node:assert/strict'),Model=require('../src/model'),Excel=require('../src/excel'),E=require('../src/engine');
function manyStations(count=100,hours=8){
 const c=Model.clone(Model.defaults);Object.assign(c,{name:count+'개 스테이션 / '+hours+'시간',hours,peak:1,jitter:0});
 const half=count/2,L=Model.length(c);c.stations=Array.from({length:count},(_,i)=>({id:(i<half?'P':'D')+(i%half+1),name:'스테이션 '+(i+1),s:L*i/count,load:6,unload:6,buffer:8,takeaway:0}));
 c.ods=Array.from({length:half},(_,i)=>({id:'OD'+(i+1),from:'P'+(i+1),to:'D'+(i+1),rate:1}));return c;
}
const rows=c=>Object.fromEntries(Object.entries(Excel.sheets(c)).map(([n,s])=>[n,s.rows]));
test('100 stations, P23+ and D23+ references, and 8-hour workbook import',()=>{const c=manyStations(),restored=Excel.fromSheets(rows(c)).config;assert.equal(restored.stations.length,100);assert.equal(restored.hours,8);assert.equal(restored.ods.at(-1).to,'D50');assert.deepEqual(restored.stations,c.stations);assert.equal(Model.calculate(restored).total,50);});
test('Upper supported limits: 200 stations and 24 hours in both JSON and Excel',()=>{const c=manyStations(200,24);assert.equal(Model.validate(c).stations.length,200);assert.equal(Excel.fromSheets(rows(c)).config.hours,24);assert.equal(Model.unpack(Model.pack(c)).stations.length,200);const a=Model.calculate(c);assert.equal(a.total,100);assert.equal(a.legRows.length,100);});
test('New limits still reject oversized station sets and 25-hour input',()=>{const c=manyStations(202,24);assert.throws(()=>Model.validate(c),/200/);const b=rows(manyStations());b.기본조건.find(r=>r[0]==='hours')[2]=25;assert.throws(()=>Excel.fromSheets(b),/입력값 "25".*0.05~24/);b.기본조건.find(r=>r[0]==='hours')[2]='8시간';assert.throws(()=>Excel.fromSheets(b),/시간 h.*8시간=8/);});
test('A large station table does not invent stations for missing OD references',()=>{const b=rows(manyStations());b.설비스테이션=b.설비스테이션.filter(r=>!['P23','P24','D39'].includes(r[0]));const before=JSON.stringify(b);let message='';try{Excel.fromSheets(b);}catch(e){message=e.message;}assert.match(message,/없는 ID 3개: P23, P24, D39/);assert.match(message,/실제 위치·상하차시간·버퍼/);assert.ok(message.split('\n').length<=6);assert.equal(JSON.stringify(b),before);});
test('Large and small equivalent station sets give identical simulation results',()=>{const c=Model.clone(Model.defaults);c.hours=.05;c.warmup=0;c.vehicles=2;c.ods=c.ods.slice(0,1);const large=Model.clone(c);for(let i=0;i<96;i++)large.stations.push({id:'S'+i,name:'추가 '+i,s:Model.length(c)*(i+.5)/96,load:6,unload:6,buffer:8,takeaway:0});const a=E.run(c).snapshot(),b=E.run(large).snapshot();for(const k of ['created','delivered','shipped','waiting','active','output','throughput','p95Wait','minGap'])assert.equal(a[k],b[k]);assert.ok(b.conserved&&b.gapOK);});
test('24-hour horizon actually completes and conserves cargo',()=>{const c=Model.preset('history');Object.assign(c,{hours:24,vehicles:1,parking:'stay',warmup:0,timeStep:.2});c.history=c.history.slice(0,1);const out=E.run(c).snapshot();assert.equal(out.time,86400);assert.ok(out.complete&&out.conserved&&out.gapOK);assert.equal(out.shipped,1);});
module.exports={manyStations};
