const test=require('node:test'),assert=require('node:assert/strict');
const Model=require('../src/model'),Tables=require('../src/tables'),Excel=require('../src/excel'),Engine=require('../src/engine');
function close(a,b){if(typeof a==='number')assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(a)));else if(Array.isArray(a)){assert.equal(a.length,b.length);a.forEach((v,i)=>close(v,b[i]));}else if(a&&typeof a==='object'){assert.deepEqual(Object.keys(a).sort(),Object.keys(b).sort());for(const k of Object.keys(a))close(a[k],b[k]);}else assert.equal(a,b);}
const book=c=>Object.fromEntries(Object.entries(Excel.sheets(c)).map(([k,v])=>[k,v.rows]));
function config(n=3){const c=Model.clone(Model.defaults);c.ods=[];c.stations=Array.from({length:n*2},(_,i)=>({...Model.defaults.stations[0],id:(i<n?'P':'D')+(i%n+1),s:i*Model.length(c)/(n*2),name:'자동 표 '+i}));return c;}
test('Station pairs generate zero-rate OD rows, never all-to-all or incomplete pairs',()=>{const c=config();c.stations.push({...c.stations[0],id:'P4'},{...c.stations[0],id:'CUSTOM'});const r=Tables.reconcile(c);assert.deepEqual(r.config.ods.map(o=>[o.from,o.to,o.rate]),[['P1','D1',0],['P2','D2',0],['P3','D3',0]]);assert.equal(c.ods.length,0);assert.deepEqual(Tables.reconcile(r.config).added,[]);});
test('Existing cross-pair OD IDs, zero values and quantities are retained',()=>{const c=config();c.ods=[{id:'OD2',from:'P1',to:'D1',rate:0},{id:'CUSTOM',from:'P1',to:'D3',rate:12.5}];const r=Tables.reconcile(c);assert.deepEqual(r.config.ods.slice(0,2),c.ods);assert.equal(r.added.length,2);assert.equal(new Set(r.config.ods.map(o=>o.id)).size,4);});
test('Missing-reference records are returned intact for review while valid data remains',()=>{const c=config();c.ods=[{id:'A',from:'P1',to:'D1',rate:12},{id:'B',from:'P23',to:'D1',rate:8},{id:'C',from:'P2',to:'D58',rate:9}];const r=Tables.reconcile(c);assert.deepEqual(r.removed,c.ods.slice(1));assert.equal(r.config.ods[0].rate,12);assert.equal(c.ods.length,3);assert.equal(r.added.length,2);assert.ok(r.config.ods.every(o=>c.stations.some(s=>s.id===o.from)&&c.stations.some(s=>s.id===o.to)));});
test('An explicit station rename updates both OD and history without changing quantities',()=>{const c=config();c.ods=[{id:'A',from:'P1',to:'D1',rate:12}];c.history=[{time:1,from:'P1',to:'D1',quantity:1}];c.stations[0].id='IN01';const r=Tables.reconcile(c,{renames:{P1:'IN01'}});assert.equal(r.config.ods[0].from,'IN01');assert.equal(r.config.ods[0].rate,12);assert.equal(r.config.history[0].from,'IN01');assert.equal(r.removed.length,0);assert.equal(r.orphanedHistory.length,0);});
test('Duplicate station IDs cannot cause automatic data removal or a guessed connection',()=>{const c=config();c.stations[1].id='P1';assert.throws(()=>Tables.reconcile(c),/중복/);const ambiguous=config(1);ambiguous.stations.push({...ambiguous.stations[0],id:'P01'});const r=Tables.reconcile(ambiguous);assert.equal(r.added.length,0);assert.equal(r.warnings.length,1);});
test('Hourly table covers warmup, full hours and last partial hour, including 24h',()=>{const c=config();c.hours=8.25;c.warmup=3;const p=Tables.reconcile(c).config.profile;assert.equal(p.length,10);assert.deepEqual(p[0],{start:0,end:3,multiplier:1});assert.deepEqual(p.at(-1),{start:483,end:498,multiplier:1});for(let i=1;i<p.length;i++)assert.equal(p[i].start,p[i-1].end);c.hours=24;assert.equal(Tables.reconcile(c).config.profile.length,25);c.warmup=0;assert.equal(Tables.reconcile(c).config.profile.length,24);});
test('Duration changes preserve entered ratios, extend with 100%, and respect manual tables',()=>{const c=Tables.reconcile(config()).config;c.profile[1].multiplier=.75;c.hours=2.5;const p=Tables.reconcile(c,{rebuildProfile:true}).config.profile;assert.deepEqual(p.map(x=>x.multiplier),[1,.75,1,1]);c.periodTableMode='manual';c.profile=[{start:10,end:20,multiplier:1.2}];assert.deepEqual(Tables.reconcile(c,{rebuildProfile:true}).config.profile,c.profile);c.odTableMode='manual';c.ods=[];c.profile=[];const r=Tables.reconcile(c);assert.equal(r.config.ods.length,0);assert.equal(r.config.profile.length,0);});
test('Automatic 100% rows preserve exact arrival sequences for takt and Poisson modes',()=>{for(const arrival of ['takt','poisson']){const c=Model.clone(Model.defaults);c.arrival=arrival;c.hours=2.5;assert.deepEqual(new Engine.Engine(c).arrivals,new Engine.Engine(Tables.reconcile(c).config).arrivals);}});
test('Legacy workbooks without mode fields generate empty tables and retain custom periods',()=>{let c=config(),b=book(c);b.기본조건=b.기본조건.filter(r=>!['odTableMode','periodTableMode'].includes(r[0]));const r=Excel.fromSheets(b,{reconcile:true});assert.equal(r.config.ods.length,3);assert.equal(r.config.profile.length,2);assert.equal(r.config.odTableMode,'paired');c.profile=[{start:2,end:20,multiplier:.8}];b=book(c);b.기본조건=b.기본조건.filter(r=>!['odTableMode','periodTableMode'].includes(r[0]));const old=Excel.fromSheets(b,{reconcile:true});assert.equal(old.config.periodTableMode,'manual');assert.deepEqual(old.config.profile,c.profile);});
test('Screenshot case: 56 missing IDs are reviewable and repair round-trips in Excel',()=>{const c=config(58);c.hours=8;c.ods=Array.from({length:58},(_,i)=>({id:'OD'+(i+1),from:'P'+(i+1),to:'D'+(i+1),rate:1}));const b=book(c);b.설비스테이션=b.설비스테이션.filter((r,i)=>!i||!(r[0].startsWith('P')&&+r[0].slice(1)>22||r[0].startsWith('D')&&+r[0].slice(1)>38));assert.throws(()=>Excel.fromSheets(b),/없는 ID 56개/);const r=Excel.fromSheets(b,{reconcile:true});assert.equal(r.repair.removed.length,36);assert.equal(r.repair.removedRowNumbers[0],24);assert.equal(r.config.stations.length,60);assert.equal(r.config.ods.length,22);assert.equal(r.config.profile.length,9);close(Excel.fromSheets(book(r.config)).config,r.config);});
test('Reconciliation never masks malformed quantities, station specs, periods or history',()=>{const c=config(),b=book(c);b.OD물동량.push(['BAD','P99','D1',-2]);assert.throws(()=>Excel.fromSheets(b,{reconcile:true}),/물동량/);b.OD물동량.pop();b.작업이력.push([1,'P99','D1',1]);assert.throws(()=>Excel.fromSheets(b,{reconcile:true}),/P99/);b.작업이력.pop();b.시간대비율.push([0,20,1],[10,30,1]);assert.throws(()=>Excel.fromSheets(b,{reconcile:true}),/겹치지/);});
test('Manual and auto settings survive project JSON and workbook serialization',()=>{for(const mode of ['manual','paired']){const c=Tables.reconcile(config()).config;c.odTableMode=mode;c.periodTableMode='manual';assert.deepEqual(Model.unpack(Model.pack(c)),c);close(Excel.fromSheets(book(c)).config,c);}});
