(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model'));else root.ShuttleEngine=factory(root.ShuttleModel);})(globalThis,function(Model){
'use strict';const EPS=1e-8;
const states={idle:'대기',route_wait:'예약 대기',empty:'공차 이동',loaded:'적재 이동',turn:'방향 전환',position:'정위치',load:'상차',unload:'하차',lift_move:'승강',lift_load:'리프트 상차',lift_unload:'리프트 하차'};
function rng(seed){let n=seed>>>0;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function percentile(values,q){if(!values.length)return 0;const a=values.slice().sort((x,y)=>x-y),p=(a.length-1)*q,k=Math.floor(p);return a[k]+(a[Math.min(k+1,a.length-1)]-a[k])*(p-k);}
function interval95(a){const n=a.length,mean=n?a.reduce((a,b)=>a+b,0)/n:0,sd=n>1?Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/(n-1)):0,t={1:12.706,2:4.303,3:3.182,4:2.776};return{n,mean,ci95:n>1?(t[n-1]||1.96)*sd/Math.sqrt(n):null};}
class Heap{constructor(){this.items=[];this.sequence=0;}less(a,b){return a.time<b.time||a.time===b.time&&a.seq<b.seq;}push(time,fn){const a=this.items,x={time,fn,seq:++this.sequence};a.push(x);let i=a.length-1;while(i){const p=(i-1)>>1;if(!this.less(a[i],a[p]))break;[a[i],a[p]]=[a[p],a[i]];i=p;}}peek(){return this.items[0];}pop(){const a=this.items,first=a[0],last=a.pop();if(a.length){a[0]=last;let i=0;while(true){let j=i,l=i*2+1,r=l+1;if(l<a.length&&this.less(a[l],a[j]))j=l;if(r<a.length&&this.less(a[r],a[j]))j=r;if(j===i)break;[a[i],a[j]]=[a[j],a[i]];i=j;}}return first;}}
class Calendar{
constructor(){this.byResource=new Map();this.guard=.05;this.bookings=0;}
requests(plan){const map=new Map();for(const p of plan.phases)if(p.duration>0)for(const key of p.resources){if(!map.has(key))map.set(key,[]);map.get(key).push({from:p.start-this.guard,to:p.start+p.duration+this.guard});}const req=[];for(const[key,rows]of map){rows.sort((a,b)=>a.from-b.from);let item=null;for(const r of rows){if(item&&r.from<=item.to+EPS)item.to=Math.max(item.to,r.to);else{item={key,...r};req.push(item);}}}return req;}
reserve(plan,earliest,owner){const req=this.requests(plan);let start=earliest,tries=0;while(true){let shift=0;for(const r of req)for(const b of this.byResource.get(r.key)||[])if(b.owner!==owner&&b.to>start+r.from+EPS&&b.from<start+r.to-EPS)shift=Math.max(shift,b.to-(start+r.from)+EPS);if(shift<=EPS)break;start+=shift;if(++tries>20000)throw Error('경로 예약 탐색 한도. 배치·대수를 줄이세요.');}
for(const r of req){if(!this.byResource.has(r.key))this.byResource.set(r.key,[]);this.byResource.get(r.key).push({from:Math.max(0,start+r.from),to:start+r.to,owner,booking:this.bookings});}this.bookings++;return start;}
at(time){return[...this.byResource].map(([key,rows])=>({key,owners:[...new Set(rows.filter(r=>r.from<=time+EPS&&r.to>time+EPS).map(r=>r.owner))]})).filter(r=>r.owners.length);}
audit(){for(const rows of this.byResource.values()){const a=rows.slice().sort((x,y)=>x.from-y.from);for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length&&a[j].from<a[i].to-EPS;j++)if(a[j].owner!==a[i].owner)return false;}return true;}}
class Engine{
constructor(input){const c=this.config=Model.validate(input);this.time=0;this.warmup=c.warmup*60;this.horizon=this.warmup+c.hours*3600;this.heap=new Heap();this.calendar=new Calendar();this.jobs=[];this.jobById=new Map();this.tus=new Map();this.slots=Model.slots(c);this.slotById=new Map(this.slots.map(s=>[s.id,s]));this.levelSlots=Array.from({length:c.levels},(_,i)=>this.slots.filter(s=>s.level===i));this.floors=c.layers.map((l,i)=>({id:l.id,level:i,ins:[],outs:[],incoming:0,outReserved:0,maxIn:0,maxOut:0}));this.output=[];this.outputReserved=0;this.outputRelease=Infinity;this.maxOutput=0;this.initialStock=0;this.arrivedIn=0;this.arrivedOut=0;this.completedIn=0;this.completedOut=0;this.measuredIn=0;this.measuredOut=0;this.shipped=0;this.measuredShipped=0;this.logs=[];this.series=[];this.lastSample=-Infinity;this.queueArea=0;this.maxQueue=0;this.events=0;this.failed=null;this.pickRandom=rng(c.seed^0x771133);
const initialRandom=rng(c.seed^0x43AB21);for(const rows of this.levelSlots){const shuffled=rows.slice();for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(initialRandom()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}for(const slot of shuffled.slice(0,Math.floor(rows.length*c.initialFill))){const id='I'+String(++this.initialStock).padStart(6,'0');slot.tu=id;this.tus.set(id,{id,where:'stock',level:slot.level,slot:slot.id});}}
const actor=(id,kind,extra)=>({id,kind,...extra,current:null,plans:[],stats:Object.fromEntries(Object.keys(states).map(k=>[k,0])),cycles:0,dual:0,handled:0,measuredHandled:0});
this.cars=c.layers.flatMap((l,level)=>Array.from({length:l.shuttles},(_,local)=>actor('S'+(level+1)+'-'+(local+1),'shuttle',{level,local})));this.lifts=Array.from({length:c.numLifts},(_,index)=>actor('L'+(index+1),'lift',{index}));this.actors=[...this.cars,...this.lifts];this.arrivals=this.generate();for(const a of this.arrivals)this.heap.push(a.time,()=>this.arrive(a));this.advanceTo(0);this.sample();}
generate(){const c=this.config;if(c.demandMode==='history')return c.history.map((j,i)=>({...j,order:i})).sort((a,b)=>a.time-b.time||a.order-b.order);const out=[];c.layers.forEach((l,level)=>{for(const type of ['in','out']){const rate=l[type==='in'?'inbound':'outbound']*c.peak;if(!rate)continue;const random=rng(c.seed^(level+1)*17309^(type==='in'?0x53221:0xA213)),gap=()=>c.arrival==='poisson'?-Math.log(Math.max(1e-12,1-random()))*3600/rate:3600/rate*(1+c.jitter*(2*random()-1));for(let time=gap();time<=this.horizon+EPS;time+=gap()){out.push({time,type,level,order:out.length});if(out.length>20000)throw Error('실제 생성 작업 20,000건 한도입니다.');}}});return out.sort((a,b)=>a.time-b.time||a.order-b.order);}
arrive(a){const id='J'+String(this.jobs.length+1).padStart(6,'0'),job={id,type:a.type,level:a.level,arrival:a.time,dispatch:null,complete:null,status:a.type==='in'?'waiting_in':'waiting_out',tu:null,slot:null};if(a.type==='in'){this.arrivedIn++;job.tu='T'+id;this.tus.set(job.tu,{id:job.tu,where:'groundIn',level:a.level,slot:null});}else this.arrivedOut++;this.jobs.push(job);this.jobById.set(id,job);}
freeSlots(level,type){return this.levelSlots[level].filter(s=>type==='in'?!s.tu&&!s.reservedIn&&!s.reservedOut:s.tu&&!s.reservedOut&&!s.reservedIn);}
selectSlot(level,type){const rows=this.freeSlots(level,type);if(!rows.length)return null;if(this.config.storage==='nearest'||type==='out'&&this.config.dispatch==='nearest')return rows.sort((a,b)=>a.x+a.z-b.x-b.z||a.id.localeCompare(b.id))[0];return rows[Math.floor(this.pickRandom()*rows.length)];}
stamp(j){if(j.dispatch===null)j.dispatch=this.time;}
sortJobs(rows,actor){const cost=j=>actor.kind==='lift'?Model.height(this.config,j.level):j.slot?j.slot.x+j.slot.z:Math.min(Infinity,...this.freeSlots(j.level,'out').map(s=>s.x+s.z));return rows.slice().sort((a,b)=>this.config.dispatch==='nearest'?(cost(a)-cost(b)||a.arrival-b.arrival||a.id.localeCompare(b.id)):(a.arrival-b.arrival||a.id.localeCompare(b.id)));}
setWhere(job,where){const tu=this.tus.get(job.tu);if(!tu)throw Error('화물 소유권 없음: '+job.id);tu.where=where;tu.level=job.level;tu.slot=where==='stock'?job.slot.id:null;}
complete(job){if(job.complete!==null)throw Error('작업 중복 완료');job.complete=this.time;job.status='complete';if(job.type==='in'){this.completedIn++;if(this.time>=this.warmup-EPS)this.measuredIn++;}else{this.completedOut++;if(this.time>=this.warmup-EPS)this.measuredOut++;}this.logs.push({id:job.id,type:job.type,level:job.level+1,tu:job.tu,slot:job.slot?.id||'',arrival:job.arrival,dispatch:job.dispatch,complete:this.time,wait:job.dispatch-job.arrival,lead:this.time-job.arrival,measured:this.time>=this.warmup-EPS});}
remove(list,job){const i=list.indexOf(job);if(i<0)throw Error('버퍼 작업 소유권 오류');list.splice(i,1);}
action(a,actor){if(!a)return;const j=this.jobById.get(a.job),f=this.floors[j.level];switch(a.kind){
case 'liftTakeIn':this.setWhere(j,'lift');break;
case 'liftPutIn':actor.handled++;if(this.time>=this.warmup-EPS)actor.measuredHandled++;this.setWhere(j,'floorIn');f.incoming--;f.ins.push(j);f.maxIn=Math.max(f.maxIn,f.ins.length);j.status='floor_in';break;
case 'takeIn':this.remove(f.ins,j);this.setWhere(j,'shuttle');break;
case 'store':if(j.slot.tu||j.slot.reservedIn!==j.id)throw Error('저장 셀 예약 오류');j.slot.tu=j.tu;j.slot.reservedIn=null;this.setWhere(j,'stock');this.complete(j);actor.handled++;if(this.time>=this.warmup-EPS)actor.measuredHandled++;break;
case 'retrieve':if(j.slot.tu!==j.tu||j.slot.reservedOut!==j.id)throw Error('출고 재고 예약 오류');j.slot.tu=null;j.slot.reservedOut=null;this.setWhere(j,'shuttle');break;
case 'floorOut':this.setWhere(j,'floorOut');f.outReserved--;f.outs.push(j);f.maxOut=Math.max(f.maxOut,f.outs.length);j.status='floor_out';actor.handled++;if(this.time>=this.warmup-EPS)actor.measuredHandled++;break;
case 'liftTakeOut':this.remove(f.outs,j);this.setWhere(j,'lift');break;
case 'liftPutOut':actor.handled++;if(this.time>=this.warmup-EPS)actor.measuredHandled++;this.setWhere(j,'groundOut');this.outputReserved--;this.output.push(j);this.maxOutput=Math.max(this.maxOutput,this.output.length);this.complete(j);if(this.output.length===1)this.nextRelease();break;
default:throw Error('알 수 없는 인계 이벤트');}}
nextRelease(){if(!this.output.length){this.outputRelease=Infinity;return;}this.outputRelease=this.time+this.config.outputTakeaway;this.heap.push(this.outputRelease,()=>{const j=this.output.shift();this.setWhere(j,'shipped');this.shipped++;if(this.time>=this.warmup-EPS)this.measuredShipped++;this.nextRelease();});}
assign(actor,plan,jobs){const start=this.calendar.reserve(plan,this.time,actor.id),task={...plan,start,end:start+plan.duration,assigned:this.time,jobs:jobs.map(j=>j.id)};actor.current=task;actor.plans.push(task);for(const j of jobs)this.stamp(j);for(const p of plan.phases){this.heap.push(start+p.start,()=>{});this.heap.push(start+p.start+p.duration,()=>this.action(p.action,actor));}this.heap.push(task.end,()=>{actor.current=null;actor.cycles++;if(jobs.length===2)actor.dual++;});return task;}
dispatch(){const c=this.config;let changed=false;
for(const car of this.cars){if(car.current)continue;const f=this.floors[car.level],ins=this.sortJobs(f.ins.filter(j=>j.status==='floor_in'),car),outs=this.sortJobs(this.jobs.filter(j=>j.type==='out'&&j.level===car.level&&j.status==='waiting_out'&&f.outs.length+f.outReserved<c.floorBuffer&&this.freeSlots(j.level,'out').length),car);let incoming=ins[0]||null,outgoing=outs[0]||null;if(c.cycleMode==='single'&&incoming&&outgoing){if(this.sortJobs([incoming,outgoing],car)[0]===outgoing)incoming=null;else outgoing=null;}if(!incoming&&!outgoing)continue;
if(outgoing){outgoing.slot=this.selectSlot(car.level,'out');outgoing.tu=outgoing.slot.tu;outgoing.slot.reservedOut=outgoing.id;f.outReserved++;outgoing.status='shuttle_out';}if(incoming)incoming.status='shuttle_in';this.assign(car,Model.shuttlePlan(c,car,incoming,outgoing),[incoming,outgoing].filter(Boolean));changed=true;}
for(const lift of this.lifts){if(lift.current)continue;const ins=this.sortJobs(this.jobs.filter(j=>j.status==='waiting_in'&&this.floors[j.level].ins.length+this.floors[j.level].incoming<c.floorBuffer&&this.freeSlots(j.level,'in').length),lift),outs=this.sortJobs(this.floors.flatMap(f=>f.outs.filter(j=>j.status==='floor_out')),lift);let incoming=ins[0]||null,outgoing=this.output.length+this.outputReserved<c.outputBuffer?outs[0]||null:null;
if(c.cycleMode==='single'&&incoming&&outgoing){if(this.sortJobs([incoming,outgoing],lift)[0]===outgoing)incoming=null;else outgoing=null;}if(!incoming&&!outgoing)continue;
if(incoming){incoming.slot=this.selectSlot(incoming.level,'in');incoming.slot.reservedIn=incoming.id;this.floors[incoming.level].incoming++;incoming.status='lift_in';}if(outgoing){this.outputReserved++;outgoing.status='lift_out';}this.assign(lift,Model.liftPlan(c,lift,incoming,outgoing),[incoming,outgoing].filter(Boolean));changed=true;}
return changed;}
actorPose(actor,time=this.time){if(!actor.current){const p=actor.kind==='lift'?Model.liftPoint(this.config,actor.index):Model.park(this.config,actor);return{...p,v:0,axis:actor.kind==='lift'?'y':'z',state:'idle',tu:null};}return Model.phaseAt(actor.current,time-actor.current.start);}
integrate(to){const from=Math.max(this.time,this.warmup),end=Math.min(to,this.horizon),dt=Math.max(0,end-from);if(!dt)return;for(const a of this.actors)a.stats[this.actorPose(a,(this.time+to)/2).state]+=dt;const q=this.jobs.filter(j=>j.dispatch===null).length;this.queueArea+=q*dt;this.maxQueue=Math.max(this.maxQueue,q);}
advanceTo(target){if(!Number.isFinite(target)||target<this.time-EPS)throw Error('과거 시각은 같은 입력으로 초기화하여 재계산하세요.');target=Math.min(target,this.horizon);try{let guard=0;while(this.heap.peek()&&this.heap.peek().time<=target+EPS){const time=Math.max(this.time,Math.min(target,this.heap.peek().time));this.integrate(time);this.time=time;while(this.heap.peek()&&this.heap.peek().time<=time+EPS){this.heap.pop().fn();this.events++;if(++guard>2000000)throw Error('이벤트 처리 한도');}this.dispatch();this.checkBuffers();if(this.time-this.lastSample>=this.horizon/240)this.sample();}this.integrate(target);this.time=target;if(this.time>=this.horizon-EPS&&this.lastSample!==this.time)this.sample();}catch(e){this.failed=e.message;throw e;}return this;}
checkBuffers(){const c=this.config;if(this.output.length+this.outputReserved>c.outputBuffer||this.outputReserved<0)throw Error('지상 출고 버퍼 용량 침범');for(const f of this.floors)if(f.ins.length+f.incoming>c.floorBuffer||f.outs.length+f.outReserved>c.floorBuffer||f.incoming<0||f.outReserved<0)throw Error('층 버퍼 용량 침범');}
sample(){this.lastSample=this.time;this.series.push({time:this.time,queue:this.jobs.filter(j=>j.dispatch===null).length,backlog:this.jobs.filter(j=>j.complete===null).length,inbound:this.completedIn,outbound:this.completedOut,stock:[...this.tus.values()].filter(t=>t.where==='stock').length});}
snapshot(){const c=this.config,measuredTime=Math.max(0,this.time-this.warmup),scale=measuredTime?3600/measuredTime:0,where={stock:0,groundIn:0,lift:0,floorIn:0,shuttle:0,floorOut:0,groundOut:0,shipped:0};for(const tu of this.tus.values())where[tu.where]=(where[tu.where]||0)+1;const physicalStock=this.slots.filter(s=>s.tu),conserved=Object.values(where).reduce((a,b)=>a+b,0)===this.initialStock+this.arrivedIn&&physicalStock.length===where.stock&&new Set(physicalStock.map(s=>s.tu)).size===physicalStock.length;
const waits=this.jobs.filter(j=>j.dispatch!==null&&j.dispatch>=this.warmup-EPS).map(j=>j.dispatch-j.arrival),pending=this.jobs.filter(j=>j.dispatch===null),snapshotActor=a=>({id:a.id,kind:a.kind,level:a.level,index:a.index,local:a.local,...this.actorPose(a),stateTime:{...a.stats},busy:measuredTime?1-(a.stats.idle+a.stats.route_wait)/measuredTime:0,routeWait:a.stats.route_wait,cycles:a.cycles,dual:a.dual,handled:a.handled,throughput:a.measuredHandled*scale,task:a.current?.jobs.join(' + ')||''});
return{time:this.time,horizon:this.horizon,complete:this.time>=this.horizon-EPS,failed:this.failed,measuredTime,throughput:(this.measuredIn+this.measuredOut)*scale,inbound:this.measuredIn*scale,outbound:this.measuredOut*scale,shippingRate:this.measuredShipped*scale,completedIn:this.completedIn,completedOut:this.completedOut,arrivedIn:this.arrivedIn,arrivedOut:this.arrivedOut,initialStock:this.initialStock,stock:where.stock,shipped:this.shipped,where,conserved,waiting:pending.length,backlog:this.jobs.filter(j=>j.complete===null).length,p95Wait:percentile(waits,.95),p95Lead:percentile(this.logs.filter(j=>j.measured).map(j=>j.lead),.95),oldest:pending.reduce((n,j)=>Math.max(n,this.time-j.arrival),0),meanQueue:measuredTime?this.queueArea/measuredTime:0,maxQueue:this.maxQueue,cars:this.cars.map(snapshotActor),lifts:this.lifts.map(snapshotActor),floors:this.floors.map(f=>({...f,ins:f.ins.length,outs:f.outs.length,capacity:c.floorBuffer,inbound:this.logs.filter(j=>j.type==='in'&&j.level===f.level+1&&j.measured).length*scale,outbound:this.logs.filter(j=>j.type==='out'&&j.level===f.level+1&&j.measured).length*scale,stock:this.levelSlots[f.level].filter(s=>s.tu).length})),output:{count:this.output.length,reserved:this.outputReserved,capacity:c.outputBuffer,max:this.maxOutput},stockWaiting:pending.filter(j=>j.type==='out'&&!this.freeSlots(j.level,'out').length).length,spaceWaiting:pending.filter(j=>j.type==='in'&&!this.freeSlots(j.level,'in').length).length,reservations:this.calendar.at(this.time),events:this.events,gridlock:this.time>5&&this.jobs.some(j=>j.complete===null)&&this.actors.every(a=>!a.current)&&!this.output.length};}
}
function run(c){const e=new Engine(c);return e.advanceTo(e.horizon);}
return{Engine,Calendar,Heap,run,states,rng,percentile,interval95};
});

