(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./motion'));else root.ShuttleModel=factory(root.ShuttleMotion);})(globalThis,function(M){
'use strict';const VERSION='0.1.0',SCHEMA='shuttle-4way/project@1',clone=x=>JSON.parse(JSON.stringify(x));
const defaults={name:'4-way 셔틀 설계 검토',system:'tierCaptive',cargoType:'pallet',distanceUnit:'m',speedUnit:'m/min',levels:4,bays:20,aisles:3,bayPitch:1.4,aislePitch:3.6,levelPitch:2.2,baseHeight:1.2,firstBay:2.4,carLength:1.1,carWidth:.8,gap:.2,cargoLength:1.2,cargoWidth:1,cargoHeight:1.4,cargoMass:800,shuttleLimit:1500,liftLimit:1500,
xEmptyV:3,xLoadedV:2,xEmptyA:.8,xLoadedA:.6,xEmptyD:.8,xLoadedD:.6,zEmptyV:1.5,zLoadedV:1,zEmptyA:.5,zLoadedA:.4,zEmptyD:.5,zLoadedD:.4,liftV:2,liftA:.8,liftD:.8,turn:1.5,position:.3,shuttleTransfer:3,liftTransfer:3,liftPosition:.3,
numLifts:1,floorBuffer:4,outputBuffer:8,outputTakeaway:0,cycleMode:'dual',dispatch:'fifo',storage:'random',peak:1.2,targetUtil:.8,A:1,Ew:1,basis:'assumption',basisNote:'초기 A=1, Ew=1은 손실 없는 비교 가정입니다. 현장 실측값으로 바꾸세요.',
hours:.5,warmup:3,seed:20260911,arrival:'takt',jitter:.1,initialFill:.5,demandMode:'rate',history:[],layers:Array.from({length:4},(_,i)=>({id:'F'+(i+1),shuttles:1,inbound:30,outbound:30}))};
const fields={
levels:['층수','층',1,8,1,'층별 셔틀과 수요 행을 자동으로 맞춥니다.'],bays:['통로당 베이 수','개',1,40,1,'양쪽에 단일 깊이 저장 셀을 둡니다.'],aisles:['통로 수','개',1,6,1,'전면 크로스레일로 연결합니다.'],bayPitch:['베이 피치','distance',.3,5,.1,'x 방향 셀 간격입니다.'],aislePitch:['통로 피치','distance',1,10,.1,'z 방향 통로 중심 간격입니다.'],levelPitch:['층 피치','distance',.3,6,.1,'y 방향 층 간격입니다.'],baseHeight:['첫 층 높이','distance',0,10,.1,'공통 지상 I/O 높이 0에서 첫 층까지 거리입니다.'],firstBay:['첫 베이 거리','distance',.5,10,.1,'크로스레일 x=0에서 첫 베이까지 거리입니다.'],carLength:['차체 길이','distance',.2,3,.1,'통로 점유와 설명용 3D 차체에 사용합니다.'],carWidth:['차체 폭','distance',.2,2,.1,'화물·통로 간격 적합성 검사에 사용합니다.'],gap:['배치 여유','distance',.05,1,.05,'차체·화물과 베이/통로의 기하학적 여유입니다.'],
cargoLength:['화물 길이','distance',.2,3,.1,'베이 피치 방향입니다.'],cargoWidth:['화물 폭','distance',.2,3,.1,'랙 깊이와 통로 피치 검사에 사용합니다.'],cargoHeight:['화물 높이','distance',.1,4,.1,'층 피치 ≥ 화물 높이 + 설명용 차체 높이(0.14~0.28m) + 여유 0.2m.'],cargoMass:['화물 중량','kg',1,3000,10,'셔틀과 리프트 정격 이하이어야 합니다.'],shuttleLimit:['셔틀 정격','kg',1,5000,50,'벤더 사양을 입력하세요.'],liftLimit:['리프트 정격','kg',1,5000,50,'화물 리프트 정격입니다.'],
liftV:['승강 최대속도','speed',.05,5,.1,'공차·적재 공통 사양입니다.'],liftA:['승강 가속도','m/s²',.05,5,.1,'승강 시작 가속도입니다.'],liftD:['승강 감속도','m/s²',.05,5,.1,'승강 정지 감속도입니다.'],turn:['방향 전환','s/회',0,30,.1,'x와 z 방향이 바뀔 때 정지한 뒤 적용합니다.'],position:['셔틀 정위치','s/정지',0,10,.1,'각 이동 구간 종료에 한 번 적용합니다.'],shuttleTransfer:['셔틀 이재','s/회',.1,60,.1,'상차·하차 각각의 순수 이재시간입니다.'],liftTransfer:['리프트 인계','s/회',.1,60,.1,'리프트 상하차와 층 버퍼 연결 인계를 포함한 시간입니다.'],liftPosition:['리프트 정위치','s/정지',0,10,.1,'실제로 이동한 승강 구간마다 적용합니다.'],
numLifts:['화물 리프트 수','대',1,4,1,'각각 독립 샤프트, 모든 층 공용 서비스, 화물 1개 적재입니다.'],floorBuffer:['층별 입·출고 버퍼','개/방향',1,20,1,'입고와 출고에 각각 적용하며 사전 예약합니다.'],outputBuffer:['지상 출고 버퍼','개',1,100,1,'리프트 하차 전 빈 공간을 예약합니다.'],outputTakeaway:['외부 반출 간격','s/개',0,600,1,'0이면 지상 하차 즉시 외부 출하입니다.'],
peak:['피크 계수','배',1,5,.1,'층별 요구량에 한 번 곱합니다. 작업이력에는 적용하지 않습니다.'],targetUtil:['목표 부하율','ratio',.1,1,.05,'0.8은 80%. 분석 필요 대수에 설계 여유를 반영합니다.'],A:['가용도 A','ratio',.01,1,.01,'분석 용량에 적용. 시뮬레이션에 고장 이벤트는 없습니다.'],Ew:['작업효율 Ew','ratio',.01,1,.01,'분석 용량에 한 번 적용하며 관측 결과에는 다시 곱하지 않습니다.'],
hours:['측정 시간','h',.05,4,.25,'준비운전 이후 측정시간입니다.'],warmup:['준비운전 제외','min',0,120,1,'재고·차량·대기 상태를 유지하고 통계에서만 제외합니다.'],seed:['난수 시드','정수',0,4294967295,1,'같은 초기 재고와 도착을 재현합니다.'],jitter:['도착 변동폭','ratio',0,.95,.05,'일정간격 도착의 ±변동 비율입니다.'],initialFill:['초기 적재율','ratio',0,1,.05,'층별 실제 저장 셀에 초기 재고를 배치합니다. 출고는 실제 재고가 있어야 합니다.']};
for(const axis of ['x','z'])for(const state of ['Empty','Loaded'])for(const k of ['V','A','D'])fields[axis+state+k]=[axis.toUpperCase()+' '+(state==='Empty'?'공차':'적재')+' '+({V:'속도',A:'가속도',D:'감속도'})[k],k==='V'?'speed':'m/s²',.05,k==='V'?6:5,.1,'축별·적재 상태별 사양. X와 Z는 순차 이동합니다.'];
const integerKeys=new Set(['levels','bays','aisles','numLifts','floorBuffer','outputBuffer','seed']);
function height(c,level){return c.baseHeight+level*c.levelPitch;}
function point(c,level,aisle,bay){return{x:c.firstBay+bay*c.bayPitch,y:height(c,level),z:(aisle+1)*c.aislePitch,aisle,bay};}
function home(c,level){return{x:0,y:height(c,level),z:0};}
function park(c,car){return{x:-2*Math.max(2,c.carLength*2,c.cargoLength*2),y:height(c,car.level),z:-(car.local+1)*(Math.max(c.carWidth,c.cargoWidth)+c.gap)};}
function liftPoint(c,index,level=-1){return{x:-5-index*(c.cargoWidth+1),y:level<0?0:height(c,level),z:0};}
function slots(c){const out=[];for(let l=0;l<c.levels;l++)for(let a=0;a<c.aisles;a++)for(let b=0;b<c.bays;b++)for(let side=0;side<2;side++)out.push({id:'F'+(l+1)+'-A'+(a+1)+'-B'+(b+1)+'-'+(side?'R':'L'),level:l,aisle:a,bay:b,side,...point(c,l,a,b),tu:null,reservedIn:null,reservedOut:null});return out;}
function number(n,min,max,label,int=false){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max||int&&!Number.isInteger(n))throw Error(label+': '+min+'~'+max+(int?' 정수':' 숫자')+' 범위를 확인하세요.');}
function validate(input){const c=clone(input);for(const[k,[label,,min,max]]of Object.entries(fields))number(c[k],min,max,label,integerKeys.has(k));
const enums={system:['tierCaptive'],cargoType:['pallet','tote','box'],distanceUnit:['m','mm'],speedUnit:['m/min','m/s'],cycleMode:['single','dual'],dispatch:['fifo','nearest'],storage:['random','nearest'],basis:['','assumption','measured','vendor'],arrival:['takt','poisson'],demandMode:['rate','history']};for(const[k,v]of Object.entries(enums))if(!v.includes(c[k]))throw Error(k+' 선택을 확인하세요. 층고정 TU 리프트만 지원합니다.');
if(typeof c.name!=='string'||!c.name.trim()||c.name.length>160)throw Error('프로젝트명은 1~160자입니다.');if(typeof c.basisNote!=='string'||c.basisNote.length>500)throw Error('보정 근거는 500자 이내입니다.');
if(Math.max(c.cargoLength,c.carLength)+c.gap>c.bayPitch+1e-8)throw Error('베이 피치는 화물·차체 길이 + 여유 이상이어야 합니다.');
if(Math.max(c.carWidth,c.cargoWidth)+2*c.cargoWidth+2*c.gap>c.aislePitch+1e-8)throw Error('통로 피치는 주행 폭 + 양쪽 랙 화물 폭 + 여유 이상이어야 합니다.');
if(c.cargoHeight+Math.max(.14,Math.min(.28,c.carLength*.22))+.2>c.levelPitch+1e-8)throw Error('층 피치는 화물·차체 높이 + 0.2m 여유 이상이어야 합니다.');if(c.firstBay<Math.max(c.carLength,c.cargoLength)+c.gap)throw Error('첫 베이 거리는 화물·차체 길이 + 여유 이상이어야 합니다.');if(c.cargoMass>Math.min(c.shuttleLimit,c.liftLimit))throw Error('화물 중량이 셔틀 또는 리프트 정격을 초과합니다.');
if(!Array.isArray(c.layers)||c.layers.length!==c.levels)throw Error('층수와 층별 입력 행 수를 맞추세요.');let totalCars=0;for(let i=0;i<c.layers.length;i++){const l=c.layers[i];if(l.id!=='F'+(i+1))throw Error('층 ID는 F1부터 순서대로 사용합니다.');number(l.shuttles,0,6,'층별 셔틀 대수',true);number(l.inbound,0,3000,'층별 입고 /h');number(l.outbound,0,3000,'층별 출고 /h');totalCars+=l.shuttles;}if(!totalCars)throw Error('셔틀을 1대 이상 배치하세요.');
if(!Array.isArray(c.history)||c.history.length>10000)throw Error('작업이력은 최대 10,000행입니다.');for(const j of c.history){number(j.time,0,(c.hours*60+c.warmup)*60,'이력 도착초');number(j.level,0,c.levels-1,'이력 층 번호',true);if(!['in','out'].includes(j.type))throw Error('이력 type은 in 또는 out입니다.');}
const expected=c.layers.reduce((n,l)=>n+l.inbound+l.outbound,0)*c.peak*(c.hours+c.warmup/60);if(c.demandMode==='rate'&&expected>10000)throw Error('예상 작업 10,000건 한도입니다. 수요 또는 시간을 줄이세요.');return c;}
function demand(c){return c.layers.map((l,i)=>{if(c.demandMode==='rate')return{level:i,inbound:l.inbound*c.peak,outbound:l.outbound*c.peak};const jobs=c.history.filter(j=>j.level===i&&j.time>=c.warmup*60&&j.time<=(c.warmup+c.hours*60)*60);return{level:i,inbound:jobs.filter(j=>j.type==='in').length/c.hours,outbound:jobs.filter(j=>j.type==='out').length/c.hours};});}
const cache=new Map();function motion(c,axis,distance,loaded){const prefix=axis+(loaded?'Loaded':'Empty'),spec=axis==='y'?{v:c.liftV,a:c.liftA,d:c.liftD}:{v:c[prefix+'V'],a:c[prefix+'A'],d:c[prefix+'D']},key=[distance,spec.v,spec.a,spec.d].join('|');if(!cache.has(key)){if(cache.size>5000)cache.clear();cache.set(key,M.solve(0,distance,spec));}return cache.get(key);}
class Planner{
constructor(c,actor){this.c=c;this.actor=actor;this.pos=actor.kind==='lift'?liftPoint(c,actor.index):park(c,actor);this.axis='x';this.t=0;this.phases=[];}
hold(duration,state,resources=[],action=null,tu=null){const p={start:this.t,duration,from:{...this.pos},to:{...this.pos},state,resources:[...new Set(resources)],action,tu,axis:this.axis,profile:null};this.phases.push(p);this.t+=duration;return p;}
move(to,axis,loaded,resources,tu=null){const d=Math.abs(to[axis]-this.pos[axis]);if(d<1e-9)return;if(axis!=='y'&&this.axis!==axis)this.hold(this.c.turn,'turn',resources,null,tu);this.axis=axis;const profile=motion(this.c,axis,d,loaded),p={start:this.t,duration:profile.duration,from:{...this.pos},to:{...to},state:axis==='y'?'lift_move':loaded?'loaded':'empty',resources:[...new Set(resources)],action:null,tu,axis,profile};this.phases.push(p);this.t+=p.duration;this.pos={...to};this.hold(axis==='y'?this.c.liftPosition:this.c.position,'position',resources,null,tu);}
route(to,loaded,tu=null){const c=this.c,l=this.actor.level,at=this.pos,node=z=>'F'+l+':N'+Math.round(z/c.aislePitch),aisle=z=>'F'+l+':A'+(Math.round(z/c.aislePitch)-1);
if(Math.abs(at.z-to.z)<1e-8){this.move({...to},'x',loaded,[aisle(to.z),node(to.z)],tu);return;}
if(Math.abs(this.pos.x)>1e-8)this.move({...this.pos,x:0},'x',loaded,[aisle(this.pos.z),node(this.pos.z)],tu);
const start=Math.round(this.pos.z/c.aislePitch),end=Math.round(to.z/c.aislePitch),step=end>start?1:-1;for(let a=start;a!==end;a+=step){const next=(a+step)*c.aislePitch;this.move({...this.pos,z:next},'z',loaded,['F'+l+':C'+Math.min(a,a+step),node(this.pos.z),node(next)],tu);}
if(Math.abs(to.x)>1e-8)this.move({...to},'x',loaded,[aisle(to.z),node(to.z)],tu);}
garage(out){const c=this.c,parking=park(c,this.actor),h=home(c,this.actor.level),feeder=parking.x/2,r=['F'+this.actor.level+':garage','F'+this.actor.level+':N0'];if(out){this.move({...parking,x:feeder},'x',false,r);this.move({...h,x:feeder},'z',false,r);this.move(h,'x',false,r);}else{this.move({...h,x:feeder},'x',false,r);this.move({...parking,x:feeder},'z',false,r);this.move(parking,'x',false,r);}}
finish(){return{duration:this.t,phases:this.phases,from:this.phases[0]?.from||this.pos,to:{...this.pos}};}}
function shuttlePlan(c,car,inJob=null,outJob=null){const actor={...car,kind:'shuttle'},p=new Planner(c,actor),l=car.level,node='F'+l+':N0';p.garage(true);if(inJob){p.hold(c.shuttleTransfer,'load',[node,'F'+l+':inDock'],{kind:'takeIn',job:inJob.id},inJob.tu);p.route(inJob.slot,true,inJob.tu);p.hold(c.shuttleTransfer,'unload',['F'+l+':A'+inJob.slot.aisle,'F'+l+':N'+(inJob.slot.aisle+1)],{kind:'store',job:inJob.id},inJob.tu);}
if(outJob){p.route(outJob.slot,false);p.hold(c.shuttleTransfer,'load',['F'+l+':A'+outJob.slot.aisle,'F'+l+':N'+(outJob.slot.aisle+1)],{kind:'retrieve',job:outJob.id},outJob.tu);p.route(home(c,l),true,outJob.tu);p.hold(c.shuttleTransfer,'unload',[node,'F'+l+':outDock'],{kind:'floorOut',job:outJob.id},outJob.tu);}else p.route(home(c,l),false);p.garage(false);return p.finish();}
function liftPlan(c,lift,inJob=null,outJob=null){const actor={...lift,kind:'lift'},p=new Planner(c,actor),ground=liftPoint(c,lift.index);if(inJob){p.hold(c.liftTransfer,'lift_load',['ground:in'],{kind:'liftTakeIn',job:inJob.id},inJob.tu);p.move(liftPoint(c,lift.index,inJob.level),'y',true,[],inJob.tu);p.hold(c.liftTransfer,'lift_unload',['F'+inJob.level+':liftIn'],{kind:'liftPutIn',job:inJob.id},inJob.tu);}
if(outJob){p.move(liftPoint(c,lift.index,outJob.level),'y',false,[]);p.hold(c.liftTransfer,'lift_load',['F'+outJob.level+':liftOut'],{kind:'liftTakeOut',job:outJob.id},outJob.tu);p.move(ground,'y',true,[],outJob.tu);p.hold(c.liftTransfer,'lift_unload',['ground:out'],{kind:'liftPutOut',job:outJob.id},outJob.tu);}else p.move(ground,'y',false,[]);return p.finish();}
function phaseAt(plan,t){if(t<0)return{...plan.from,v:0,axis:'x',state:'route_wait',tu:null,progress:0};if(t>=plan.duration-1e-9)return{...plan.to,v:0,axis:plan.phases.at(-1)?.axis||'x',state:'idle',tu:null,progress:1};const p=plan.phases.find(x=>x.duration>0&&t<x.start+x.duration-1e-9)||plan.phases.at(-1),dt=Math.max(0,t-p.start),q=p.profile?M.at(p.profile,dt):null;let pos={...p.from};if(q){const sign=Math.sign(p.to[p.axis]-p.from[p.axis]);pos[p.axis]+=sign*q.x;}return{...pos,v:q?q.v:0,axis:p.axis,state:p.state,tu:p.tu,progress:p.duration?dt/p.duration:1,phase:p};}
let analysisCache=null;
function horizontal(c){const keys=['bays','aisles','bayPitch','aislePitch','firstBay','carLength','carWidth','cargoWidth','cargoLength','gap','turn','position','shuttleTransfer',...Object.keys(fields).filter(k=>/^[xz](Empty|Loaded)/.test(k))],key=JSON.stringify(keys.map(k=>c[k]));if(analysisCache?.key===key)return analysisCache.value;
const pos=[];for(let a=0;a<c.aisles;a++)for(let b=0;b<c.bays;b++)pos.push(point(c,0,a,b));const car={level:0,local:0},n=pos.length,job=slot=>({id:'reference',tu:'TU',slot});let single=0,dual=0,empty=0,loaded=0;for(const a of pos){const p=shuttlePlan(c,car,job(a));single+=p.duration/n;empty+=p.phases.filter(p=>p.state==='empty').reduce((s,p)=>s+p.duration,0)/n;loaded+=p.phases.filter(p=>p.state==='loaded').reduce((s,p)=>s+p.duration,0)/n;for(const b of pos)dual+=shuttlePlan(c,car,job(a),job(b)).duration*(a===b?1:2)/(n*(2*n-1));}
const garage=[];for(let i=0;i<6;i++){const p=new Planner(c,{level:0,local:i,kind:'shuttle'});p.garage(true);p.garage(false);garage.push(p.t);}
const value={single,dual,empty,loaded,garage};analysisCache={key,value};return value;}
function calculate(input){const c=validate(input),rates=demand(c),h=horizontal(c),factor=c.basis?c.A*c.Ew:null,total=rates.reduce((s,x)=>s+x.inbound+x.outbound,0),liftSingles=rates.map(r=>liftPlan(c,{index:0},{id:'in',tu:'TU',level:r.level}).duration);
const layers=rates.map((r,i)=>{const n=c.layers[i].shuttles,pairs=c.cycleMode==='dual'?Math.min(r.inbound,r.outbound):0,singles=r.inbound+r.outbound-2*pairs,extra=n?h.garage.slice(0,n).reduce((a,b)=>a+b,0)/n-h.garage[0]:0,work=singles*(h.single+extra)+pairs*(h.dual+extra),nominal=r.inbound+r.outbound?3600*n*(r.inbound+r.outbound)/work:0,available=factor===null?null:nominal*factor,needed=0;let required=null;for(let m=1;m<=6;m++){const e=h.garage.slice(0,m).reduce((a,b)=>a+b,0)/m-h.garage[0],w=singles*(h.single+e)+pairs*(h.dual+e);if(factor!==null&&w<=3600*m*factor*c.targetUtil+1e-8){required=m;break;}}return{...r,id:'F'+(i+1),shuttles:n,pairs,singles,singleCycle:h.single+extra,dualCycle:h.dual+extra,work,nominal,available,util:factor&&n?work/(3600*n*factor):r.inbound+r.outbound?Infinity:0,required:r.inbound+r.outbound?required:0};});
const totalIn=rates.reduce((n,r)=>n+r.inbound,0),totalOut=rates.reduce((n,r)=>n+r.outbound,0),pairs=c.cycleMode==='dual'?Math.min(totalIn,totalOut):0;let liftWork=0,dualMean=0,singleMean=0;
for(const a of rates){const pi=totalIn?a.inbound/totalIn:0,po=totalOut?a.outbound/totalOut:0;liftWork+=(a.inbound-pairs*pi+a.outbound-pairs*po)*liftSingles[a.level];singleMean+=total?(a.inbound+a.outbound)/total*liftSingles[a.level]:0;for(const b of rates){const w=pi*(totalOut?b.outbound/totalOut:0),t=liftPlan(c,{index:0},{id:'in',tu:'TU',level:a.level},{id:'out',tu:'TU',level:b.level}).duration;dualMean+=w*t;liftWork+=pairs*w*t;}}
const constraints=layers.filter(r=>r.inbound+r.outbound>0).map(l=>({name:l.id+' 셔틀',scale:l.work?3600*l.shuttles/l.work:0,work:l.work,units:l.shuttles}));if(total)constraints.push({name:'공용 리프트',scale:liftWork?3600*c.numLifts/liftWork:0,work:liftWork,units:c.numLifts});if(totalOut&&c.outputTakeaway)constraints.push({name:'지상 외부 반출',scale:3600/(totalOut*c.outputTakeaway),work:totalOut*c.outputTakeaway,units:1,uncorrected:true});
const nominalScale=constraints.length?Math.min(...constraints.map(x=>x.scale)):0,effScale=factor===null?null:constraints.length?Math.min(...constraints.map(x=>x.scale*(x.uncorrected?1:factor))):0,bottleneck=constraints.slice().sort((a,b)=>a.scale*(a.uncorrected?1:factor??1)-b.scale*(b.uncorrected?1:factor??1))[0]?.name||'수요 없음',nominal=total*nominalScale,available=effScale===null?null:total*effScale;
const liftCapacity=liftWork?3600*c.numLifts*total/liftWork:0,liftRequired=factor&&liftWork?Math.ceil(liftWork/(3600*factor*c.targetUtil)):total?null:0,allRequired=layers.every(l=>l.required!==null)?layers.reduce((n,l)=>n+l.required,0):null;
const warnings=['층별 독립 재고 위치가 균일하다고 가정한 무경합 자원 업무량 분석입니다. 실제 경합·재고·버퍼는 시뮬레이션에서 확인하세요.','이중 사이클은 층별 입출고 중 작은 물량만 결합합니다. 시뮬레이션은 배차 시 준비된 작업끼리만 결합합니다.'];
if(liftRequired>4)warnings.push('필요 리프트가 현재 지원 범위 4대를 초과합니다. 사양·수요 또는 시스템 구성을 재검토하세요.');if(layers.some(l=>l.required===null)&&c.basis)warnings.push('일부 층은 셔틀 6대 이내로 목표 부하를 만족하지 못합니다. 사양·층별 수요를 재검토하세요.');if(totalOut*c.outputTakeaway>3600*c.targetUtil)warnings.push('외부 반출 능력이 목표 부하 기준 수요보다 작습니다. 셔틀·리프트 증설만으로 해결되지 않습니다.');if(!c.basis)warnings.push('보정 근거가 미선택이므로 추정 능력과 필요 대수는 미산정입니다.');if(layers.some(l=>!l.shuttles&&l.inbound+l.outbound>0))warnings.push('수요가 있는 층에 셔틀이 없습니다. 다른 층의 여유 대수로 대체할 수 없습니다.');if(totalOut&&c.initialFill===0)warnings.push('초기 재고가 없어 입고·적치가 끝나기 전까지 출고 요청이 기다립니다.');
return{config:c,version:VERSION,kernelVersion:M.VERSION,hash:hash(c),rates,layers,total,totalIn,totalOut,nominal,available,nominalIn:totalIn*nominalScale,nominalOut:totalOut*nominalScale,availableIn:effScale===null?null:totalIn*effScale,availableOut:effScale===null?null:totalOut*effScale,bottleneck,constraints,horizontal:h,lift:{work:liftWork,single:singleMean,dual:dualMean,pairs,capacity:liftCapacity,util:factor?liftWork/(3600*c.numLifts*factor):null,required:liftRequired},requiredShuttles:allRequired,balance:liftWork&&total?liftCapacity*layers.reduce((n,l)=>n+l.work,0)/(3600*total):0,ratio:available?total/available:null,shortage:available===null?null:Math.max(0,total-available*c.targetUtil),slots:c.levels*c.aisles*c.bays*2,warnings};}
function hash(c){let h=2166136261;for(const ch of JSON.stringify(c)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
function pack(c){return{schemaVersion:SCHEMA,deviceType:'shuttle_4way',moduleVersion:VERSION,kernelVersion:M.VERSION,axisConvention:{x:'aisle',y:'vertical',z:'crossrail'},units:{distance:'m',speed:'m/s',time:'s',acceleration:'m/s²'},config:validate(c)};}
function unpack(doc){if(doc?.schemaVersion!==SCHEMA||doc.deviceType!=='shuttle_4way'||doc.moduleVersion?.split('.')[0]!=='0')throw Error('지원하는 4-way 셔틀 프로젝트 JSON을 선택하세요.');if(doc.units?.distance!=='m'||doc.units?.speed!=='m/s'||doc.units?.time!=='s'||doc.units?.acceleration!=='m/s²')throw Error('프로젝트 내부 SI 단위를 확인하세요.');return validate(doc.config);}
function preset(name){const c=clone(defaults);if(name==='single'){c.name='1층 · 셔틀 1대 · 단일 사이클';c.levels=1;c.layers=c.layers.slice(0,1);c.cycleMode='single';}if(name==='skew'){c.name='층별 물동량 편중';c.layers.forEach((l,i)=>{l.inbound=i===3?100:10;l.outbound=l.inbound;});}if(name==='blocked'){c.name='지상 출고 정체';c.outputBuffer=2;c.outputTakeaway=60;c.layers.forEach(l=>l.shuttles=2);}if(name==='tote'){c.name='TOTE 설명용 예시';Object.assign(c,{cargoType:'tote',cargoLength:.6,cargoWidth:.4,cargoHeight:.35,cargoMass:30,carLength:.65,carWidth:.5,bayPitch:.85,aislePitch:1.8,levelPitch:.8,baseHeight:.8,firstBay:1.2,shuttleLimit:80,liftLimit:100,xEmptyV:4,xLoadedV:3,zEmptyV:2,zLoadedV:1.5,shuttleTransfer:1.5,liftTransfer:2});}if(name==='box'){Object.assign(c,preset('tote'),{name:'BOX 설명용 예시',cargoType:'box',cargoLength:.5,cargoWidth:.4,cargoHeight:.4,cargoMass:15,shuttleLimit:50,liftLimit:80,xEmptyV:2.5,xLoadedV:2,zEmptyV:1.2,zLoadedV:1,shuttleTransfer:2.5,liftTransfer:2.5});}if(name==='history'){c.name='셔틀 작업이력 예제';c.warmup=0;c.demandMode='history';c.history=[{time:0,type:'in',level:0},{time:0,type:'out',level:0},{time:30,type:'out',level:2},{time:60,type:'in',level:3}];}return c;}
return{VERSION,SCHEMA,defaults,fields,integerKeys,clone,validate,demand,height,home,park,point,liftPoint,slots,motion,Planner,shuttlePlan,liftPlan,phaseAt,calculate,hash,pack,unpack,preset};
});
