(function(){'use strict';
const $=id=>document.getElementById(id),V=AgvView,Model=AgvModel,Engine=AgvEngine,IO=AgvIO,Report=AgvReport;
let config=Model.preset(),applied=null,analysis=null,run=null,worker=null,sweepWorker=null,experiments=[],dirty=false,busy=false,playing=false,replayTime=0,selected='V1',pendingImport=null,currentTab='simulation',selectedNode=null,connectMode=false,connectFrom=null,toastTimer=null,sweepBaseHash=null;
try{const previous=localStorage.getItem('agv-amr-last-project');if(previous)config=Model.unpack(JSON.parse(previous));}catch{}
const scene=new AgvScene.Scene($('scene'),id=>{selected=id;scene.selected=id;updateReplay(true);});
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3600);}
function error(message){$('error').textContent=message||'';$('error').hidden=!message;if(message)$('error').scrollIntoView({block:'nearest',behavior:'smooth'});}
function download(name,data,type='text/plain;charset=utf-8'){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return (config.name||'AGV_AMR').replace(/[\\/:*?"<>|]/g,'_')+'.'+ext;}
function get(obj,key){return key.split('.').reduce((x,k)=>x?.[k],obj);}function set(obj,key,value){const parts=key.split('.');let o=obj;for(const k of parts.slice(0,-1))o=o[k];o[parts.at(-1)]=value;}
function bindFields(){for(const el of document.querySelectorAll('[data-key]')){const value=get(config,el.dataset.key),scale=Number(el.dataset.scale||1);if(el.type==='checkbox')el.checked=Boolean(value);else el.value=typeof value==='number'?Number((value/scale).toPrecision(12)):value??'';}}
function readField(el){return el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?NaN:Number(el.value)*Number(el.dataset.scale||1)):el.value;}
function markDirty(){
  dirty=true;busy=false;document.body.dataset.dirty='true';$('stale').hidden=!run;$('dirtyHint').textContent='변경된 설정을 적용하세요';playing=false;$('simPlay').textContent='▶ 재생';
  if(worker){worker.terminate();worker=null;$('progress').hidden=true;$('cancelRun').hidden=true;$('calculate').disabled=false;}
  if(sweepWorker){sweepWorker.terminate();sweepWorker=null;$('cancelSweep').hidden=true;$('runSweep').disabled=false;$('sweepStatus').textContent='설정 변경으로 대안 계산이 중단되었습니다.';}
  if(experiments.length)$('sweepStatus').textContent='이전 입력 조건의 비교 결과입니다. 설정 적용 후 다시 실행하세요.';
  updateDemandTotal();
}
function ensureCurrent(){if(busy||dirty||!run||run.configHash!==Model.hash(config)){toast(busy?'새 조건의 계산이 진행 중입니다.':'설정 적용 · 계산 실행으로 결과를 갱신하세요.');return false;}return true;}
function renderAnalysis(){if(!analysis)return;const a=analysis;$('analysisKpis').innerHTML=V.kpis([{label:'해석 초기 대수',value:a.vehicles,unit:'대',note:'목표 점유율 '+V.fmt(applied.targetUtil*100,0)+'% 반영'},{label:'미정수 대수',value:V.fmt(a.raw,4),unit:'대',note:'중간 반올림 없이 올림'},{label:'평균 작업시간',value:V.fmt(a.cycle),unit:'s/작업',note:'선택 공차 기준 + 해석 교통 추가'},{label:'요구 물동량',value:V.fmt(a.qty),unit:'PLT/Hr',note:V.fmt(a.jobs)+' 작업/Hr'}]);$('emptyComparison').innerHTML=V.table(['공차 기준','공차 부하 s/h','미정수','초기 대수'],a.alternatives.map(x=>[x.label,V.fmt(x.emptyWork),V.fmt(x.raw,3),x.vehicles+'대']));$('cycleChart').innerHTML=V.bars([{label:'적재 주행',value:a.loadedTravel,color:V.colors.loaded},{label:'픽업·하역·제어',value:a.handling,color:'#61aab4'},{label:'공차 주행',value:a.emptyWork,color:V.colors.empty},{label:'해석 교통 추가',value:a.extra,color:V.colors.traffic}].map(x=>({...x,display:V.fmt(a.jobs?x.value/a.jobs:0)+' s/작업'})));$('analyticOD').innerHTML=V.table(['OD','출발 → 목적지','물동량 PLT/Hr','작업/Hr','적재 거리 mm','적재 주행 s','픽업 s','하역 s','제어 s'],a.rows.map(r=>[r.id,r.from+' → '+r.to,V.fmt(r.rate),V.fmt(r.lambda),V.fmt(r.distance*1000,0),V.fmt(r.loadedTime),r.pick,r.drop,r.control]));$('assumptions').innerHTML='<ul class="muted">'+a.validation.warnings.map(s=>'<li>'+V.esc(s)+'</li>').join('')+'<li>지원: 단일 층 / 리프트·롤러 / 직선 경로·제자리 회전 / 링크 내 추종 없이 경로 전체 예약.</li><li>미지원: 곡선·조향·견인, 돌발 고장, 센서·SLAM, 다층, 현장 검증. v1.0 정식 검수 전입니다.</li></ul>';}
function renderResults(){if(!run)return;const a=analysis,m=run.metrics,p=applied;$('overviewKpis').innerHTML=V.kpis([{label:'해석 초기 필요 대수',value:a.vehicles,unit:'대',note:'미정수 '+V.fmt(a.raw,3)+'대 · 운영 '+p.fleet+'대'},{label:'시뮬레이션 완료 처리량',value:V.fmt(m.throughput),unit:'PLT/Hr',note:'요구 '+V.fmt(a.qty)+' PLT/Hr · 측정창 전체'},{label:'완료 요청 P95 리드타임',value:V.fmt(m.p95,0),unit:'s',note:'미완료 '+m.backlog+'건 · 기한초과 '+m.overdue+'건'},{label:'종료 시 백로그',value:m.backlog,unit:'건',note:'최장 미완료 경과 '+V.fmt(m.oldest,0)+' s'}]);
  const status=Engine.assess(run);$('resultVerdict').className='notice '+(status.eligible?'':'warning');$('resultVerdict').textContent=(run.audit.ok?'보존·예약 검사 통과. ':'검사 오류: '+run.audit.errors.join(', ')+'. ')+status.label+' · '+status.issues.join(' / ');$('resultVerdict').title='계산 완료 결과이며 아래 재생 시각과 별도로 전체 측정창을 집계합니다.';
  $('throughputChart').innerHTML=V.lineChart([{label:'누적 요청 건',color:'#adc0cc',points:run.snapshots.map(s=>({x:s.time/60,y:s.released}))},{label:'누적 완료 건',color:'#128a82',points:run.snapshots.map(s=>({x:s.time/60,y:s.completed}))},{label:'백로그 건',color:'#d99d43',points:run.snapshots.map(s=>({x:s.time/60,y:s.backlog}))}],{yLabel:'작업 건'});
  $('stateChart').innerHTML=V.bars(Object.entries(m.states).filter(([,r])=>r>.001).sort((a,b)=>b[1]-a[1]).map(([key,value])=>({label:Engine.STATES[key],value,display:V.fmt(value*100)+'%',color:V.colors[key]})));
  const palette=['#138d83','#568bd0','#9b7acb','#c99b44','#a6757b','#7fa07c'];$('socChart').innerHTML=V.lineChart(run.vehicles.map((v,i)=>({label:v.id,color:palette[i%palette.length],points:run.snapshots.map(s=>({x:s.time/60,y:s.soc[i]*100}))})),{yLabel:'SOC %',yMax:100});
  $('resourceTable').innerHTML=V.table(['자원','차량 서비스','후공정','대기 s'],m.resources.map(r=>[r.id,V.fmt(r.busy*100)+'%',r.type==='station'?V.fmt(r.processBusy*100)+'%':'—',V.fmt(r.wait,0)]));renderEvents();renderReport();$('simSeek').max=p.horizon;$('vehicleCount').textContent=p.fleet+'대';$('simStatus').textContent='계산 완료 · 기록 재생';$('simStatus').dataset.completed='true';$('projectSummary').textContent=p.name+' · '+V.fmt(p.horizon/3600,1)+' h · '+p.dataStatus+' · '+run.configHash;
  document.body.dataset.configHash=run.configHash;document.body.dataset.runId=run.runId;
}
function renderEvents(){if(!run)return;const filter=$('eventFilter').value,events=run.events.filter(e=>filter==='all'||(filter==='completed'?e.type==='completed':['traffic','blocked','chargeWait','charging','failure','deadlock','closure'].includes(e.type))).slice(-200);$('eventTable').innerHTML='<table><thead><tr><th>시각</th><th>차량</th><th>상태</th><th>위치 · 원인</th></tr></thead><tbody>'+events.map(e=>'<tr class="clickable" data-time="'+e.time+'" data-vehicle="'+V.esc(e.vehicle)+'"><td>'+V.clock(e.time)+'</td><td>'+V.esc(e.vehicle||'—')+'</td><td>'+V.esc(Engine.STATES[e.type]||({closure:'통로 제어',completed:'완료',failure:'실패',deadlock:'교착'}[e.type]||e.type))+'</td><td>'+V.esc(e.node+' · '+e.detail)+'</td></tr>').join('')+'</tbody></table>'+(events.length?'':'<div class="empty-message">해당 이벤트가 없습니다.</div>');}
function renderReport(){if(run&&!dirty)$('reportPreview').innerHTML=V.markdown(Report.markdown(applied,run,sweepBaseHash===run.configHash?experiments:[]));}
let lastInfo=-1;function updateReplay(force=false){if(!run)return;scene.selected=selected;scene.follow=$('followVehicle').checked;scene.showPaths=$('showPaths').checked;scene.showLabels=$('showLabels').checked;scene.envelopes=$('showEnvelope').checked;scene.render(replayTime);if(!force&&Math.abs(replayTime-lastInfo)<.18)return;lastInfo=replayTime;$('simSeek').value=replayTime;$('replayClock').textContent=V.clock(replayTime);$('replayClock').dataset.time=String(replayTime);const completed=run.tasks.filter(j=>j.completed!==null&&j.completed<=replayTime),released=run.tasks.filter(j=>j.release<=replayTime);$('sceneCount').textContent='완료 '+completed.reduce((s,j)=>s+j.qty,0)+' PLT · 백로그 '+(released.length-completed.length)+'건';
  const poses=run.vehicles.map(v=>({id:v.id,...Engine.vehiclePose(run,v,replayTime)}));$('vehicleList').innerHTML=poses.map(p=>'<button class="vehicle-row '+(p.id===selected?'selected':'')+'" data-vehicle="'+p.id+'" style="--color:'+V.colors[p.state]+'"><span class="robot-icon">'+p.id+'</span><div><strong>'+p.id+'</strong><span class="status-text">'+V.esc(Engine.STATES[p.state])+'</span><div class="soc-bar"><i style="width:'+p.soc*100+'%"></i></div><span class="soc-label">'+V.fmt(p.soc*100,1)+'% SOC</span></div></button>').join('');
  const p=poses.find(x=>x.id===selected)||poses[0];if(p){const pair=(a,b)=>'<div class="pair"><span>'+a+'</span><strong>'+V.esc(b)+'</strong></div>';$('vehicleDetail').innerHTML='<span class="eyebrow">'+p.id+' · SELECTED VEHICLE</span>'+pair('현재 상태',Engine.STATES[p.state])+pair('현재 속도',V.fmt(p.speed*60)+' m/min')+pair('적재',p.loaded?'화물 운반중':'공차')+pair('작업 ID',p.taskId||'—')+pair('X / Y mm',V.fmt(p.x*1000,0)+' / '+V.fmt(p.y*1000,0))+'<p style="margin-top:9px">'+V.esc(p.reason||'주차 베이 대기')+'</p>';$('vehicleDetail').dataset.vehicle=p.id;$('vehicleDetail').dataset.x=p.x;$('vehicleDetail').dataset.y=p.y;$('vehicleDetail').dataset.state=p.state;}
}
function makeWorker(){const url=URL.createObjectURL(new Blob([AGV_WORKER_SOURCE],{type:'text/javascript'}));try{const w=new Worker(url);setTimeout(()=>URL.revokeObjectURL(url),1000);return w;}catch(e){URL.revokeObjectURL(url);throw e;}}
async function calculate(){
  if(worker)worker.terminate();playing=false;error('');const check=Model.validate(config);if(check.errors.length){error(check.errors.join('\n'));return;}try{analysis=Model.analytics(config);applied=Model.clone(config);renderAnalysis();}catch(e){error(e.message);return;}
  dirty=false;busy=true;document.body.dataset.dirty='false';$('stale').hidden=!run;$('dirtyHint').textContent='계산 중 · 입력과 결과 동기화';$('calculate').disabled=true;$('cancelRun').hidden=false;$('progress').hidden=false;$('progressText').textContent='차량 배차·교통·충전 사건 계산 중…';$('progressBar').value=0;$('simStatus').textContent='계산 중';
  function done(result){if(result.configHash!==Model.hash(config))return;run=result;busy=false;worker?.terminate();worker=null;$('calculate').disabled=false;$('cancelRun').hidden=true;$('progress').hidden=true;$('stale').hidden=true;$('dirtyHint').textContent='적용 완료 · '+run.configHash;replayTime=0;selected=run.vehicles[0]?.id||'V1';renderResults();scene.setRun(run);updateReplay(true);try{localStorage.setItem('agv-amr-last-project',JSON.stringify(Model.pack(applied)));}catch{}$('runtime').textContent=(scene.fallback?'2D 대체 표시':'3D WebGL')+' · 오프라인';}
  function failed(e){busy=false;worker?.terminate();worker=null;$('calculate').disabled=false;$('cancelRun').hidden=true;$('progress').hidden=true;error(e.message||String(e));dirty=true;document.body.dataset.dirty='true';$('stale').hidden=!run;}
  try{worker=makeWorker();worker.onmessage=e=>{const msg=e.data;if(msg.type==='progress'){$('progressBar').value=msg.progress;$('progressText').textContent='운전 '+V.clock(msg.time)+' / '+V.clock(applied.horizon)+' · '+msg.events+'개 사건';}else if(msg.type==='result')done(msg.run);else if(msg.type==='error')failed(new Error(msg.message));};worker.onerror=e=>failed(new Error('계산 Worker 오류: '+e.message));worker.postMessage({type:'run',config:applied});}
  catch(e){$('runtime').textContent='Worker 대체 실행';try{const sim=new Engine.Simulation(applied),token=applied;while(!sim.done){sim.stepBatch(1000);$('progressBar').value=sim.time/applied.horizon;await new Promise(r=>setTimeout(r,0));if(dirty||applied!==token)return;}done(sim.result());}catch(e){failed(e);}}
}
const specs={
  nodes:{target:'nodesTable',columns:[['id','노드 ID','text'],['type','유형',['junction:경유','station:스테이션','parking:주차','charger:충전기']],['x','X mm','number',.001],['y','Y mm','number',.001],['stop','정지점','boolean'],['pickup','픽업 s','number'],['dropoff','하역 s','number'],['buffer','화물 버퍼 PLT','number'],['process','후공정 s/PLT','number'],['processSlots','후공정 슬롯','number'],['enabled','활성','boolean']]},
  paths:{target:'pathsTable',columns:[['id','경로 ID','text'],['from','시작','node'],['to','끝','node'],['width','통로폭 mm','number',.001],['speed','제한 m/min','number',1/60],['direction','방향',['both:양방향','forward:일방통행']],['door','도어 개방 s','number'],['enabled','활성','boolean']]},
  od:{target:'odTable',columns:[['id','OD ID','text'],['from','출발','station'],['to','목적지','station'],['rate','PLT/Hr','number'],['qty','PLT/작업','number'],['weight','총 하중 kg/작업','number'],['priority','우선순위','number'],['due','납기 s','number']]},
  profiles:{target:'profilesTable',columns:[['start','시작 s','number'],['end','종료 s','number'],['multiplier','배율 ×','number']]},
  history:{target:'historyTable',columns:[['id','작업 ID','text'],['release','발생 s','number'],['from','출발','station'],['to','목적지','station'],['qty','PLT','number'],['weight','총 하중 kg','number'],['due','절대 납기 s','number'],['priority','우선순위','number']]},
  closures:{target:'closuresTable',columns:[['id','이벤트 ID','text'],['pathId','폐쇄 경로','path'],['start','시작 s','number'],['end','종료 s','number']]},
  stops:{target:'stopsTable',columns:[['vehicle','차량 번호','number'],['start','시작 s','number'],['end','종료 s','number']]}
};
function renderTable(key){const spec=specs[key],rows=config[key],optionsFor=type=>type==='node'?config.nodes.map(n=>n.id):type==='station'?config.nodes.filter(n=>n.type==='station').map(n=>n.id):config.paths.map(e=>e.id);$(spec.target).innerHTML='<table><thead><tr>'+spec.columns.map(c=>'<th>'+c[1]+'</th>').join('')+'<th></th></tr></thead><tbody>'+rows.map((row,i)=>'<tr data-row="'+i+'"'+(key==='nodes'&&row.id===selectedNode?' class="selected"':'')+'>'+spec.columns.map(([field,label,type,scale=1])=>{const attr='data-table="'+key+'" data-row="'+i+'" data-field="'+field+'" data-scale="'+scale+'" aria-label="'+V.esc((row.id||i+1)+' '+label)+'"',value=row[field];let input;if(type==='boolean')input='<input type="checkbox" '+attr+(value?' checked':'')+'>';else if(Array.isArray(type)||['node','station','path'].includes(type)){const opts=Array.isArray(type)?type:optionsFor(type);input='<select '+attr+'>'+opts.map(s=>{const [val,name]=String(s).split(':');return '<option value="'+V.esc(val)+'"'+(val===value?' selected':'')+'>'+V.esc(name||val)+'</option>';}).join('')+'</select>';}else input='<input type="'+type+'" '+attr+' value="'+V.esc(type==='number'?Number((value/scale).toPrecision(12)):value)+'"'+(type==='number'?' step="any"':'')+'>';return '<td>'+input+'</td>';}).join('')+'<td><button class="delete-row" data-delete="'+key+'" data-row="'+i+'" aria-label="'+V.esc((row.id||i+1)+' 삭제')+'">×</button></td></tr>').join('')+'</tbody></table>'+(rows.length?'':'<div class="empty-message">등록된 항목이 없습니다. 추가 버튼 또는 Excel로 입력하세요.</div>');}
function renderEditors(){for(const k of Object.keys(specs))renderTable(k);renderLayout();updateDemandTotal();}
function renderLayout(){if(config.nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y)))$('layoutCanvas').innerHTML=V.layoutSvg(config,{selected:selectedNode});}
function updateDemandTotal(){if(!$('demandTotal'))return;const sum=config.od.reduce((s,o)=>s+(Number.isFinite(o.rate)?o.rate:0),0);$('demandTotal').textContent=config.demandMode==='od'?'OD 합계 '+V.fmt(sum)+' PLT/Hr':'이력 '+config.history.length+'건';}
function unique(prefix,rows){let i=1;while(rows.some(r=>r.id===prefix+i))i++;return prefix+i;}
function addRow(key){const stations=config.nodes.filter(n=>n.type==='station'),defaults={nodes:()=>({id:unique('N',config.nodes),x:Math.max(...config.nodes.map(n=>n.x),0)+4,y:0,type:'junction',stop:false,pickup:15,dropoff:15,buffer:4,process:0,processSlots:1,enabled:true}),paths:()=>({id:unique('E',config.paths),from:config.nodes[0]?.id||'',to:config.nodes[1]?.id||'',width:3,speed:1.5,direction:'both',door:0,enabled:true}),od:()=>({id:unique('OD',config.od),from:stations[0]?.id||'',to:stations[1]?.id||'',rate:12,qty:1,weight:500,priority:1,due:600}),profiles:()=>({start:0,end:Math.min(600,config.horizon),multiplier:1.5}),history:()=>({id:unique('TASK',config.history),release:0,from:stations[0]?.id||'',to:stations[1]?.id||'',qty:1,weight:500,due:600,priority:1}),closures:()=>({id:unique('BLOCK',config.closures),pathId:config.paths[0]?.id||'',start:Math.min(300,config.horizon/3),end:Math.min(900,config.horizon*2/3)}),stops:()=>({vehicle:1,start:Math.min(300,config.horizon/3),end:Math.min(900,config.horizon*2/3)})};const row=defaults[key]();config[key].push(row);if(key==='nodes')selectedNode=row.id;markDirty();renderTable(key);renderLayout();}
function switchTab(name){currentTab=name;for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-selected',String(b.dataset.tab===name));}for(const p of document.querySelectorAll('[data-panel]'))p.hidden=p.dataset.panel!==name;if(name==='simulation')scene.resize();if(name==='layout')renderLayout();if(name==='report')renderReport();}
function previewImport(p,label){const checks=Model.validate(p);if(checks.errors.length){error(checks.errors.join('\n'));return;}pendingImport=p;const a=Model.analytics(p);$('importPreview').innerHTML='<p><strong>'+V.esc(label)+'</strong></p>'+V.table(['항목','가져올 설정'],[['프로젝트',p.name],['운영 대수',p.fleet+'대'],['노드 / 경로',p.nodes.length+' / '+p.paths.length],['OD / 작업 이력',p.od.length+' / '+p.history.length],['수요',V.fmt(a.qty)+' PLT/Hr'],['해석 대수',a.vehicles+'대'],['입력 검증','오류 0건'],['설정 해시',Model.hash(p)]])+'<p class="muted">적용하면 현재 시나리오 입력을 교체하고 새로 계산합니다. 원본은 파일로 보존됩니다.</p>';$('importDialog').showModal();}
async function importFile(file){if(!file)return;error('');try{if(file.size>30e6)throw Error('파일 크기는 30 MB 이하로 제한됩니다.');if(file.name.toLowerCase().endsWith('.xlsx'))previewImport(await IO.readXlsx(file,Model.preset()),file.name);else {const data=JSON.parse(await file.text());if(data.schemaVersion==='agv-amr/run@1'){const p=Model.unpack(data.config);if(data.engineVersion!==Model.VERSION||data.configHash!==Model.hash(p))throw Error('지원하지 않는 재생 버전 또는 설정 해시 오류');previewImport(p,file.name+' · 동일 설정으로 재계산');}else previewImport(Model.unpack(data),file.name);}}catch(e){error('가져오기 실패 — '+e.message);}finally{$('projectFile').value='';}}
function motionChart(){try{const distance=Number($('motionDistance').value)/1000,speed=Number($('motionSpeed').value)/60,a=Number($('motionAccel').value),b=Number($('motionDecel').value),p=AgvMotion.profile(distance,speed,a,b),points=Array.from({length:161},(_,i)=>{const t=p.duration*i/160;return {x:t,y:AgvMotion.sample(p,t).velocity};});$('motionSummary').textContent='이동시간 '+p.duration.toFixed(9)+' s · 최고 도달속도 '+p.peak.toFixed(6)+' m/s · 임계거리 '+(speed*speed/(2*a)+speed*speed/(2*b)).toFixed(6)+' m · '+(p.peak<speed-1e-8?'삼각 프로파일':'사다리꼴 프로파일');$('motionChart').innerHTML=V.lineChart([{label:'속도 m/s',color:'#198f85',points}],{xLabel:'시간 s',yLabel:'속도 m/s'});}catch(e){error(e.message);}}
function renderSweep(){if(!experiments.length)return;const palette=['#168f85','#6094cb','#a281c1','#cf9d49'],groups=new Map();for(const e of experiments){const key=e.chargers+' 충전기 · '+(e.routing==='dynamic'?'동적':'고정');if(!groups.has(key))groups.set(key,[]);groups.get(key).push({x:e.fleet,y:e.ci.mean});}$('sweepChart').innerHTML=V.lineChart([...groups].map(([label,points],i)=>({label,points:points.sort((a,b)=>a.x-b.x),color:palette[i%palette.length]})),{xLabel:'차량 대수',yLabel:'평균 PLT/Hr'});$('sweepTable').innerHTML=V.table(['대안','반복','평균 PLT/Hr','반복 간 평균 95% CI','최대 P95 s','최대 백로그','오류 실행','판정'],experiments.map(e=>[e.label,e.ci.n,V.fmt(e.ci.mean),e.ci.low===null?'반복 부족':V.fmt(e.ci.low)+' ~ '+V.fmt(e.ci.high),V.fmt(e.maxP95,0),e.maxBacklog,e.failed,e.labelStatus]));}
async function runSweep(){
  if(!ensureCurrent())return;error('');const min=Number($('sweepMin').value),max=Number($('sweepMax').value),repeats=Number($('sweepRepeats').value),chargerInput=$('sweepChargers').value.split(',').map(x=>x.trim()),chargers=[...new Set(chargerInput.map(Number))],hours=Number($('sweepHours').value),warmup=Number($('sweepWarmup').value)*60,factor=Number($('sweepLoad').value),routing=$('sweepPolicy').value==='both'?['fixed','dynamic']:[config.routing],nodes=config.nodes.filter(n=>n.type==='charger'),homes=config.nodes.filter(n=>n.type==='parking'&&n.enabled),seedOffset=$('sweepSeedGroup').value==='validate'?100000:0;
  if(!Number.isInteger(min)||!Number.isInteger(max)||min<1||max<min||max>homes.length||max>50){error('대수 범위: 1~'+Math.min(50,homes.length)+'대, 최소 ≤ 최대 정수');return;}if(chargerInput.some(x=>!x)||chargers.some(x=>!Number.isInteger(x)||x<(config.battery.enabled?1:0)||x>nodes.length)){error('충전기 수는 존재하는 충전기 노드 수 이하의 정수를 쉼표로 구분하세요.');return;}
  if(!(hours>=.1&&hours<=48&&warmup>=0&&warmup<hours*3600&&factor>0&&factor<=20)){error('시험시간·준비운전·수요 배율 범위 오류');return;}if(config.demandMode==='history'&&(hours*3600!==config.horizon||factor!==1)){error('작업 이력 비교는 원래 운전시간과 수요 배율 1을 사용하세요.');return;}
  const cases=[];for(let n=min;n<=max;n++)for(const c of chargers)for(const policy of routing){const p=Model.clone(config);p.fleet=n;p.horizon=hours*3600;p.warmup=warmup;p.demandFactor*=factor;p.routing=policy;p.nodes.filter(n=>n.type==='charger').forEach((n,i)=>n.enabled=i<c);p.stops=p.stops.filter(s=>s.vehicle<=n);const check=Model.validate(p);if(check.errors.length){error('대안 입력 오류: '+check.errors.join('\n'));return;}cases.push({config:p,fleet:n,chargers:c,routing:policy});}
  if(cases.length*repeats>300){error('한 번에 최대 300회 실행합니다. 대수/충전기/정책/반복 범위를 줄이세요.');return;}
  experiments=[];sweepBaseHash=run.configHash;renderSweep();$('sweepTable').innerHTML='';$('sweepChart').innerHTML='';$('runSweep').disabled=true;$('cancelSweep').hidden=false;$('sweepStatus').textContent='총 '+cases.length*repeats+'회 계산을 시작합니다.';
  try{sweepWorker=makeWorker();sweepWorker.onmessage=e=>{const msg=e.data;if(msg.type==='experiment'){experiments.push(msg.result);renderSweep();$('sweepStatus').textContent=experiments.length+' / '+cases.length+'개 대안 완료 · '+msg.completed+' / '+cases.length*repeats+'회';}if(msg.type==='sweepProgress')$('sweepStatus').textContent='운전 비교 '+msg.completed+' / '+msg.total+'회 · 현재 '+V.fmt(msg.progress*100,0)+'%';if(msg.type==='sweepDone'){sweepWorker.terminate();sweepWorker=null;$('runSweep').disabled=false;$('cancelSweep').hidden=true;const eligible=experiments.filter(e=>e.eligible).sort((a,b)=>a.fleet-b.fleet||a.chargers-b.chargers),best=eligible[0];$('sweepStatus').textContent=(best?'탐색 범위 내 조건 충족 후보: '+best.label:'탐색 범위 내 모든 조건을 충족한 구성 없음')+' · '+(config.arrival==='periodic'?'결정론 도착: 같은 시드 반복의 변동 0은 통계적 검증이 아닙니다.':'반복 간 평균 95% 신뢰구간. P95의 신뢰구간과 다릅니다.')+' · '+(seedOffset?'독립 검증 시드 사용':'별도 검증 시드로 최종 후보를 재시험하세요.');renderReport();}if(msg.type==='error'){sweepWorker.terminate();sweepWorker=null;$('runSweep').disabled=false;$('cancelSweep').hidden=true;error(msg.message);}};sweepWorker.onerror=e=>{error('대안 계산 오류: '+e.message);$('runSweep').disabled=false;$('cancelSweep').hidden=true;sweepWorker?.terminate();sweepWorker=null;};sweepWorker.postMessage({type:'sweep',cases,repeats,seedOffset});}catch(e){$('runSweep').disabled=false;$('cancelSweep').hidden=true;error('대안 계산에는 Worker 지원이 필요합니다. '+e.message);}
}
document.addEventListener('change',e=>{
  const el=e.target;if(el.matches('[data-key]')){set(config,el.dataset.key,readField(el));markDirty();return;}
  if(el.matches('[data-table]')){const key=el.dataset.table,i=Number(el.dataset.row),field=el.dataset.field,row=config[key][i],old=row[field],value=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?NaN:Number(el.value)*Number(el.dataset.scale||1)):el.value;
    if(field==='id'){if(!String(value).trim()||config[key].some((r,j)=>j!==i&&r.id===value)){el.value=old;error('ID는 비어 있거나 중복될 수 없습니다.');return;}if(key==='nodes'){for(const edge of config.paths){if(edge.from===old)edge.from=value;if(edge.to===old)edge.to=value;}for(const task of [...config.od,...config.history]){if(task.from===old)task.from=value;if(task.to===old)task.to=value;}selectedNode=value;}if(key==='paths')for(const c of config.closures)if(c.pathId===old)c.pathId=value;}
    row[field]=value;markDirty();if(field==='id'||(key==='nodes'&&field==='type'))renderEditors();else if(['nodes','paths','closures'].includes(key))renderLayout();
  }
});
document.addEventListener('click',e=>{
  const tab=e.target.closest('[data-tab]');if(tab)switchTab(tab.dataset.tab);
  const del=e.target.closest('[data-delete]');if(del){const key=del.dataset.delete,i=Number(del.dataset.row),item=config[key][i];if(key==='nodes'&&[...config.paths,...config.od,...config.history].some(x=>x.from===item.id||x.to===item.id)){toast('연결 경로·OD를 먼저 삭제하거나 다른 노드로 변경하세요.');return;}if(key==='paths'&&config.closures.some(c=>c.pathId===item.id)){toast('이 경로의 폐쇄 이벤트를 먼저 삭제하세요.');return;}config[key].splice(i,1);markDirty();renderTable(key);renderLayout();}
  const vehicle=e.target.closest('#vehicleList [data-vehicle]');if(vehicle){selected=vehicle.dataset.vehicle;updateReplay(true);}
  const event=e.target.closest('#eventTable [data-time]');if(event&&ensureCurrent()){playing=false;replayTime=Number(event.dataset.time);if(event.dataset.vehicle)selected=event.dataset.vehicle;$('simPlay').textContent='▶ 재생';updateReplay(true);$('scene').scrollIntoView({block:'center',behavior:'smooth'});}
  const camera=e.target.closest('[data-camera]');if(camera){scene.setCamera(camera.dataset.camera);for(const b of document.querySelectorAll('[data-camera]'))b.classList.toggle('active',b===camera);}
});
$('calculate').onclick=calculate;$('cancelRun').onclick=()=>{worker?.terminate();worker=null;markDirty();$('calculate').disabled=false;$('progress').hidden=true;$('cancelRun').hidden=true;toast('계산을 취소했습니다. 기존 결과를 유지합니다.');};
$('applyPreset').onclick=()=>{config=Model.preset($('preset').value);selectedNode=null;markDirty();bindFields();renderEditors();calculate();};
$('duplicateProject').onclick=()=>{config=Model.clone(config);config.parentScenarioId=config.scenarioId;config.scenarioId='scenario-'+Date.now();config.name+=' · 복제';markDirty();bindFields();toast('시나리오를 복제했습니다. 변경 후 계산하세요.');};
$('saveProject').onclick=()=>{const check=Model.validate(config);if(check.errors.length){error(check.errors.join('\n'));return;}download(filename('json'),JSON.stringify(Model.pack(config),null,2),'application/json');toast('프로젝트 JSON을 저장했습니다.');};
$('saveWorkbook').onclick=()=>{const check=Model.validate(config);if(check.errors.length){error(check.errors.join('\n'));return;}download(filename('xlsx'),IO.xlsx(config));toast('Excel 입력 템플릿과 현재 설정을 저장했습니다.');};
$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=()=>importFile($('projectFile').files[0]);$('openHelp').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
$('cancelImport').onclick=()=>{pendingImport=null;$('importDialog').close();};$('confirmImport').onclick=()=>{if(!pendingImport)return;config=pendingImport;pendingImport=null;$('importDialog').close();markDirty();bindFields();renderEditors();calculate();};
$('exportOD').onclick=()=>download('AGV_AMR_OD.csv',IO.csv(IO.sheets(config).OD),'text/csv;charset=utf-8');$('importOD').onclick=()=>$('odFile').click();$('odFile').onchange=async()=>{try{const f=$('odFile').files[0];if(f)previewImport(IO.importOD(await f.text(),config),f.name);}catch(e){error(e.message);}finally{$('odFile').value='';}};
for(const [id,key]of [['addNode','nodes'],['addPath','paths'],['addOD','od'],['addProfile','profiles'],['addHistory','history'],['addClosure','closures'],['addStop','stops']])$(id).onclick=()=>addRow(key);
$('simPlay').onclick=()=>{if(!ensureCurrent())return;if(replayTime>=run.config.horizon)replayTime=0;playing=!playing;$('simPlay').textContent=playing?'Ⅱ 일시정지':'▶ 재생';};
function seek(t){if(!ensureCurrent())return;playing=false;$('simPlay').textContent='▶ 재생';replayTime=Math.max(0,Math.min(run.config.horizon,t));updateReplay(true);}
$('simReset').onclick=()=>seek(0);$('simEnd').onclick=()=>seek(run?.config.horizon||0);$('simStep').onclick=()=>seek(run?.events.find(e=>e.time>replayTime+1e-7)?.time||run?.config.horizon||0);$('simSeek').oninput=()=>seek(Number($('simSeek').value));
for(const id of ['showPaths','showLabels','showEnvelope','followVehicle'])$(id).onchange=()=>{scene.lastFallback=-1;if(id==='followVehicle'&&$('followVehicle').checked)scene.focusVehicle(selected);updateReplay(true);};$('toggle2D').onclick=()=>{scene.forced2D=!scene.forced2D;scene.lastFallback=-1;$('toggle2D').textContent=scene.forced2D?'3D':'2D';updateReplay(true);};
$('captureScene').onclick=()=>{if(!ensureCurrent())return;try{const a=document.createElement('a');a.download='AGV_AMR_3D_'+Math.floor(replayTime)+'s.png';a.href=scene.capture();a.click();toast('시각·시나리오·KPI 포함 3D 이미지를 저장했습니다.');}catch(e){toast(e.message);}};
$('eventFilter').onchange=renderEvents;$('motionCalculate').onclick=motionChart;$('runSweep').onclick=runSweep;$('cancelSweep').onclick=()=>{sweepWorker?.terminate();sweepWorker=null;$('runSweep').disabled=false;$('cancelSweep').hidden=true;$('sweepStatus').textContent='비교 계산을 중단했습니다. 완료된 대안 '+experiments.length+'개만 표시합니다.';};
$('exportReport').onclick=()=>{if(ensureCurrent())download(filename('md'),Report.markdown(applied,run,sweepBaseHash===run.configHash?experiments:[]));};$('printReport').onclick=()=>{if(ensureCurrent()){renderReport();window.print();}};$('exportJobs').onclick=()=>{if(ensureCurrent())download('AGV_AMR_작업기록.csv',Report.jobs(run),'text/csv;charset=utf-8');};$('exportEvents').onclick=()=>{if(ensureCurrent())download('AGV_AMR_이벤트.csv',Report.events(run),'text/csv;charset=utf-8');};$('exportRun').onclick=()=>{if(ensureCurrent())download('AGV_AMR_재생기록.json',JSON.stringify(run),'application/json');};
$('layoutSelect').onclick=()=>{connectMode=false;connectFrom=null;$('layoutSelect').classList.add('active');$('layoutConnect').classList.remove('active');$('layoutSelection').textContent='노드를 드래그하거나 아래 표에서 좌표를 입력하세요.';};$('layoutConnect').onclick=()=>{connectMode=true;connectFrom=null;$('layoutSelect').classList.remove('active');$('layoutConnect').classList.add('active');$('layoutSelection').textContent='시작 노드와 종료 노드를 차례로 클릭하세요.';};
let drag=null;$('layoutCanvas').addEventListener('pointerdown',e=>{const target=e.target.closest('[data-node]');if(!target)return;const id=target.dataset.node;selectedNode=id;renderTable('nodes');if(connectMode){if(!connectFrom){connectFrom=id;$('layoutSelection').textContent=id+' → 종료 노드를 선택하세요.';}else if(connectFrom!==id){config.paths.push({id:unique('E',config.paths),from:connectFrom,to:id,width:3,speed:1.5,direction:'both',door:0,enabled:true});connectFrom=null;markDirty();renderTable('paths');renderLayout();$('layoutSelection').textContent='경로를 추가했습니다. 다음 시작 노드를 선택할 수 있습니다.';}return;}const svg=$('layoutCanvas').querySelector('svg'),pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),node=config.nodes.find(n=>n.id===id);drag={id,dx:node.x-pt.x,dy:node.y+pt.y,moved:false};$('layoutCanvas').setPointerCapture(e.pointerId);$('layoutSelection').textContent=id+' · 좌표를 드래그로 변경';});
$('layoutCanvas').addEventListener('pointermove',e=>{if(!drag)return;const svg=$('layoutCanvas').querySelector('svg'),pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),n=config.nodes.find(n=>n.id===drag.id);n.x=Math.round((pt.x+drag.dx)*4)/4;n.y=Math.round((-pt.y+drag.dy)*4)/4;drag.moved=true;const group=svg.querySelector('[data-node="'+CSS.escape(n.id)+'"]');if(group){const circle=group.querySelector('circle'),text=group.querySelector('text');circle.setAttribute('cx',n.x);circle.setAttribute('cy',-n.y);text.setAttribute('x',n.x);text.setAttribute('y',-n.y-1.25);}});
function finishDrag(){if(!drag)return;if(drag.moved){markDirty();renderTable('nodes');renderLayout();}drag=null;}$('layoutCanvas').addEventListener('pointerup',finishDrag);$('layoutCanvas').addEventListener('pointercancel',finishDrag);
let lastFrame=performance.now();function frame(now){const dt=Math.min(.25,(now-lastFrame)/1000);lastFrame=now;if(playing&&run&&!dirty){replayTime=Math.min(run.config.horizon,replayTime+dt*Number($('simSpeed').value));if(replayTime>=run.config.horizon){playing=false;$('simPlay').textContent='▶ 재생';}}if(currentTab==='simulation'&&run)updateReplay();requestAnimationFrame(frame);}requestAnimationFrame(frame);
bindFields();renderEditors();motionChart();calculate();
})();
