(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model'):root.AgvModel);if(typeof module==='object'&&module.exports)module.exports=api;root.AgvIO=api;})(globalThis,function(Model){
'use strict';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function csv(rows){return '\uFEFF'+rows.map(row=>row.map(x=>{const s=String(x??'');const safe=/^[=+@\t\r]/.test(s)?"'"+s:s;return /[",\r\n]/.test(safe)?'"'+safe.replace(/"/g,'""')+'"':safe;}).join(',')).join('\r\n');}
function parseCsv(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else throw Error('CSV 따옴표 형식 오류');}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV 닫히지 않은 따옴표');row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows;}
function flatten(o,prefix='',rows=[]){for(const [k,v]of Object.entries(o)){const path=prefix?prefix+'.'+k:k;if(Array.isArray(v))continue;if(v&&typeof v==='object')flatten(v,path,rows);else rows.push([path,typeof v,String(v)]);}return rows;}
function sheets(p){const spec={Nodes:['nodes',['id','x','y','type','stop','pickup','dropoff','buffer','process','processSlots','enabled']],Paths:['paths',['id','from','to','width','speed','direction','door','enabled']],OD:['od',['id','from','to','rate','qty','weight','priority','due']],DemandProfiles:['profiles',['start','end','multiplier']],TaskHistory:['history',['id','release','from','to','qty','weight','due','priority']],Closures:['closures',['id','pathId','start','end']],PlannedStops:['stops',['vehicle','start','end']]};
  const out={Project:[['field','type','value'],['distance_unit','string','mm'],['speed_unit','string','m/min'],...flatten(p)]};
  for(const [name,[key,fields]]of Object.entries(spec)){const headers=fields.map(k=>({x:'x_mm',y:'y_mm',width:'width_mm',speed:'speed_m_min'}[k]||k));out[name]=[headers,...p[key].map(row=>fields.map(k=>['x','y','width'].includes(k)?row[k]*1000:k==='speed'?row[k]*60:row[k]))];}
  out.Instructions=[['항목','안내'],['단위','Nodes X/Y 및 Paths 폭: mm / 경로 속도: m/min. Project 차량 사양의 SI 필드는 이름 그대로 m, m/s, Wh.'],['입력','Project의 field/type/value 및 표준 시트·헤더를 유지하세요. 가져오기 미리보기에서 검증 후 적용됩니다.'],['모델','단일 층 / 리프트·롤러 / 경로망 / 보수적 전 구간 예약 / 노드당 차량 1대 / 전용 주차 복귀'],['출처',p.sources],['작업 수량','OD.weight 및 TaskHistory.weight는 작업 1건의 총 적재중량 kg입니다. OD.qty는 동일 OD 일괄 운반 수량입니다.']];return out;
}
function fromSheets(book,current){
  const p=Model.clone(current),errors=[],mapping={Nodes:'nodes',Paths:'paths',OD:'od',DemandProfiles:'profiles',TaskHistory:'history',Closures:'closures',PlannedStops:'stops'},numeric=new Set(['x','y','pickup','dropoff','buffer','process','processSlots','width','speed','door','rate','qty','weight','priority','due','start','end','multiplier','release','vehicle']),boolean=new Set(['stop','enabled']);
  for(const name of ['Project',...Object.keys(mapping)])if(!book[name])errors.push(name+' 시트 누락');if(errors.length)throw Error(errors.join('\n'));
  const allowed=new Map(flatten(current).map(([key,type])=>[key,type])),seen=new Set(),units={};
  const projectRows=book.Project;if(projectRows[0]?.join('|')!=='field|type|value')errors.push('Project 헤더: field,type,value 필요');
  projectRows.slice(1).forEach((row,i)=>{const [path,type,raw]=row;if(!path)return;if(seen.has(path)){errors.push('Project '+(i+2)+'행: 중복 필드 '+path);return;}seen.add(path);if(['distance_unit','speed_unit'].includes(path)){units[path]=raw;return;}if(!allowed.has(path)||allowed.get(path)!==type){errors.push('Project '+(i+2)+'행: 지원하지 않는 필드/유형 '+path);return;}const parts=path.split('.');let obj=p;for(let j=0;j<parts.length-1;j++)obj=obj[parts[j]];if(type==='number'){if(raw===''||!Number.isFinite(Number(raw)))errors.push(path+': 숫자 형식 오류');else obj[parts.at(-1)]=Number(raw);}else if(type==='boolean'){if(!['true','false'].includes(String(raw).toLowerCase()))errors.push(path+': true/false 필요');else obj[parts.at(-1)]=String(raw).toLowerCase()==='true';}else obj[parts.at(-1)]=String(raw??'');});
  for(const key of allowed.keys())if(!seen.has(key))errors.push('Project 필수 필드 누락: '+key);
  if(units.distance_unit!=='mm'||units.speed_unit!=='m/min')errors.push('워크북 단위는 mm / m/min이어야 합니다.');
  const expected=sheets(current);
  for(const [sheet,key]of Object.entries(mapping)){const rows=book[sheet],headers=rows[0]||[];if(headers.join('|')!==expected[sheet][0].join('|')){errors.push(sheet+' 헤더 또는 열 순서가 템플릿과 다릅니다.');continue;}p[key]=rows.slice(1).filter(row=>row.some(x=>x!==''&&x!==null&&x!==undefined)).map((row,i)=>{const obj={};for(let col=0;col<headers.length;col++){let k=headers[col],raw=row[col]??'',scale=1;if(['x_mm','y_mm','width_mm'].includes(k)){k=k.replace('_mm','');scale=1/1000;}if(k==='speed_m_min'){k='speed';scale=1/60;}if(numeric.has(k)){if(raw===''||!Number.isFinite(Number(raw)))errors.push(sheet+' '+(i+2)+'행 '+headers[col]+': 유효한 숫자 필요');obj[k]=Number(raw)*scale;}else if(boolean.has(k)){if(!['true','false','1','0'].includes(String(raw).toLowerCase()))errors.push(sheet+' '+(i+2)+'행 '+k+': true/false 필요');obj[k]=['true','1'].includes(String(raw).toLowerCase());}else obj[k]=String(raw);}return obj;});}
  const extra=Object.keys(book).filter(k=>!['Project','Instructions',...Object.keys(mapping)].includes(k));if(extra.length)errors.push('미지원 시트: '+extra.join(', ')+' — 데이터를 조용히 생략하지 않습니다.');if(errors.length)throw Error(errors.slice(0,40).join('\n'));const checked=Model.validate(p);if(checked.errors.length)throw Error(checked.errors.join('\n'));return p;
}
function importOD(text,p){const rows=parseCsv(text),expected=sheets(p).OD[0];if(rows[0]?.join('|')!==expected.join('|'))throw Error('OD CSV 헤더: '+expected.join(','));const book=sheets(p);book.OD=rows;return fromSheets(book,p);}
function colName(n){let s='';while(n>=0){s=String.fromCharCode(n%26+65)+s;n=Math.floor(n/26)-1;}return s;}
function sheetXml(rows){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="30" customWidth="1"/><col min="2" max="30" width="20" customWidth="1"/></cols><sheetData>'+rows.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((v,j)=>'<c r="'+colName(j)+(i+1)+'" s="'+(i===0?1:0)+'"'+(typeof v==='number'&&Number.isFinite(v)?'><v>'+v+'</v>':' t="inlineStr"><is><t xml:space="preserve">'+escape(v)+'</t></is>')+'</c>').join('')+'</row>').join('')+'</sheetData></worksheet>';}
let crcTable;function crc32(bytes){if(!crcTable)crcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xEDB88320^(n>>>1):n>>>1;return n>>>0;});let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xFFFFFFFF)>>>0;}
function zip(files){const enc=new TextEncoder(),chunks=[],central=[];let offset=0,total=0;for(const [name,text]of Object.entries(files)){const filename=enc.encode(name),body=enc.encode(text),crc=crc32(body),local=new Uint8Array(30+filename.length),d=new DataView(local.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x800,true);d.setUint32(14,crc,true);d.setUint32(18,body.length,true);d.setUint32(22,body.length,true);d.setUint16(26,filename.length,true);local.set(filename,30);chunks.push(local,body);const c=new Uint8Array(46+filename.length),v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x800,true);v.setUint32(16,crc,true);v.setUint32(20,body.length,true);v.setUint32(24,body.length,true);v.setUint16(28,filename.length,true);v.setUint32(42,offset,true);c.set(filename,46);central.push(c);offset+=local.length+body.length;total+=c.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,total,true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
function xlsx(p){const book=sheets(p),names=Object.keys(book),files={};files['[Content_Types].xml']='<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+names.map((n,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>';
  files['_rels/.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
  files['xl/workbook.xml']='<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+names.map((n,i)=>'<sheet name="'+escape(n)+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>';
  files['xl/_rels/workbook.xml.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+names.map((n,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'<Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';
  files['xl/styles.xml']='<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="맑은 고딕"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="맑은 고딕"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF123543"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
  names.forEach((n,i)=>files['xl/worksheets/sheet'+(i+1)+'.xml']=sheetXml(book[n]));return zip(files);
}
async function unzip(buffer){const bytes=new Uint8Array(buffer),v=new DataView(buffer),dec=new TextDecoder(),out={};let e=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){e=i;break;}if(e<0)throw Error('정상 XLSX ZIP 파일이 아닙니다.');const count=v.getUint16(e+10,true);let pos=v.getUint32(e+16,true),expanded=0;if(count>200)throw Error('워크북 내부 파일 수 상한 초과');for(let i=0;i<count;i++){if(v.getUint32(pos,true)!==0x02014b50)throw Error('ZIP 디렉터리 손상');const flag=v.getUint16(pos+8,true),method=v.getUint16(pos+10,true),size=v.getUint32(pos+20,true),rawSize=v.getUint32(pos+24,true),nameLen=v.getUint16(pos+28,true),extra=v.getUint16(pos+30,true),comment=v.getUint16(pos+32,true),loc=v.getUint32(pos+42,true),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen));expanded+=rawSize;if(expanded>30e6||flag&1)throw Error('암호화 또는 30 MB 초과 워크북은 지원하지 않습니다.');const begin=loc+30+v.getUint16(loc+26,true)+v.getUint16(loc+28,true),data=bytes.slice(begin,begin+size);if(/\.xml$|\.rels$/.test(name)){let result;if(method===0)result=data;else if(method===8){if(typeof DecompressionStream==='undefined')throw Error('이 브라우저는 압축 XLSX 가져오기를 지원하지 않습니다. 최신 Edge/Chrome 또는 CSV를 사용하세요.');result=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer());}else throw Error('미지원 ZIP 압축 방식');if(result.length!==rawSize||crc32(result)!==v.getUint32(pos+16,true))throw Error('XLSX 파일 CRC/크기 불일치');out[name]=dec.decode(result);}pos+=46+nameLen+extra+comment;}return out;}
async function readXlsx(file,current){const files=await unzip(await file.arrayBuffer()),xml=s=>{if(!s)throw Error('XLSX 필수 XML 누락');const x=new DOMParser().parseFromString(s,'application/xml');if(x.getElementsByTagName('parsererror').length)throw Error('XLSX XML 형식 오류');return x;},els=(x,n)=>Array.from(x.getElementsByTagNameNS('*',n)),texts=x=>els(x,'t').map(t=>t.textContent).join('');const shared=files['xl/sharedStrings.xml']?els(xml(files['xl/sharedStrings.xml']),'si').map(texts):[],wb=xml(files['xl/workbook.xml']),rels=els(xml(files['xl/_rels/workbook.xml.rels']),'Relationship'),book={};
  for(const sh of els(wb,'sheet')){const id=sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),rel=rels.find(r=>r.getAttribute('Id')===id);if(!rel)throw Error('워크시트 관계 누락');let target=rel.getAttribute('Target');target=target.startsWith('/')?target.slice(1):'xl/'+target;const sheet=xml(files[target]),rows=[];for(const row of els(sheet,'row')){const values=[];for(const c of els(row,'c')){const cellRef=c.getAttribute('r'),letters=cellRef?.match(/^[A-Z]+/)?.[0];if(!letters)throw Error('셀 주소 오류');let col=0;for(const letter of letters)col=col*26+letter.charCodeAt(0)-64;if(col>50)throw Error('템플릿 범위 외 셀 '+cellRef);if(els(c,'f').length)throw Error(sh.getAttribute('name')+'!'+cellRef+': 수식 대신 확정 값을 입력하세요.');const t=c.getAttribute('t'),value=els(c,'v')[0]?.textContent??'';values[col-1]=t==='inlineStr'?texts(c):t==='s'?shared[Number(value)]??'':t==='b'?(value==='1'?'true':'false'):value;}rows.push(Array.from({length:values.length},(_,i)=>values[i]??''));}book[sh.getAttribute('name')]=rows;}
  return fromSheets(book,current);
}
return {csv,parseCsv,sheets,fromSheets,importOD,xlsx,readXlsx,zip,unzip,crc32};
});
