(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model'):root.AgvModel,typeof module==='object'&&module.exports?require('./engine'):root.AgvEngine,typeof module==='object'&&module.exports?require('./io'):root.AgvIO);if(typeof module==='object'&&module.exports)module.exports=api;root.AgvReport=api;})(globalThis,function(Model,Engine,IO){
const num=(v,d=2)=>v===null||v===undefined?'계산 불가':Number(v).toFixed(d),clean=s=>String(s).replace(/\|/g,'/').replace(/[\r\n]/g,' ');
function markdown(p,run,experiments=[]){const a=Model.analytics(p),m=run?.metrics,status=run?Engine.assess(run):null;let text='# AGV·AMR 물동량 검토 보고서\n\n'+p.name+'\n\n';text+='- 프로젝트: '+p.projectId+' / 시나리오: '+p.scenarioId+'\n- 검토 수준: '+p.dataStatus+'\n- 엔진: '+Model.VERSION+' / 스키마: '+Model.SCHEMA+'\n- 설정 해시: '+Model.hash(p)+' / 시드: '+p.seed+'\n- 입력 근거: '+p.sources+'\n\n';text+='## 물동량 및 대수\n\n| 항목 | 결과 |\n|---|---:|\n| 요구 수량 | '+num(a.qty)+' PLT/Hr |\n| 작업 발생률 | '+num(a.jobs)+' 작업/Hr |\n| 해석 미정수 대수 | '+num(a.raw,9)+' |\n| 해석 초기 대수 | '+a.vehicles+'대 |\n| 운영 대수 | '+p.fleet+'대 |\n| 평균 해석 작업시간 | '+num(a.cycle)+' s/작업 |\n\n';text+='초기 대수 = ceil((적재·이재 부하 + 선택 공차 부하 + 해석 교통 추가) / (3600 × 기술 가용도 × 조건부 충전 가용도 × 목표 점유율)).\n\n';text+='| 시간부하 | s/h |\n|---|---:|\n| 적재 주행 | '+num(a.loadedTravel)+' |\n| 이재·제어 | '+num(a.handling)+' |\n| 공차 | '+num(a.emptyWork)+' |\n| 해석 교통 추가 | '+num(a.extra)+' |\n\n';
  text+='## 운전 모델\n\n- 단일 층 경로망, '+p.vehicle.kind+', '+p.vehicle.module+' 모듈, '+(p.vehicle.turning?'제자리 회전':'방향 전환시간 0의 전방향 시험 가정')+'.\n- '+(p.routing==='dynamic'?'동적 우회 허용':'기본 경로 고정')+', 배차 '+p.dispatch+', 작업 종료 후 전용 주차 베이 복귀.\n- 차량·적재 외곽을 감싸는 원을 이용한 전 경로 배타 예약. 링크 내 연속 추종, 조향·견인 궤적, 센서/SLAM은 미지원.\n- 폐쇄는 신규 경로 진입 제한. 이미 진입한 예약 차량은 통과를 마칩니다. 계획 정지는 현재 동작과 주차 복귀 후 적용합니다.\n- 스테이션/충전기 노드당 차량 1대. 후공정은 화물별 서비스시간과 병렬 슬롯을 사용합니다.\n- 배터리 '+(p.battery.enabled?'상태 전력·80% 이후 2단 순충전곡선 사용':'비활성')+'. 해석 손실계수와 DES 사건 손실을 중복 적용하지 않습니다.\n- 경로 탐색 비용은 구간 정지·회전시간 기준이며, 선택 경로의 실제 주행은 연속 경계속도 프로파일로 계산합니다.\n\n';
  if(m){text+='## 시뮬레이션\n\n- 실행 ID: '+run.runId+'\n- 측정창: ['+p.warmup+', '+p.horizon+') s, 완료 시각 기준 처리량.\n- 리드타임/납기: 측정창 발생 요청 코호트. P95는 종료 시 완료 요청만 사용; 미완료·기한초과 동시 제시.\n- 판정: '+status.label+(status.issues.length?' — '+status.issues.join(', '):'')+'\n- 보존·예약 검사: '+(run.audit.ok?'통과':run.audit.errors.join(', '))+'\n\n| KPI | 결과 |\n|---|---:|\n| 완료 처리량 | '+num(m.throughput)+' PLT/Hr |\n| 측정창 완료 수량 | '+m.completedQty+' PLT |\n| 측정창 완료 작업 | '+m.completedJobs+'건 |\n| 요청 수량 충족률 | '+num(m.fulfillment===null?null:m.fulfillment*100)+'% |\n| 완료 코호트 P95 | '+num(m.p95)+' s |\n| 완료 코호트 평균 리드타임 | '+num(m.meanLead)+' s |\n| 종료 백로그 | '+m.backlog+'건 |\n| 기한 초과 미완료 | '+m.overdue+'건 |\n| 최장 미완료 경과 | '+num(m.oldest)+' s |\n| 납기 준수율(기한 도래 요청) | '+num(m.onTime===null?null:m.onTime*100)+'% |\n| 최저 SOC | '+num(m.minSoc*100)+'% |\n| 총 소비/순충전 | '+num(m.consumed)+' / '+num(m.charged)+' Wh |\n| 시작/종료 총 에너지 | '+num(m.initialEnergy)+' / '+num(m.finalEnergy)+' Wh |\n| 충전 방문 | '+m.chargeVisits+'회 |\n| 모델 실패 | '+m.failures+'건 |\n\n';
    text+='| 차량 상태 | 측정 차량시간 비율 |\n|---|---:|\n'+Object.entries(m.states).map(([k,v])=>'| '+Engine.STATES[k]+' | '+num(v*100)+'% |').join('\n')+'\n\n';text+='| 자원 | 차량 서비스 점유율 | 후공정 점유율 | 차량 대기 s |\n|---|---:|---:|---:|\n'+m.resources.map(r=>'| '+r.id+' | '+num(r.busy*100)+'% | '+num(r.processBusy*100)+'% | '+num(r.wait)+' |').join('\n')+'\n\n';
    if(run.failures.length)text+='실패 기록:\n\n'+run.failures.map(f=>'- '+num(f.time)+' s / '+f.vehicle+' / '+f.reason).join('\n')+'\n\n';
  }
  if(experiments.length)text+='## 대안 비교\n\n| 대안 | 평균 PLT/Hr | 반복 간 평균 95% CI | 최대 백로그 | 판정 |\n|---|---:|---|---:|---|\n'+experiments.map(e=>'| '+clean(e.label)+' | '+num(e.ci.mean)+' | '+(e.ci.low===null?'반복 부족':num(e.ci.low)+' ~ '+num(e.ci.high))+' | '+e.maxBacklog+' | '+clean(e.labelStatus)+' |').join('\n')+'\n\n';
  text+='## 적용 조건 및 미확인 항목\n\n'+a.validation.warnings.map(s=>'- '+s).join('\n')+'\n- 입력 수요의 완료량은 포화 처리능력과 다릅니다. 충분한 부하·장기 충전 반복·백로그 및 독립 검증 시드 재시험 전에는 지속능력으로 확정하지 않습니다.\n- 이 버전은 v0.3 운영 검토판입니다. 계획서 F01~F13 / V01~V12 전체 정식 검수 및 현장 검증을 완료한 버전은 아닙니다.\n\n## 재현 입력 (SI 단위)\n\n```json\n'+JSON.stringify(Model.pack(p),null,2)+'\n```\n';return text;
}
function jobs(run){return IO.csv([['task_id','origin','destination','quantity_PLT','release_s','assigned_s','completed_s','lead_s','due_s','vehicle_id','status'],...run.tasks.map(j=>[j.id,j.from,j.to,j.qty,j.release,j.assigned,j.completed,j.completed===null?'':j.completed-j.release,j.due,j.vehicle,j.completed===null?'미완료':'완료'])]);}
function events(run){return IO.csv([['sim_time_s','event','vehicle_id','node_id','task_id','cause'],...run.events.map(e=>[e.time,e.type,e.vehicle,e.node,e.taskId,e.detail])]);}
return {markdown,jobs,events};
});
