(function(root){'use strict';
class Scene{
  constructor(container,onSelect){this.container=container;this.onSelect=onSelect;this.actors=new Map();this.stationActors=new Map();this.labels=[];this.mode='iso';this.fallback=false;this.forced2D=false;this.showPaths=true;this.showLabels=true;this.envelopes=false;this.selected='V1';this.time=0;this.lastFallback=-1;
    try{if(!root.THREE)throw Error('3D 라이브러리 없음');const T=root.THREE;this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0xeaf0f4);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.domElement.setAttribute('aria-label','AGV AMR 3D 운전 장면');container.prepend(this.renderer.domElement);container.dataset.renderer='webgl';this.world=new T.Scene();this.camera=new T.PerspectiveCamera(40,1,.1,1500);this.controls=new T.OrbitControls(this.camera,this.renderer.domElement);
      // Wheel-button drag pans the view; rolling the wheel still zooms.
      this.controls.mouseButtons.MIDDLE = T.MOUSE.PAN; this.controls.screenSpacePanning = true;
this.controls.enableDamping=true;this.controls.dampingFactor=.12;this.controls.maxPolarAngle=Math.PI/2.03;this.controls.minDistance=4;this.controls.maxDistance=250;this.renderer.domElement.addEventListener('pointerdown',e=>this.down={x:e.clientX,y:e.clientY});this.renderer.domElement.addEventListener('pointerup',e=>{if(e.button===0&&this.down&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)<4)this.pick(e);});this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();this.fallback=true;container.dataset.renderer='2d';this.render(this.time);});new ResizeObserver(()=>this.resize()).observe(container);
    }catch(e){this.fallback=true;container.dataset.renderer='2d';this.error=e.message;}
  }
  material(color,extra={}){return new THREE.MeshStandardMaterial({color:new THREE.Color(color).convertSRGBToLinear(),roughness:.72,metalness:.04,...extra});}
  box(parent,w,h,d,x,y,z,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof mat==='number'?this.material(mat):mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  cylinder(parent,radius,height,x,y,z,color){const m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,16),this.material(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
  label(parent,text,x,y,z,color='#4f6e7f',width=3.2){const canvas=document.createElement('canvas');canvas.width=384;canvas.height=96;const c=canvas.getContext('2d');c.fillStyle='rgba(255,255,255,.96)';c.fillRect(0,0,384,96);c.strokeStyle='#b3c9d4';c.strokeRect(1,1,382,94);c.fillStyle=color;c.textAlign='center';c.textBaseline='middle';c.font='bold 42px Segoe UI, Malgun Gothic';c.fillText(text,192,51);const texture=new THREE.CanvasTexture(canvas);texture.encoding=THREE.sRGBEncoding;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false,transparent:true,toneMapped:false}));sprite.scale.set(width,width/4,1);sprite.position.set(x,y,z);parent.add(sprite);this.labels.push(sprite);return sprite;}
  cargo(parent,p,scale=1){const g=new THREE.Group(),v=p.vehicle,L=v.cargoLength*scale,W=v.cargoWidth*scale,H=v.cargoHeight*scale;this.box(g,L,.11,W,0,.06,0,0xb69b72);for(const z of [-W*.32,W*.32])this.box(g,L*.92,.1,.12,0,.14,z,0xa18b67);this.box(g,L*.91,H*.87,W*.9,0,.2+H*.435,0,0xc4ac83);this.box(g,L*.925,H*.88,.035,0,.2+H*.44,0,0xe6d7b9);this.box(g,.04,H*.88,W*.91,0,.2+H*.44,0,0xe6d7b9);this.box(g,.23,.18,.012,L*.22,.3+H*.4,W*.458,0xf5f0e5);parent.add(g);return g;}
  robot(v,p){const T=THREE,g=new T.Group(),spec=p.vehicle,L=spec.length,W=spec.width,paint=this.material(0x18ab97),dark=this.material(0x283d49),silver=this.material(0xc6d3d9,{metalness:.6,roughness:.4});this.box(g,L,.27,W,0,.3,0,paint);this.box(g,L*.95,.12,W*.93,0,.12,0,dark);this.box(g,L*.88,.08,W*.86,0,.48,0,silver);for(const x of [-L*.32,L*.32])for(const z of [-W*.5,W*.5]){const wheel=this.cylinder(g,.115,.07,x,.13,z,0x233642);wheel.rotation.x=Math.PI/2;}
    if(spec.module==='roller')for(let i=0;i<8;i++){const r=this.cylinder(g,.026,W*.79,-L*.36+i*L*.72/7,.555,0,0xb8c9d2);r.rotation.x=Math.PI/2;}else this.box(g,L*.62,.045,W*.63,0,.55,0,0x334b59);
    const lidar=this.cylinder(g,.085,.07,L*.37,.46,0,0x202e38);const lamp=this.box(g,.04,.04,W*.6,L*.504,.32,0,this.material(0x76ffe7,{emissive:0x27bdae,emissiveIntensity:.6}));this.box(g,.013,.09,W*.23,L*.51,.19,0,0x162834);this.box(g,L*.13,.012,W*.09,L*.14,.564,0,0xffffff);
    const load=this.cargo(g,p);load.position.y=.56;load.visible=false;const halo=new T.Mesh(new T.RingGeometry(.82,1,40),new T.MeshBasicMaterial({color:0x2ba99b,transparent:true,opacity:.45,side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.022;g.add(halo);
    const radius=Math.hypot(Math.max(L,spec.cargoLength),Math.max(W,spec.cargoWidth))/2+spec.clearance,envelope=new T.Mesh(new T.CircleGeometry(radius,40),new T.MeshBasicMaterial({color:0xdea243,transparent:true,opacity:.15,depthWrite:false}));envelope.rotation.x=-Math.PI/2;envelope.position.y=.027;g.add(envelope);const label=this.label(g,v.id,0,2.5,0,'#3c6374',1.7);this.dynamic.add(g);g.userData.vehicle=v.id;g.traverse(o=>o.userData.vehicle=v.id);return {g,paint,load,halo,envelope,label,lidar,lamp};}
  disposeGroup(group){if(!group)return;group.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});this.world.remove(group);}
  setRun(run){this.followAnchor=null;this.run=run;this.p=run.config;this.time=0;this.lastFallback=-1;if(this.fallback){this.render(0);return;}const T=THREE;this.disposeGroup(this.facility);this.disposeGroup(this.dynamic);this.actors.clear();this.stationActors.clear();this.labels=[];this.facility=new T.Group();this.dynamic=new T.Group();this.world.add(this.facility,this.dynamic);if(!this.light){this.world.add(new T.HemisphereLight(0xeaf8ff,0xa4afb5,.95));const light=new T.DirectionalLight(0xffffff,1.15);light.position.set(-15,65,20);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-70,right:70,top:70,bottom:-70,near:1,far:180});light.shadow.bias=-.0004;this.world.add(light);this.light=light;}
    const nodes=this.p.nodes,minX=Math.min(...nodes.map(n=>n.x))-10,maxX=Math.max(...nodes.map(n=>n.x))+10,minY=Math.min(...nodes.map(n=>n.y))-9,maxY=Math.max(...nodes.map(n=>n.y))+9,W=maxX-minX,D=maxY-minY;this.center=new T.Vector3((minX+maxX)/2,0,-(minY+maxY)/2);this.span=Math.max(W,D);this.light.target.position.copy(this.center);this.world.add(this.light.target);
    const floor=this.box(this.facility,W,.15,D,this.center.x,-.12,this.center.z,0xe7edf1);floor.castShadow=false;const grid=new T.GridHelper(Math.ceil(Math.max(W,D)/4)*4,Math.ceil(Math.max(W,D)/4),0xc8d6df,0xd7e2e8);grid.position.copy(this.center);grid.position.y=-.03;this.facility.add(grid);
    this.paths=new T.Group();this.facility.add(this.paths);const byId=new Map(nodes.map(n=>[n.id,n]));for(const e of this.p.paths){if(!e.enabled)continue;const a=byId.get(e.from),b=byId.get(e.to),len=Math.hypot(b.x-a.x,b.y-a.y),angle=Math.atan2(b.y-a.y,b.x-a.x),path=new T.Group();path.position.set((a.x+b.x)/2,.005,-(a.y+b.y)/2);path.rotation.y=angle;this.box(path,len,.01,e.width,0,0,0,0xadc3ce).castShadow=false;for(const z of [-e.width*.46,e.width*.46])this.box(path,len,.015,.025,0,.012,z,0xffffff).castShadow=false;for(let x=-len/2+.4;x<len/2;x+=1.3)this.box(path,Math.min(.55,len/2-x),.016,.045,x,.02,0,0x36798c).castShadow=false;this.paths.add(path);if(e.direction==='forward'){const cone=new T.Mesh(new T.ConeGeometry(.22,.55,3),this.material(0x699ca9));cone.rotation.z=-Math.PI/2;cone.scale.z=.12;cone.position.y=.07;path.add(cone);}if(e.door>0){this.box(path,.15,2.8,.16,0,1.4,-e.width*.55,0x7397a9);this.box(path,.15,2.8,.16,0,1.4,e.width*.55,0x7397a9);this.box(path,.16,.16,e.width*1.2,0,2.8,0,0x8aabb7);}}
    this.closureMeshes=[];for(const c of this.p.closures){const edge=this.p.paths.find(e=>e.id===c.pathId),a=byId.get(edge.from),b=byId.get(edge.to),g=new T.Group();g.position.set((a.x+b.x)/2,0,-(a.y+b.y)/2);g.rotation.y=Math.atan2(b.y-a.y,b.x-a.x);for(const z of [-.65,.65])this.box(g,.15,.8,.15,0,.4,z,0x7e8790);this.box(g,.12,.25,1.7,0,.75,0,0xe6a240);this.label(g,'통행 폐쇄',0,1.7,0,'#ab723c',2.3);this.facility.add(g);this.closureMeshes.push({g,c});}
    for(const n of nodes){if(n.type==='junction')continue;const g=new T.Group();g.position.set(n.x,0,-n.y);if(n.type==='station'){const pad=this.box(g,3.8,.025,3.8,0,.013,0,0xcbdfe1);pad.castShadow=false;for(const z of [-1.7,1.7])this.box(g,3.5,.02,.05,0,.035,z,0x88afae);this.label(g,n.id+' · '+(this.p.od.some(o=>o.from===n.id)?'공급':'공정'),0,2.8,-2.3,'#4d7a84',3.5);const stationCargo=this.cargo(g,this.p,.8);stationCargo.position.set(0,.03,2.6);stationCargo.visible=false;this.stationActors.set(n.id,{g,cargo:stationCargo,label:null});}
      if(n.type==='parking'){const pad=this.box(g,2,.02,2.5,0,.01,0,0xd3e0e6);pad.castShadow=false;for(const z of [-1.15,1.15])this.box(g,1.8,.02,.05,0,.025,z,0xf6f9fa);this.label(g,n.id,0,.15,2,'#91a5af',1.7);}
      if(n.type==='charger'){const mat=n.enabled?0x9477b6:0xc0c7d0;this.box(g,2.5,.025,2.5,0,.018,0,n.enabled?0xe2ddec:0xe2e6eb);this.box(g,1.05,1.3,.5,0,.65,-1.8,0xecf0f4);this.box(g,.64,.4,.02,0,.96,-1.53,0x41556a);this.box(g,.16,.3,.025,0,.4,-1.52,mat);this.label(g,n.id+(n.enabled?' · 충전':' · 비활성'),0,2.4,-1.8,n.enabled?'#8563a5':'#a0adb8',3);}
      this.facility.add(g);
    }
    // Explanatory racks are placed only in open areas, away from every driving corridor.
    let rackCount=0;for(let x=minX+15;x<maxX-12;x+=12)for(let y=minY+16;y<maxY-12;y+=14){if(rackCount>=6)continue;const point={x,y},free=this.p.paths.every(e=>{const a=byId.get(e.from),b=byId.get(e.to);return AgvMotion.pointSegment(point,a,b)>6+e.width/2;})&&nodes.every(n=>Math.hypot(n.x-x,n.y-y)>6);if(!free)continue;const rack=new T.Group();rack.position.set(x,0,-y);for(const xx of [-3,3])for(const zz of [-1.25,1.25])this.box(rack,.1,4,.1,xx,2,zz,0x5a8199);for(const h of [.25,1.7,3.15]){this.box(rack,6.2,.1,2.7,0,h,0,0xafa185);for(const xx of [-2,0,2])this.box(rack,1.6,1,1.9,xx,h+.56,0,0xc4b79f);}this.facility.add(rack);rackCount++;}
    for(const v of run.vehicles)this.actors.set(v.id,this.robot(v,this.p));this.reservedGroup=new T.Group();this.dynamic.add(this.reservedGroup);this.setCamera('iso');this.resize();this.render(0);
  }
  setCamera(mode){this.mode=mode;if(this.fallback||!this.center)return;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.85;const s=this.span,c=this.center;this.controls.target.copy(c);this.camera.position.copy(c).add(mode==='top'?new THREE.Vector3(0,s*1.12,.001):new THREE.Vector3(s*.55,s*.74,s*.72));this.camera.lookAt(c);this.controls.update();}
  focusVehicle(id){if(this.fallback||!this.run)return;const vehicle=this.run.vehicles.find(v=>v.id===id);if(!vehicle)return;const p=AgvEngine.vehiclePose(this.run,vehicle,this.time),target=new THREE.Vector3(p.x,.8,-p.y);this.followAnchor={id,position:target.clone()};this.controls.target.copy(target);this.camera.position.copy(target).add(new THREE.Vector3(6,5,6));this.camera.lookAt(target);this.controls.update();}
  resize(){if(this.fallback||!this.renderer)return;const r=this.container.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.render(this.time);}
  pick(e){if(!this.run||this.fallback)return;const rect=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const hits=ray.intersectObjects([...this.actors.values()].map(a=>a.g),true),hit=hits.find(h=>h.object.userData.vehicle);if(hit)this.onSelect(hit.object.userData.vehicle);}
  render(time){this.time=time;if(!this.run)return;const is2D=this.fallback||this.forced2D,el=document.getElementById('sceneFallback');if(this.renderer)this.renderer.domElement.hidden=is2D;el.hidden=!is2D;const poses=this.run.vehicles.map(v=>({id:v.id,...AgvEngine.vehiclePose(this.run,v,time)}));if(is2D){if(Math.abs(time-this.lastFallback)>.08||this.lastFallback<0){el.innerHTML=AgvView.layoutSvg(this.p,{poses,time,envelopes:this.envelopes});this.lastFallback=time;}return;}
    if(!this.follow)this.followAnchor=null;
    this.paths.visible=this.showPaths;for(const l of this.labels)l.visible=this.showLabels;for(const {g,c}of this.closureMeshes)g.visible=time>=c.start&&time<c.end;
    for(const pose of poses){
      const actor=this.actors.get(pose.id),vehicle=this.run.vehicles.find(v=>v.id===pose.id),seg=AgvEngine.segmentAt(vehicle,time);
      actor.g.position.set(pose.x,0,-pose.y);actor.g.rotation.y=pose.heading;actor.paint.color.set(AgvView.colors[pose.state]||'#7893a3').convertSRGBToLinear();actor.halo.visible=pose.id===this.selected;actor.envelope.visible=this.envelopes;actor.load.visible=pose.loaded;actor.load.position.set(0,.56,0);actor.label.position.y=pose.loaded?2.65:1.5;
      if(pose.state==='pickup'){const f=(time-seg.start)/(seg.end-seg.start);actor.load.visible=true;actor.load.position.y=.2+.36*f;}else if(pose.state==='dropoff'){const f=(time-seg.start)/(seg.end-seg.start);actor.load.position.y=.56-.25*f;}
      const routeKey=seg?.motion?seg.start:null;if(actor.routeKey!==routeKey){if(actor.routeLine){this.reservedGroup.remove(actor.routeLine);actor.routeLine.geometry.dispose();actor.routeLine.material.dispose();actor.routeLine=null;}actor.routeKey=routeKey;if(seg?.motion){const points=seg.motion.points.map(n=>new THREE.Vector3(n.x,.075,-n.y)),geometry=new THREE.BufferGeometry().setFromPoints(points);actor.routeLine=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:AgvView.colors[pose.state],transparent:true,opacity:.8}));this.reservedGroup.add(actor.routeLine);}}
      if(actor.routeLine)actor.routeLine.visible=this.envelopes;
      if(this.follow&&pose.id===this.selected){const target=new THREE.Vector3(pose.x,.8,-pose.y),delta=target.clone().sub(this.followAnchor?.id===pose.id?this.followAnchor.position:this.controls.target);this.controls.target.add(delta);this.camera.position.add(delta);this.followAnchor={id:pose.id,position:target};}
    }
    for(const [id,a]of this.stationActors){const buffer=this.run.buffers[id],qty=[...(buffer?.changes||[])].reverse().find(x=>x.time<=time)?.qty||0;a.cargo.visible=qty>0;}
    this.controls.update();this.renderer.render(this.world,this.camera);
  }
  capture(){this.render(this.time);if(this.fallback||this.forced2D)throw Error('PNG 캡처는 3D 화면에서 지원합니다.');const src=this.renderer.domElement,c=document.createElement('canvas');c.width=src.width;c.height=src.height+160;const ctx=c.getContext('2d');ctx.fillStyle='#123543';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(src,0,85);const ratio=c.width/1000;ctx.fillStyle='#e8f2f5';ctx.font='bold '+Math.max(18,20*ratio)+'px Malgun Gothic';ctx.fillText(this.p.name+' · '+AgvView.clock(this.time),24,35);ctx.font=Math.max(13,13*ratio)+'px Malgun Gothic';const m=AgvEngine.metrics(this.run,this.time);ctx.fillStyle='#a9c7d2';ctx.fillText('시나리오 '+this.p.scenarioId+' / '+this.run.configHash+' · 완료 '+m.totalCompleted+'건 · 백로그 '+m.backlog+'건',24,63);ctx.fillText('청록: 공차·복귀   파랑: 적재   황색: 대기   보라: 충전   회색: 유휴   빨강: 정지·실패',24,c.height-39);ctx.fillText('가정 기반 · 전 경로 배타 예약 · v'+AgvModel.VERSION+' · 재생 시각의 KPI',24,c.height-15);return c.toDataURL('image/png');}
}
root.AgvScene={Scene};
})(globalThis);
