(function(root){'use strict';const colors={idle:'#7893a3',empty:'#18ab97',loaded:'#367dde',pickup:'#398fcc',dropoff:'#398fcc',control:'#559ea4',traffic:'#e2a036',blocked:'#d79032',returning:'#18ab97',toCharge:'#8262c9',dock:'#aa83df',charging:'#9c6ee8',undock:'#aa83df',chargeWait:'#c59247',stopped:'#df6556',failed:'#dc4d4d'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('ko-KR',{minimumFractionDigits:d,maximumFractionDigits:d}),clock=t=>{t=Math.max(0,Math.floor(t));return [Math.floor(t/3600),Math.floor(t/60)%60,t%60].map(x=>String(x).padStart(2,'0')).join(':');};
function table(headers,rows){return '<table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function kpis(items){return items.map((x,i)=>'<article class="kpi '+(i===0?'featured':'')+'"><div class="kpi-label">'+esc(x.label)+'</div><div class="kpi-value">'+esc(x.value)+'<small>'+esc(x.unit||'')+'</small></div><p>'+esc(x.note||'')+'</p></article>').join('');}
function bars(items){const max=Math.max(1,...items.map(x=>x.value));return items.filter(x=>x.value>0).map(x=>'<div class="bar-row"><div class="label"><span>'+esc(x.label)+'</span><span>'+esc(x.display??fmt(x.value))+'</span></div><div class="bar-track"><div class="bar-fill" style="width:'+Math.min(100,x.value/max*100)+'%;background:'+x.color+'"></div></div></div>').join('');}
function lineChart(series,{xLabel='시간 min',yLabel='',width=560,height=210,yMax=null}={}){const points=series.flatMap(s=>s.points);if(!points.length)return '<div class="empty-message">실행 결과가 없습니다.</div>';const L=42,R=18,T=22,B=28,W=width-L-R,H=height-T-B,maxX=Math.max(1,...points.map(p=>p.x)),maxY=yMax||Math.max(1,...points.map(p=>p.y))*1.12,x=v=>L+v/maxX*W,y=v=>T+H-v/maxY*H;let s='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(yLabel+' '+xLabel)+'">';for(let i=0;i<=4;i++){const value=maxY*i/4,yy=y(value);s+='<line class="grid" x1="'+L+'" x2="'+(width-R)+'" y1="'+yy+'" y2="'+yy+'"/><text x="'+(L-8)+'" y="'+(yy+3)+'" text-anchor="end">'+fmt(value,value<10?1:0)+'</text>';}for(let i=0;i<=4;i++){const value=maxX*i/4;s+='<text x="'+x(value)+'" y="'+(height-10)+'" text-anchor="middle">'+fmt(value,0)+'</text>';}s+='<text x="'+L+'" y="12">'+esc(yLabel)+'</text><text x="'+(width-R)+'" y="12" text-anchor="end">'+esc(xLabel)+'</text>';for(const line of series){s+='<path d="'+line.points.map((p,i)=>(i?'L':'M')+x(p.x).toFixed(2)+','+y(p.y).toFixed(2)).join(' ')+'" fill="none" stroke="'+line.color+'" stroke-width="2" stroke-linejoin="round"'+(line.dashed?' stroke-dasharray="4 3"':'')+'/>';if(line.points.length===1)s+='<circle cx="'+x(line.points[0].x)+'" cy="'+y(line.points[0].y)+'" r="3" fill="'+line.color+'"/>';}return s+'</svg><div class="chart-key">'+series.map(s=>'<span style="--color:'+s.color+'">'+esc(s.label)+'</span>').join('')+'</div>';}
function markdown(text){const lines=text.split('\n');let html='',inCode=false,code='',inList=false,tableRows=[];function flushTable(){if(tableRows.length){const heads=tableRows[0];html+=table(heads,tableRows.slice(2));tableRows=[];}}for(const line of lines){if(line.startsWith('```')){flushTable();if(inList){html+='</ul>';inList=false;}if(inCode){html+='<pre><code>'+esc(code)+'</code></pre>';code='';}inCode=!inCode;continue;}if(inCode){code+=line+'\n';continue;}if(line.startsWith('|')){tableRows.push(line.split('|').slice(1,-1).map(s=>s.trim()));continue;}flushTable();if(line.startsWith('- ')){if(!inList){html+='<ul>';inList=true;}html+='<li>'+esc(line.slice(2))+'</li>';continue;}if(inList){html+='</ul>';inList=false;}if(/^#{1,3} /.test(line)){const level=line.match(/^#+/)[0].length;html+='<h'+Math.min(3,level+1)+'>'+esc(line.slice(level+1))+'</h'+Math.min(3,level+1)+'>';}else if(line.trim())html+='<p>'+esc(line)+'</p>';}flushTable();if(inList)html+='</ul>';return html;}
function layoutSvg(p,{selected=null,poses=[],time=0,envelopes=false}={}){if(!p.nodes.length)return '<svg viewBox="-10 -10 20 20"></svg>';const minX=Math.min(...p.nodes.map(n=>n.x))-9,maxX=Math.max(...p.nodes.map(n=>n.x))+9,minY=Math.min(...p.nodes.map(n=>n.y))-9,maxY=Math.max(...p.nodes.map(n=>n.y))+9,w=maxX-minX,h=maxY-minY,byId=new Map(p.nodes.map(n=>[n.id,n])),nodeColors={station:'#298c9b',junction:'#a4bbc4',parking:'#7d96a4',charger:'#a07bc6'};let s='<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+[minX,-maxY,w,h].join(' ')+'" role="img" aria-label="AGV AMR 평면 레이아웃"><defs><pattern id="grid" width="4" height="4" patternUnits="userSpaceOnUse"><path d="M 4 0 L 0 0 0 4" fill="none" stroke="#dfe8ed" stroke-width=".05"/></pattern><marker id="arrow" markerWidth="4" markerHeight="4" refX="2" refY="2" orient="auto"><path d="M0,0 L4,2 L0,4 z" fill="#7598a9"/></marker></defs><rect x="'+minX+'" y="'+(-maxY)+'" width="'+w+'" height="'+h+'" fill="url(#grid)"/>';
  for(const e of p.paths){const a=byId.get(e.from),b=byId.get(e.to);if(!a||!b)continue;const blocked=p.closures.some(c=>c.pathId===e.id&&time>=c.start&&time<c.end);s+='<line x1="'+a.x+'" y1="'+(-a.y)+'" x2="'+b.x+'" y2="'+(-b.y)+'" stroke="'+(blocked?'#efc5b1':e.enabled?'#dde8ec':'#eee')+'" stroke-width="'+e.width+'"/>';s+='<line data-edge="'+esc(e.id)+'" x1="'+a.x+'" y1="'+(-a.y)+'" x2="'+b.x+'" y2="'+(-b.y)+'" stroke="'+(blocked?'#d88361':'#7da7b2')+'" stroke-width=".1" stroke-dasharray=".4 .35"'+(e.direction==='forward'?' marker-end="url(#arrow)"':'')+'><title>'+esc(e.id+' · '+e.from+' → '+e.to+' · '+fmt(e.speed*60)+' m/min')+'</title></line>';}
  for(const n of p.nodes){const special=n.type!=='junction',r=special?.72:.24;s+='<g class="node" data-node="'+esc(n.id)+'" opacity="'+(n.enabled?1:.35)+'"><circle cx="'+n.x+'" cy="'+(-n.y)+'" r="'+(n.id===selected?1.1:r)+'" fill="'+(n.id===selected?'#e9b755':nodeColors[n.type])+'" stroke="white" stroke-width=".12"/><text x="'+n.x+'" y="'+(-n.y-1.25)+'" text-anchor="middle" fill="#5e7b8a" font-size="'+(special?.95:.6)+'" style="pointer-events:none">'+esc(n.id)+'</text><title>'+esc(n.id+' / '+n.type+' / '+fmt(n.x*1000,0)+', '+fmt(n.y*1000,0)+' mm')+'</title></g>';}
  const v=p.vehicle;for(const x of poses){const c=colors[x.state];s+='<g data-vehicle="'+esc(x.id)+'" transform="translate('+x.x+' '+(-x.y)+') rotate('+(-x.heading*180/Math.PI)+')">'+(envelopes?'<circle r="'+(Math.hypot(Math.max(v.length,v.cargoLength),Math.max(v.width,v.cargoWidth))/2+v.clearance)+'" fill="'+c+'" fill-opacity=".13" stroke="'+c+'" stroke-width=".08"/>':'')+'<rect x="'+(-v.length/2)+'" y="'+(-v.width/2)+'" width="'+v.length+'" height="'+v.width+'" rx=".15" fill="'+c+'" stroke="white" stroke-width=".1"/>'+(x.loaded?'<rect x="-.4" y="-.35" width=".8" height=".7" fill="#cfac7a"/>':'')+'<path d="M .4,-.2 L .65,0 .4,.2" fill="none" stroke="white" stroke-width=".08"/></g><text x="'+x.x+'" y="'+(-x.y+1.8)+'" text-anchor="middle" font-size=".8" fill="#526e7f">'+esc(x.id)+'</text>';}
  return s+'<text x="'+(minX+2)+'" y="'+(-minY-2)+'" font-size=".8" fill="#8da5b3">격자 4,000 mm · X → / Y ↑</text></svg>';
}
root.AgvView={colors,esc,fmt,clock,table,kpis,bars,lineChart,markdown,layoutSvg};
})(globalThis);
