'use strict';
const {chromium}=require(process.env.LIFT_PLAYWRIGHT_PATH||'../../06_conveyor/node_modules/playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..'),qa=path.join(root,'07_vertical_lift/qa'),records=[];fs.mkdirSync(qa,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1580,height:1050},acceptDownloads:true});const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
async function check(name,fn){try{await fn();records.push({name,pass:true});console.log('PASS '+name);}catch(e){records.push({name,pass:false,error:e.message});await page.screenshot({path:path.join(qa,'failure.png'),fullPage:true});throw e;}}
async function download(id,name){const promise=page.waitForEvent('download');await page.click('#'+id);const d=await promise,file=path.join(qa,name||d.suggestedFilename());await d.saveAs(file);return file;}
async function run(){await page.click('#run');await page.waitForFunction(()=>!!window.LiftApp.run,{},{timeout:60000});}
try{
await page.goto(pathToFileURL(path.join(root,'리프트_실행.html')).href);await page.waitForFunction(()=>window.LiftApp?.scene.ready);await page.screenshot({path:path.join(qa,'01-default.png'),fullPage:true});
await check('offline WebGL application initializes without script errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);assert.equal(await page.locator('#scene canvas').count(),1);assert.equal(await page.locator('#errors').isVisible(),false);});
await check('middle-button drag pans and wheel still zooms',async()=>{const before=await page.evaluate(()=>LiftApp.scene.controls.target.toArray()),box=await page.locator('#scene canvas').boundingBox();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.55);await page.mouse.down({button:'middle'});await page.mouse.move(box.x+box.width*.55+80,box.y+box.height*.55+35,{steps:10});await page.mouse.up({button:'middle'});const after=await page.evaluate(()=>LiftApp.scene.controls.target.toArray());assert.ok(Math.hypot(...after.map((v,i)=>v-before[i]))>.05);const a=await page.evaluate(()=>LiftApp.scene.camera.position.distanceTo(LiftApp.scene.controls.target));await page.mouse.wheel(0,-200);await page.waitForTimeout(150);const b=await page.evaluate(()=>LiftApp.scene.camera.position.distanceTo(LiftApp.scene.controls.target));assert.ok(b<a);await page.click('[data-view=iso]');});
await check('worker computes conservation and separates unload from handoff',async()=>{await run();const r=await page.evaluate(()=>({m:LiftApp.run.metrics,count:LiftApp.run.items.length}));assert.ok(r.m.conservation);assert.ok(r.m.throughput>0);assert.ok(r.count>100);assert.equal(await page.locator('#errors').isVisible(),false);});
await check('3D seek uses simulated loaded car position',async()=>{const target=await page.evaluate(()=>{const s=LiftApp.run.cars[0].segments.find(s=>s.state==='loaded'&&s.end>s.start);return (s.start+s.end)/2;});await page.locator('#seek').evaluate((el,t)=>{el.value=t;el.dispatchEvent(new Event('input',{bubbles:true}));},target);const delta=await page.evaluate(()=>Math.abs(LiftApp.scene.carGroups[0].position.y-LiftEngine.snapshot(LiftApp.run,LiftApp.scene.time).poses[0].y));assert.ok(delta<1e-8);await page.screenshot({path:path.join(qa,'02-loaded-lift.png'),fullPage:true});});
await check('pallet cargo geometry stays within its stated dimensions',async()=>{const sizes=await page.evaluate(()=>LiftApp.scene.actors.filter(g=>g.visible).map(g=>({actual:new THREE.Box3().setFromObject(g).getSize(new THREE.Vector3()).toArray(),cargo:LiftApp.config.cargo.find(c=>c.id===g.userData.cargo)})));assert.ok(sizes.length>0);for(const x of sizes){assert.ok(Math.abs(x.actual[0]-x.cargo.length)<.01);assert.ok(Math.abs(x.actual[1]-x.cargo.height)<.01);assert.ok(x.actual[2]<=x.cargo.width+.01);}});
await check('play pause and rewind operate on simulation time',async()=>{await page.click('#play');await page.waitForTimeout(250);assert.equal(await page.locator('#play').innerText(),'일시정지');await page.click('#play');await page.click('#rewind');assert.equal(await page.locator('#seek').inputValue(),'0');});
await check('result tables and charts are available',async()=>{await page.click('[data-tab=results]');assert.ok((await page.locator('#results').innerText()).includes('OD별 결과'));assert.equal(await page.locator('#queueChart').count(),1);await page.screenshot({path:path.join(qa,'03-results.png'),fullPage:true});});
await check('report CSV and interface downloads include actual results',async()=>{const report=await download('saveReport','test-report.html'),ports=await download('savePorts','test-interface.json');assert.ok(fs.readFileSync(report,'utf8').includes('계산 정의'));const doc=JSON.parse(fs.readFileSync(ports));assert.equal(doc.deviceType,'vertical_lift');assert.equal(doc.ports.length,6);assert.ok(doc.events.length>0);assert.ok(doc.metrics.conservation);const csv=await download('downloadResult','test-results.csv');assert.ok(fs.readFileSync(csv,'utf8').includes('최종 인계'));});
let excel,json,originalHash;
await check('all settings export as an actual 8-sheet XLSX workbook',async()=>{originalHash=await page.evaluate(()=>LiftModel.hash(LiftApp.config));excel=await download('saveExcel','test-input.xlsx');json=await download('saveJson','test-input.json');assert.equal(fs.readFileSync(excel).readUInt32LE(0),0x04034b50);const names=await page.evaluate(async()=>Object.keys(await LiftXlsx.read(new Blob([LiftIO.writeXlsx(LiftApp.config)]))));assert.equal(names.length,8);});
await check('editing inputs invalidates stale simulation results',async()=>{const el=page.locator('[data-setting=loadedV]');await el.fill('48');await el.dispatchEvent('change');assert.equal(await page.evaluate(()=>LiftApp.run),null);assert.equal(await page.locator('#play').isDisabled(),true);assert.ok((await page.locator('#inputStatus').innerText()).includes('실행 전'));});
await check('XLSX file input restores exact config atomically',async()=>{await page.setInputFiles('#fileExcel',excel);await page.waitForFunction(h=>LiftModel.hash(LiftApp.config)===h,originalHash);assert.equal(await page.locator('#errors').isVisible(),false);});
if(fs.existsSync(path.join(qa,'compressed-input.xlsx')))await check('externally compressed XLSX imports all settings',async()=>{await page.setInputFiles('#fileExcel',path.join(qa,'compressed-input.xlsx'));await page.waitForFunction(()=>document.getElementById('message').textContent.includes('compressed-input.xlsx'));assert.equal(await page.evaluate(()=>LiftModel.hash(LiftApp.config)),originalHash);assert.equal(await page.locator('#errors').isVisible(),false);});
if(fs.existsSync(path.join(qa,'formula-input.xlsx')))await check('formula workbook is rejected without changing the project',async()=>{await page.setInputFiles('#fileExcel',path.join(qa,'formula-input.xlsx'));await page.waitForFunction(()=>!document.getElementById('errors').hidden);assert.ok((await page.locator('#errors').innerText()).includes('수식'));assert.equal(await page.evaluate(()=>LiftModel.hash(LiftApp.config)),originalHash);await page.setInputFiles('#fileExcel',excel);await page.waitForFunction(()=>document.getElementById('errors').hidden);});
await check('invalid JSON import leaves existing input intact',async()=>{const broken=JSON.parse(fs.readFileSync(json));broken.config.lifts=4;const bad=path.join(qa,'invalid-input.json');fs.writeFileSync(bad,JSON.stringify(broken));await page.setInputFiles('#fileJson',bad);await page.waitForFunction(()=>!document.getElementById('errors').hidden);assert.equal(await page.evaluate(()=>LiftModel.hash(LiftApp.config)),originalHash);assert.ok((await page.locator('#errors').innerText()).includes('해시'));await page.setInputFiles('#fileJson',json);await page.waitForFunction(()=>document.getElementById('errors').hidden);});
await check('adding a floor creates all missing zero-demand ODs',async()=>{await page.click('[data-tab=layout]');await page.click('#addFloor');const data=await page.evaluate(()=>LiftApp.config);assert.equal(data.floors.length,4);assert.equal(data.ods.length,12);assert.ok(data.ods.filter(o=>o.from==='F4'||o.to==='F4').every(o=>o.rate===0));await page.screenshot({path:path.join(qa,'04-floor-od.png'),fullPage:true});await page.click('#undo');assert.equal(await page.evaluate(()=>LiftApp.config.floors.length),3);});
await check('hourly ratios and planned-stop tables can be edited',async()=>{await page.click('[data-tab=cargo]');await page.click('#autoPeriods');await page.click('#addStop');const q=await page.evaluate(()=>LiftApp.config);assert.equal(q.periods.length,1);assert.equal(q.stops.length,1);assert.equal(q.periods[0].factor,1);assert.equal(await page.locator('#errors').isVisible(),false);await page.screenshot({path:path.join(qa,'05-cargo-timebands.png'),fullPage:true});});
await check('blocked preset visibly reduces throughput and retains cargo',async()=>{await page.selectOption('#preset','blocked');await page.click('#loadPreset');await page.click('[data-tab=scene]');await run();const m=await page.evaluate(()=>LiftApp.run.metrics);assert.ok(m.backlog>50);assert.ok(m.carRows[0].blocked>.5);assert.ok(m.conservation);const target=await page.evaluate(()=>{const s=LiftApp.run.cars[0].segments.find(s=>s.state==='waitOut'&&s.end-s.start>10);return s.start+5;});await page.locator('#seek').evaluate((el,t)=>{el.value=t;el.dispatchEvent(new Event('input',{bubbles:true}));},target);assert.ok((await page.locator('#live').innerText()).includes('출구 공간'));await page.screenshot({path:path.join(qa,'06-buffer-blocked.png'),fullPage:true});});
await check('comparison uses true simulations and identifies downstream improvement',async()=>{await page.click('#compare');await page.waitForFunction(()=>LiftApp.comparisons.length===7,{},{timeout:60000});const rows=await page.evaluate(()=>LiftApp.comparisons);assert.ok(rows.find(x=>x.name.includes('반출')).throughput>rows[0].throughput);await page.screenshot({path:path.join(qa,'07-comparison.png'),fullPage:true});const idx=rows.findIndex(x=>x.name.includes('반출'));await page.click('[data-apply="'+idx+'"]');assert.equal(await page.evaluate(()=>LiftApp.run),null);assert.equal(await page.evaluate(()=>LiftApp.config.floors[1].takeaway),96);});
await check('box preset loads multiple cargo pieces with valid 3D geometry',async()=>{await page.selectOption('#preset','box');await page.click('#loadPreset');await page.click('[data-tab=scene]');await run();const d=await page.evaluate(()=>({type:LiftApp.config.cargo[0].kind,m:LiftApp.run.metrics,ready:LiftApp.scene.ready}));assert.equal(d.type,'box');assert.ok(d.ready&&d.m.conservation);await page.locator('#seek').evaluate(el=>{el.value=100;el.dispatchEvent(new Event('input',{bubbles:true}));});await page.screenshot({path:path.join(qa,'08-box-lift.png'),fullPage:true});});
await check('two-lift preset builds and animates two independent shafts',async()=>{await page.selectOption('#preset','two');await page.click('#loadPreset');await run();assert.equal(await page.evaluate(()=>LiftApp.scene.carGroups.length),2);await page.locator('#seek').evaluate(el=>{el.value=140;el.dispatchEvent(new Event('input',{bubbles:true}));});await page.screenshot({path:path.join(qa,'09-two-lifts.png'),fullPage:true});});
await check('narrow viewport retains controls without page overflow',async()=>{await page.setViewportSize({width:900,height:1000});await page.waitForTimeout(150);const dimensions=await page.evaluate(()=>({w:innerWidth,doc:document.documentElement.scrollWidth}));assert.ok(dimensions.doc<=dimensions.w+2);await page.screenshot({path:path.join(qa,'10-responsive.png'),fullPage:true});});
await check('HTML manual opens with ten sections and visible screenshot',async()=>{const manual=await context.newPage();await manual.goto(pathToFileURL(path.join(root,'리프트_사용매뉴얼.html')).href);assert.equal(await manual.locator('article h2').count(),10);assert.equal(await manual.locator('article img').evaluate(el=>el.complete&&el.naturalWidth>0),true);assert.ok((await manual.locator('article').innerText()).includes('공유 시계'));await manual.screenshot({path:path.join(qa,'11-manual.png')});await manual.close();});
await check('all UI actions complete without script errors or network requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
}finally{fs.writeFileSync(path.join(qa,'browser-results.json'),JSON.stringify({passed:records.filter(x=>x.pass).length,records,errors,requests},null,2));await browser.close();}console.log(records.length+' browser checks passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
