(function(){
  'use strict';
  const Model=RGVModel,M=RGVMotion,E=RGVEngine,V=RGVView,R=RGVReport,$=id=>document.getElementById(id),{esc,fmt,table,kpi}=V;
  let draft=Model.clone(Model.defaults),config,result,engine,plan,dirty=false,activeTab='overview',shownDistance='m',shownSpeed='m/min',shownHandling='total';
  let simPlaying=false,motionPlaying=false,motionTime=0,lastFrame=0,lastRender=0,bulkToken=0,experimentToken=0,experimentData=null,toastTimer;
  let worker=null,workerReady=false,workerPending=null,workerSequence=0,scene=null;
  const scalarSelects=['layout','distanceUnit','speedUnit','unit','handlingMode','jerkMode','dispatch','parking','basis','arrival','demandMode'];
  const groups={layoutFields:['length','batchSize'],emptyFields:['emptyV','emptyA','emptyD'],loadedFields:['loadedV','loadedA','loadedD'],handlingFields:['position','interlock','signal'],delayFields:['control','stopDwell'],approachFields:['accelScale','jerkDelay','creepDistance','creepV'],demandFields:['peak','targetUtil'],factorFields:['A','Ft','Ew'],simulationFields:['hours','warmup','seed','jitter']};
  const definitions={
    sections:{target:'sectionsEditor',cols:[['id','구간 ID','text'],['name','차량명','text'],['start','시작','distance'],['end','끝','distance'],['home','대기점','distance'],['speedFactor','속도 비율','number']]},
    stations:{target:'stationsEditor',cols:[['id','ID','text'],['name','스테이션명','text'],['x','위치 X','distance'],['load','상차','handling'],['unload','하차','handling'],['buffer','출고 버퍼 개','integer'],['takeaway','반출 s/개','number'],['stop','통과 시 정지','boolean']]},
    handoffs:{target:'handoffsEditor',cols:[['capacity','방향별 버퍼 개','integer'],['transfer','상·하차 각 s','number']]},
    zones:{target:'zonesEditor',cols:[['from','시작','distance'],['to','끝','distance'],['v','제한속도','speed']]},
    ods:{target:'odsEditor',cols:[['id','OD ID','text'],['from','출발 ID','station'],['to','도착 ID','station'],['rate','평균 요구량 /h','number']]},
    profile:{target:'profileEditor',cols:[['start','시작 min','number'],['end','끝 min','number'],['multiplier','수요 배율','number']]}
  };
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
  function showError(error){$('error').textContent=error.message;$('error').hidden=false;document.querySelectorAll('[aria-invalid]').forEach(e=>e.removeAttribute('aria-invalid'));const field=$(error.field);if(field){field.setAttribute('aria-invalid','true');const details=field.closest('details');if(details)details.open=true;field.focus();}else $('error').scrollIntoView({block:'center'});}
  function clearError(){$('error').hidden=true;document.querySelectorAll('[aria-invalid]').forEach(e=>e.removeAttribute('aria-invalid'));}
  function scale(kind){return kind==='distance'?(shownDistance==='mm'?1000:1):kind==='speed'?(shownSpeed==='m/min'?60:1):1;}
  function displayUnit(kind){return kind==='distance'?shownDistance:kind==='speed'?shownSpeed:kind==='ratio'?'비율 · 0~1':kind;}
  for(const [group,keys]of Object.entries(groups))$(group).innerHTML=keys.map(key=>{const [label,unit,min,max,step,help]=Model.fields[key];return'<div class="field"><label for="'+key+'">'+esc(label)+'<span class="unit" data-unit-for="'+key+'">'+esc(unit)+'</span></label><button class="help" type="button" data-help="'+key+'" aria-label="'+esc(label)+' 도움말" title="'+esc(help)+'">?</button><input id="'+key+'" type="number" step="any" placeholder="'+(['A','Ft','Ew'].includes(key)?'미선택':'')+'"></div>';}).join('');
  const helpDialog=document.createElement('dialog');helpDialog.id='helpDialog';helpDialog.innerHTML='<h2></h2><p></p><button type="button">닫기</button>';document.body.append(helpDialog);helpDialog.querySelector('button').onclick=()=>helpDialog.close();
  document.querySelectorAll('[data-help]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.help,[title,u,min,max,,text]=Model.fields[key];helpDialog.querySelector('h2').textContent=title;helpDialog.querySelector('p').textContent=text+' 허용 범위: '+fmt(min*scale(u),3)+'~'+fmt(max*scale(u),3)+' '+displayUnit(u)+'.';helpDialog.showModal();}));
  function read(check=true){const c=Model.clone(draft);for(const key of Object.keys(Model.fields)){const raw=$(key).value.trim();c[key]=raw===''&&['A','Ft','Ew'].includes(key)?null:raw===''?NaN:Number(raw)/scale(Model.fields[key][1]);}for(const key of scalarSelects)c[key]=$(key).value;c.name=$('name').value;c.basisNote=$('basisNote').value;const overhead=c.position+c.interlock+c.signal;
    for(const [array,def]of Object.entries(definitions)){c[array]=[...$(def.target).querySelectorAll('tbody tr')].map((row,index)=>{const entry={...(draft[array][index]||{})};for(const [key,,type]of def.cols){const input=row.querySelector('[data-key="'+key+'"]');if(type==='boolean')entry[key]=input.checked;else if(type==='text'||type==='station')entry[key]=input.value.trim();else{entry[key]=input.value.trim()===''?NaN:Number(input.value)/scale(type);if(type==='handling'&&shownHandling==='detail')entry[key]+=overhead;}}if(array==='sections')entry.vehicles=1;return entry;});}
    return check?Model.validate(c):c;
  }
  function write(c){draft=Model.clone(c);shownDistance=c.distanceUnit;shownSpeed=c.speedUnit;shownHandling=c.handlingMode;for(const [key,[,,min,max,step]]of Object.entries(Model.fields)){const unit=Model.fields[key][1];$(key).value=c[key]===null?'':Number((c[key]*scale(unit)).toPrecision(12));$(key).min=min*scale(unit);$(key).max=max*scale(unit);$(key).step=['seed','batchSize'].includes(key)?1:'any';document.querySelector('[data-unit-for="'+key+'"]').textContent=displayUnit(unit);}for(const key of scalarSelects)$(key).value=c[key];$('name').value=c.name;$('basisNote').value=c.basisNote;renderEditors();}
  function renderEditors(){const c=draft,overhead=c.position+c.interlock+c.signal;
    for(const [array,def]of Object.entries(definitions)){
      if(!c[array].length){$(def.target).innerHTML='<p class="empty-state">'+(array==='handoffs'?'Tandem을 선택하고 구간 수에 맞춰 갱신하세요.':array==='profile'?'시간대 미지정 · 전체 운전시간에 1배 적용':'등록된 항목이 없습니다.')+'</p>';continue;}
      $(def.target).innerHTML='<div class="table-scroll"><table><thead><tr><th>#</th>'+def.cols.map(([,label,type])=>'<th>'+esc(label)+(type==='distance'||type==='speed'?' ('+displayUnit(type)+')':type==='handling'?(shownHandling==='detail'?' 순수 s':' 총 s'):'')+'</th>').join('')+'<th></th></tr></thead><tbody>'+c[array].map((row,index)=>'<tr><td>'+(array==='handoffs'?'H':'')+(index+1)+'</td>'+def.cols.map(([key,label,type])=>{
        const value=type==='handling'&&shownHandling==='detail'?row[key]-overhead:typeof row[key]==='number'?Number((row[key]*scale(type)).toPrecision(12)):row[key];const attr=' data-key="'+key+'" aria-label="'+esc(array+' '+(index+1)+' '+label)+'"';
        if(type==='station')return'<td><select'+attr+'>'+c.stations.map(s=>'<option value="'+esc(s.id)+'"'+(s.id===value?' selected':'')+'>'+esc(s.id+' · '+s.name)+'</option>').join('')+(!c.stations.some(s=>s.id===value)?'<option selected value="'+esc(value)+'">'+esc(value)+' (확인 필요)</option>':'')+'</select></td>';
        if(type==='boolean')return'<td><input type="checkbox"'+attr+(value?' checked':'')+'></td>';
        return'<td><input type="'+(type==='text'?'text':'number')+'"'+attr+' value="'+esc(value??'')+'"'+(type==='text'?' maxlength="80"':' step="'+(type==='integer'?'1':'any')+'"')+'></td>';
      }).join('')+'<td><button type="button" data-remove="'+array+'" data-row="'+index+'" aria-label="'+esc(array+' '+(index+1)+'행 삭제')+'">삭제</button></td></tr>').join('')+'</tbody></table></div>';
    }
    $('handlingHint').textContent=shownHandling==='total'?'총 시간 = 순수 이재 + 정위치 + 인터록 + 신호. 추가 중복 가산하지 않습니다.':'상세 입력: 표의 순수 이재시간 + 공통 지연 '+fmt(overhead,2)+' s = 적용 총 시간.';
    $('historyStatus').textContent='저장된 작업이력 '+c.history.length.toLocaleString()+'건 · '+(c.demandMode==='history'?'이력 모드 선택':'OD 수요 모드 선택');$('historyPreview').innerHTML=table(['time_s','from','to','quantity'],c.history.slice(0,8).map(j=>[j.time,j.from,j.to,j.quantity]));
  }
  function stopPlayback(){simPlaying=false;motionPlaying=false;bulkToken++;$('simPlay').textContent='▶ 시뮬레이션 재생';$('motionPlay').textContent='▶ 동작 재생';$('simFinish').disabled=false;}
  function stopExperiments(){experimentToken++;if(workerPending){worker?.terminate();worker=null;workerReady=false;workerPending.reject(Error('cancelled'));workerPending=null;$('runtime').textContent='OFFLINE · 분할 계산';} $('runExperiments').disabled=false;$('cancelExperiments').disabled=true;if(experimentData)$('experimentStatus').textContent='중단됨 · 완료된 반복 결과를 보존합니다.';}
  function markDirty(){clearError();dirty=true;document.body.dataset.dirty='true';$('dirtyNotice').hidden=false;stopPlayback();stopExperiments();}
  function fresh(){if(dirty||!result){toast('계산 및 설정 적용으로 현재 입력을 반영하세요.');return false;}return true;}
  function apply(){try{const next=read(),computed=Model.calculate(next),nextEngine=new E.Engine(next);stopPlayback();stopExperiments();if(scene){scene.dispose();scene=null;}config=next;draft=Model.clone(next);result=computed;engine=nextEngine;dirty=false;document.body.dataset.dirty='false';$('dirtyNotice').hidden=true;clearError();$('projectSummary').textContent=config.name+' · '+config.sections.length+'구간 / '+config.sections.length+'대 · '+({single:'단일 차량',independent:'독립 분리 구간',tandem:'Tandem 직렬 인계'})[config.layout];renderAnalysis();refreshMotionOptions();renderMotion();renderSimulation();experimentData=null;$('experimentResults').innerHTML='<p class="empty-state">반복 실험을 시작하면 비교 결과를 표시합니다.</p>';$('experimentProgress').value=0;$('exportExperiments').disabled=true;$('experimentStatus').textContent='현재 적용 설정으로 실행할 수 있습니다.';return true;}catch(error){markDirty();showError(error);return false;}}
  function renderAnalysis(){const r=result,c=config,u=c.unit+'/h';$('analysisKpis').innerHTML=kpi('이론 능력 · 전체',fmt(r.theory),u,'현재 OD 혼합 · 병목 기준',true)+kpi('보정 능력 · 전체',fmt(r.available),u,r.factor===null?'보정계수와 근거 선택 필요':'차량에 A × Fₜ × E𝑤 적용')+kpi('요구 물동량 · 전체',fmt(r.total),u,c.demandMode==='history'?'측정구간 이력 평균':'피크·최대 시간대 배율 반영')+kpi('현재 RGV 구성',String(c.sections.length),'대','물리적 분리 구간당 1대');
    const notes=[...r.warnings];if(r.factor!==null)notes.unshift(r.shortage>0?'목표 부하율 '+fmt(c.targetUtil*100,0)+'% 기준 부족량 '+fmt(r.shortage)+' '+u+'. 병목: '+r.bottleneck:'분석상 목표 부하율 이내입니다. 대기·차단은 시뮬레이션으로 확인하세요.');$('analysisNotice').innerHTML=notes.length?'<ul>'+notes.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>':'분석 계산 완료';$('analysisNotice').className='notice'+(r.shortage>0?' warning':'');
    $('overviewScene').innerHTML=V.layout(c);$('layoutTag').textContent=c.stations.length+' 스테이션 · '+c.ods.length+' OD';const values=[['요구량',r.total,'#be944e'],['전체 이론 능력',r.theory,'#91b0bf'],['전체 보정 능력',r.available,'#118e87']].filter(x=>x[1]!==null),maximum=Math.max(1,...values.map(v=>v[1]));$('capacityBars').innerHTML=values.map(v=>bar(v[0],v[1],maximum,v[2],u)).join('');
    $('fleetAdvice').innerHTML='<div class="metric-row"><span>병목 자원</span><b>'+esc(r.bottleneck)+'</b></div><div class="metric-row"><span>목표부하 고려 부족량</span><strong>'+fmt(r.shortage)+' <small>'+u+'</small></strong></div><p class="muted">구간별 환산 대수가 2 이상이면 속도·이재·구간 분할을 검토하세요. 같은 레일에 차량 수만 더하는 계산은 지원하지 않습니다.</p>';
    $('sectionResults').innerHTML=table(['구간','차량','사이클 s/회','수요 /h','이론 /h','보정 /h','부하율 %','환산 대수','공차거리 %'],r.sections.map(s=>[s.id,s.name,fmt(s.cycle,2),fmt(s.cargoRate),fmt(s.theory),fmt(s.available),fmt(s.util===null?null:s.util*100),s.required??'미산정',fmt(s.emptyRatio*100)]));
    $('odResults').innerHTML=table(['OD','출발→도착','구간','수요 /h','공차 s','적재 s','상차 s','하차 s','제어 s','합계 s'],r.legRows.map(x=>[x.od,x.from+' → '+x.to,x.section,fmt(x.rate),fmt(x.emptyTime,2),fmt(x.loadedTime,2),fmt(x.load,2),fmt(x.unload,2),fmt(x.control,2),fmt(x.cycle,2)]));
    $('stationResults').innerHTML=table(['스테이션','이재부 부하 %','반출 부하 %'],r.stations.map(s=>[s.id+' '+s.name,fmt(s.util*100),fmt(s.releaseUtil*100)]));
    const sens=[];if(r.factor!==null)for(const key of ['A','Ft','Ew'])for(const delta of [-.1,-.05,.05,.1]){const changed=Model.clone(c);changed[key]=Math.min(1,Math.max(.01,c[key]*(1+delta)));const x=Model.calculate(changed);sens.push([key,(delta>0?'+':'')+delta*100+'%',fmt(changed[key],3),fmt(x.available),fmt(x.shortage)]);}
    $('sensitivity').innerHTML=sens.length?table(['계수','상대 변화','적용값','전체 능력 /h','목표 부족 /h'],sens):'<p class="empty-state">계수와 근거를 선택하면 표시합니다.</p>';
    $('distanceMatrix').innerHTML=table(['출발 / 도착',...c.stations.map(s=>s.id)],c.stations.map(a=>[a.id,...c.stations.map(b=>fmt(Math.abs(a.x-b.x),3))]));
  }
  function bar(label,value,max,color,unit){return'<div class="bar"><div class="bar-label"><span>'+esc(label)+'</span><b>'+fmt(value)+' '+esc(unit)+'</b></div><div class="bar-track"><span style="width:'+Math.min(100,value/Math.max(1e-9,max)*100)+'%;background:'+color+'"></span></div></div>';}
  function clock(t){t=Math.floor(t);return[String(Math.floor(t/3600)).padStart(2,'0'),String(Math.floor(t/60)%60).padStart(2,'0'),String(t%60).padStart(2,'0')].join(':');}
  function renderSimulation(){if(!engine)return;const s=engine.snapshot(),c=config,u=c.unit+'/h';$('simKpis').innerHTML=kpi('최종 목적지 완료',fmt(s.throughput),u,'측정구간 하차 완료 · 중간 인계 제외',true)+kpi('외부 출하량',fmt(s.shippingRate),u,'출고 버퍼 반출 완료')+kpi('미배차 대기',fmt(s.waiting,0),'개','운송·이재 중 '+s.active+'개 / 출고 버퍼 '+s.output+'개')+kpi('P95 최초 배차 대기',fmt(s.p95Wait),'s','미배차 최장 '+fmt(s.oldest)+' s');
    $('simNotice').textContent=R.status(s)+' · 고장 없는 조건 / 보정계수 추가 차감 없음'+(s.deadlock?' · 교착 징후: 인계 버퍼·양방향 반송을 검토하세요.':s.saturated?' · 대기열 증가: 처리능력·반출을 검토하세요.':'')+(s.failed?' · '+s.failed:'');$('simNotice').className='notice'+(s.deadlock||s.saturated||s.failed?' warning':' subtle');
    if(activeTab==='simulation')ensureScene();renderSceneInfo();$('simClock').textContent=clock(s.time);$('simSeek').value=s.time/s.horizon*1000;$('simEnd').textContent=clock(s.horizon);
    $('carStats').innerHTML=table(['차량','동작','작업','X m','속도 '+c.speedUnit,'관측가동 %','구간 취급 /h','공차거리 %','인계 포함 P95 s'],s.cars.map(x=>[x.id,E.states[x.state]+(x.reason?' · '+x.reason:''),x.job||'—',fmt(x.x,2),fmt(x.v*(c.speedUnit==='m/min'?60:1),2),fmt(x.busy*100),fmt(x.throughput),fmt(x.emptyRatio*100),fmt(x.p95Wait)]));
    $('conservation').textContent='화물 수 보존 '+(s.conserved?'✓ 정상':'오류')+' · 전체 운전: 생성 '+s.created+' = 외부 출하 '+s.shipped+' + 대기 '+s.waiting+' + 진행 '+s.active+' + 출고 버퍼 '+s.output+' · 종료 시점 진행 화물도 포함';
    $('queueChart').innerHTML=V.line([{color:'#c18c35',points:engine.series.map(p=>({x:p.time/60,y:p.queue}))},{color:'#0b9695',points:engine.series.map(p=>({x:p.time/60,y:p.wip}))}],{xMax:s.horizon/60,xLabel:'운전 시간 (min)',yLabel:'화물 수 (개)'});
    const summed=Object.fromEntries(Object.keys(E.states).map(k=>[k,s.cars.reduce((n,car)=>n+car.stateTime[k],0)]));$('stateChart').innerHTML=Object.entries(summed).map(([key,value])=>bar(E.states[key],value,s.measuredTime*c.sections.length,V.colors[key],'s')).join('');
    $('bufferStats').innerHTML=table(['버퍼','현재 개','예약 개','용량 개','최대 개'],[...s.buffers,...s.stations].map(b=>[b.id,b.count,b.reserved,b.capacity,b.max]));const delta=result.theory?(s.throughput/result.theory-1)*100:null;
    $('comparison').innerHTML=table(['항목','결과'],[['이론 능력',fmt(result.theory)+' '+u],['관측 최종 완료',fmt(s.throughput)+' '+u],['이론 대비 차이',fmt(delta)+'%'],['평균 대기열 / 최대',fmt(s.meanQueue)+' / '+s.maxQueue+'개'],['평균 대기 / P95 리드타임',fmt(s.meanWait)+' / '+fmt(s.p95Lead)+' s'],['후반 / 전반 대기 추이',fmt(s.queueTrend,2)+'배 (각 평균+1)']]);
  }
  function ensureScene(){
    if(scene&&scene.config!==config){scene.dispose();scene=null;}
    if(!scene){scene=new RGVScene.Scene($('simScene'),config,index=>{$('sceneVehicle').value=index;renderSceneInfo();});$('sceneVehicle').innerHTML=config.sections.map((s,i)=>'<option value="'+i+'">'+esc(s.id+' · '+s.name)+'</option>').join('');scene.setLabels($('sceneLabels').checked);scene.follow=$('sceneFollow').checked;if(scene.follow)scene.setView('selected');}
    scene.update(engine);const unavailable=scene.fallback;
    for(const id of ['viewIso','viewFront','viewTop','viewSelected','sceneFollow','sceneLabels'])$(id).disabled=unavailable;
    $('sceneMode').textContent=unavailable?'2D 대체 표시':'3D · ALL RGVs';
  }
  function renderSceneInfo(){if(!engine)return;const i=Number($('sceneVehicle').value)||0,car=engine.cars[i]||engine.cars[0],p=engine.pose(car);$('sceneSelection').textContent=car.section.id+' · '+E.states[car.state]+' · X '+fmt(p.x,2)+' m · '+fmt(p.v*(config.speedUnit==='m/min'?60:1),2)+' '+config.speedUnit+(car.job?' · '+car.job.id+' / '+car.job.quantity+'개':'');}
  for(const [id,view]of [['viewIso','iso'],['viewFront','front'],['viewTop','top'],['viewSelected','selected']])$(id).onclick=()=>{if(!fresh())return;ensureScene();if(view!=='selected'){$('sceneFollow').checked=false;scene.follow=false;}scene.setView(view);scene.update(engine);};
  $('sceneVehicle').onchange=()=>{if(!fresh())return;ensureScene();scene.select(Number($('sceneVehicle').value));renderSceneInfo();};
  $('sceneLabels').onchange=()=>{if(scene)scene.setLabels($('sceneLabels').checked);};
  $('sceneFollow').onchange=()=>{if(!fresh())return;ensureScene();scene.follow=$('sceneFollow').checked;if(scene.follow)scene.setView('selected');};
  function motionODs(){const ods=Model.demand(config);return ods.length?ods:[{id:'경로 예시',from:config.stations[0].id,to:config.stations.at(-1).id}];}
  function refreshMotionOptions(){const ods=motionODs();$('motionOd').innerHTML=ods.map((od,i)=>'<option value="'+i+'">'+esc(od.id+' · '+od.from+' → '+od.to)+'</option>').join('');refreshMotionSections();}
  function refreshMotionSections(){const od=motionODs()[Number($('motionOd').value)||0];let legs;try{legs=Model.route(config,od);}catch{legs=[];}$('motionSection').innerHTML=legs.map(l=>'<option value="'+l.section+'">'+esc(config.sections[l.section].name)+'</option>').join('');}
  function renderMotion(){const ods=motionODs(),od=ods[Number($('motionOd').value)||0];try{plan=Model.preview(config,od,Number($('motionSection').value));}catch{plan=null;for(const id of ['speedGraph','positionGraph','accelGraph','motionTimeline'])$(id).innerHTML='';$('motionDescription').textContent='유효한 OD를 등록하면 경로를 확인할 수 있습니다.';return;}
    motionTime=0;motionPlaying=false;$('motionPlay').textContent='▶ 동작 재생';$('motionDescription').textContent=od.from+' → '+od.to+' / '+config.sections[plan.leg.section].id+' · 구간 '+fmt(plan.leg.from.x)+'→'+fmt(plan.leg.to.x)+' m · '+(config.parking==='home'?'대기점 복귀 포함':'위치 대기 미리보기: 상차점에서 시작, 평균 공차와 구분');const charts=V.motion(config,plan);$('speedGraph').innerHTML=charts.speed;$('positionGraph').innerHTML=charts.position;$('accelGraph').innerHTML=charts.acceleration;$('motionTimeline').innerHTML=V.timeline(plan);for(const id of ['speedGraph','positionGraph','accelGraph']){const svg=$(id).querySelector('svg'),line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('y1','20');line.setAttribute('y2','180');line.setAttribute('stroke','#c89043');line.setAttribute('stroke-dasharray','4 4');line.setAttribute('data-motion-cursor','');svg.append(line);}updateMotion();}
  function updateMotion(){if(!plan)return;const p=Model.previewAt(plan,motionTime);$('motionClock').textContent=fmt(motionTime,2)+' / '+fmt(plan.duration,2)+' s';$('motionSeek').value=plan.duration?motionTime/plan.duration*1000:0;$('motionValues').textContent=(E.states[p.kind]||'대기')+' · X '+fmt(p.x,3)+' m · 속도 '+fmt(p.v*(config.speedUnit==='m/min'?60:1),3)+' '+config.speedUnit+' · 가속도 '+fmt(p.a,3)+' m/s²';document.querySelectorAll('[data-motion-cursor]').forEach(line=>{const x=62+(plan.duration?motionTime/plan.duration:0)*934;line.setAttribute('x1',x);line.setAttribute('x2',x);});}
  function setTab(name){activeTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);if(name==='simulation')renderSimulation();}
  function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
  function filename(suffix){return(config?.name||'직선RGV').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,65)+suffix;}
  function newId(prefix,array){let n=1;while(array.some(x=>x.id===prefix+n))n++;return prefix+n;}
  function mutate(fn){try{const c=read(false);fn(c);write(c);markDirty();}catch(error){showError(error);}}
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
  $('configForm').addEventListener('submit',e=>{e.preventDefault();apply();});
  document.addEventListener('input',event=>{if(event.target.closest('#configForm')||event.target.closest('[data-panel="layout"]')||event.target.closest('[data-panel="demand"]'))markDirty();});
  document.addEventListener('change',event=>{if(['distanceUnit','speedUnit','handlingMode'].includes(event.target.id)){mutate(()=>{});return;}if(event.target.closest('#configForm')||event.target.closest('[data-panel="demand"]')||event.target.closest('[data-panel="layout"]'))markDirty();});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(button)mutate(c=>c[button.dataset.remove].splice(Number(button.dataset.row),1));});
  $('calculate').onclick=()=>{if(apply())toast('현재 조건을 계산과 시뮬레이션에 적용했습니다.');};
  $('loadPreset').onclick=()=>{write(Model.preset($('preset').value));if(apply())toast('설명용 예시를 적용했습니다. 실제 설비 사양으로 수정하세요.');};
  $('idealFactors').onclick=()=>mutate(c=>{c.A=c.Ft=c.Ew=1;c.basis='ideal';c.basisNote='고장·운영 손실이 없는 이상 조건 비교';});
  $('assumedFactors').onclick=()=>mutate(c=>{c.A=.95;c.Ft=.95;c.Ew=1;c.basis='assumption';c.basisNote='설계 가정 예시: A 0.95, Ft 0.95, Ew 1.0. 실측값 아님.';});
  $('addSection').onclick=()=>mutate(c=>{if(c.sections.length>=8)throw Error('최대 8구간입니다.');const last=c.sections.at(-1);if(!last)throw Error('구간 시작값을 먼저 입력하세요.');const end=last.end,middle=(last.start+end)/2;last.end=middle;last.home=Math.min(last.home,middle);const id=newId('R',c.sections);c.sections.push({id,name:'RGV '+id.slice(1),start:middle,end,home:middle,speedFactor:1,vehicles:1});if(c.layout==='single')c.layout='tandem';while(c.handoffs.length<c.sections.length-1)c.handoffs.push({capacity:Math.max(2,c.batchSize),transfer:4});});
  $('addStation').onclick=()=>mutate(c=>{const id=newId('S',c.stations);c.stations.push({id,name:'스테이션 '+id,x:c.length/2,load:6,unload:6,buffer:Math.max(8,c.batchSize),takeaway:0,stop:false});});
  $('syncHandoffs').onclick=()=>mutate(c=>{c.handoffs=Array.from({length:Math.max(0,c.sections.length-1)},(_,i)=>c.handoffs[i]||{capacity:Math.max(2,c.batchSize),transfer:4});});
  $('addZone').onclick=()=>mutate(c=>c.zones.push({from:c.length*.3,to:c.length*.5,v:1}));
  $('addOd').onclick=()=>mutate(c=>{if(!c.stations.length)throw Error('스테이션을 먼저 등록하세요.');c.ods.push({id:newId('OD',c.ods),from:c.stations[0].id,to:c.stations.at(-1).id,rate:10});});
  $('addPeriod').onclick=()=>mutate(c=>{const start=c.profile.at(-1)?.end||0;c.profile.push({start,end:Math.min(start+30,c.hours*60+c.warmup),multiplier:1});});
  $('historyTemplate').onclick=()=>download('RGV_작업이력_양식.csv',R.csv([['time_s','from','to','quantity'],[0,'S1','S2',1],[120,'S1','S2',1]]),'text/csv;charset=utf-8');$('importHistory').onclick=()=>{$('historyFile').value='';$('historyFile').click();};
  $('historyFile').onchange=async()=>{const file=$('historyFile').files[0];if(!file)return;try{if(file.size>5000000)throw Error('CSV는 5MB 이하여야 합니다.');const c=read(false);c.history=R.parseCSV(await file.text());c.demandMode='history';Model.validate(c);write(c);markDirty();toast(c.history.length+'건의 작업이력을 읽었습니다. 계산 및 설정 적용을 누르세요.');}catch(e){showError(e);}};
  $('clearHistory').onclick=()=>mutate(c=>{c.history=[];c.demandMode='rate';});
  $('saveProject').onclick=()=>{try{const c=read();download(c.name.replace(/[\\/:*?"<>|]/g,'_').slice(0,65)+'_RGV프로젝트.json',JSON.stringify(Model.pack(c),null,2),'application/json;charset=utf-8');}catch(e){showError(e);}};
  $('loadProject').onclick=()=>{$('projectFile').value='';$('projectFile').click();};$('projectFile').onchange=async()=>{const f=$('projectFile').files[0];if(!f)return;try{if(f.size>10000000)throw Error('프로젝트는 10MB 이하여야 합니다.');const parsed=JSON.parse(await f.text()),c=Model.unpack(parsed);write(c);if(apply())toast('프로젝트를 불러왔습니다.'+(parsed.moduleVersion.split('.').slice(0,2).join('.')!==Model.VERSION.split('.').slice(0,2).join('.')?' 저장 버전과 현재 버전이 다르므로 결과를 확인하세요.':''));}catch(e){showError(e);}};
  $('exportReport').onclick=()=>{if(fresh())download(filename('_RGV계산서.md'),R.markdown(result,engine.time>0?engine.snapshot():null),'text/markdown;charset=utf-8');};
  $('exportJobs').onclick=()=>{if(fresh())download(filename('_RGV완료작업.csv'),R.csv([['job_id','from','to','quantity','arrival_s','dispatch_s','complete_s','wait_s','lead_s','measurement_window','seed'],...engine.logs.map(j=>[j.id,j.from,j.to,j.quantity,j.arrival,j.dispatch,j.complete,j.wait,j.lead,j.measured,config.seed])]),'text/csv;charset=utf-8');};
  $('simPlay').onclick=()=>{if(!fresh())return;bulkToken++;$('simFinish').disabled=false;if(engine.time>=engine.horizon)engine=new E.Engine(config);simPlaying=!simPlaying;$('simPlay').textContent=simPlaying?'Ⅱ 일시정지':'▶ 시뮬레이션 재생';};
  $('simStep').onclick=()=>{if(!fresh())return;stopPlayback();const next=engine.heap.peek();if(next)engine.advanceTo(next.time);renderSimulation();};
  $('simReset').onclick=()=>{if(!fresh())return;stopPlayback();engine=new E.Engine(config);renderSimulation();};
  $('simFinish').onclick=async()=>{if(!fresh())return;stopPlayback();const token=++bulkToken;$('simFinish').disabled=true;try{while(engine.time<engine.horizon&&token===bulkToken){engine.advanceTo(Math.min(engine.horizon,engine.time+120));if(activeTab==='simulation')renderSimulation();await new Promise(r=>setTimeout(r,0));}if(token===bulkToken)toast('시뮬레이션 측정을 마쳤습니다. 대기·진행 화물을 함께 확인하세요.');}catch(e){showError(e);}finally{if(token===bulkToken)$('simFinish').disabled=false;renderSimulation();}};
  $('simSeek').onchange=()=>{if(!fresh())return;stopPlayback();const target=Number($('simSeek').value)/1000*engine.horizon;if(target<engine.time)engine=new E.Engine(config);try{engine.advanceTo(target);renderSimulation();}catch(e){showError(e);}};
  $('motionOd').onchange=()=>{if(fresh()){refreshMotionSections();renderMotion();}};$('motionSection').onchange=()=>{if(fresh())renderMotion();};$('applyMotion').onclick=()=>{if(fresh())renderMotion();};
  $('motionPlay').onclick=()=>{if(!fresh()||!plan)return;if(motionTime>=plan.duration)motionTime=0;motionPlaying=!motionPlaying;$('motionPlay').textContent=motionPlaying?'Ⅱ 일시정지':'▶ 동작 재생';};$('motionReset').onclick=()=>{motionPlaying=false;motionTime=0;$('motionPlay').textContent='▶ 동작 재생';updateMotion();};$('motionSeek').oninput=()=>{if(!fresh()||!plan)return;motionPlaying=false;$('motionPlay').textContent='▶ 동작 재생';motionTime=Number($('motionSeek').value)/1000*plan.duration;updateMotion();};
  $('pdfReport').onclick=()=>{if(!fresh())return;stopPlayback();$('pdfStatus').textContent='시뮬레이션: '+R.status(engine.snapshot())+' · 미리보기에서 PDF로 저장/A4를 선택하세요.';$('includeSim').disabled=engine.time===0;$('pdfOptions').showModal();};$('pdfCancel').onclick=()=>$('pdfOptions').close();
  $('pdfForm').onsubmit=event=>{event.preventDefault();if(!fresh())return;try{const options={};for(const key of ['documentNo','recipient','author','reviewer'])options[key]=$(key).value.trim();options.includeGraphs=$('includeGraphs').checked;options.includeSim=$('includeSim').checked&&engine.time>0;options.plan=plan;options.routeDescription=$('motionDescription').textContent;const html=R.html(result,engine.snapshot(),options),w=window.open('','_blank');if(!w){$('pdfStatus').textContent='팝업이 차단되었습니다. 이 파일의 팝업을 허용한 뒤 다시 미리보기를 누르세요.';return;}w.document.open();w.document.write(html);w.document.close();w.document.getElementById('printPdf').onclick=()=>w.print();w.document.getElementById('closeReport').onclick=()=>w.close();w.opener=null;$('pdfOptions').close();}catch(e){$('pdfStatus').textContent=e.message;}};
  // Experiments use an embedded worker when available, with bounded main-thread fallback.
  function setupWorker(){try{const code=['motion','model','engine'].map(id=>document.querySelector('script[data-module="'+id+'"]').textContent).join('\n')+'\nonmessage=function(event){const m=event.data;if(m.type==="ping"){postMessage({type:"ready"});return;}try{const e=RGVEngine.run(m.config);postMessage({type:"result",id:m.id,result:e.snapshot()});}catch(error){postMessage({type:"error",id:m.id,error:error.message});}};';const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=event=>{const message=event.data;if(message.type==='ready'){workerReady=true;$('runtime').textContent='OFFLINE · Worker OK';}else if(workerPending&&message.id===workerPending.id){const pending=workerPending;workerPending=null;if(message.type==='error')pending.reject(Error(message.error));else pending.resolve(message.result);}};worker.onerror=event=>{event.preventDefault();workerReady=false;worker?.terminate();worker=null;const pending=workerPending;workerPending=null;if(pending)pending.reject(Error('Worker 오류: '+event.message));$('runtime').textContent='OFFLINE · 분할 계산';};worker.postMessage({type:'ping'});setTimeout(()=>{if(!workerReady){worker?.terminate();worker=null;$('runtime').textContent='OFFLINE · 분할 계산';}},500);}catch{worker=null;workerReady=false;$('runtime').textContent='OFFLINE · 분할 계산';}}
  async function trial(c,token){if(workerReady&&worker){return await new Promise((resolve,reject)=>{const id=++workerSequence;workerPending={resolve,reject,id};worker.postMessage({type:'run',id,config:c});});}const e=new E.Engine(c);while(e.time<e.horizon){if(token!==experimentToken)throw Error('cancelled');e.advanceTo(Math.min(e.horizon,e.time+120));await new Promise(r=>setTimeout(r,0));}return e.snapshot();}
  const policies=[['fifo','home'],['fifo','stay'],['nearest','home'],['nearest','stay']];
  function renderExperiments(){if(!experimentData)return;$('experimentResults').innerHTML=table(['배차','대기','반복','완료량 평균 ±95% CI /h','외부출하 /h','P95 대기 평균 s','종료대기 평균','최대가동 평균 %','차단 평균 s','교착 반복'],policies.map(([dispatch,parking])=>{const samples=experimentData.runs.filter(x=>x.dispatch===dispatch&&x.parking===parking),stat=key=>E.interval95(samples.map(x=>x[key])),flow=stat('throughput');return[dispatch==='fifo'?'FIFO':'가까운 작업',parking==='home'?'대기점 복귀':'위치 대기',samples.length,flow.n?fmt(flow.mean,2)+' ± '+fmt(flow.ci95,2):'—',fmt(stat('shippingRate').mean),fmt(stat('p95Wait').mean),fmt(stat('waiting').mean),fmt(stat('busy').mean*100),fmt(stat('blocked').mean),samples.filter(x=>x.deadlock).length];}));}
  $('runExperiments').onclick=async()=>{if(!fresh())return;stopPlayback();const token=++experimentToken,reps=Number($('repCount').value);experimentData={schemaVersion:'rgv-linear/experiment@1',config:Model.clone(config),version:Model.VERSION,repetitions:reps,runs:[]};$('runExperiments').disabled=true;$('cancelExperiments').disabled=false;$('exportExperiments').disabled=true;try{for(let r=0;r<reps;r++)for(const [dispatch,parking]of policies){if(token!==experimentToken)return;const c={...Model.clone(config),dispatch,parking,seed:(config.seed+r)>>>0},s=await trial(c,token);if(token!==experimentToken)return;experimentData.runs.push({repetition:r+1,seed:c.seed,dispatch,parking,throughput:s.throughput,shippingRate:s.shippingRate,p95Wait:s.p95Wait,waiting:s.waiting,active:s.active,busy:Math.max(...s.cars.map(c=>c.busy)),blocked:s.cars.reduce((n,c)=>n+c.stateTime.blocked,0),deadlock:s.deadlock,conserved:s.conserved});$('experimentProgress').value=experimentData.runs.length/(reps*4)*100;$('experimentStatus').textContent=experimentData.runs.length+' / '+reps*4+'회 완료 · seed '+c.seed;$('exportExperiments').disabled=false;renderExperiments();await new Promise(r=>setTimeout(r,0));}if(token===experimentToken)$('experimentStatus').textContent=reps*4+'회 완료 · 동일 수요 시드 · Student t 95% 신뢰구간';}catch(e){if(e.message!=='cancelled')showError(e);}finally{if(token===experimentToken){$('runExperiments').disabled=false;$('cancelExperiments').disabled=true;}}};
  $('cancelExperiments').onclick=stopExperiments;$('exportExperiments').onclick=()=>{if(fresh()&&experimentData)download(filename('_RGV반복실험.json'),JSON.stringify(experimentData,null,2),'application/json;charset=utf-8');};
  function frame(now){const dt=lastFrame?Math.min((now-lastFrame)/1000,.1):0;lastFrame=now;try{if(simPlaying&&!dirty){engine.advanceTo(Math.min(engine.horizon,engine.time+dt*Number($('simSpeed').value)));if(engine.time>=engine.horizon){simPlaying=false;$('simPlay').textContent='▶ 다시 재생';}if(activeTab==='simulation'&&now-lastRender>120){renderSimulation();lastRender=now;}}
      if(activeTab==='simulation'&&scene&&!dirty){if(scene.fallback&&$('sceneMode').textContent!=='2D 대체 표시')ensureScene();else scene.update(engine);if(simPlaying)renderSceneInfo();}
      if(motionPlaying&&plan&&!dirty){motionTime=Math.min(plan.duration,motionTime+dt*2);updateMotion();if(motionTime>=plan.duration){motionPlaying=false;$('motionPlay').textContent='▶ 다시 재생';}}}catch(e){stopPlayback();showError(e);}requestAnimationFrame(frame);}
  write(draft);apply();setTab('overview');setupWorker();requestAnimationFrame(frame);
})();
