(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model.js'),require('./view.js'));else root.RGVReport=factory(root.RGVModel,root.RGVView);})(typeof globalThis!=='undefined'?globalThis:this,function(Model,V){
  'use strict';const {esc,fmt,table}=V;
  const scope='FEM 9.860 준용, 규격 적용대상 아님. 안전규격 참고 EN 619:2022. 현장 성능·안전 인증 기능은 포함하지 않습니다.';
  function csv(rows){return'\ufeff'+rows.map(row=>row.map(cell=>{let s=String(cell??'');if(/^[\s]*[=+@-]/.test(s)&&typeof cell!=='number')s="'"+s;return'"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
  function parseCSV(text){text=text.replace(/^\ufeff/,'');const rows=[],row=[];let value='',quoted=false,afterQuote=false;
    for(let i=0;i<=text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){value+='"';i++;}else{quoted=false;afterQuote=true;}}else if(ch===undefined)throw Error('CSV 따옴표가 닫히지 않았습니다.');else value+=ch;continue;}
      if(ch==='"'){if(value.length||afterQuote)throw Error('CSV 따옴표 위치를 확인하세요.');quoted=true;continue;}
      if(ch===','||ch==='\n'||ch==='\r'||ch===undefined){row.push(value);value='';afterQuote=false;if(ch!==','){if(row.some(v=>v.trim()!==''))rows.push(row.splice(0));else row.length=0;if(ch==='\r'&&text[i+1]==='\n')i++;}continue;}
      if(afterQuote&&!/\s/.test(ch))throw Error('CSV 닫는 따옴표 다음에 구분자가 필요합니다.');if(!afterQuote)value+=ch;
    }
    if(!rows.length)throw Error('CSV가 비어 있습니다.');const headers=rows.shift().map(s=>s.trim());for(const h of ['time_s','from','to','quantity'])if(!headers.includes(h))throw Error('CSV 열이 필요합니다: time_s, from, to, quantity');if(new Set(headers).size!==headers.length)throw Error('CSV 헤더가 중복되었습니다.');
    return rows.map((r,i)=>{if(r.length!==headers.length)throw Error('CSV '+(i+2)+'행 열 수가 다릅니다.');const get=k=>r[headers.indexOf(k)].trim();if(!get('time_s')||!get('quantity'))throw Error('CSV 숫자가 비어 있습니다.');return{time:Number(get('time_s')),from:get('from'),to:get('to'),quantity:Number(get('quantity'))};});
  }
  function status(s){return !s||s.time===0?'미실행':s.failed?'오류로 중단 · 부분 결과':s.complete?'완료':s.measuredTime>0?'진행 중 · 부분 결과':'준비운전 중 · 측정 전';}
  function markdown(r,s){const c=r.config;let text='# 직선 RGV 물동량 계산서\n\n프로젝트: '+c.name+'\n\n작성: '+new Date().toISOString()+' · 프로그램 '+r.version+' · 커널 '+r.kernelVersion+' · 입력 ID '+r.hash+'\n\n';
    text+='## 결과 요약\n\n| 항목 | 결과 |\n|---|---|\n| 요구 물동량 | '+fmt(r.total)+' '+c.unit+'/h |\n| 이론 전체 능력 | '+fmt(r.theory)+' '+c.unit+'/h |\n| 보정 전체 능력 | '+fmt(r.available)+' '+c.unit+'/h |\n| 병목 | '+r.bottleneck+' |\n| 목표 부하율 | '+fmt(c.targetUtil*100)+'% |\n| 구성 | '+c.layout+' / 구간 '+c.sections.length+'개, 각 1대 |\n\n';
    text+='## OD·구간 시간 분해\n\n| OD | 구간 | 공차 s | 적재 s | 상차 s | 하차 s | 제어 s | 사이클 s |\n|---|---|---|---|---|---|---|---|\n'+r.legRows.map(x=>'| '+[x.od,x.section,fmt(x.emptyTime,3),fmt(x.loadedTime,3),fmt(x.load,3),fmt(x.unload,3),fmt(x.control,3),fmt(x.cycle,3)].join(' | ')+' |').join('\n')+'\n\n';
    text+='## 시뮬레이션\n\n상태: '+status(s)+'\n\n';if(s)text+='최종 목적지 완료 '+fmt(s.throughput)+' '+c.unit+'/h · 외부 출하 '+fmt(s.shippingRate)+' '+c.unit+'/h\n\n준비운전 '+c.warmup+' min, 측정 '+fmt(s.measuredTime/3600,3)+' h, 시드 '+c.seed+'\n\n생성 '+s.created+' = 외부 출하 '+s.shipped+' + 대기 '+s.waiting+' + 진행 '+s.active+' + 출고 버퍼 '+s.output+' · 보존 '+(s.conserved?'정상':'오류')+'\n\nP95 대기 '+fmt(s.p95Wait,2)+' s, 미배차 최장 '+fmt(s.oldest,2)+' s\n\n';
    text+='## 해석 조건\n\n'+r.warnings.map(s=>'- '+s).join('\n')+'\n\n'+scope+'\n\n안전규격 참고: [BSI EN 619:2022](https://knowledge.bsigroup.com/products/continuous-handling-equipment-and-systems-safety-requirements-for-equipment-for-mechanical-handling-of-unit-loads)\n\n## 전체 입력 (내부 SI 단위)\n\n```json\n'+JSON.stringify(Model.pack(c),null,2)+'\n```\n';return text;
  }
  function html(r,s,options={}){const c=r.config,unit=c.unit+'/h';const rows=r.sections.map(x=>[x.id,x.name,fmt(x.cycle,2),fmt(x.theory),fmt(x.available),fmt(x.util===null?null:x.util*100),x.required??'미산정']);
    const keyRows=Object.entries(Model.fields).map(([key,[label,u]])=>[label,key==='creepV'||key==='emptyV'||key==='loadedV'?fmt(c[key]*(c.speedUnit==='m/min'?60:1),3):fmt(c[key],3),u==='speed'?c.speedUnit:u==='distance'?'m':u]);
    const summary=table(['지표','결과'],[['전체 요구량',fmt(r.total)+' '+unit],['전체 이론 능력',fmt(r.theory)+' '+unit],['전체 보정 능력',fmt(r.available)+' '+unit],['목표부하 고려 부족량',fmt(r.shortage)+' '+unit],['병목 자원',r.bottleneck],['구성',c.layout+' / 구간 '+c.sections.length+'개 / 각 차량 1대'],['판정',r.factor===null?'보정계수 미선택 · 보류':r.shortage>0?'목표 부하율 기준 부족':'분석 목표 이내 · 운영 결과 확인 필요']]);
    let out='<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>'+esc(c.name)+' · RGV 계산 보고서</title><style>@page{size:A4;margin:16mm 13mm}*{box-sizing:border-box}body{margin:0;background:#eaf0f3;color:#243e4b;font:12px/1.8 "Malgun Gothic",sans-serif}.sheet{max-width:900px;margin:30px auto;padding:45px;background:white}h1{font-size:27px;margin:8px 0 12px}h2{font-size:17px;border-bottom:2px solid #adc9c8;padding-bottom:8px;margin:28px 0 14px;break-after:avoid}h3{font-size:14px;margin:20px 0 10px}p{margin:10px 0}.eyebrow{color:#148787;font-size:10px;letter-spacing:2px}.meta{color:#728b96;font-size:10px}.notice{background:#f0f5f4;padding:12px 16px;border-left:3px solid #579f92;margin:14px 0}.table-scroll{margin:12px 0}table{width:100%;border-collapse:collapse;font-size:10px;line-height:1.65}th,td{padding:7px 8px;border-bottom:1px solid #dde5e8;text-align:left;word-break:break-word}th{background:#edf3f5;font-weight:600}tr{break-inside:avoid}thead{display:table-header-group}svg{width:100%;display:block}.figure{break-inside:avoid}.toolbar{background:#183743;color:#fff;padding:14px 25px;display:flex;justify-content:space-between;align-items:center;gap:15px}button{padding:9px 14px;border:0;border-radius:5px;cursor:pointer;font:inherit}a{color:#217c81}footer{border-top:1px solid #ddd;padding-top:12px;margin-top:25px;font-size:9px;color:#758e9b}.timeline{display:none}@media print{body{background:white}.sheet{margin:0;padding:0;max-width:none}.toolbar{display:none}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><nav class="toolbar"><span>대상: PDF로 저장 · 용지: A4 · 브라우저 머리글/바닥글 끄기</span><div><button id="printPdf">PDF 저장 / 인쇄</button> <button id="closeReport">닫기</button></div></nav><main class="sheet"><span class="eyebrow">LINEAR RGV · ENGINEERING REPORT</span><h1>'+esc(c.name)+'</h1><p class="meta">직선 RGV 물동량 계산 보고서 · '+esc(new Date().toLocaleString('ko-KR'))+'</p>';
    out+=table(['문서번호','제출처','작성자','검토자'],[[options.documentNo||'—',options.recipient||'—',options.author||'—',options.reviewer||'—']]);out+='<h2>1. 검토 결과</h2>'+summary+'<div class="notice">'+r.warnings.map(esc).join('<br>')+'</div><div class="figure">'+V.layout(c)+'</div>';
    out+='<h2>2. 구간별 차량 부하</h2>'+table(['구간','차량','평균 사이클 s','이론 /h','보정 /h','부하율 %','환산 대수'],rows)+'<p>환산 대수는 목표 부하율을 반영한 작업부하 값입니다. 동일 레일 복수 차량을 지원하거나 증설을 승인하는 값이 아닙니다. Tandem 능력을 차량별 처리량의 합으로 계산하지 않습니다.</p>';
    out+='<h3>구간 좌표와 운영</h3>'+table(['구간','시작 m','끝 m','대기점 m','속도 비율'],c.sections.map(x=>[x.id,x.start,x.end,x.home,x.speedFactor]))+'<p>배차 '+esc(c.dispatch)+' / 대기 '+esc(c.parking)+' / 도착 '+esc(c.demandMode==='history'?'작업이력 CSV':c.arrival)+' / 이재 '+esc(c.handlingMode)+' / jerk '+esc(c.jerkMode)+'</p>';
    out+='<h2>3. 스테이션·수요</h2>'+table(['ID','이름','위치 m','상차 총 s','하차 총 s','버퍼 개','반출 s/개','통과 정지'],c.stations.map(x=>[x.id,x.name,x.x,x.load,x.unload,x.buffer,x.takeaway,x.stop?'예':'아니오']))+table(['OD','출발','도착','적용 수요 /h','작업 /h'],Model.demand(c).map(x=>[x.id,x.from,x.to,fmt(x.rate,2),fmt(x.missions,2)]));
    out+=table(['속도구간 시작 m','끝 m','제한 m/s'],c.zones.map(z=>[z.from,z.to,z.v]));out+=table(['인계 경계','방향별 용량','상차/하차 각각 s'],c.handoffs.map((b,i)=>['H'+(i+1),b.capacity,b.transfer]));out+=table(['시작 min','끝 min','시간대 배율'],c.profile.map(p=>[p.start,p.end,p.multiplier]));
    out+='<h2>4. OD·구간별 시간 분해</h2>'+table(['OD','구간','공차 s','적재 s','상차 s','하차 s','제어 s','사이클 s'],r.legRows.map(x=>[x.od,x.section,fmt(x.emptyTime,2),fmt(x.loadedTime,2),fmt(x.load,2),fmt(x.unload,2),fmt(x.control,2),fmt(x.cycle,2)]));
    if(options.includeGraphs&&options.plan){const graphs=V.motion(c,options.plan);out+='<h2>5. 선택 경로 운동 그래프</h2><p>'+esc(options.routeDescription||'')+' · 전체 '+fmt(options.plan.duration,3)+' s</p><p>위치 대기 미리보기는 상차점에서 시작합니다. 분석 평균 공차 또는 실제 배차 경로와 다를 수 있습니다.</p><div class="figure">'+graphs.speed+'</div><div class="figure">'+graphs.position+'</div><div class="figure">'+graphs.acceleration+'</div>';}
    out+='<h2>시뮬레이션 결과</h2><p>상태: '+(options.includeSim?status(s):'보고서에서 제외')+'</p>';
    if(options.includeSim&&s)out+=table(['항목','관측값'],[['측정시간',fmt(s.measuredTime/3600,3)+' h'],['최종 목적지 완료',fmt(s.throughput)+' '+unit],['외부 출하',fmt(s.shippingRate)+' '+unit],['최초 배차 대기 평균 / P95',fmt(s.meanWait)+' / '+fmt(s.p95Wait)+' s'],['미배차 최장 경과',fmt(s.oldest)+' s'],['생성 / 외부 출하 / 대기 / 진행 / 출고 버퍼',[s.created,s.shipped,s.waiting,s.active,s.output].join(' / ')],['화물 보존',s.conserved?'정상':'오류'],['교착 징후',s.deadlock?'있음':'없음']])+table(['차량','관측가동 %','구간 취급 /h','공차거리 비중 %','차단 s'],s.cars.map(x=>[x.id,fmt(x.busy*100),fmt(x.throughput),fmt(x.emptyRatio*100),fmt(x.stateTime.blocked)]));
    out+='<h2>입력 사양·근거</h2>'+table(['항목','값','단위'],keyRows)+'<p>보정 근거: '+esc(c.basis||'미선택')+' / '+esc(c.basisNote)+'</p><p>수요·화물은 프로젝트 JSON에 저장됩니다. 시뮬레이션은 고장 없는 조건이며 분석 보정계수를 추가 적용하지 않습니다.</p><p>'+esc(scope)+'</p><p><a href="https://knowledge.bsigroup.com/products/continuous-handling-equipment-and-systems-safety-requirements-for-equipment-for-mechanical-handling-of-unit-loads">EN 619:2022 · BSI 공식 안내</a></p><footer>프로그램 '+esc(r.version)+' · 운동 커널 '+esc(r.kernelVersion)+' · 입력 ID '+esc(r.hash)+' · 단일 레일 1대 또는 물리적 분리 구간당 1대</footer></main></body></html>';return out;
  }
  return{csv,parseCSV,markdown,html,status,scope};
});
