(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model.js'),require('./engine.js'));else root.RGVView=factory(root.RGVModel,root.RGVEngine);})(typeof globalThis!=='undefined'?globalThis:this,function(Model,E){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmt=(v,n=1)=>v===null||v===undefined||!Number.isFinite(v)?'—':v.toLocaleString('ko-KR',{minimumFractionDigits:n,maximumFractionDigits:n});
  const colors={empty:'#829cb0',loaded:'#0b9695',load:'#4f80d8',unload:'#8866b2',control:'#b19a6a',blocked:'#ce694b',dock:'#cf9847',idle:'#c4d1d8'};
  const table=(heads,rows)=>'<div class="table-scroll"><table><thead><tr>'+heads.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
  function kpi(label,value,unit,note,featured=false){return'<article class="kpi '+(featured?'featured':'')+'"><div class="kpi-label">'+esc(label)+'</div><div class="kpi-value">'+esc(value)+'<small>'+esc(unit)+'</small></div><p>'+esc(note)+'</p></article>';}
  function layout(c,snapshot=null){const w=1080,h=145+c.sections.length*130,scale=x=>70+x/c.length*930;let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="구간별 RGV 배치와 현재 위치"><rect width="1080" height="'+h+'" rx="10" fill="#112e3d"/>';
    for(let i=0;i<=6;i++){const x=70+i*155;svg+='<line x1="'+x+'" x2="'+x+'" y1="65" y2="'+(h-45)+'" stroke="#254453" stroke-dasharray="3 7"/><text x="'+x+'" y="'+(h-18)+'" text-anchor="middle" fill="#7996a5" font-size="11">'+fmt(c.length*i/6,1)+' m</text>';}
    c.sections.forEach((section,i)=>{const y=96+i*130;svg+='<text x="30" y="'+(y-50)+'" fill="#b3cbd4" font-size="12">'+esc(section.name||section.id)+' · '+fmt(section.start)+'–'+fmt(section.end)+' m</text><line x1="'+scale(section.start)+'" x2="'+scale(section.end)+'" y1="'+y+'" y2="'+y+'" stroke="#5e8596" stroke-width="5"/>';
      for(const z of c.zones){const a=Math.max(z.from,section.start),b=Math.min(z.to,section.end);if(b>a)svg+='<rect x="'+scale(a)+'" y="'+(y-7)+'" width="'+(scale(b)-scale(a))+'" height="14" fill="#d4a052" opacity=".35"/>';}
      for(const station of c.stations.filter(s=>s.x>=section.start-1e-8&&s.x<=section.end+1e-8)){svg+='<circle cx="'+scale(station.x)+'" cy="'+y+'" r="6" fill="#b6ddd6"/><text x="'+scale(station.x)+'" y="'+(y+30)+'" text-anchor="middle" fill="#b6d0da" font-size="11">'+esc(station.id)+' '+esc(station.name)+'</text>';}
      const car=snapshot?.cars[i],x=scale(car?.x??section.home),loaded=car?.loaded,color=car?.state==='blocked'?'#ed9b6c':'#6be0c6';
      svg+='<g><title>'+esc(section.name)+' '+(car?esc(E.states[car.state]):'대기점')+'</title><rect x="'+(x-20)+'" y="'+(y-25)+'" width="40" height="22" rx="5" fill="'+color+'"/><circle cx="'+(x-12)+'" cy="'+(y-2)+'" r="4" fill="#071b29"/><circle cx="'+(x+12)+'" cy="'+(y-2)+'" r="4" fill="#071b29"/>'+(loaded?'<rect x="'+(x-12)+'" y="'+(y-39)+'" width="24" height="14" fill="#e8c47c" rx="2"/>':'')+'<text x="'+x+'" y="'+(y+51)+'" fill="'+color+'" font-size="10" text-anchor="middle">'+esc(car?E.states[car.state]:'대기 위치')+'</text></g>';
    });
    if(c.layout==='tandem')c.handoffs.forEach((b,i)=>{const x=scale(c.sections[i].end),y=148+i*130,count=snapshot?snapshot.buffers.filter(v=>v.id.startsWith('H'+i)).reduce((n,b)=>n+b.count,0):0;svg+='<path d="M'+x+' '+(y-48)+' V'+(y+78)+'" stroke="#c9b986" stroke-dasharray="5 4" fill="none"/><rect x="'+(x-65)+'" y="'+y+'" width="130" height="26" rx="5" fill="#334e57"/><text x="'+x+'" y="'+(y+17)+'" text-anchor="middle" font-size="10" fill="#e2d7b4">H'+(i+1)+' · 방향별 '+b.capacity+'칸'+(snapshot?' / '+count+'개':'')+'</text>';});
    return svg+'</svg>';
  }
  function line(series,{height=220,xMax=1,xLabel='시간 (s)',yLabel='',dark=false}={}){const width=1020,left=62,right=24,top=24,bottom=40,values=series.flatMap(s=>s.points.map(p=>p.y)),low=Math.min(0,...values),high=Math.max(1,...values),span=high-low,px=x=>left+x/Math.max(xMax,1e-9)*(width-left-right),py=y=>height-bottom-(y-low)/span*(height-top-bottom);let html='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(yLabel)+'"><rect width="100%" height="100%" fill="'+(dark?'#112e3d':'#fff')+'"/>';
    for(let i=0;i<=4;i++){const value=low+span*i/4,y=py(value);html+='<line x1="'+left+'" x2="'+(width-right)+'" y1="'+y+'" y2="'+y+'" stroke="#e4ebee"/><text x="'+(left-10)+'" y="'+(y+4)+'" text-anchor="end" fill="#758d98" font-size="11">'+fmt(value,1)+'</text>';}
    for(let i=0;i<=5;i++)html+='<text x="'+px(xMax*i/5)+'" y="'+(height-14)+'" text-anchor="middle" fill="#758d98" font-size="11">'+fmt(xMax*i/5,1)+'</text>';
    for(const s of series)html+='<path d="'+s.points.map((p,i)=>(i?'L':'M')+px(p.x).toFixed(2)+' '+py(p.y).toFixed(2)).join(' ')+'" fill="none" stroke="'+s.color+'" stroke-width="2"/>';
    return html+'<text x="'+left+'" y="14" fill="#657d89" font-size="11">'+esc(yLabel)+'</text><text x="'+(width-right)+'" y="'+(height-1)+'" text-anchor="end" fill="#657d89" font-size="10">'+esc(xLabel)+'</text></svg>';
  }
  function motion(c,plan){const factor=c.speedUnit==='m/min'?60:1,points=[];const times=new Set([0,plan.duration]);for(let t=0;t<plan.duration;t+=Math.max(.01,plan.duration/600))times.add(t);for(const a of plan.actions){times.add(a.start);times.add(Math.max(0,a.start-1e-6));if(a.profile)for(const p of a.profile.phases){times.add(a.start+p.start);times.add(Math.max(0,a.start+p.start-1e-6));}}for(const t of [...times].sort((a,b)=>a-b))points.push({t,p:Model.previewAt(plan,t)});
    return{position:line([{color:colors.loaded,points:points.map(p=>({x:p.t,y:p.p.x}))}],{xMax:plan.duration,yLabel:'위치 X (m)'}),speed:line([{color:'#0b9695',points:points.map(p=>({x:p.t,y:p.p.v*factor}))}],{xMax:plan.duration,yLabel:'속도 ('+c.speedUnit+')'}),acceleration:line([{color:'#4f80d8',points:points.map(p=>({x:p.t,y:p.p.a}))}],{xMax:plan.duration,yLabel:'가속도 (m/s²)'})};
  }
  function timeline(plan){return'<div class="timeline">'+plan.actions.map(a=>'<span title="'+esc(E.states[a.kind])+' '+fmt(a.duration,2)+' s" style="flex:'+a.duration+';background:'+colors[a.kind]+'">'+(a.duration/plan.duration>.08?esc(E.states[a.kind]):'')+'</span>').join('')+'</div><div class="legend">'+Object.entries(statesUsed(plan)).map(([k,v])=>'<span><i style="background:'+colors[k]+'"></i>'+esc(E.states[k])+' '+fmt(v,2)+' s</span>').join('')+'</div>';}
  function statesUsed(plan){const parts={};for(const a of plan.actions)parts[a.kind]=(parts[a.kind]||0)+a.duration;return parts;}
  return{esc,fmt,table,kpi,layout,line,motion,timeline,colors,statesUsed};
});
