(function(root){'use strict';
const colors={moving:0x258d88,waiting:0xda9b3d,transfer:0x787abd,stopped:0xd26161};
class Plan{
 constructor(canvas,onEdit){this.canvas=canvas;this.onEdit=onEdit;this.p=null;this.drag=null;canvas.addEventListener('pointerdown',e=>{if(!this.p||!this.onEdit)return;const q=this.local(e),n=this.p.nodes.find(n=>Math.hypot(this.tx(n.x)-q.x,this.ty(n.z)-q.y)<18);if(n){this.drag=n;canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const q=this.local(e);this.drag.x=Math.round(((q.x-this.ox)/this.scale)*2)/2;this.drag.z=Math.round(((q.y-this.oy)/this.scale)*2)/2;this.draw(this.p);});const up=()=>{if(this.drag){this.drag=null;this.onEdit();}};canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);this.observer=new ResizeObserver(()=>{if(this.p)this.draw(this.p,this.poses);});this.observer.observe(canvas);}
 local(e){const r=this.canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}tx(x){return this.ox+x*this.scale;}ty(z){return this.oy+z*this.scale;}
 draw(p,poses=[]){this.p=p;this.poses=poses;const c=this.canvas,r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(!r.width||!r.height)return;c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=r.width,h=r.height;ctx.fillStyle='#edf3f6';ctx.fillRect(0,0,w,h);const xs=p.nodes.map(n=>n.x),zs=p.nodes.map(n=>n.z);if(!xs.length)return;const minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);if(!this.drag){this.scale=Math.min((w-100)/Math.max(maxX-minX,10),(h-85)/Math.max(maxZ-minZ,10));this.ox=w/2-(minX+maxX)/2*this.scale;this.oy=h/2-(minZ+maxZ)/2*this.scale;}
 ctx.strokeStyle='#dde7ed';ctx.lineWidth=1;for(let x=this.ox%(this.scale*2);x<w;x+=this.scale*2){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=this.oy%(this.scale*2);y<h;y+=this.scale*2){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const map=new Map(p.nodes.map(n=>[n.id,n]));for(const e of p.edges){const a=map.get(e.from),b=map.get(e.to);if(!a||!b)continue;const x=this.tx(a.x),y=this.ty(a.z),dx=this.tx(b.x)-x,dy=this.ty(b.z)-y;ctx.strokeStyle='#a6bac5';ctx.lineWidth=Math.max(9,e.width*this.scale);ctx.lineCap='butt';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx,y+dy);ctx.stroke();ctx.strokeStyle='#d3dfe6';ctx.lineWidth=Math.max(5,e.width*this.scale-4);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx,y+dy);ctx.stroke();const angle=Math.atan2(dy,dx),mx=x+dx*.57,my=y+dy*.57;ctx.save();ctx.translate(mx,my);ctx.rotate(angle);ctx.fillStyle='#367f89';ctx.beginPath();ctx.moveTo(6,0);ctx.lineTo(-5,-4);ctx.lineTo(-5,4);ctx.closePath();ctx.fill();ctx.restore();ctx.font='10px Segoe UI';ctx.fillStyle='#6a8a9c';ctx.textAlign='center';ctx.fillText(e.id,x+dx*.4-8*Math.sin(angle),y+dy*.4+8*Math.cos(angle)-5);}
 for(const n of p.nodes){const x=this.tx(n.x),y=this.ty(n.z);ctx.fillStyle=n.type==='source'?'#138e88':n.type==='sink'?'#487ba8':'#70849a';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x-10,y-10,20,20,4);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 11px Segoe UI';ctx.textAlign='center';ctx.fillText(n.type==='source'?'→':n.type==='sink'?'✓':'↔',x,y+4);ctx.fillStyle='#345767';ctx.font='bold 10px Segoe UI';ctx.fillText(n.id,x,y-18);}
 for(const pose of poses.slice(0,600)){ctx.save();ctx.translate(this.tx(pose.x),this.ty(pose.z));ctx.rotate(pose.heading);const cargo=p.cargo.find(c=>c.id===pose.cargoId);ctx.fillStyle='#'+(colors[pose.state]||colors.moving).toString(16).padStart(6,'0');ctx.fillRect(-cargo.length*this.scale/2,-cargo.width*this.scale/2,cargo.length*this.scale,cargo.width*this.scale);ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.strokeRect(-cargo.length*this.scale/2,-cargo.width*this.scale/2,cargo.length*this.scale,cargo.width*this.scale);ctx.restore();}ctx.fillStyle='#8a9fa9';ctx.font='10px Segoe UI';ctx.textAlign='left';ctx.fillText('GRID 2 m',15,h-14);
 }
}
class Scene{
 constructor(container,onSelect){this.container=container;this.onSelect=onSelect;this.time=0;this.lastPose=-1;this.actors=new Map();this.actorPool=new Map();this.fallback=false;try{const T=THREE;this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.setClearColor(0xe9eff3);container.appendChild(this.renderer.domElement);this.world=new T.Scene();this.world.fog=new T.Fog(0xe9eff3,85,230);this.camera=new T.PerspectiveCamera(38,1,.1,1000);this.controls=new T.OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.maxPolarAngle=Math.PI*.48;this.controls.minDistance=5;this.controls.maxDistance=250;this.controls.addEventListener('change',()=>this.draw());this.world.add(new T.HemisphereLight(0xf5fbff,0xb9c5d0,.95));const light=new T.DirectionalLight(0xfff9ec,.9);light.position.set(-18,34,24);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-50,right:50,top:50,bottom:-50,near:.1,far:120});light.shadow.bias=-.0003;this.world.add(light);this.buildGroup=new T.Group();this.world.add(this.buildGroup);this.renderer.domElement.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];});this.renderer.domElement.addEventListener('pointerup',e=>{if(this.down&&Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])<5)this.pick(e);});}catch(e){this.fallback=true;this.fallbackReason=e.message;const c=document.createElement('canvas');container.appendChild(c);this.plan=new Plan(c);}
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);
 }
 material(color,metalness=.2){return new THREE.MeshStandardMaterial({color,roughness:.65,metalness});}
 box(group,x,y,z,px,py,pz,color){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),typeof color==='number'?this.material(color):color);m.position.set(px,py,pz);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
 label(group,text,x,y,z,color='#4b7181',width=3){const c=document.createElement('canvas');c.width=512;c.height=100;const ctx=c.getContext('2d');ctx.font='600 36px Segoe UI, Malgun Gothic';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='rgba(255,255,255,.85)';ctx.beginPath();ctx.roundRect(8,8,496,84,14);ctx.fill();ctx.fillStyle=color;ctx.fillText(text,256,51);const tex=new THREE.CanvasTexture(c);tex.encoding=THREE.sRGBEncoding;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true}));s.position.set(x,y,z);s.scale.set(width,width*100/512,1);group.add(s);}
 disposeGroup(group){const gs=new Set(),ms=new Set(),ts=new Set();group.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);if(m.map)ts.add(m.map);}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());group.clear();}
 build(run){this.run=run;this.p=run.config;this.time=0;this.lastPose=-1;if(this.fallback){this.plan.draw(this.p);return;}const T=THREE;this.disposeGroup(this.buildGroup);this.actors.clear();this.actorPool.clear();this.pickables=[];this.edgeMeshes=new Map();const ns=this.p.nodes,byId=new Map(ns.map(n=>[n.id,n])),minX=Math.min(...ns.map(n=>n.x)),maxX=Math.max(...ns.map(n=>n.x)),minZ=Math.min(...ns.map(n=>n.z)),maxZ=Math.max(...ns.map(n=>n.z));this.center=new T.Vector3((minX+maxX)/2,0,(minZ+maxZ)/2);this.span=Math.max(maxX-minX,maxZ-minZ,16)+12;
 const floor=this.box(this.buildGroup,this.span*2,.08,this.span*2,this.center.x,-.08,this.center.z,0xe4ecf0);floor.castShadow=false;const grid=new T.GridHelper(Math.ceil(this.span*1.8/2)*2,Math.ceil(this.span*1.8/2),0xc0d0d9,0xd1dfe6);grid.position.copy(this.center);grid.position.y=-.025;this.buildGroup.add(grid);
 const steel=this.material(0x879ba9,.6),rail=this.material(0xc4d2dc,.7),belt=this.material(0x526c78,.3),leg=this.material(0x45677a,.5),yellow=this.material(0xe3b554,.25),rollerGeo=new T.CylinderGeometry(.052,.052,1,8);rollerGeo.rotateX(Math.PI/2);
 for(const e of this.p.edges){const a=byId.get(e.from),b=byId.get(e.to),len=Math.hypot(b.x-a.x,b.z-a.z),full=Math.hypot(len,b.height-a.height),g=new T.Group();g.position.set((a.x+b.x)/2,(a.height+b.height)/2,(a.z+b.z)/2);g.rotation.y=-Math.atan2(b.z-a.z,b.x-a.x);const body=new T.Group();body.rotation.z=Math.atan2(b.height-a.height,len);g.add(body);const width=e.width;this.box(body,full,.18,width,0,-.12,0,steel);const bed=this.box(body,Math.max(.1,full-.1),.05,width-.1,0,0,0,e.mechanism==='belt'?belt:rail);this.edgeMeshes.set(e.id,bed);for(const side of [-1,1])this.box(body,full,.15,.07,0,.04,side*(width/2),leg);
  if(e.mechanism==='roller'){const count=Math.min(180,Math.floor(full/.28));for(let i=0;i<count;i++){const mesh=new T.Mesh(rollerGeo,rail);mesh.scale.z=width-.12;mesh.position.set(-full/2+(i+.5)*full/count,.055,0);mesh.castShadow=false;body.add(mesh);}}else if(e.mechanism==='chain')for(const z of [-width*.3,width*.3])this.box(body,full,.08,.11,0,.07,z,belt);
  for(let x=-len/2+.75;x<len/2;x+=3.5){const height=a.height+(x+len/2)/len*(b.height-a.height);for(const z of [-width*.4,width*.4]){this.box(g,.12,Math.max(.1,height-.15),.12,x,-(a.height+b.height)/2+height/2-.1,z,leg);this.box(g,.34,.055,.28,x,-(a.height+b.height)/2+.015,z,steel);}}
  for(let x=-full/2+e.pitch;x<full/2;x+=e.pitch){this.box(body,.025,.01,width-.1,x,.09,0,yellow);}const arrowShape=new T.Shape();arrowShape.moveTo(.35,0);arrowShape.lineTo(-.18,.15);arrowShape.lineTo(-.18,-.15);arrowShape.closePath();for(let x=-full/2+2.2;x<full/2-1;x+=5){const arrow=new T.Mesh(new T.ShapeGeometry(arrowShape),this.material(0x258f93));arrow.rotation.x=-Math.PI/2;arrow.position.set(x,.12,0);body.add(arrow);}body.traverse(o=>{if(o.isMesh){o.userData.edgeId=e.id;this.pickables.push(o);}});this.buildGroup.add(g);this.label(this.buildGroup,e.id+' · '+(e.speed*60).toFixed(0)+' m/min',(a.x+b.x)/2,(a.height+b.height)/2+.5,(a.z+b.z)/2, '#5f7f90',3.3);
 }
 for(const n of ns){const g=new T.Group();g.position.set(n.x,n.height,n.z);const size=Math.max(1.6,...this.p.edges.filter(e=>e.from===n.id||e.to===n.id).map(e=>e.width+.3));this.box(g,size,.27,size,0,-.08,0,n.type==='source'?0x318e8a:n.type==='sink'?0x4c7fa1:0x74899c);this.box(g,size-.15,.07,size-.15,0,.1,0,rail);if(n.type==='junction'){for(let z=-size/2+.2;z<size/2;z+=.24)this.box(g,size-.22,.05,.1,0,.17,z,belt);for(const x of [-size*.4,size*.4])this.box(g,.08,.08,size-.1,x,.2,0,0xd1ae55);}for(const x of [-size*.35,size*.35])for(const z of [-size*.35,size*.35])this.box(g,.12,n.height,.12,x,-n.height/2-.12,z,leg);this.box(g,.25,.7,.2,-size*.55,.25,0,0x536f81);this.box(g,.12,.12,.1,-size*.55,.66,0,n.type==='source'?0x4edac1:0x8eb9e6);this.buildGroup.add(g);this.label(this.buildGroup,n.id+(n.type==='source'?' / IN':n.type==='sink'?' / OUT':''),n.x,n.height+2,n.z,n.type==='source'?'#197c7b':'#4b7087',3.4);}
 this.setCamera('iso');this.resize();this.render(0);
 }
 cargo(c){const g=new THREE.Group();if(c.kind==='pallet'){this.box(g,c.length,.13,c.width,0,.17,0,0xa9865b);for(const x of [-c.length*.36,0,c.length*.36])this.box(g,.15,.12,c.width,x,.06,0,0x98764f);const bx=c.length*.43,bz=c.width*.44;for(const x of [-c.length*.23,c.length*.23])for(const z of [-c.width*.23,c.width*.23])this.box(g,bx,Math.max(.1,c.height-.27),bz,x,.26+Math.max(.1,c.height-.27)/2,z,parseInt(c.color.slice(1),16));}else{this.box(g,c.length,c.height,c.width,0,c.height/2+.03,0,parseInt(c.color.slice(1),16));if(c.kind==='tote'){this.box(g,c.length+.025,.045,c.width+.025,0,c.height+.02,0,0x347b9c);this.box(g,c.length-.075,.025,c.width-.075,0,c.height+.05,0,0x1e576d);}else this.box(g,.065,.006,c.width+.01,0,c.height+.035,0,0xe6d2b1);}const indicator=this.box(g,.12,.025,c.width*.7,c.length/2+.035,.17,0,colors.moving);return {g,indicator};}
 setCamera(mode){this.mode=mode;if(this.fallback||!this.center)return;const T=THREE,rect=this.container.getBoundingClientRect(),aspect=(rect.width||this.lastViewport?.width||1000)/(rect.height||this.lastViewport?.height||490),dir=(mode==='top'?new T.Vector3(0,1,.001):new T.Vector3(.55,.8,.85)).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right).normalize(),tan=Math.tan(this.camera.fov*Math.PI/360);let distance=10;this.needsFit=!rect.width||!rect.height;this.controls.target.copy(this.center);for(const n of this.p.nodes)for(const dx of [-2,2])for(const dz of [-2,2])for(const y of [0,n.height+3]){const q=new T.Vector3(n.x+dx,y,n.z+dz).sub(this.center);distance=Math.max(distance,q.dot(dir)+1.13*Math.max(Math.abs(q.dot(right))/(tan*aspect),Math.abs(q.dot(up))/tan));}this.camera.position.copy(this.center).addScaledVector(dir,distance);this.camera.lookAt(this.center);this.controls.update();this.draw();}
 resize(){if(this.fallback){if(this.p)this.plan.draw(this.p,this.poses||[]);return;}const r=this.container.getBoundingClientRect();if(!r.width||!r.height)return;this.lastViewport={width:r.width,height:r.height};this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();if(this.needsFit)this.setCamera(this.mode||'iso');this.draw();}
 pick(e){if(!this.run)return;const r=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const hit=ray.intersectObjects(this.pickables)[0];if(hit?.object.userData.edgeId)this.onSelect(hit.object.userData.edgeId);}
 render(t){this.time=t;if(!this.run)return;if(Math.abs(t-this.lastPose)>.08||this.lastPose<0){const snap=CvEngine.snapshot(this.run,t);this.poses=snap.poses;this.lastPose=t;if(this.fallback){this.plan.draw(this.p,snap.poses);return;}const visible=snap.poses.slice(0,600),active=new Set(visible.map(x=>x.id));for(const [id,a]of this.actors)if(!active.has(id)){a.g.visible=false;if(!this.actorPool.has(a.cargoId))this.actorPool.set(a.cargoId,[]);this.actorPool.get(a.cargoId).push(a);this.actors.delete(id);}for(const pose of visible){let a=this.actors.get(pose.id);if(!a){a=this.actorPool.get(pose.cargoId)?.pop();if(!a){a=this.cargo(this.p.cargo.find(c=>c.id===pose.cargoId));a.cargoId=pose.cargoId;this.buildGroup.add(a.g);}this.actors.set(pose.id,a);}a.g.visible=true;a.g.position.set(pose.x,pose.y+.15,pose.z);a.g.rotation.y=-pose.heading;a.indicator.material.color.setHex(colors[pose.state]);}for(const [id,bed]of this.edgeMeshes){const stopped=this.p.stops.some(s=>s.edgeId===id&&t>=s.start&&t<s.end);bed.material=bed.userData.originalMaterial||bed.material;if(!bed.userData.originalMaterial)bed.userData.originalMaterial=bed.material;if(stopped){if(!bed.userData.stopMaterial)bed.userData.stopMaterial=this.material(0xc97b77);bed.material=bed.userData.stopMaterial;}}}
 this.draw();}
 draw(){if(this.fallback||!this.renderer)return;this.renderer.render(this.world,this.camera);}
 capture(){if(this.fallback)return this.plan.canvas.toDataURL('image/png');this.draw();return this.renderer.domElement.toDataURL('image/png');}
}
root.CvScene={Scene,Plan};
})(globalThis);
