(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model.js'));else root.LoopEngine=factory(root.LoopModel);})(globalThis,function(Model){
  'use strict';const EPS=1e-7;
  const states={idle:'위치 대기',circulate:'빈차 순환',empty:'공차 접근',loaded:'적재 이동',following:'차량 추종',block:'블록 대기',control:'배차 제어',load:'상차',unload:'하차',output:'출고 차단',dock:'이재부 대기'};
  function rng(seed){let n=seed>>>0;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
  function percentile(values,q){if(!values.length)return 0;const a=values.slice().sort((x,y)=>x-y),p=(a.length-1)*q,k=Math.floor(p);return a[k]+(a[Math.min(k+1,a.length-1)]-a[k])*(p-k);}
  function interval95(values){const n=values.length,mean=n?values.reduce((a,b)=>a+b,0)/n:0,sd=n>1?Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/(n-1)):0,t=[0,12.706,4.303,3.182,2.776,2.571,2.447,2.365,2.306,2.262,2.228,2.201,2.179,2.16,2.145,2.131,2.12,2.11,2.101,2.093,2.086,2.08,2.074,2.069,2.064,2.06,2.056,2.052,2.048,2.045];return{n,mean,sd,ci95:n>1?(t[Math.min(n-1,29)]||1.96)*sd/Math.sqrt(n):null};}
  function kinematics(v,a,dt){const t=a<0?Math.min(dt,v/-a):dt;return{distance:Math.max(0,v*t+.5*a*t*t),v:Math.max(0,v+a*dt),a};}
  class Engine{
    constructor(input){this.config=Model.validate(input);const c=this.config;this.L=Model.length(c);this.dt=Model.stepSize(c);this.time=0;this.tick=0;this.warmup=c.warmup*60;this.horizon=this.warmup+c.hours*3600;this.jobs=[];this.pending=[];this.logs=[];this.series=[];this.waits=[];this.leads=[];this.created=0;this.delivered=0;this.shipped=0;this.measuredDelivered=0;this.measuredShipped=0;this.queueArea=0;this.maxQueue=0;this.minGap=Infinity;this.failed=null;this.eventCount=0;this.lastProgress=0;this.lastSample=-Infinity;this.arrivalIndex=0;
      this.byId=Object.fromEntries(c.stations.map(s=>[s.id,s]));this.outputs=Object.fromEntries(c.stations.map(s=>[s.id,{...s,items:[],count:0,reserved:0,releaseAt:Infinity,max:0,owner:null,busyTime:0}]));this.zones=Model.speedZones(c);this.blockLength=this.L/c.blocks;this.blockOwners=Array(c.blocks).fill(null);
      this.cars=Array.from({length:c.vehicles},(_,i)=>{const x=c.controlMode==='block'?(Math.floor(i*c.blocks/c.vehicles)+.5)*this.blockLength:i*this.L/c.vehicles;const car={index:i,id:'RGV'+String(i+1).padStart(2,'0'),x,v:0,a:0,loaded:false,stage:'idle',state:'idle',job:null,target:null,timer:null,quantity:0,stateTime:Object.fromEntries(Object.keys(states).map(k=>[k,0])),emptyDistance:0,loadedDistance:0,completed:0,measuredCompleted:0,reservations:new Map(),reservedEnd:0};if(c.controlMode==='block'){const k=Math.floor(x/this.blockLength);this.blockOwners[k]=i;car.reservations.set(k,(k+1)*this.blockLength);car.reservedEnd=(k+1)*this.blockLength;}return car;});this.arrivals=this.generate();this.settle();this.sample();}
    generate(){const c=this.config,arr=[];if(c.demandMode==='history')return c.history.map((j,i)=>({...j,order:i})).sort((a,b)=>a.time-b.time||a.order-b.order);
      for(const od of c.ods){const random=rng(c.seed^parseInt(Model.hash(od),16)),bands=c.profile.length?c.profile.map(p=>({start:p.start*60,end:p.end*60,multiplier:p.multiplier})):[{start:0,end:this.horizon,multiplier:1}];for(const b of bands){const rate=od.rate*c.peak*b.multiplier/c.batchSize;if(!rate)continue;const gap=()=>c.arrival==='poisson'?-Math.log(Math.max(1e-12,1-random()))*3600/rate:3600/rate*(1+c.jitter*(2*random()-1));for(let t=b.start+gap();t<=b.end+EPS&&t<=this.horizon+EPS;t+=gap()){arr.push({time:t,from:od.from,to:od.to,quantity:c.batchSize,order:arr.length});if(arr.length>40000)throw Error('실제 작업 생성 40,000회 한도입니다.');}}}return arr.sort((a,b)=>a.time-b.time||a.order-b.order);}
    process(){const t=this.time,c=this.config;
      for(const output of Object.values(this.outputs))while(output.items.length&&output.releaseAt<=t+EPS){const job=output.items.shift();output.count-=job.quantity;job.status='done';job.shippedAt=t;this.shipped+=job.quantity;if(t>=this.warmup-EPS)this.measuredShipped+=job.quantity;output.releaseAt=output.items.length?output.releaseAt+output.takeaway*output.items[0].quantity:Infinity;this.eventCount++;}
      while(this.arrivalIndex<this.arrivals.length&&this.arrivals[this.arrivalIndex].time<=t+EPS){const a=this.arrivals[this.arrivalIndex++],job={id:'J'+String(this.jobs.length+1).padStart(6,'0'),from:a.from,to:a.to,quantity:a.quantity,arrival:a.time,dispatch:null,status:'waiting'};this.jobs.push(job);this.pending.push(job);this.created+=job.quantity;this.eventCount++;}
      for(const car of this.cars){let guard=0;while(car.timer&&car.timer.end<=t+EPS&&guard++<8){const kind=car.timer.kind;car.timer=null;this.eventCount++;this.lastProgress=t;if(kind==='control'){this.service(car,'load',this.byId[car.job.from].load);}
          else if(kind==='load'){this.outputs[car.job.from].owner=null;car.loaded=true;car.stage='delivery';car.target=car.x+Model.distance(c,this.byId[car.job.from].s,this.byId[car.job.to].s);car.state='loaded';}
          else{const job=car.job,output=this.outputs[job.to];output.owner=null;output.reserved-=job.quantity;output.items.push(job);output.count+=job.quantity;output.max=Math.max(output.max,output.count);if(output.items.length===1)output.releaseAt=t+output.takeaway*job.quantity;
            job.status='output';job.complete=t;this.delivered+=job.quantity;car.completed+=job.quantity;if(t>=this.warmup-EPS){this.measuredDelivered+=job.quantity;car.measuredCompleted+=job.quantity;this.leads.push(t-job.arrival);}this.logs.push({id:job.id,from:job.from,to:job.to,quantity:job.quantity,arrival:job.arrival,dispatch:job.dispatch,complete:t,wait:job.dispatch-job.arrival,lead:t-job.arrival,measured:t>=this.warmup-EPS});car.job=null;car.loaded=false;car.quantity=0;car.stage='idle';car.target=null;car.state='idle';}
        }}
      this.dispatch();for(const car of this.cars)this.tryService(car);
      this.maxQueue=Math.max(this.maxQueue,t>=this.warmup?this.pending.reduce((s,j)=>s+j.quantity,0):0);
    }
    settle(){for(let i=0;i<64;i++){this.process();if(!this.cars.some(car=>car.timer&&car.timer.end<=this.time+EPS)&&!Object.values(this.outputs).some(o=>o.items.length&&o.releaseAt<=this.time+EPS))return;}throw Error('같은 시각의 이벤트 처리 한도를 초과했습니다.');}
    pickupTarget(car,job){const c=this.config,at=Model.travelCoord(c,this.byId[job.from].s),d=Model.mod(at-Model.mod(car.x,this.L),this.L),stop=car.v*car.v/(2*c.emptyD),approach=c.creepDistance>0&&car.v>c.creepV?c.creepDistance+(car.v*car.v-c.creepV*c.creepV)/(2*c.emptyD):0,need=Math.max(stop,approach);return car.x+d+Math.max(0,Math.ceil((need-d-1e-8)/this.L))*this.L;}
    dispatch(){const idle=this.cars.filter(c=>c.stage==='idle');while(idle.length&&this.pending.length){let bestI=0,bestJ=0,best=Infinity;const jobs=this.config.dispatch==='fifo'?Math.min(1,this.pending.length):this.pending.length;for(let i=0;i<idle.length;i++)for(let j=0;j<jobs;j++){const d=this.pickupTarget(idle[i],this.pending[j])-idle[i].x;if(d<best-EPS){best=d;bestI=i;bestJ=j;}}const car=idle.splice(bestI,1)[0],job=this.pending.splice(bestJ,1)[0];car.target=this.pickupTarget(car,job);car.job=job;car.quantity=job.quantity;car.stage='approach';this.lastProgress=this.time;job.status='active';job.dispatch=this.time;if(this.time>=this.warmup-EPS)this.waits.push(this.time-job.arrival);}}
    service(car,kind,duration){car.state=kind;car.stage=kind;car.timer={kind,start:this.time,end:this.time+duration,duration};}
    tryService(car){if(car.timer||car.target===null||car.v>1e-5||car.target-car.x>1e-5)return;
      if(car.stage==='approach'){const output=this.outputs[car.job.from];if(output.owner!==null&&output.owner!==car.index){car.state='dock';return;}output.owner=car.index;this.service(car,'control',this.config.control);}
      else if(car.stage==='delivery'){const output=this.outputs[car.job.to];if(output.count+output.reserved+car.quantity>output.buffer){car.state='output';return;}if(output.owner!==null&&output.owner!==car.index){car.state='dock';return;}output.owner=car.index;output.reserved+=car.quantity;this.service(car,'unload',output.unload);}}
    reserveBlocks(){if(this.config.controlMode!=='block')return;const c=this.config,B=c.blocks,b=this.blockLength;
      for(const car of this.cars){const tail=car.x-c.carLength/2;for(const[k,end]of car.reservations)if(end<=tail+EPS){car.reservations.delete(k);if(this.blockOwners[k]===car.index)this.blockOwners[k]=null;}}
      const cars=this.cars.slice().sort((a,b)=>(a.reservedEnd-a.x)-(b.reservedEnd-b.x)||a.index-b.index);
      for(const car of cars){const d=car.loaded?c.loadedD:c.emptyD,need=car.v*car.v/(2*d)+car.v*this.dt+c.carLength/2+b*.15;let tries=0;while(car.reservedEnd-car.x<need&&tries++<B){const k=Model.mod(Math.round(car.reservedEnd/b),B);if(this.blockOwners[k]!==null&&this.blockOwners[k]!==car.index)break;this.blockOwners[k]=car.index;car.reservedEnd+=b;car.reservations.set(k,car.reservedEnd);}}
    }
    limits(car,spec,dt){const reach=spec.v*spec.v/(2*spec.d)+spec.v*dt+1,out=[];
      for(const z of this.zones){if(z.v>=spec.v)continue;const k=Math.floor((car.x-z.to+EPS)/this.L)+1,a=z.from+k*this.L,b=z.to+k*this.L;if(a-car.x>reach)continue;out.push({from:a-car.x,to:b-car.x,v:z.v});}
      if(this.config.creepDistance>0&&car.target!==null&&car.target-car.x-this.config.creepDistance<reach)out.push({from:car.target-car.x-this.config.creepDistance,to:car.target-car.x,v:this.config.creepV});return out;
    }
    proposal(car,dt,spec,zones,hard,upper=spec.a){const v=car.v,d=spec.d;
      const feasible=(a,tolerance=1e-10)=>{const p=kinematics(v,a,dt),stop=p.v*p.v/(2*d);if(p.v>spec.v+tolerance)return false;for(const h of hard)if(p.distance+stop+p.v*h.reaction>h.distance+tolerance)return false;
        for(const z of zones){if(p.distance<z.from){if(p.v*p.v>z.v*z.v+2*d*(z.from-p.distance)+tolerance)return false;}else if(z.to>0&&p.distance>=z.from){const lo=Math.max(0,z.from),hi=Math.min(p.distance,z.to),speed2=Math.max(v*v+2*a*lo,v*v+2*a*hi);if(speed2>z.v*z.v+tolerance)return false;}}return true;};
      const top=Math.min(upper,(spec.v-v)/dt);if(feasible(top))return kinematics(v,top,dt);let low=-d,high=top;
      if(!feasible(low)){if(feasible(low,1e-6))return kinematics(v,low,dt);throw Error(car.id+' 제동 가능 영역 이탈 · 입력 및 시간간격을 확인하세요.');}
      for(let i=0;i<28;i++){const mid=(low+high)/2;if(feasible(mid))low=mid;else high=mid;}return kinematics(v,low,dt);
    }
    move(dt){const c=this.config,L=this.L;this.reserveBlocks();const proposals=[];
      for(let i=0;i<this.cars.length;i++){const car=this.cars[i];if(car.timer||car.state==='output'||car.state==='dock'||(car.stage==='idle'&&c.parking==='stay')){proposals.push({distance:0,v:0,a:0});continue;}
        const spec={v:car.loaded?c.loadedV:c.emptyV,a:car.loaded?c.loadedA:c.emptyA,d:car.loaded?c.loadedD:c.emptyD},zones=this.limits(car,spec,dt),hard=[];if(car.target!==null)hard.push({distance:Math.max(0,car.target-car.x),reaction:0});
        const free=this.proposal(car,dt,spec,zones,hard),traffic=[];if(this.cars.length>1){const next=this.cars[(i+1)%this.cars.length],ahead=next.x+(i===this.cars.length-1?L:0);traffic.push({distance:Math.max(0,ahead-car.x-c.carLength-c.gap),reaction:c.reaction,kind:'following'});}
        if(c.controlMode==='block')traffic.push({distance:Math.max(0,car.reservedEnd-car.x-c.carLength/2-1e-6),reaction:0,kind:'block'});
        const p=this.proposal(car,dt,spec,zones,[...hard,...traffic],free.a);car.state=p.distance<free.distance-1e-8?(traffic.slice().sort((a,b)=>a.distance-b.distance)[0]?.kind||'following'):(car.loaded?'loaded':car.job?'empty':'circulate');
        if(car.stage==='idle'&&p.v<1e-6&&p.distance<1e-6&&c.parking==='stay')car.state='idle';proposals.push(p);
      }
      if(proposals.some(p=>p.distance>1e-6))this.lastProgress=this.time+dt;
      const measured=Math.max(0,Math.min(this.time+dt,this.horizon)-Math.max(this.time,this.warmup));const queue=this.pending.reduce((n,j)=>n+j.quantity,0);this.queueArea+=queue*measured;
      this.cars.forEach((car,i)=>{const p=proposals[i];car.stateTime[car.state]+=measured;if(measured){const start=Math.max(0,this.warmup-this.time),lo=kinematics(car.v,p.a,start).distance;car[car.loaded?'loadedDistance':'emptyDistance']+=Math.max(0,p.distance-lo);}car.x+=p.distance;car.v=p.v;car.a=p.a;if(car.target!==null&&Math.abs(car.target-car.x)<1e-5&&car.v<1e-5){car.x=car.target;car.v=0;}});
      for(const out of Object.values(this.outputs))if(out.owner!==null)out.busyTime+=measured;
      for(let i=0;i<this.cars.length;i++){const car=this.cars[i],next=this.cars[(i+1)%this.cars.length],gap=(this.cars.length===1?L:next.x+(i===this.cars.length-1?L:0)-car.x)-c.carLength;this.minGap=Math.min(this.minGap,gap);if(gap<c.gap-1e-5)throw Error('차량 최소 간격 침범');if(c.controlMode==='block'){const front=Model.mod(Math.floor((car.x+c.carLength/2-1e-7)/this.blockLength),c.blocks),rear=Model.mod(Math.floor((car.x-c.carLength/2+1e-7)/this.blockLength),c.blocks);if(this.blockOwners[front]!==i||this.blockOwners[rear]!==i)throw Error('미예약 블록 진입');}}
    }
    advanceTo(target){if(!Number.isFinite(target)||target<this.time-EPS)throw Error('과거 시각은 같은 설정으로 리셋하여 재계산하세요.');target=Math.min(target,this.horizon);try{while(this.time<this.horizon-EPS){const next=Math.min((this.tick+1)*this.dt,this.horizon);if(next>target+EPS)break;this.settle();this.move(next-this.time);this.time=next;this.tick++;this.settle();if(this.time-this.lastSample>=this.horizon/240||this.time>=this.horizon-EPS)this.sample();}}catch(error){this.failed=error.message;throw error;}return this;}
    sample(){this.lastSample=this.time;this.series.push({time:this.time,queue:this.pending.reduce((n,j)=>n+j.quantity,0),wip:this.created-this.shipped,delivered:this.delivered});}
    pose(car){return{...Model.point(this.config,Model.physical(this.config,car.x)),v:car.v,a:car.a,loaded:car.loaded,heading:this.config.direction==='forward'?1:-1};}
    snapshot(){const c=this.config,measuredTime=Math.max(0,this.time-this.warmup),scale=measuredTime?3600/measuredTime:0,waiting=this.pending.reduce((s,j)=>s+j.quantity,0),active=this.cars.reduce((s,car)=>s+(car.job?.quantity||0),0),output=Object.values(this.outputs).reduce((s,o)=>s+o.count,0),cars=this.cars.map(car=>({...this.pose(car),id:car.id,state:car.state,stage:car.stage,job:car.job?.id||'',quantity:car.quantity,busy:measuredTime?1-(car.stateTime.idle+car.stateTime.circulate)/measuredTime:0,stateTime:{...car.stateTime},emptyDistance:car.emptyDistance,loadedDistance:car.loadedDistance,completed:car.completed,throughput:car.measuredCompleted*scale,emptyRatio:(car.emptyDistance+car.loadedDistance)?car.emptyDistance/(car.emptyDistance+car.loadedDistance):0}));
      return{time:this.time,horizon:this.horizon,dt:this.dt,complete:this.time>=this.horizon-EPS,failed:this.failed,measuredTime,throughput:this.measuredDelivered*scale,shippingRate:this.measuredShipped*scale,created:this.created,delivered:this.delivered,shipped:this.shipped,waiting,active,output,conserved:this.created===this.shipped+waiting+active+output,minGap:Number.isFinite(this.minGap)?this.minGap:(this.L/c.vehicles-c.carLength),gapOK:this.minGap>=c.gap-1e-5,p95Wait:percentile(this.waits,.95),p95Lead:percentile(this.leads,.95),meanWait:this.waits.length?this.waits.reduce((a,b)=>a+b,0)/this.waits.length:0,oldest:this.pending.reduce((n,j)=>Math.max(n,this.time-j.arrival),0),meanQueue:measuredTime?this.queueArea/measuredTime:0,maxQueue:this.maxQueue,cars,stations:Object.values(this.outputs).map(o=>({id:o.id,count:o.count,reserved:o.reserved,capacity:o.buffer,max:o.max,owner:o.owner,busy:measuredTime?o.busyTime/measuredTime:0})),blocks:this.blockOwners.slice(),gridlock:this.time-this.lastProgress>=5&&waiting+active>0&&cars.every(car=>car.v<1e-5)&&this.cars.every(car=>!car.timer)&&Object.values(this.outputs).every(o=>!Number.isFinite(o.releaseAt)),tick:this.tick,eventCount:this.eventCount};}
  }
  function run(c){const e=new Engine(c);return e.advanceTo(e.horizon);}
  return{Engine,run,rng,states,percentile,interval95,kinematics};
});
