(function(root){
 'use strict';const Model=root.LoopModel,E=root.LoopEngine;
 class Scene{
  constructor(container,c,onSelect=()=>{}){this.container=container;this.config=c;this.onSelect=onSelect;this.selected=0;this.follow=false;this.mode='iso';this.labelsVisible=true;this.labels=[];this.materials=[];this.geometries=[];this.textures=[];this.cars=[];this.ports=[];this.lastTime=null;this.lastRender=-Infinity;this.needsRender=true;this.L=Model.length(c);this.width=0;this.height=0;
   const T=root.THREE;if(!T||!T.OrbitControls){this.fallback=true;return;}try{this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{this.fallback=true;return;}
   this.renderer.setPixelRatio(Math.min(root.devicePixelRatio||1,1.5));this.renderer.setClearColor(0x122a3a);this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.domElement.setAttribute('aria-label','Loop RGV 3D 순환 레일과 다중 차량');this.renderer.domElement.setAttribute('role','img');container.replaceChildren(this.renderer.domElement);container.dataset.renderer='webgl';
   this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(42,1,.01,20000);this.scene.add(new T.HemisphereLight(0xdaeeff,0x243440,1.1));const sun=new T.DirectionalLight(0xfff1d5,1);sun.position.set(15,35,20);this.scene.add(sun);
   this.controls=new T.OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.1;this.controls.maxPolarAngle=Math.PI/2.01;this.controls.minDistance=.5;this.controls.maxDistance=this.L*3;this.controls.addEventListener('change',()=>this.needsRender=true);this.controls.addEventListener('start',()=>{if(!this.follow)this.mode='free';});
   this.unit=this.geometry(new T.BoxGeometry(1,1,1));this.palette={floor:this.material(0x193342),rail:this.material(0xa3bdca),steel:this.material(0x456b7c),teal:this.material(0x239d8a),yellow:this.material(0xe6b45c),cargo:this.material(0xc88e50),band:this.material(0xebd1a0),dark:this.material(0x142633)};this.build();
   this.pointer=new T.Vector2();this.raycaster=new T.Raycaster();this.down=e=>this.start={x:e.clientX,y:e.clientY};this.up=e=>{if(e.button!==0||!this.start||Math.hypot(e.clientX-this.start.x,e.clientY-this.start.y)>5)return;const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects(this.cars.map(x=>x.body),true).find(hit=>hit.object.isMesh&&!hit.object.material.wireframe);if(hit){let o=hit.object;while(o&&o.userData.index===undefined)o=o.parent;if(o){this.select(o.userData.index);this.onSelect(this.selected);}}};this.lost=e=>{e.preventDefault();this.fallback=true;this.lastFallback=null;if(this.engine)this.update(this.engine);};this.renderer.domElement.addEventListener('pointerdown',this.down);this.renderer.domElement.addEventListener('pointerup',this.up);this.renderer.domElement.addEventListener('webglcontextlost',this.lost);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.resize();this.setView('iso');
  }
  geometry(g){this.geometries.push(g);return g;}
  material(color,extra={}){const m=new root.THREE.MeshStandardMaterial({color,roughness:.72,metalness:.18,...extra});this.materials.push(m);return m;}
  box(w,h,d,x,y,z,material,parent=this.scene){const m=new root.THREE.Mesh(this.unit,material);m.scale.set(w,h,d);m.position.set(x,y,z);parent.add(m);return m;}
  label(text,x,y,z,parent=this.scene,pixels=13){const T=root.THREE,canvas=document.createElement('canvas');canvas.width=640;canvas.height=80;const ctx=canvas.getContext('2d'),texture=new T.CanvasTexture(canvas),material=new T.SpriteMaterial({map:texture,transparent:true,depthTest:false});this.textures.push(texture);this.materials.push(material);const sprite=new T.Sprite(material);sprite.position.set(x,y,z);parent.add(sprite);sprite.userData={ctx,texture,pixels,text:null,anchor:sprite.position.clone()};this.labels.push(sprite);this.setLabel(sprite,text);return sprite;}
  setLabel(label,text){const d=label.userData;if(d.text===text)return;d.text=text;d.ctx.clearRect(0,0,640,80);d.ctx.font='500 32px "Malgun Gothic",sans-serif';d.ctx.fillStyle='#d5e8eb';d.ctx.textAlign='center';d.ctx.textBaseline='middle';d.ctx.fillText(text,320,40,624);d.width=Math.min(624,d.ctx.measureText(text).width);d.texture.needsUpdate=true;this.needsRender=true;}
  cargo(parent){const T=root.THREE,g=new T.Group(),size=Math.min(.65,this.config.carLength*.35),h=size*.65;for(let i=0;i<8;i++){const box=new T.Group();this.box(size,h,size*.8,0,0,0,this.palette.cargo,box);this.box(size*.08,h*1.01,size*.81,0,0,0,this.palette.band,box);this.box(size*1.06,h*.13,size*.85,0,-h*.57,0,this.palette.band,box);box.position.set((i%2?1:-1)*size*.53,Math.floor(i/4)*h*1.15,(Math.floor(i/2)%2?1:-1)*size*.46);box.visible=false;g.add(box);}parent.add(g);return g;}
  build(){const T=root.THREE,c=this.config,L=this.L,p=this.palette,gauge=Math.min(.55,c.radius*.5,c.carLength*.4),carWidth=Math.max(.2,gauge*2+.25),height=Math.max(.15,Math.min(.7,c.carLength*.4));this.carWidth=carWidth;this.cargoHeight=height*1.4;
   this.box(c.horizontal+2*c.radius+9,.12,c.vertical+2*c.radius+9,0,-.22,0,p.floor);
   const samples=Math.min(2400,Math.max(240,Math.ceil(L/Math.max(.02,c.radius/10))));
   for(const side of [-1,1]){class Rail extends T.Curve{getPoint(t,out=new T.Vector3()){const v=Model.point(c,t*L);return out.set(v.x+v.tz*gauge*side,.08,v.z-v.tx*gauge*side);}}const geom=this.geometry(new T.TubeGeometry(new Rail(),samples,Math.min(.035,gauge*.08),6,true));this.scene.add(new T.Mesh(geom,p.rail));}
   const ties=Math.min(500,Math.ceil(L/Math.max(.5,c.carLength))),mesh=new T.InstancedMesh(this.unit,p.steel,ties),dummy=new T.Object3D();for(let i=0;i<ties;i++){const q=Model.point(c,i*L/ties);dummy.position.set(q.x,-.02,q.z);dummy.rotation.y=-Math.atan2(q.tz,q.tx);dummy.scale.set(.09,.07,gauge*2+.3);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);}this.scene.add(mesh);
   const vertices=[],color=[],zoneLimits=Model.speedZones({...c,direction:'forward'});this.trackBlocks=[];for(let i=0;i<samples;i++){const s=(i+.5)*L/samples,k=Math.floor(s/(L/c.blocks)),zone=zoneLimits.some(z=>s>=z.from&&s<=z.to);for(const at of [i*L/samples,(i+1)*L/samples]){const q=Model.point(c,at);vertices.push(q.x,.005,q.z);color.push(...(zone?[.8,.52,.17]:[.15,.35,.4]));}this.trackBlocks.push({block:k,zone});}
   const lineGeometry=this.geometry(new T.BufferGeometry());lineGeometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));lineGeometry.setAttribute('color',new T.Float32BufferAttribute(color,3));const lineMat=new T.LineBasicMaterial({vertexColors:true});this.materials.push(lineMat);this.scene.add(new T.LineSegments(lineGeometry,lineMat));this.trackColors=lineGeometry.attributes.color;
   for(let i=0;i<c.vehicles;i++){const body=new T.Group();body.userData.index=i;body.name='RGV'+String(i+1).padStart(2,'0');this.scene.add(body);this.box(c.carLength,height*.45,carWidth,0,height*.5,0,p.yellow,body);this.box(c.carLength*.82,height*.13,carWidth*.9,0,height*.83,0,p.rail,body);this.box(c.carLength*.2,height*.35,carWidth*.72,-c.carLength*.35,height*.95,0,p.teal,body);
    const wheelGeometry=this.geometry(new T.CylinderGeometry(height*.2,height*.2,.12,12));for(const x of [-.3,.3])for(const z of [-.5,.5]){const wheel=new T.Mesh(wheelGeometry,p.dark);wheel.rotation.x=Math.PI/2;wheel.position.set(x*c.carLength,height*.22,z*carWidth);body.add(wheel);}for(let j=0;j<6;j++)this.box(c.carLength*.6,.045,carWidth*.05,c.carLength*.09,height*.94,(j-2.5)*carWidth*.12,p.steel,body);
    const lamp=this.material(0x5dd7b8,{emissive:0x123529});this.box(.1,height*.23,.1,-c.carLength*.35,height*1.24,-carWidth*.3,lamp,body);const outlineMat=new T.MeshBasicMaterial({color:0x7affd7,wireframe:true,transparent:true,opacity:.8});this.materials.push(outlineMat);const outline=this.box(c.carLength*1.08,height*.75,carWidth*1.1,0,height*.7,0,outlineMat,body);outline.visible=i===0;const label=this.label(String(i+1).padStart(2,'0'),0,height*2.5,0,body,12);this.cars.push({body,cargo:this.cargo(this.scene),label,outline,lamp});}
   for(const st of c.stations){const q=Model.point(c,st.s),offset=Math.max(2.5,carWidth*2),x=q.x+q.tz*offset,z=q.z-q.tx*offset,port=new T.Group();port.position.set(x,0,z);port.rotation.y=-Math.atan2(q.tz,q.tx);this.scene.add(port);this.box(c.carLength*1.05,height*.15,carWidth*1.2,0,height*.83,0,p.teal,port);for(const dx of [-.4,.4])for(const dz of [-.4,.4])this.box(.08,height*.8,.08,dx*c.carLength,height*.4,dz*carWidth,p.steel,port);const label=this.label(st.id+' '+st.name,x,height*1.8,z,this.scene,14),count=this.label('출고 0 / '+st.buffer,x,height*.4,z,this.scene,11),cargo=this.cargo(this.scene);cargo.position.set(x,this.cargoHeight,z);this.ports.push({id:st.id,x,z,body:port,label,count,cargo});}
   const zero=Model.point(c,0),arrow=new T.ArrowHelper(new T.Vector3(c.direction==='forward'?1:-1,0,0),new T.Vector3(zero.x+2,0,zero.z-1.5),3,0x60d9bf,.6,.35);this.scene.add(arrow);arrow.traverse(o=>{if(o.geometry)this.geometries.push(o.geometry);if(o.material)this.materials.push(o.material);});
  }
  resize(){if(this.fallback||this.disposed)return;const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h||w===this.width&&h===this.height)return;this.width=w;this.height=h;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();if(this.mode!=='free')this.setView(this.mode);this.needsRender=true;}
  setView(mode){this.mode=mode;if(this.fallback||this.disposed)return;const T=root.THREE,c=this.config,focus=mode==='selected',car=this.cars[this.selected].body.position,center=focus?new T.Vector3(car.x,.7,car.z):new T.Vector3(0,0,0);const wide=focus?Math.max(7,c.carLength*4):c.horizontal+2*c.radius+10,deep=focus?Math.max(7,c.carLength*4):c.vertical+2*c.radius+10,size=Math.max(wide/Math.max(.4,this.camera.aspect),deep,8);this.controls.target.copy(center);if(mode==='top')this.camera.position.copy(center).add(new T.Vector3(0,size*1.55,.01));else if(mode==='front')this.camera.position.copy(center).add(new T.Vector3(0,size*.13,size*1.6));else this.camera.position.copy(center).add(new T.Vector3(size*.35,size*1.05,size*1.35));this.controls.update();this.needsRender=true;this.lastRender=-Infinity;}
  select(i){this.selected=Math.max(0,Math.min(this.cars.length-1,Number(i)||0));this.cars.forEach((c,k)=>{c.outline.visible=k===this.selected;if(this.engine){const car=this.engine.cars[k];this.setLabel(c.label,car.id+(k===this.selected?' · '+E.states[car.state]:''));}});if(this.mode==='selected')this.setView('selected');this.needsRender=true;}
  setLabels(v){this.labelsVisible=v;this.needsRender=true;}
  update(engine){if(this.disposed)return;this.engine=engine;if(this.fallback){if(this.lastFallback!==engine.time||this.oldFallbackEngine!==engine){this.container.dataset.renderer='fallback';this.container.innerHTML='<p class="fallback-note">WebGL을 사용할 수 없어 2D로 표시합니다. 설정 재적용 시 3D를 다시 시도합니다.</p>'+root.LoopView.layout(this.config,engine.snapshot());this.lastFallback=engine.time;this.oldFallbackEngine=engine;}return;}this.resize();this.controls.update();const now=performance.now();if(now-this.lastRender<35)return;
   if(this.lastTime!==engine.time||this.lastEngine!==engine){const before=this.cars[this.selected].body.position.clone();engine.cars.forEach((car,i)=>{const v=engine.pose(car),mesh=this.cars[i];mesh.body.position.set(v.x,0,v.z);mesh.body.rotation.y=-Math.atan2(v.tz,v.tx)+(v.heading<0?Math.PI:0);mesh.body.userData.pose=v;mesh.cargo.visible=car.loaded||car.state==='load';let x=v.x,z=v.z;if(car.timer&&(car.state==='load'||car.state==='unload')){const from=car.state==='load',p=this.ports.find(p=>p.id===car.job[from?'from':'to']),progress=Math.max(0,Math.min(1,car.timer.duration?(engine.time-car.timer.start)/car.timer.duration:1)),f=from?1-progress:progress;x+=f*(p.x-x);z+=f*(p.z-z);mesh.cargo.visible=true;}mesh.cargo.position.set(x,this.cargoHeight,z);mesh.cargo.rotation.y=mesh.body.rotation.y;mesh.cargo.children.forEach((m,j)=>m.visible=j<car.quantity);mesh.lamp.color.setHex(['output','block','following'].includes(car.state)?0xeb985e:car.loaded?0x52ddae:0x9cbfd0);this.setLabel(mesh.label,car.id+(i===this.selected?' · '+E.states[car.state]:''));});
    for(const port of this.ports){const o=engine.outputs[port.id];port.cargo.children.forEach((m,i)=>m.visible=i<Math.min(8,o.count));this.setLabel(port.count,'출고 '+o.count+'/'+o.buffer+(o.reserved?' · 예약 '+o.reserved:''));}
    if(this.config.controlMode==='block'){this.trackBlocks.forEach((b,i)=>{const index=this.config.direction==='forward'?b.block:this.config.blocks-1-b.block,occupied=engine.blockOwners[index]!==null;for(let j=0;j<2;j++)this.trackColors.setXYZ(i*2+j,occupied?.25:b.zone?.8:.15,occupied?.85:b.zone?.52:.35,occupied?.7:b.zone?.17:.4);});this.trackColors.needsUpdate=true;}
    if(this.follow&&this.mode==='selected'){const delta=this.cars[this.selected].body.position.clone().sub(before);this.camera.position.add(delta);this.controls.target.add(delta);}this.lastTime=engine.time;this.lastEngine=engine;this.needsRender=true;}
   if(this.needsRender&&this.width&&this.height){const T=root.THREE,boxes=[];this.camera.updateMatrixWorld();this.scene.updateMatrixWorld(true);const up=new T.Vector3().setFromMatrixColumn(this.camera.matrixWorld,1);for(const label of this.labels){const d=label.userData;label.position.copy(d.anchor);label.updateMatrixWorld(true);const p=new T.Vector3();label.getWorldPosition(p);const depth=p.clone().applyMatrix4(this.camera.matrixWorldInverse).z,unit=Math.max(.001,-depth)*2*Math.tan(this.camera.fov*Math.PI/360)/this.height,h=unit*d.pixels*2.5;label.scale.set(h*8,h,1);const proj=p.clone().project(this.camera),x=(proj.x+1)*this.width/2,y=(1-proj.y)*this.height/2,w=d.width/32*d.pixels,ph=d.pixels+5;label.visible=this.labelsVisible&&proj.z>=-1&&proj.z<=1&&x-w/2>0&&x+w/2<this.width&&y>0&&y<this.height;if(!label.visible)continue;let sy=y;for(let j=0;j<this.labels.length;j++){const hit=boxes.find(b=>Math.abs(b.x-x)<(b.w+w)/2+3&&Math.abs(b.y-sy)<(b.h+ph)/2+3);if(!hit)break;sy=hit.y-(hit.h+ph)/2-4;}if(sy<ph){label.visible=false;continue;}const shift=up.clone().multiplyScalar((y-sy)*unit);if(label.parent!==this.scene)shift.applyQuaternion(label.parent.quaternion.clone().invert());label.position.add(shift);boxes.push({x,y:sy,w,h:ph});}this.renderer.render(this.scene,this.camera);this.lastRender=now;this.needsRender=false;}
  }
  dispose(){this.disposed=true;this.observer?.disconnect();this.controls?.dispose();if(this.renderer){const canvas=this.renderer.domElement;canvas.removeEventListener('pointerdown',this.down);canvas.removeEventListener('pointerup',this.up);canvas.removeEventListener('webglcontextlost',this.lost);this.geometries.forEach(g=>g.dispose());this.materials.forEach(m=>m.dispose());this.textures.forEach(t=>t.dispose());this.renderer.dispose();this.renderer.forceContextLoss();}this.container.replaceChildren();}
 }
 root.LoopScene={Scene};
})(globalThis);
