// Local Edge fallback: the connected Browser runtime had no available browser.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.RGV_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),qa=path.join(root,'qa');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1480,height:1050},acceptDownloads:true}),page=await context.newPage();
 const errors=[],requests=[],checks=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await context.route(/^https?:/,r=>r.abort());
 const check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS '+name);};
 try{
  await page.goto(pathToFileURL(path.resolve(root,'../직선RGV_실행.html')).href);await page.locator('#analysisKpis .kpi').first().waitFor();
  check('offline startup and four KPI cards',await page.locator('#analysisKpis .kpi').count()===4&&await page.locator('#error').isHidden());
  const initial=await page.locator('#analysisKpis').innerText();
  await page.locator('#speedUnit').selectOption('m/s');check('speed conversion m/min → m/s',Number(await page.locator('#loadedV').inputValue())===2);await page.locator('#calculate').click();check('speed unit preserves throughput',initial===await page.locator('#analysisKpis').innerText());
  await page.locator('#distanceUnit').selectOption('mm');check('distance converts 60m → 60000mm',Number(await page.locator('#length').inputValue())===60000);await page.locator('[data-tab="layout"]').click();check('station coordinates also convert',Number(await page.locator('#stationsEditor tbody tr').nth(1).locator('[data-key="x"]').inputValue())===60000);await page.locator('#calculate').click();await page.locator('[data-tab="overview"]').click();check('distance conversion preserves calculation',initial===await page.locator('#analysisKpis').innerText());
  await page.locator('#distanceUnit').selectOption('m');await page.locator('#speedUnit').selectOption('m/min');await page.locator('#calculate').click();
  await page.locator('#idealFactors').evaluate(b=>b.closest('details').open=true);await page.locator('#idealFactors').click();await page.locator('#calculate').click();check('ideal factors populate corrected capacity',!(await page.locator('#analysisKpis .kpi').nth(1).innerText()).includes('—'));
  await page.locator('#handlingMode').evaluate(e=>e.closest('details').open=true);await page.locator('#handlingMode').selectOption('detail');check('detailed transfer subtracts included overhead',Number(await page.locator('#stationsEditor tbody tr').first().locator('[data-key="load"]').inputValue())===5);await page.locator('#calculate').click();const detailResult=await page.locator('#analysisKpis').innerText();await page.locator('#handlingMode').selectOption('total');await page.locator('#calculate').click();check('handling mode switch preserves totals',detailResult===await page.locator('#analysisKpis').innerText());
  await page.locator('#name').fill('RGV <검토> & 기준안');await page.locator('#calculate').click();
  await page.locator('[data-help="length"]').click();check('field help works',await page.locator('#helpDialog').isVisible());await page.keyboard.press('Escape');
  await page.locator('[data-tab="overview"]').click();await page.locator('.sidebar').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(qa,'01_물동량계산.png')});
  const saved=page.waitForEvent('download');await page.locator('#saveProject').click();const file=await saved;await file.saveAs(path.join(qa,'ui-project.json'));const project=JSON.parse(fs.readFileSync(path.join(qa,'ui-project.json'),'utf8'));check('saved project uses SI units',project.config.loadedV===2&&project.units.speed==='m/s');
  await page.locator('#length').fill('1');await page.locator('#calculate').click();check('invalid geometry blocks stale results',await page.locator('#error').isVisible()&&await page.locator('body').getAttribute('data-dirty')==='true');
  await page.locator('#projectFile').setInputFiles(path.join(qa,'ui-project.json'));await page.waitForFunction(()=>document.body.dataset.dirty==='false');check('project import restores state',Number(await page.locator('#length').inputValue())===60);
  await page.locator('[data-tab="simulation"]').click();await page.locator('#simPlay').click();await page.waitForFunction(()=>document.getElementById('simClock').textContent!=='00:00:00');await page.locator('#simPlay').click();check('simulation playback advances',await page.locator('#simClock').innerText()!=='00:00:00');
  await page.locator('#simFinish').click();await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'));check('simulation completes with conservation',(await page.locator('#conservation').innerText()).includes('정상'));await page.screenshot({path:path.join(qa,'02_시뮬레이션.png')});
  const csvDownload=page.waitForEvent('download');await page.locator('#exportJobs').click();await (await csvDownload).saveAs(path.join(qa,'ui-completed.csv'));check('completed CSV has actual records',fs.readFileSync(path.join(qa,'ui-completed.csv'),'utf8').split('\n').length>10);
  await page.locator('[data-tab="motion"]').click();check('three motion charts',await page.locator('#speedGraph svg,#positionGraph svg,#accelGraph svg').count()===3);await page.locator('#motionPlay').click();await page.waitForFunction(()=>!document.getElementById('motionClock').textContent.startsWith('0.00'));await page.locator('#motionPlay').click();await page.screenshot({path:path.join(qa,'03_운동그래프.png')});
  await page.locator('#pdfReport').click();await page.locator('#documentNo').fill('RGV-2026-001');const popup=context.waitForEvent('page');await page.locator('#pdfForm button[type="submit"]').click();const report=await popup;await report.waitForLoadState();check('PDF preview contains metadata, escaped project, graphs and simulation',(await report.locator('h1').innerText())==='RGV <검토> & 기준안'&&(await report.locator('body').innerText()).includes('RGV-2026-001')&&await report.locator('svg').count()===4);await report.screenshot({path:path.join(qa,'04_PDF미리보기.png')});await report.close();
  await page.locator('[data-tab="experiments"]').click();await page.locator('#repCount').selectOption('5');await page.locator('#runExperiments').click();await page.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('20회 완료'),{timeout:30000});check('twenty common-seed policy trials finish',await page.locator('#experimentResults tbody tr').count()===4);await page.screenshot({path:path.join(qa,'05_반복실험.png')});
  await page.locator('#preset').selectOption('blocked');await page.locator('#loadPreset').click();await page.locator('[data-tab="simulation"]').click();await page.locator('#simFinish').click();await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'));check('Tandem shows two vehicles and conserved cargo',await page.locator('#carStats tbody tr').count()===2&&(await page.locator('#conservation').innerText()).includes('정상'));await page.screenshot({path:path.join(qa,'06_Tandem인계차단.png')});
  await page.locator('[data-tab="experiments"]').click();await page.locator('#repCount').selectOption('30');await page.locator('#runExperiments').click();await page.locator('#cancelExperiments').click();check('experiment cancellation restores UI',await page.locator('#runExperiments').isEnabled());
  await page.locator('[data-tab="demand"]').click();await page.locator('#historyFile').setInputFiles(path.join(root,'examples/작업이력_양식.csv'));await page.waitForFunction(()=>document.getElementById('demandMode').value==='history');await page.locator('#calculate').click();check('CSV history accepted without double peak',await page.locator('#error').isHidden()&&(await page.locator('#historyStatus').innerText()).includes('3건'));
  await page.setViewportSize({width:390,height:844});await page.locator('[data-tab="overview"]').click();check('mobile page fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(qa,'07_모바일.png')});
  const fallbackContext=await browser.newContext({viewport:{width:1200,height:900}});await fallbackContext.addInitScript(()=>{window.Worker=function(){throw Error('Disabled for fallback test');};});const fallback=await fallbackContext.newPage();await fallback.goto(pathToFileURL(path.resolve(root,'../직선RGV_실행.html')).href);await fallback.locator('[data-tab="experiments"]').click();await fallback.locator('#repCount').selectOption('5');await fallback.locator('#runExperiments').click();await fallback.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('20회 완료'),{timeout:30000});check('worker-unavailable sliced fallback completes',true);await fallbackContext.close();
  check('no JavaScript errors or runtime HTTP requests',errors.length===0&&requests.length===0);
  fs.writeFileSync(path.join(qa,'browser-results.json'),JSON.stringify({browser:await browser.version(),checks,errors,requests,testedAt:new Date().toISOString()},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
