// Local Edge fallback: Browser runtime discovery returned no available browser.
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.RGV_PLAYWRIGHT_PATH || 'playwright');
const Model = require('../src/model.js'), root = path.resolve(__dirname, '..'), qa = path.join(root, 'qa');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1480, height: 1100 }, acceptDownloads: true });
  const errors = [], requests = [], checks = [];
  context.on('page', p => p.on('pageerror', error => errors.push(error.message)));
  context.on('request', r => { if (/^https?:/.test(r.url())) requests.push(r.url()); });
  await context.route(/^https?:/, r => r.abort());
  const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log('PASS ' + name); };
  const page = await context.newPage();
  const ready = async () => {
    await page.waitForFunction(() => window.__rgvScene && !window.__rgvScene.fallback && window.__rgvScene.lastTime === window.__rgvScene.engine.time && window.__rgvScene.renderer.info.render.calls > 0);
  };
  const seek = async value => {
    await page.locator('#simSeek').evaluate((el, value) => { el.value = value; el.dispatchEvent(new Event('change', { bubbles: true })); }, value);
    await page.waitForFunction(value => Math.abs(window.__rgvScene.engine.time / window.__rgvScene.engine.horizon * 1000 - value) < .01, value);
    await ready();
  };
  const camera = () => page.evaluate(() => window.__rgvScene.camera.position.toArray());
  try {
    await page.goto(pathToFileURL(path.resolve(root, '../직선RGV_실행.html')).href);
    await page.evaluate(() => { const Original = RGVScene.Scene; RGVScene.Scene = class extends Original { constructor(...args) { super(...args); window.__rgvScene = this; } }; });
    await page.locator('[data-tab="simulation"]').click(); await ready();
    check('offline WebGL canvas and scene initialized', await page.locator('#simScene canvas').count() === 1 && (await page.locator('#sceneMode').innerText()).includes('3D'));
    check('one vehicle and two station models', await page.evaluate(() => window.__rgvScene.cars.length === 1 && window.__rgvScene.stocks.length === 2));
    check('static geometry batching under 70 initial draw calls', await page.evaluate(() => window.__rgvScene.renderer.info.render.calls < 70));
    await page.locator('.scene-card').scrollIntoViewIfNeeded();
    await page.locator('.scene-card').screenshot({ path: path.join(qa, 'v020-01-3d-overview.png') });
    const iso = await camera(); await page.locator('#viewFront').click(); const front = await camera(); await page.locator('#viewTop').click(); const top = await camera();
    check('front top and perspective cameras are distinct', JSON.stringify(iso) !== JSON.stringify(front) && top[1] > front[1]);
    await page.locator('#sceneLabels').uncheck(); check('label visibility control', await page.evaluate(() => window.__rgvScene.labels.every(l => !l.visible))); await page.locator('#sceneLabels').check();
    await page.locator('#viewIso').click();
    const rect = await page.locator('#simScene canvas').boundingBox(), beforeDrag = await camera();
    await page.mouse.move(rect.x + rect.width * .5, rect.y + rect.height * .5); await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .62, rect.y + rect.height * .62, { steps: 8 }); await page.mouse.up();
    check('mouse drag rotates scene while paused', JSON.stringify(beforeDrag) !== JSON.stringify(await camera()));
    const beforeZoom = await page.evaluate(() => window.__rgvScene.camera.position.distanceTo(window.__rgvScene.controls.target)); await page.mouse.wheel(0, -350);
    await page.waitForFunction(d => window.__rgvScene.camera.position.distanceTo(window.__rgvScene.controls.target) < d, beforeZoom); check('mouse wheel zooms', true);
    const c = Model.preset('single'); c.warmup = 0; c.hours = .05; c.demandMode = 'history'; c.history = [{ time: 0, from: 'S1', to: 'S2', quantity: 1 }];
    const project = path.join(qa, 'v020-transfer-input.json'); fs.writeFileSync(project, JSON.stringify(Model.pack(c)));
    await page.locator('#projectFile').setInputFiles(project); await page.waitForFunction(() => window.__rgvScene.engine.config.demandMode === 'history' && window.__rgvScene.engine.horizon === 180); await ready();
    await seek(15);
    check('loading cargo visibly moves from station to vehicle', await page.evaluate(() => { const s = window.__rgvScene, car = s.cars[0], pose = car.body.userData.pose; return pose.state === 'load' && car.cargo.visible && pose.cargo.z > s.diagram.ports[0].z && pose.cargo.z < 0 && !pose.loaded; }));
    await page.locator('#viewSelected').click(); await page.locator('#sceneFollow').check();
    const offset = await page.evaluate(() => window.__rgvScene.camera.position.x - window.__rgvScene.cars[0].body.position.x);
    await seek(100);
    check('loaded travel mesh matches engine and camera tracks vehicle', await page.evaluate(offset => { const s = window.__rgvScene, p = s.engine.pose(s.engine.cars[0]); return p.loaded && Math.abs(s.cars[0].body.position.x - p.x) < 1e-8 && Math.abs(s.camera.position.x - p.x - offset) < .1; }, offset));
    await page.locator('.scene-card').screenshot({ path: path.join(qa, 'v020-02-3d-vehicle.png') });
    await page.locator('#simPlay').click(); const start = await page.locator('#simClock').innerText(); await page.waitForFunction(t => document.getElementById('simClock').textContent !== t, start); await page.locator('#simPlay').click(); check('3D playback advances', true);
    await seek(0); check('seek backwards restores initial engine position', await page.evaluate(() => window.__rgvScene.cars[0].body.position.x === 0));
    await page.locator('#preset').selectOption('blocked'); await page.locator('#loadPreset').click(); await ready();
    await page.locator('#sceneFollow').uncheck(); await page.locator('#viewIso').click(); await page.locator('#simFinish').click(); await page.waitForFunction(() => document.getElementById('simNotice').textContent.startsWith('완료')); await ready();
    check('Tandem has two independent vehicles and two directional buffers', await page.evaluate(() => window.__rgvScene.cars.length === 2 && window.__rgvScene.diagram.buffers.length === 2));
    check('blocked loaded vehicle and buffer occupancies match engine', await page.evaluate(() => { const s = window.__rgvScene; return s.cars.some(c => c.body.userData.pose.state === 'blocked' && c.cargo.visible) && s.stocks.filter(b => b.kind === 'handoff').every(b => b.cargo.userData.count === s.engine.contents(s.engine.buffers[b.id])); }));
    await page.locator('.scene-card').screenshot({ path: path.join(qa, 'v020-03-3d-tandem.png') });
    await page.locator('#sceneVehicle').selectOption('1'); await page.locator('#viewSelected').click();
    check('select vehicle focuses downstream RGV', await page.evaluate(() => window.__rgvScene.selected === 1 && window.__rgvScene.cars[1].outline.visible && !window.__rgvScene.cars[0].outline.visible));
    await page.locator('#viewTop').click();
    const hit = await page.evaluate(() => { const s = window.__rgvScene, v = new THREE.Vector3(0, s.diagram.unit * .7, 0); s.cars[0].body.localToWorld(v); v.project(s.camera); const r = s.renderer.domElement.getBoundingClientRect(); return { x: r.left + (v.x + 1) * r.width / 2, y: r.top + (1 - v.y) * r.height / 2 }; });
    await page.mouse.click(hit.x, hit.y);
    check('clicking a 3D vehicle updates selection', await page.locator('#sceneVehicle').inputValue() === '0');
    await page.locator('.scene-card').screenshot({ path: path.join(qa, 'v020-04-3d-top.png') });
    await page.setViewportSize({ width: 390, height: 844 }); await ready();
    check('mobile canvas resizes without horizontal page overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && window.__rgvScene.renderer.domElement.width > 0));
    await page.locator('.scene-card').screenshot({ path: path.join(qa, 'v020-05-3d-mobile.png') });
    await page.setViewportSize({ width: 1480, height: 1100 }); await page.locator('#viewIso').click();
    await page.evaluate(() => { const s = window.__rgvScene; window.__oldRGVScene = s; s.renderer.forceContextLoss(); });
    await page.waitForFunction(() => document.getElementById('simScene').dataset.renderer === 'fallback');
    await page.waitForFunction(() => document.getElementById('sceneMode').textContent === '2D 대체 표시');
    check('WebGL context loss shows working 2D fallback', await page.locator('#simScene svg').count() === 1 && await page.locator('#viewIso').isDisabled());
    await page.locator('#calculate').click(); await ready();
    check('reapply disposes old scene and restores WebGL', await page.evaluate(() => window.__oldRGVScene.disposed && !window.__rgvScene.fallback) && await page.locator('#simScene canvas').count() === 1);
    check('no JavaScript errors or network requests', errors.length === 0 && requests.length === 0);
    fs.writeFileSync(path.join(qa, 'scene-results.json'), JSON.stringify({ version: Model.VERSION, browser: await browser.version(), checks, errors, requests, testedAt: new Date().toISOString() }, null, 2));
  } catch (error) { console.error(await page.evaluate(() => ({ error: document.getElementById('error').textContent, dirty: document.body.dataset.dirty, time: window.__rgvScene?.engine?.time, horizon: window.__rgvScene?.engine?.horizon, seek: document.getElementById('simSeek').value, disposed: window.__rgvScene?.disposed }))); throw error; } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
