// Local Edge fallback after Browser runtime discovery returned no connected browser.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.LOOP_PLAYWRIGHT_PATH||process.env.RGV_PLAYWRIGHT_PATH||'playwright');
const Model=require('../src/model'),root=path.resolve(__dirname,'..'),qa=path.join(root,'qa'),url=pathToFileURL(path.resolve(root,'../LoopRGV_실행.html')).href;
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1600,height:1050},acceptDownloads:true}),page=await context.newPage(),errors=[],requests=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await context.route(/^https?:/,r=>r.abort());
const check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS '+name);},tab=async name=>page.locator('[data-tab="'+name+'"]').click(),open=async id=>page.locator('#'+id).evaluate(e=>{const d=e.closest('details');if(d)d.open=true;});
async function importConfig(c){await page.locator('#projectFile').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(Model.pack(c)))});await page.waitForFunction(name=>document.getElementById('projectSummary').textContent.startsWith(name)&&document.body.dataset.dirty==='false',c.name);}
try{
await page.goto(url);await page.locator('#analysisKpis .kpi').first().waitFor();await page.waitForFunction(()=>document.getElementById('runtime').textContent.includes('Worker OK'));
check('Offline startup, worker and four KPIs',await page.locator('#analysisKpis .kpi').count()===4&&await page.locator('#error').isHidden());
await page.evaluate(()=>{const Original=LoopScene.Scene;LoopScene.Scene=class extends Original{constructor(...args){super(...args);window.__loopScene=this;}};});
const initial=await page.locator('#analysisKpis').textContent();await page.locator('#distanceUnit').selectOption('mm');check('Metres to millimetres',Number(await page.locator('#horizontal').inputValue())===60000);await tab('layout');check('Station coordinate unit conversion',Number(await page.locator('#stationsEditor [data-key="s"]').first().inputValue())===10652);await page.locator('#calculate').click();check('Unit conversion preserves KPI',initial===await page.locator('#analysisKpis').textContent());await page.locator('#distanceUnit').selectOption('m');await page.locator('#speedUnit').selectOption('m/s');await page.locator('#calculate').click();check('Speed display preserves KPI',initial===await page.locator('#analysisKpis').textContent());await page.locator('#speedUnit').selectOption('m/min');await page.locator('#calculate').click();
await open('handlingMode');await page.locator('#handlingMode').selectOption('detail');check('Detailed handling subtracts included overhead',Number(await page.locator('#stationsEditor [data-key="load"]').first().inputValue())===5);await page.locator('#calculate').click();await page.locator('#handlingMode').selectOption('total');await page.locator('#calculate').click();check('Handling mode preserves totals',initial===await page.locator('#analysisKpis').textContent());
await tab('overview');await page.locator('#name').fill('Loop <검토> & 기준안');await page.locator('#calculate').click();await page.locator('[data-help="horizontal"]').click();check('Contextual field help opens',await page.locator('#helpDialog').isVisible());await page.keyboard.press('Escape');await page.locator('.sidebar').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(qa,'01_물동량계산.png')});
const dl=page.waitForEvent('download');await page.locator('#saveProject').click();await(await dl).saveAs(path.join(qa,'ui-project.json'));const saved=JSON.parse(fs.readFileSync(path.join(qa,'ui-project.json'),'utf8'));check('JSON uses SI internal units',saved.units.speed==='m/s'&&saved.config.horizontal===60);
await page.locator('#horizontal').fill('.1');await page.locator('#calculate').click();check('Invalid geometry blocks outdated results',await page.locator('#error').isVisible()&&await page.locator('body').getAttribute('data-dirty')==='true');await importConfig(saved.config);check('JSON import restores input',Number(await page.locator('#horizontal').inputValue())===60);
await tab('simulation');await page.waitForFunction(()=>window.__loopScene?.cars.length===8);check('All eight vehicles and closed curved track rendered with WebGL',await page.locator('#simScene').getAttribute('data-renderer')==='webgl');
await page.locator('#simSpeed').selectOption('1');await page.locator('#simPlay').click();await page.waitForFunction(()=>__loopScene.engine.time>=1);await page.locator('#simPlay').click();check('1x playback advances on fixed physics grid',await page.evaluate(()=>__loopScene.engine.time>=1));const before=await page.evaluate(()=>__loopScene.engine.time);await page.locator('#simStep').click();check('Single step advances one calculation tick',Math.abs(await page.evaluate(()=>__loopScene.engine.time)-before-.1)<1e-7);
await page.locator('#simSeek').fill('250');await page.locator('#simSeek').dispatchEvent('change');await page.waitForTimeout(100);check('3D bodies match simulation coordinates and headings',await page.evaluate(()=>__loopScene.cars.every((m,i)=>{const p=__loopScene.engine.pose(__loopScene.engine.cars[i]);return Math.hypot(m.body.position.x-p.x,m.body.position.z-p.z)<1e-6&&Math.abs(m.body.rotation.y+Math.atan2(p.tz,p.tx))<1e-6;})));
await page.locator('#viewIso').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'02_3D_전체.png')});
for(const [id,mode]of [['viewTop','top'],['viewFront','front'],['viewIso','iso']]){await page.locator('#'+id).click();check('Camera '+mode,await page.evaluate(()=>__loopScene.mode)===mode);}
await page.locator('#sceneVehicle').selectOption('2');await page.locator('#viewSelected').click();check('Vehicle selection and close view',await page.evaluate(()=>__loopScene.selected===2&&__loopScene.mode==='selected'));await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'03_3D_차량확대.png')});
await page.locator('#sceneFollow').check();const followA=await page.evaluate(()=>({time:__loopScene.engine.time,car:__loopScene.cars[2].body.position.toArray(),camera:__loopScene.camera.position.toArray()}));await page.locator('#simSeek').fill('300');await page.locator('#simSeek').dispatchEvent('change');await page.waitForTimeout(100);check('Tracking camera translates with selected vehicle',await page.evaluate(a=>{const s=__loopScene,c=s.cars[2].body.position,p=s.camera.position;return Math.abs((c.x-a.car[0])-(p.x-a.camera[0]))<1e-5&&Math.abs((c.z-a.car[2])-(p.z-a.camera[2]))<1e-5;},followA));
await page.locator('#sceneLabels').uncheck();await page.waitForTimeout(100);check('3D labels toggle',await page.evaluate(()=>__loopScene.labels.every(l=>!l.visible)));await page.locator('#sceneLabels').check();await page.locator('#viewTop').click();await page.waitForTimeout(200);
await page.locator('.rgv-scene-shell').scrollIntoViewIfNeeded();const projected=await page.evaluate(()=>{const s=__loopScene,p=s.cars[4].body.position.clone();p.y=.5;p.project(s.camera);return{x:p.x,y:p.y};}),box=await page.locator('#simScene canvas').boundingBox();await page.mouse.click(box.x+(projected.x+1)*box.width/2,box.y+(1-projected.y)*box.height/2);check('Clicking 3D body selects vehicle',await page.evaluate(()=>__loopScene.selected===4));
const cameraBefore=await page.evaluate(()=>__loopScene.camera.position.toArray());await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.5+100,box.y+box.height*.5+40,{steps:8});await page.mouse.up();await page.waitForTimeout(200);check('Mouse drag rotates orbit camera',JSON.stringify(cameraBefore)!==JSON.stringify(await page.evaluate(()=>__loopScene.camera.position.toArray())));
await page.locator('#simSeek').fill('50');await page.locator('#simSeek').dispatchEvent('change');check('Backward seek deterministically resets',await page.evaluate(()=>Math.abs(__loopScene.engine.time-99)<.101));await page.locator('#simFinish').click();await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'));check('Simulation completes with cargo conservation and required spacing',await page.evaluate(()=>{const s=__loopScene.engine.snapshot();return s.complete&&s.conserved&&s.gapOK&&s.throughput>0;}));
const jobs=page.waitForEvent('download');await page.locator('#exportJobs').click();await(await jobs).saveAs(path.join(qa,'ui-completed.csv'));check('Completed CSV contains delivered jobs',fs.readFileSync(path.join(qa,'ui-completed.csv'),'utf8').split('\n').length>10);
await tab('motion');check('Three movement graphs present',await page.locator('#speedGraph svg,#positionGraph svg,#accelGraph svg').count()===3);await page.locator('#motionPlay').click();await page.waitForFunction(()=>!document.getElementById('motionClock').textContent.startsWith('0.00'));await page.locator('#motionPlay').click();await page.screenshot({path:path.join(qa,'04_운동선도.png')});
await page.locator('#pdfReport').click();await page.locator('#documentNo').fill('LOOP-2026-001');const popup=context.waitForEvent('page');await page.locator('#pdfForm button[type="submit"]').click();const report=await popup;await report.waitForLoadState();check('Report popup includes metadata, escaped title and completed results',await report.locator('h1').innerText()==='Loop <검토> & 기준안'&&(await report.locator('body').innerText()).includes('LOOP-2026-001')&&(await report.locator('body').innerText()).includes('시뮬레이션 · 완료'));await report.screenshot({path:path.join(qa,'05_PDF미리보기.png')});await report.close();
await tab('experiments');await page.locator('#fleetMax').fill('4');await page.locator('#fleetStep').fill('1');await page.locator('#repCount').selectOption('3');await page.locator('#runExperiments').click();await page.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('12회 완료'),null,{timeout:60000});check('Common-seed fleet sweep finishes twelve runs',await page.locator('#experimentResults tbody tr').count()===4);await page.screenshot({path:path.join(qa,'06_대수별실험.png')});
const exp=page.waitForEvent('download');await page.locator('#exportExperiments').click();await(await exp).saveAs(path.join(qa,'ui-experiment.json'));const experiment=JSON.parse(fs.readFileSync(path.join(qa,'ui-experiment.json'),'utf8'));check('Experiment JSON contains common seeds and conserved cargo',experiment.runs.length===12&&experiment.runs.every(r=>r.conserved)&&new Set(experiment.runs.filter(r=>r.repetition===1).map(r=>r.seed)).size===1);
await page.locator('#fleetMax').fill('20');await page.locator('#repCount').selectOption('5');await page.locator('#runExperiments').click();await page.locator('#cancelExperiments').click();check('Cancellation restores controls',await page.locator('#runExperiments').isEnabled());
await page.locator('#preset').selectOption('congested');await page.locator('#loadPreset').click();await tab('simulation');await page.locator('#simFinish').click();await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'));check('Sixteen-vehicle output congestion is observed',await page.evaluate(()=>{const s=__loopScene.engine.snapshot();return s.cars.length===16&&s.waiting>0&&s.cars.some(c=>c.stateTime.output>0)&&s.conserved;}));await page.locator('#viewIso').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'07_출고정체_3D.png')});
const reverse=Model.preset('block');reverse.name='역방향 블록 검증';reverse.direction='reverse';await importConfig(reverse);await page.locator('#simSeek').fill('250');await page.locator('#simSeek').dispatchEvent('change');await page.waitForTimeout(100);check('Reverse movement headings and physical block colors',await page.evaluate(()=>{const s=__loopScene;return s.cars.every((m,i)=>{const p=s.engine.pose(s.engine.cars[i]);return Math.abs(m.body.rotation.y+Math.atan2(p.tz,p.tx)-Math.PI)<1e-5;})&&s.trackBlocks.every((b,i)=>Math.abs(s.trackColors.getX(i*2)-(s.engine.blockOwners[s.config.blocks-1-b.block]!==null?.25:b.zone?.8:.15))<1e-5);}));
await page.locator('#viewTop').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'08_블록제어_평면.png')});
await tab('demand');await page.locator('#historyFile').setInputFiles(path.join(root,'examples/작업이력_양식.csv'));await page.waitForFunction(()=>document.getElementById('demandMode').value==='history');await open('warmup');await page.locator('#warmup').fill('0');await page.locator('#calculate').click();check('CSV history import accepted',await page.locator('#error').isHidden()&&(await page.locator('#historyStatus').innerText()).includes('3건'));
await page.setViewportSize({width:390,height:844});await tab('overview');check('Mobile overview fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(qa,'09_모바일.png')});await tab('simulation');await page.locator('.rgv-scene-shell').scrollIntoViewIfNeeded();check('Mobile 3D canvas fits container',await page.evaluate(()=>{const e=document.getElementById('simScene');return e.querySelector('canvas').clientWidth<=e.clientWidth&&document.documentElement.scrollWidth<=innerWidth;}));await page.locator('.rgv-scene-shell').screenshot({path:path.join(qa,'10_모바일3D.png')});
const fallbackContext=await browser.newContext({viewport:{width:1200,height:900}});await fallbackContext.addInitScript(()=>{window.Worker=function(){throw Error('test worker unavailable');};const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/.test(type)?null:original.call(this,type,...args);};});const fallback=await fallbackContext.newPage();fallback.on('pageerror',e=>errors.push(e.message));await fallback.goto(url);await fallback.locator('[data-tab="simulation"]').click();check('WebGL-unavailable 2D fallback works',await fallback.locator('#simScene').getAttribute('data-renderer')==='fallback'&&await fallback.locator('#simScene svg').count()===1);await fallback.locator('#simStep').click();check('Fallback simulation controls work',await fallback.locator('#error').isHidden());await fallback.locator('[data-tab="experiments"]').click();await fallback.locator('#fleetMax').fill('2');await fallback.locator('#fleetStep').fill('1');await fallback.locator('#repCount').selectOption('1');await fallback.locator('#runExperiments').click();await fallback.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('2회 완료'),null,{timeout:30000});check('Worker-unavailable sliced calculation completes',true);await fallbackContext.close();
check('No JavaScript errors or runtime HTTP requests',errors.length===0&&requests.length===0);
fs.writeFileSync(path.join(qa,'browser-results.json'),JSON.stringify({browser:await browser.version(),checks,errors,requests,testedAt:new Date().toISOString()},null,2));
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
