// Documentation capture only: the executable and user settings are not modified.
'use strict';
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.LOOP_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'qa/manual-20260915'),url=pathToFileURL(path.resolve(root,'../LoopRGV_실행.html')).href;
fs.mkdirSync(folder,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1500,height:1050},deviceScaleFactor:1.5}),errors=[],checks={};page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(url);await page.locator('#analysisKpis .kpi').first().waitFor();checks.analysis=await page.locator('#analysisKpis').innerText();checks.geometry=await page.locator('#projectSummary').innerText();await page.locator('#analysisKpis').screenshot({path:path.join(folder,'analysis.png')});await page.screenshot({path:path.join(folder,'overview.png')});
const tab=async id=>page.locator('[data-tab="'+id+'"]').click();
await tab('layout');await page.locator('#stationsEditor').screenshot({path:path.join(folder,'stations.png')});await tab('demand');await page.locator('#odsEditor').screenshot({path:path.join(folder,'demand.png')});
await tab('simulation');await page.locator('#simSeek').fill('250');await page.locator('#simSeek').dispatchEvent('change');await page.locator('#viewIso').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(folder,'simulation.png')});await page.locator('#sceneVehicle').selectOption('2');await page.locator('#viewSelected').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(folder,'vehicle.png')});await page.locator('#viewIso').click();await page.locator('#sceneVehicle').selectOption('0');
await page.locator('#simFinish').evaluate(el=>el.click());await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'),{},{timeout:120000});checks.default=await page.locator('#simKpis').innerText();checks.conservation=await page.locator('#conservation').innerText();await page.locator('#simKpis').screenshot({path:path.join(folder,'simulation-kpis.png')});
await tab('motion');await page.locator('#speedGraph').screenshot({path:path.join(folder,'motion.png')});
await tab('experiments');await page.locator('#fleetMin').fill('6');await page.locator('#fleetMax').fill('10');await page.locator('#fleetStep').fill('2');await page.locator('#repCount').selectOption('3');await page.locator('#runExperiments').click();await page.waitForFunction(()=>document.getElementById('experimentStatus').textContent.startsWith('9회 완료'),{},{timeout:60000});checks.experiment=await page.locator('#experimentResults').innerText();await page.locator('#experimentResults').screenshot({path:path.join(folder,'experiments.png')});
for(const kind of ['single','congested','block','history']){console.log('Checking '+kind);await page.locator('#preset').selectOption(kind);await page.locator('#loadPreset').click();await tab('simulation');await page.locator('#simSeek').fill('1000');await page.locator('#simSeek').dispatchEvent('change');await page.waitForFunction(()=>document.getElementById('simNotice').textContent.startsWith('완료'),{},{timeout:120000});checks[kind]=await page.locator('#simKpis').innerText();if(kind==='congested'){await page.locator('#viewIso').click();await page.locator('.rgv-scene-shell').screenshot({path:path.join(folder,'congestion.png')});}}
fs.writeFileSync(path.join(folder,'source-checks.json'),JSON.stringify({program:'LoopRGV_실행.html',capturedAt:new Date().toISOString(),checks,errors},null,2));if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify(checks,null,2));
}catch(e){console.log('Current state',await page.locator('#simNotice').innerText(),await page.locator('#error').innerText());await page.screenshot({path:path.join(folder,'capture-error.png')});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
