(function(){'use strict';const Model=ShuttleModel,E=ShuttleEngine,M=ShuttleMotion,V=ShuttleView,R=ShuttleReport,$=id=>document.getElementById(id),{esc,fmt,table,kpi}=V;
let draft=Model.clone(Model.defaults),config,result,engine,scene,dirty=false,tab='overview',shownDistance='m',shownSpeed='m/min',playing=false,bulk=0,lastFrame=0,lastRender=0,motionPlan=null,motionTime=0,motionPlaying=false,motionLevel=0,expToken=0,expData=null,worker=null,pending=null,workerReady=false,sequence=0,toastTimer;
const selects=['system','cargoType','distanceUnit','speedUnit','cycleMode','dispatch','storage','basis','arrival','demandMode'];
const groups={geometryFields:['levels','bays','aisles','bayPitch','aislePitch','levelPitch','baseHeight','firstBay'],cargoFields:['carLength','carWidth','gap','cargoLength','cargoWidth','cargoHeight','cargoMass','shuttleLimit','liftLimit'],xFields:Object.keys(Model.fields).filter(k=>/^x(Empty|Loaded)/.test(k)),zFields:Object.keys(Model.fields).filter(k=>/^z(Empty|Loaded)/.test(k)),liftFields:['numLifts','liftV','liftA','liftD'],handlingFields:['turn','position','shuttleTransfer','liftTransfer','liftPosition'],bufferFields:['floorBuffer','outputBuffer','outputTakeaway','initialFill'],factorFields:['peak','targetUtil','A','Ew'],simulationFields:['hours','warmup','seed','jitter']};
const factor=u=>u==='distance'?(shownDistance==='mm'?1000:1):u==='speed'?(shownSpeed==='m/min'?60:1):1,unit=u=>u==='distance'?shownDistance:u==='speed'?shownSpeed:u==='ratio'?'비율 · 0~1':u;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3000);}
function error(e){$('error').textContent=e.message;$('error').hidden=false;}function clearError(){$('error').hidden=true;}
for(const[group,keys]of Object.entries(groups))$(group).innerHTML=keys.map(k=>{const[label,u,,,,help]=Model.fields[k];return'<div class="field"><label for="'+k+'">'+esc(label)+'<span data-unit="'+k+'" class="unit">'+esc(u)+'</span></label><button type="button" class="help" data-help="'+k+'" title="'+esc(help)+'" aria-label="'+esc(label)+' 도움말">?</button><input id="'+k+'" type="number" step="any"></div>';}).join('');
const help=document.createElement('dialog');help.id='helpDialog';help.innerHTML='<h2></h2><p></p><button type="button">닫기</button>';document.body.append(help);help.querySelector('button').onclick=()=>help.close();document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{const[label,u,min,max,,text]=Model.fields[b.dataset.help];help.querySelector('h2').textContent=label;help.querySelector('p').textContent=text+' 입력 범위 '+fmt(min*factor(u),3)+'~'+fmt(max*factor(u),3)+' '+unit(u);help.showModal();});
function read(check=true){const c=Model.clone(draft);for(const[k,[,u]]of Object.entries(Model.fields))c[k]=$(k).value.trim()===''?NaN:Number($(k).value)/factor(u);for(const k of selects)c[k]=$(k).value;c.name=$('name').value;c.basisNote=$('basisNote').value;c.layers=[...$('layersEditor').querySelectorAll('tbody tr')].map((row,i)=>({id:'F'+(i+1),...Object.fromEntries(['shuttles','inbound','outbound'].map(k=>{const x=row.querySelector('[data-key="'+k+'"]');return[k,x.value.trim()===''?NaN:Number(x.value)];}))}));return check?Model.validate(c):c;}
function write(c){draft=Model.clone(c);shownDistance=c.distanceUnit;shownSpeed=c.speedUnit;for(const[k,[,u,min,max]]of Object.entries(Model.fields)){$(k).value=Number((c[k]*factor(u)).toPrecision(12));$(k).min=min*factor(u);$(k).max=max*factor(u);document.querySelector('[data-unit="'+k+'"]').textContent=unit(u);}for(const k of selects)$(k).value=c[k];$('name').value=c.name;$('basisNote').value=c.basisNote;editors();}
function editors(){$('layersEditor').innerHTML='<div class="table-scroll"><table><thead><tr><th>층</th><th>높이 '+unit('distance')+'</th><th>셔틀 대수</th><th>입고 /h</th><th>출고 /h</th><th>저장 셀</th></tr></thead><tbody>'+draft.layers.map((l,i)=>'<tr><td>'+l.id+'</td><td>'+fmt(Model.height(draft,i)*factor('distance'),2)+'</td>'+['shuttles','inbound','outbound'].map(k=>'<td><input type="number" step="any" data-key="'+k+'" aria-label="'+l.id+' '+k+'" value="'+l[k]+'"></td>').join('')+'<td>'+draft.aisles*draft.bays*2+'</td></tr>').join('')+'</tbody></table></div>';$('historyStatus').textContent='작업이력 '+draft.history.length+'건 · '+(draft.demandMode==='history'?'이력 모드':'층별 수요 모드');$('historyPreview').innerHTML=table(['time_s','type','level'],draft.history.slice(0,10).map(j=>[j.time,j.type,j.level+1]));}
function stop(){playing=false;motionPlaying=false;bulk++;$('simPlay').textContent='▶ 시뮬레이션 재생';$('motionPlay').textContent='▶ 동작 재생';$('simFinish').disabled=false;}
function cancel(){expToken++;if(pending){worker?.terminate();worker=null;workerReady=false;pending.reject(Error('cancelled'));pending=null;$('runtime').textContent='OFFLINE · 분할 계산';}$('runExperiments').disabled=false;$('cancelExperiments').disabled=true;if(expData)$('experimentStatus').textContent='중단됨 · 완료 결과 보존';}
function markDirty(){dirty=true;document.body.dataset.dirty='true';$('dirtyNotice').hidden=false;clearError();stop();cancel();}
function fresh(){if(dirty||!result){toast('계산 및 설정 적용을 눌러 변경 내용을 반영하세요.');return false;}return true;}
function apply(){try{const c=read(),r=Model.calculate(c),e=new E.Engine(c);stop();cancel();scene?.dispose();scene=null;config=c;draft=Model.clone(c);result=r;engine=e;dirty=false;document.body.dataset.dirty='false';$('dirtyNotice').hidden=true;clearError();$('projectSummary').textContent=c.name+' · '+c.levels+'층 / 셔틀 '+e.cars.length+'대 / 리프트 '+e.lifts.length+'대';editors();renderAnalysis();prepareMotion();renderSimulation();expData=null;$('experimentResults').innerHTML='<p class="empty-state">조합 실험을 시작하세요.</p>';$('experimentChart').innerHTML='';$('experimentProgress').value=0;$('experimentStatus').textContent='현재 적용 조건으로 비교합니다.';$('exportExperiments').disabled=true;return true;}catch(e){markDirty();error(e);return false;}}
function renderAnalysis(){const c=config,r=result;$('analysisKpis').innerHTML=kpi('보정 추정 능력',fmt(r.available),'개/h','입력 층별 입출고 비율 유지 · A × Ew',true)+kpi('전체 요구 물동량',fmt(r.total),'개/h','입고 '+fmt(r.totalIn)+' / 출고 '+fmt(r.totalOut))+kpi('현재 병목',r.bottleneck,'','층별 수요와 공유 자원 기준')+kpi('필요 셔틀 합계',r.requiredShuttles??'—','대','리프트 '+(r.lift.required??'—')+'대 · 목표 부하 '+fmt(c.targetUtil*100,0)+'%');$('analysisNotice').innerHTML='<ul>'+r.warnings.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';$('overviewLayout').innerHTML=V.layout(c);$('layoutTag').textContent=r.slots+'셀 · '+c.cargoType;
$('capacitySummary').innerHTML=table(['지표','값'],[['무경합 참고 능력',fmt(r.nominal)+'개/h'],['참고 입고 / 출고',fmt(r.nominalIn)+' / '+fmt(r.nominalOut)],['보정 입고 / 출고',fmt(r.availableIn)+' / '+fmt(r.availableOut)],['수요/추정능력',fmt(r.ratio===null?null:r.ratio*100)+'%'],['목표부하 기준 부족량',fmt(r.shortage)+'개/h']]);
$('liftSummary').innerHTML=table(['항목','값'],[['독립 리프트 수',c.numLifts+'대'],['평균 SC / DC',fmt(r.lift.single,2)+' / '+fmt(r.lift.dual,2)+'s'],['리프트 부하',fmt(r.lift.util===null?null:r.lift.util*100)+'%'],['리프트 참고 능력',fmt(r.lift.capacity)+'개/h'],['균형 셔틀 수 (연속 참고)',fmt(r.balance,2)+'대'],['목표부하 필요 리프트',r.lift.required??'—']]);
$('layerResults').innerHTML=table(['층','대수','입고 /h','출고 /h','SC s','DC s','부하 %','필요 대수'],r.layers.map(l=>[l.id,l.shuttles,fmt(l.inbound),fmt(l.outbound),fmt(l.singleCycle,2),fmt(l.dualCycle,2),Number.isFinite(l.util)?fmt(l.util*100):'대수 부족',l.required===null?(c.basis?'범위 내 미달':'근거 미선택'):l.required]));
$('cycleSummary').innerHTML=table(['기준 셔틀 SC · 균일 위치','평균시간 s'],[['공차 이동 (주차 왕복 포함)',fmt(r.horizontal.empty,2)],['적재 이동',fmt(r.horizontal.loaded,2)],['전환·정위치·이재',fmt(r.horizontal.single-r.horizontal.empty-r.horizontal.loaded,2)],['합계',fmt(r.horizontal.single,2)]]);
$('geometrySummary').innerHTML=table(['항목','값'],[['저장 셀',r.slots],['X 첫 / 끝 베이',fmt(c.firstBay,2)+' / '+fmt(c.firstBay+(c.bays-1)*c.bayPitch,2)+'m'],['Z 크로스레일',fmt(c.aisles*c.aislePitch,2)+'m'],['Y 첫 / 마지막 층',fmt(c.baseHeight,2)+' / '+fmt(Model.height(c,c.levels-1),2)+'m'],['층별 입고 / 출고 버퍼',c.floorBuffer+' / '+c.floorBuffer+'개'],['운영 리프트','독립 샤프트 · 화물 1개 / 공통 지상 I/O']]);}
const clock=t=>[Math.floor(t/3600),Math.floor(t/60)%60,Math.floor(t)%60].map(v=>String(v).padStart(2,'0')).join(':');
function ensureScene(){if(!scene){scene=new ShuttleScene.Scene($('simScene'),config,id=>{$('sceneActor').value=id;sceneInfo();});$('sceneActor').innerHTML=engine.actors.map(a=>'<option value="'+a.id+'">'+a.id+(a.kind==='lift'?' · 리프트':' · F'+(a.level+1))+'</option>').join('');$('sceneLevel').innerHTML='<option value="all">전체 층</option>'+config.layers.map((l,i)=>'<option value="'+i+'">'+l.id+'</option>').join('');if(scene.selected)$('sceneActor').value=scene.selected;scene.setLabels($('sceneLabels').checked);scene.follow=$('sceneFollow').checked;scene.update(engine);if(scene.follow)scene.setView('selected');}scene.update(engine);$('sceneMode').textContent=scene.fallback?'2D 대체 표시':'3D · SHUTTLE / LIFT';for(const id of ['viewSelected','viewTop','viewFront','viewIso','sceneFollow','sceneLabels'])$(id).disabled=!!scene.fallback;}
function sceneInfo(){if(!engine)return;const a=engine.actors.find(a=>a.id===$('sceneActor').value)||engine.actors[0],p=engine.actorPose(a);$('sceneSelection').textContent=a.id+' · '+E.states[p.state]+' · X '+fmt(p.x,2)+' / Y '+fmt(p.y,2)+' / Z '+fmt(p.z,2)+' m · '+fmt(p.v*(config.speedUnit==='m/min'?60:1),2)+' '+config.speedUnit;}
function renderSimulation(){if(!engine)return;const s=engine.snapshot(),c=config;$('simKpis').innerHTML=kpi('입고 적치 완료',fmt(s.inbound),'개/h','랙에 저장 완료된 실제 화물',true)+kpi('출고 지상 완료',fmt(s.outbound),'개/h','외부 출하 '+fmt(s.shippingRate)+'개/h')+kpi('미배차 요청',s.waiting,'건','미완료 '+s.backlog+' / 재고 대기 '+s.stockWaiting)+kpi('P95 최초 배차 대기',fmt(s.p95Wait),'s','미배차 최장 '+fmt(s.oldest)+'s');$('simNotice').textContent=R.status(s)+' · 실제 경로·버퍼 예약 · 입출고 합계 '+fmt(s.throughput)+'개/h'+(s.stockWaiting?' · 재고를 기다리는 출고 '+s.stockWaiting+'건':'')+(s.spaceWaiting?' · 빈 셀 대기 입고 '+s.spaceWaiting+'건':'')+(s.gridlock?' · 현재 진행 가능한 작업 없음: 재고·층별 차량·버퍼를 확인하세요.':'')+(s.failed?' · '+s.failed:'');$('simNotice').className='notice '+(s.failed||s.gridlock?'warning':'subtle');if(tab==='simulation')ensureScene();sceneInfo();$('simClock').textContent=clock(s.time);$('simEnd').textContent=clock(s.horizon);$('simSeek').value=s.time/s.horizon*1000;
$('observedLayers').innerHTML=table(['층','요구 입고','관측 입고','요구 출고','관측 출고','부족 입고 / 출고','재고'],s.floors.map((f,i)=>[f.id,fmt(result.rates[i].inbound),fmt(f.inbound),fmt(result.rates[i].outbound),fmt(f.outbound),fmt(Math.max(0,result.rates[i].inbound-f.inbound))+' / '+fmt(Math.max(0,result.rates[i].outbound-f.outbound)),f.stock]));
const material=Object.entries(s.where).filter(([k])=>!['stock','shipped'].includes(k)).reduce((n,[,v])=>n+v,0);$('conservation').textContent='화물 보존 '+(s.conserved?'✓ 정상':'오류')+' · 초기 재고 '+s.initialStock+' + 도착 입고 '+s.arrivedIn+' = 현재 저장 '+s.stock+' + 대기·운반·버퍼 '+material+' + 외부 출하 '+s.shipped;
$('actorStats').innerHTML=table(['장비','상태','작업','실제 가동 %','예약 대기 s','SC+DC 완료','DC 수','취급 /h'],[...s.cars,...s.lifts].map(a=>[a.id,E.states[a.state],a.task||'—',fmt(a.busy*100),fmt(a.routeWait),a.cycles,a.dual,fmt(a.throughput)]));$('queueChart').innerHTML=V.line([{color:'#c29954',points:engine.series.map(p=>({x:p.time/60,y:p.queue}))},{color:'#129485',points:engine.series.map(p=>({x:p.time/60,y:p.backlog}))}],{xMax:s.horizon/60,xLabel:'운전시간 min',yLabel:'미배차(황색) / 미완료(녹색)'});const total=s.measuredTime*engine.actors.length;$('stateChart').innerHTML=Object.keys(E.states).map(k=>{const t=[...s.cars,...s.lifts].reduce((n,a)=>n+a.stateTime[k],0);return'<div class="bar"><div class="bar-label"><span>'+E.states[k]+'</span><b>'+fmt(t)+'s</b></div><div class="bar-track"><span style="width:'+Math.min(100,total?t/total*100:0)+'%;background:'+V.colors[k]+'"></span></div></div>';}).join('');
$('bufferStats').innerHTML=table(['층','입고 / 예약','출고 / 예약','각 방향 용량','최대 입 / 출'],s.floors.map(f=>[f.id,f.ins+' / '+f.incoming,f.outs+' / '+f.outReserved,f.capacity,f.maxIn+' / '+f.maxOut]));$('waitingStats').innerHTML=table(['지표','관측'],[['지상 출고 / 예약 / 용량',s.output.count+' / '+s.output.reserved+' / '+s.output.capacity],['출고 재고 대기',s.stockWaiting],['입고 빈 셀 대기',s.spaceWaiting],['평균 / 최대 미배차',fmt(s.meanQueue)+' / '+s.maxQueue],['P95 완료 리드타임',fmt(s.p95Lead)+'s']]);$('resourceStats').innerHTML=s.reservations.length?table(['자원','예약·점유 장비'],s.reservations.map(r=>[r.key.replace(/^F(\d+)/,(_,n)=>'F'+(Number(n)+1)),r.owners.join(', ')])):'<p class="empty-state">현재 점유·예약 자원이 없습니다.</p>';}
function prepareMotion(){$('motionFloor').innerHTML=config.layers.map((l,i)=>'<option value="'+i+'">'+l.id+'</option>').join('');for(const id of ['motionAisle','motionOutAisle']){$(id).max=config.aisles;$(id).value=Math.min(Number($(id).value)||1,config.aisles);}for(const id of ['motionBay','motionOutBay']){$(id).max=config.bays;$(id).value=Math.min(Number($(id).value)||1,config.bays);}renderMotion();}
function renderMotion(){try{const c=config,l=Number($('motionFloor').value),a=Number($('motionAisle').value)-1,b=Number($('motionBay').value)-1,aa=Number($('motionOutAisle').value)-1,bb=Number($('motionOutBay').value)-1,type=$('motionType').value;if(![a,b,aa,bb].every(Number.isInteger)||Math.min(a,b,aa,bb)<0||a>=c.aisles||aa>=c.aisles||b>=c.bays||bb>=c.bays)throw Error('경로의 통로·베이 번호를 확인하세요.');motionLevel=l;const job=(aisle,bay)=>({id:'preview',tu:'TU',slot:Model.point(c,l,aisle,bay)});motionPlan=Model.shuttlePlan(c,{level:l,local:0},type==='out'?null:job(a,b),type==='in'?null:job(type==='out'?a:aa,type==='out'?b:bb));motionTime=0;motionPlaying=false;const points=Array.from({length:501},(_,i)=>{const t=motionPlan.duration*i/500,p=Model.phaseAt(motionPlan,t),q=p.phase?.profile?M.at(p.phase.profile,t-p.phase.start):null,sign=p.phase?Math.sign(p.phase.to[p.axis]-p.phase.from[p.axis]):0;return{t,...p,speed:q?q.v*sign:0,accel:q?q.a*sign:0};}),sf=c.speedUnit==='m/min'?60:1,series=key=>['x','z'].map((axis,i)=>({color:i?'#739ab7':'#14978a',points:points.map(p=>({x:p.t,y:key==='position'?p[axis]:p.axis===axis?p[key]*(key==='speed'?sf:1):0}))}));
$('speedGraph').innerHTML=V.line(series('speed'),{xMax:motionPlan.duration,xLabel:'시간 s',yLabel:'X 녹색 / Z 청색 · '+c.speedUnit});$('positionGraph').innerHTML=V.line(series('position'),{xMax:motionPlan.duration,xLabel:'시간 s',yLabel:'X / Z 좌표 m'});$('accelGraph').innerHTML=V.line(series('accel'),{xMax:motionPlan.duration,xLabel:'시간 s',yLabel:'X / Z 가속도 m/s²'});$('motionDescription').textContent='F'+(l+1)+' · '+type.toUpperCase()+' · '+fmt(motionPlan.duration,3)+'s · 주차 복귀 포함, 교통·재고·리프트 대기 제외';$('motionPhases').innerHTML=table(['단계','동작','시간 s','도착 X / Z m'],motionPlan.phases.filter(p=>p.duration>0).map((p,i)=>[i+1,E.states[p.state],fmt(p.duration,3),fmt(p.to.x,2)+' / '+fmt(p.to.z,2)]));updateMotion();}catch(e){error(e);}}
function updateMotion(){if(!motionPlan)return;const p=Model.phaseAt(motionPlan,motionTime);$('motionSeek').value=motionTime/motionPlan.duration*1000;$('motionClock').textContent=fmt(motionTime,2)+' / '+fmt(motionPlan.duration,2)+'s';$('motionValues').textContent=E.states[p.state]+' · '+p.axis.toUpperCase()+' · X '+fmt(p.x,2)+' / Y '+fmt(p.y,2)+' / Z '+fmt(p.z,2)+'m · '+fmt(p.v*(config.speedUnit==='m/min'?60:1),2)+' '+config.speedUnit;$('motionLayout').innerHTML=V.layout(config,{cars:[{...p,level:motionLevel,id:'셔틀',state:p.state}]},motionLevel);}
function setTab(name){tab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);if(name==='simulation')renderSimulation();}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
const filename=suffix=>(config?.name||'셔틀').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,60)+suffix;
function mutate(fn){try{const c=read(false);fn(c);write(c);markDirty();}catch(e){error(e);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('configForm').onsubmit=e=>{e.preventDefault();apply();};document.addEventListener('input',e=>{if(e.target.closest('#configForm,[data-panel="layout"],[data-panel="demand"]'))markDirty();});document.addEventListener('change',e=>{if(['distanceUnit','speedUnit'].includes(e.target.id)){mutate(()=>{});return;}if(e.target.id==='levels'){mutate(c=>{if(!Number.isInteger(c.levels)||c.levels<1||c.levels>8)throw Error('층수는 1~8 정수입니다.');c.layers=Array.from({length:c.levels},(_,i)=>c.layers[i]||{id:'F'+(i+1),shuttles:1,inbound:30,outbound:30});});return;}if(e.target.closest('#configForm,[data-panel="layout"],[data-panel="demand"]'))markDirty();});
$('calculate').onclick=()=>{if(apply())toast('새 조건을 계산과 시뮬레이션에 적용했습니다.');};$('loadPreset').onclick=()=>{write(Model.preset($('preset').value));if(apply())toast('설명용 예시를 적용했습니다.');};
$('saveProject').onclick=()=>{try{download(filename('_셔틀.json'),JSON.stringify(Model.pack(read()),null,2),'application/json;charset=utf-8');}catch(e){error(e);}};$('loadProject').onclick=()=>{$('projectFile').value='';$('projectFile').click();};$('projectFile').onchange=async()=>{const f=$('projectFile').files[0];if(!f)return;try{if(f.size>10000000)throw Error('프로젝트는 10MB 이하여야 합니다.');write(Model.unpack(JSON.parse(await f.text())));if(apply())toast('프로젝트를 불러왔습니다.');}catch(e){error(e);}};
$('historyTemplate').onclick=()=>download('셔틀_작업이력_양식.csv',R.csv([['time_s','type','level'],[0,'in',1],[0,'out',1],[60,'out',2]]),'text/csv;charset=utf-8');$('importHistory').onclick=()=>{$('historyFile').value='';$('historyFile').click();};$('historyFile').onchange=async()=>{const f=$('historyFile').files[0];if(!f)return;try{if(f.size>5000000)throw Error('CSV는 5MB 이하여야 합니다.');const c=read(false);c.history=R.parseCSV(await f.text());c.demandMode='history';write(Model.validate(c));markDirty();toast(c.history.length+'건을 읽었습니다. 설정을 적용하세요.');}catch(e){error(e);}};$('clearHistory').onclick=()=>mutate(c=>{c.history=[];c.demandMode='rate';});
$('simPlay').onclick=()=>{if(!fresh())return;bulk++;$('simFinish').disabled=false;if(engine.time>=engine.horizon-1e-8)engine=new E.Engine(config);playing=!playing;$('simPlay').textContent=playing?'Ⅱ 일시정지':'▶ 시뮬레이션 재생';};$('simStep').onclick=()=>{if(!fresh())return;stop();try{engine.advanceTo(Math.min(engine.horizon,engine.heap.peek()?.time??engine.horizon));renderSimulation();}catch(e){error(e);}};$('simReset').onclick=()=>{if(!fresh())return;stop();engine=new E.Engine(config);renderSimulation();};$('simSeek').onchange=()=>{if(!fresh())return;stop();const t=Number($('simSeek').value)/1000*engine.horizon;if(t<engine.time)engine=new E.Engine(config);try{engine.advanceTo(t);renderSimulation();}catch(e){error(e);}};
$('simFinish').onclick=async()=>{if(!fresh())return;stop();const token=++bulk;$('simFinish').disabled=true;try{while(token===bulk&&engine.time<engine.horizon-1e-8){engine.advanceTo(Math.min(engine.horizon,engine.time+120));if(tab==='simulation')renderSimulation();await new Promise(r=>setTimeout(r,0));}if(token===bulk)renderSimulation();}catch(e){error(e);}finally{if(token===bulk)$('simFinish').disabled=false;}};
for(const[id,mode]of [['viewIso','iso'],['viewFront','front'],['viewTop','top'],['viewSelected','selected']])$(id).onclick=()=>{if(!fresh())return;ensureScene();if(mode!=='selected'){scene.follow=false;$('sceneFollow').checked=false;}scene.setView(mode);};$('sceneActor').onchange=()=>{if(!fresh())return;ensureScene();scene.select($('sceneActor').value);const a=engine.actors.find(a=>a.id===$('sceneActor').value);if(scene.level!==null&&a.level!==undefined&&a.level!==scene.level){scene.setLevel(a.level);$('sceneLevel').value=a.level;}sceneInfo();};$('sceneLevel').onchange=()=>{if(!fresh())return;ensureScene();scene.setLevel($('sceneLevel').value==='all'?null:Number($('sceneLevel').value));scene.update(engine);};$('sceneFollow').onchange=()=>{if(!fresh())return;ensureScene();scene.follow=$('sceneFollow').checked;if(scene.follow)scene.setView('selected');};$('sceneLabels').onchange=()=>scene?.setLabels($('sceneLabels').checked);
$('applyMotion').onclick=()=>{if(fresh())renderMotion();};$('motionPlay').onclick=()=>{if(!fresh()||!motionPlan)return;if(motionTime>=motionPlan.duration)motionTime=0;motionPlaying=!motionPlaying;$('motionPlay').textContent=motionPlaying?'Ⅱ 일시정지':'▶ 동작 재생';};$('motionSeek').oninput=()=>{if(!fresh()||!motionPlan)return;motionPlaying=false;motionTime=Number($('motionSeek').value)/1000*motionPlan.duration;updateMotion();};
$('exportJobs').onclick=()=>{if(fresh())download(filename('_완료작업.csv'),R.csv([['job_id','type','level','tu','slot','arrival_s','dispatch_s','complete_s','wait_s','lead_s','measurement_window'],...engine.logs.map(j=>[j.id,j.type,j.level,j.tu,j.slot,j.arrival,j.dispatch,j.complete,j.wait,j.lead,j.measured])]),'text/csv;charset=utf-8');};$('exportReport').onclick=()=>{if(fresh())download(filename('_계산서.md'),R.markdown(result,engine.snapshot()),'text/markdown;charset=utf-8');};$('pdfReport').onclick=()=>{if(fresh())$('pdfOptions').showModal();};$('pdfCancel').onclick=()=>$('pdfOptions').close();$('pdfForm').onsubmit=e=>{e.preventDefault();if(!fresh())return;const p=window.open('','_blank');if(!p){error(Error('보고서 팝업이 차단되었습니다. 이 파일의 팝업 설정을 확인하세요.'));return;}const meta=Object.fromEntries(['documentNo','recipient','author','reviewer'].map(k=>[k,$(k).value]));p.document.open();p.document.write(R.html(result,engine.snapshot(),meta));p.document.close();p.document.getElementById('printPdf').onclick=()=>p.print();$('pdfOptions').close();};
function setupWorker(){try{const code=['motion','model','engine'].map(k=>document.querySelector('script[data-module="'+k+'"]').textContent).join('\n')+'\nonmessage=function(e){if(e.data.type==="ping"){postMessage({type:"ready"});return;}try{const engine=ShuttleEngine.run(e.data.config),s=engine.snapshot();s.reservationOK=engine.calendar.audit();postMessage({id:e.data.id,type:"result",result:s});}catch(error){postMessage({id:e.data.id,type:"error",error:error.message});}};',url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{const x=e.data;if(x.type==='ready'){workerReady=true;$('runtime').textContent='OFFLINE · Worker OK';}else if(pending&&pending.id===x.id){const p=pending;pending=null;x.type==='error'?p.reject(Error(x.error)):p.resolve(x.result);}};worker.onerror=e=>{e.preventDefault();workerReady=false;worker?.terminate();worker=null;if(pending){pending.reject(Error('Worker 계산 오류'));pending=null;}$('runtime').textContent='OFFLINE · 분할 계산';};worker.postMessage({type:'ping'});}catch{worker=null;workerReady=false;$('runtime').textContent='OFFLINE · 분할 계산';}}
async function trial(c,token){if(workerReady&&worker)return await new Promise((resolve,reject)=>{const id=++sequence;pending={id,resolve,reject};worker.postMessage({id,config:c});});const e=new E.Engine(c);while(e.time<e.horizon-1e-8){if(token!==expToken)throw Error('cancelled');e.advanceTo(Math.min(e.horizon,e.time+180));await new Promise(r=>setTimeout(r,0));}const s=e.snapshot();s.reservationOK=e.calendar.audit();return s;}
function renderExperiments(){if(!expData)return;const rows=expData.combos.map(combo=>{const runs=expData.runs.filter(r=>r.shuttles===combo.shuttles&&r.lifts===combo.lifts);return{...combo,runs,flow:E.interval95(runs.map(r=>r.throughput)),inbound:E.interval95(runs.map(r=>r.inbound)),outbound:E.interval95(runs.map(r=>r.outbound))};}),liftCounts=[...new Set(rows.map(r=>r.lifts))],colors=['#159f8b','#718bb7','#c29c51','#ac80a7'];$('experimentChart').innerHTML=V.line([...liftCounts.map((n,i)=>({color:colors[i],dots:true,points:rows.filter(r=>r.lifts===n&&r.flow.n).map(r=>({x:r.shuttles,y:r.flow.mean}))})),{color:'#c9aa74',points:[{x:0,y:result.total},{x:Math.max(...rows.map(r=>r.shuttles)),y:result.total}]}],{xMax:Math.max(...rows.map(r=>r.shuttles)),xLabel:'층당 셔틀 수',yLabel:'관측 합계 /h · '+liftCounts.map((n,i)=>'L'+n+' '+['녹색','청색','황색','보라'][i]).join(' / ')});$('experimentResults').innerHTML=table(['층당 S','리프트','전체 장비','반복','합계 평균 ±95% CI','입고 / 출고 평균','종료대기 평균','층별 미달 평균','보존·예약'],rows.map(r=>{const avg=k=>r.runs.length?r.runs.reduce((n,x)=>n+x[k],0)/r.runs.length:null;return[r.shuttles,r.lifts,r.shuttles*config.levels+r.lifts,r.flow.n,r.flow.n?fmt(r.flow.mean,2)+' ± '+fmt(r.flow.ci95,2):'—',r.flow.n?fmt(r.inbound.mean)+' / '+fmt(r.outbound.mean):'—',fmt(avg('waiting')),fmt(avg('shortFloors')),r.runs.length?r.runs.every(x=>x.conserved&&x.reservationOK)?'정상':'확인 필요':'—'];}));}
$('runExperiments').onclick=async()=>{if(!fresh())return;let combos=[],reps;try{const min=Number($('shuttleMin').value),max=Number($('shuttleMax').value),lo=Number($('liftMin').value),hi=Number($('liftMax').value);reps=Number($('repCount').value);if(![min,max,lo,hi].every(Number.isInteger)||min<1||max<min||max>6||lo<1||hi<lo||hi>4)throw Error('셔틀 1~6대/층, 리프트 1~4대 정수 범위를 확인하세요.');for(let s=min;s<=max;s++)for(let l=lo;l<=hi;l++)combos.push({shuttles:s,lifts:l});if(combos.length*reps>120)throw Error('한 번에 최대 120회 실험입니다.');}catch(e){error(e);return;}stop();const token=++expToken;expData={schemaVersion:'shuttle-4way/experiment@1',version:Model.VERSION,config:Model.clone(config),combos,repetitions:reps,runs:[]};$('runExperiments').disabled=true;$('cancelExperiments').disabled=false;$('exportExperiments').disabled=true;try{for(let i=0;i<reps;i++)for(const combo of combos){if(token!==expToken)return;const c=Model.clone(config);c.numLifts=combo.lifts;c.layers.forEach(l=>l.shuttles=combo.shuttles);c.seed=(config.seed+i)>>>0;const s=await trial(c,token);if(token!==expToken)return;const shortFloors=s.floors.filter((f,i)=>f.inbound+1e-7<result.rates[i].inbound||f.outbound+1e-7<result.rates[i].outbound).length;expData.runs.push({...combo,repetition:i+1,seed:c.seed,throughput:s.throughput,inbound:s.inbound,outbound:s.outbound,shippingRate:s.shippingRate,waiting:s.waiting,p95Wait:s.p95Wait,shortFloors,floors:s.floors,conserved:s.conserved,reservationOK:s.reservationOK});$('experimentProgress').value=expData.runs.length/(combos.length*reps)*100;$('experimentStatus').textContent=expData.runs.length+' / '+combos.length*reps+'회 완료';$('exportExperiments').disabled=false;renderExperiments();await new Promise(r=>setTimeout(r,0));}if(token===expToken)$('experimentStatus').textContent=expData.runs.length+'회 완료 · 총량과 층별 입출고 미달을 함께 확인하세요.';}catch(e){if(e.message!=='cancelled')error(e);}finally{if(token===expToken){$('runExperiments').disabled=false;$('cancelExperiments').disabled=true;}}};$('cancelExperiments').onclick=cancel;$('exportExperiments').onclick=()=>{if(fresh()&&expData)download(filename('_조합실험.json'),JSON.stringify(expData,null,2),'application/json;charset=utf-8');};
function frame(now){const dt=lastFrame?Math.min(.1,(now-lastFrame)/1000):0;lastFrame=now;try{if(playing&&!dirty){engine.advanceTo(Math.min(engine.horizon,engine.time+dt*Number($('simSpeed').value)));if(engine.time>=engine.horizon-1e-8){playing=false;$('simPlay').textContent='▶ 다시 재생';}if(tab==='simulation'&&now-lastRender>150){renderSimulation();lastRender=now;}}if(tab==='simulation'&&scene&&!dirty){scene.update(engine);if(scene.fallback&&document.getElementById('sceneMode').textContent!=='2D 대체 표시')ensureScene();if(playing)sceneInfo();}if(motionPlaying&&motionPlan&&!dirty){motionTime=Math.min(motionPlan.duration,motionTime+dt*2);if(now-lastRender>80){updateMotion();lastRender=now;}if(motionTime>=motionPlan.duration){motionPlaying=false;$('motionPlay').textContent='▶ 다시 재생';updateMotion();}}}catch(e){stop();error(e);}requestAnimationFrame(frame);}
write(draft);apply();setTab('overview');setupWorker();requestAnimationFrame(frame);
})();


