(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model'),require('./view'));else root.ShuttleReport=factory(root.ShuttleModel,root.ShuttleView);})(globalThis,function(Model,V){
'use strict';const{esc,fmt,table}=V;
function csv(rows){return'\ufeff'+rows.map(row=>row.map(v=>{let s=String(v??'');if(typeof v!=='number'&&/^\s*[=+@-]/.test(s))s="'"+s;return'"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
function parseCSV(text){text=text.replace(/^\ufeff/,'');let rows=[],row=[],value='',quoted=false,closed=false;for(let i=0;i<=text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){value+='"';i++;}else{quoted=false;closed=true;}}else if(ch===undefined)throw Error('CSV 따옴표가 닫히지 않았습니다.');else value+=ch;continue;}if(ch==='"'){if(value||closed)throw Error('CSV 따옴표 위치 오류');quoted=true;continue;}if(ch===','||ch==='\n'||ch==='\r'||ch===undefined){row.push(value);value='';closed=false;if(ch!==','){if(row.some(x=>x.trim()))rows.push(row);row=[];if(ch==='\r'&&text[i+1]==='\n')i++;}continue;}if(closed&&!/\s/.test(ch))throw Error('CSV 구분자 오류');if(!closed)value+=ch;}
if(!rows.length)throw Error('CSV가 비어 있습니다.');const heads=rows.shift().map(x=>x.trim());if(new Set(heads).size!==heads.length||['time_s','type','level'].some(h=>!heads.includes(h)))throw Error('CSV 열은 time_s, type, level입니다.');return rows.map((row,i)=>{if(row.length!==heads.length)throw Error('CSV '+(i+2)+'행의 열 수를 확인하세요.');const at=k=>row[heads.indexOf(k)].trim();if(!at('time_s')||!at('level'))throw Error('CSV 숫자 값이 비어 있습니다.');return{time:Number(at('time_s')),type:at('type'),level:Number(at('level'))-1};});}
const status=s=>!s||!s.time?'미실행':s.failed?'오류로 중단 · 부분 결과':s.complete?'완료':s.measuredTime?'진행 중 · 부분 결과':'준비운전 중';
function markdown(r,s){return'# 4-way 셔틀 물동량 계산서\n\n'+r.config.name+'\n\n버전 '+r.version+' · 운동 커널 '+r.kernelVersion+' · 입력 ID '+r.hash+'\n\n| 항목 | 값 |\n|---|---|\n| 수요 입고 / 출고 | '+fmt(r.totalIn)+' / '+fmt(r.totalOut)+'개/h |\n| 무경합 참고 능력 | '+fmt(r.nominal)+'개/h |\n| 보정 추정 능력 | '+fmt(r.available)+'개/h |\n| 병목 | '+r.bottleneck+' |\n| 층별 필요 셔틀 합계 | '+(r.requiredShuttles??'미산정')+'대 |\n| 필요 리프트 | '+(r.lift.required??'미산정')+'대 |\n\n시뮬레이션 '+status(s)+(s?' · 관측 입고 '+fmt(s.inbound)+' / 출고 '+fmt(s.outbound)+' / 외부 출하 '+fmt(s.shippingRate)+'개/h · 화물 보존 '+s.conserved:'')+'\n\n'+r.warnings.map(w=>'- '+w).join('\n')+'\n\n분석 능력은 입력된 층별 입출고 비율을 유지하는 능력입니다. 관측 총합만으로 층별 수요 달성을 판단하지 마세요.\n\n## 전체 입력 (SI)\n\n~~~json\n'+JSON.stringify(Model.pack(r.config),null,2)+'\n~~~\n';}
function html(r,s,meta={}){const c=r.config;return'<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>'+esc(c.name)+' · 셔틀 계산서</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{margin:0;background:#eaf0f2;color:#24414e;font:12px/1.8 "Malgun Gothic",sans-serif}.sheet{max-width:920px;margin:24px auto;padding:40px;background:white}h1{font-size:27px}h2{font-size:17px;border-bottom:2px solid #b6cfc8;margin-top:28px;break-after:avoid}table{width:100%;border-collapse:collapse;font-size:10px}td,th{padding:7px;border-bottom:1px solid #dce5e8;text-align:left;word-break:break-word}th{background:#edf4f4}tr{break-inside:avoid}thead{display:table-header-group}svg{width:100%}.notice{padding:12px;background:#edf5f2}nav{padding:14px;background:#163b48;color:white}button{padding:9px 15px;cursor:pointer}@media print{body{background:white}.sheet{margin:0;padding:0}nav{display:none}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><nav><button id="printPdf">PDF 저장 / 인쇄</button> A4 · 브라우저 머리글/바닥글 끄기</nav><main class="sheet"><small>4-WAY SHUTTLE · ENGINEERING REPORT</small><h1>'+esc(c.name)+'</h1>'+table(['문서번호','제출처','작성자','검토자'],[[meta.documentNo,meta.recipient,meta.author,meta.reviewer]])+
'<h2>1. 프로젝트·설비</h2>'+table(['항목','입력'],[['구성','층고정 셔틀 + 화물 1개 적재 TU 리프트'],['층 / 통로 / 베이',c.levels+' / '+c.aisles+' / '+c.bays],['셔틀 / 리프트',c.layers.reduce((n,l)=>n+l.shuttles,0)+' / '+c.numLifts+'대'],['화물',c.cargoType+' · '+c.cargoMass+'kg'],['축','x 통로 / y 수직 / z 크로스레일'],['운전',c.cycleMode+' / '+c.dispatch+' / '+c.storage]])+V.layout(c)+
'<h2>2. 사이클과 층별 업무량</h2>'+table(['층','대수','SC s','DC s','입고 /h','출고 /h','부하 %','필요 대수'],r.layers.map(l=>[l.id,l.shuttles,fmt(l.singleCycle,2),fmt(l.dualCycle,2),fmt(l.inbound),fmt(l.outbound),fmt(l.util*100),l.required??'미달']))+table(['공유 자원','SC s','DC s','부하 %','필요 대수'],[['리프트',fmt(r.lift.single,2),fmt(r.lift.dual,2),fmt(r.lift.util===null?null:r.lift.util*100),r.lift.required??'—']])+
'<h2>3. 물동량과 제약</h2>'+table(['항목','값'],[['요구 입고 / 출고',fmt(r.totalIn)+' / '+fmt(r.totalOut)+'개/h'],['무경합 참고',fmt(r.nominal)+'개/h'],['보정 추정',fmt(r.available)+'개/h'],['병목',r.bottleneck],['목표부하 부족량',fmt(r.shortage)+'개/h'],['독립 용량 균형 셔틀 수',fmt(r.balance,2)+'대 (연속 참고값)']])+'<p class="notice">층별 입출고 비율을 유지하는 분석 능력입니다. 관측 총합만으로 목표 달성을 판단하지 않습니다.</p>'+
'<h2>4. 시뮬레이션 · '+status(s)+'</h2>'+(s?table(['항목','관측값'],[['측정 시간',fmt(s.measuredTime/3600,3)+'h'],['입고 / 출고',fmt(s.inbound)+' / '+fmt(s.outbound)+'개/h'],['외부 출하',fmt(s.shippingRate)+'개/h'],['P95 최초 배차 / 리드타임',fmt(s.p95Wait)+' / '+fmt(s.p95Lead)+'s'],['초기 재고 / 입고 도착',s.initialStock+' / '+s.arrivedIn],['현재 저장 / 외부 출하',s.stock+' / '+s.shipped],['화물 보존',s.conserved?'정상':'오류'],['미배차 / 미완료 요청',s.waiting+' / '+s.backlog]])+table(['층','관측 입고 /h','관측 출고 /h','입고 버퍼','출고 버퍼','재고'],s.floors.map(f=>[f.id,fmt(f.inbound),fmt(f.outbound),f.ins,f.outs,f.stock])):'시뮬레이션 미실행')+
'<h2>5. 비교와 재현</h2><p>대수별 실험 결과는 실험 JSON으로 별도 저장합니다. 이 보고서는 현재 적용한 구성과 현재 실행 결과입니다. 시드 '+c.seed+', 준비운전 '+c.warmup+'분, 측정 '+c.hours+'시간.</p>'+
'<h2>6. 입력 사양</h2>'+table(['입력','값','단위'],Object.entries(Model.fields).map(([k,[label,u]])=>[label,fmt(c[k],4),u==='distance'?'m':u==='speed'?'m/s':u]))+
'<h2>7. 계산 가정과 적용 범위</h2><p>'+r.warnings.map(esc).join('<br>')+'</p><p>보정 근거: '+esc(c.basis)+' · '+esc(c.basisNote)+'</p><p>교차로·통로·인계 자원을 시간 구간으로 사전 예약합니다. 노드 사이 정차와 통로 단위 독점은 보수 제어 가정입니다. 대기는 본선 밖 전용 주차 위치에서 합니다. 화물 리프트는 독립 샤프트와 공통 층 버퍼를 사용합니다. 인계시간에는 버퍼 연결 동작이 포함되며 연결 컨베이어 내부는 별도 모사하지 않습니다.</p><p>차량 층이동·다중 적재 리프트·더블딥·배터리·고장·SKU 제약·현장 PLC 및 규격 적합성 검증은 포함하지 않습니다. 상세 재현에는 프로젝트 JSON을 함께 보관하세요.</p><small>프로그램 '+r.version+' · 커널 '+r.kernelVersion+' · 입력 ID '+r.hash+'</small></main></body></html>';}
return{csv,parseCSV,status,markdown,html};
});

