(function(root){'use strict';const Model=root.ShuttleModel,E=root.ShuttleEngine;
class Scene{
constructor(container,c,onSelect=()=>{}){this.container=container;this.config=c;this.onSelect=onSelect;this.selected=null;this.follow=false;this.level=null;this.mode='iso';this.labelsVisible=true;this.labels=[];this.geometries=[];this.materials=[];this.textures=[];this.actors=new Map();this.levels=[];this.nodes=[];this.stock=[];this.lastRender=-Infinity;this.needsRender=true;this.lastTime=null;this.disposed=false;const T=root.THREE;
if(!T||!T.OrbitControls){this.fallback=true;return;}try{this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{this.fallback=true;return;}
this.renderer.setPixelRatio(Math.min(root.devicePixelRatio||1,1.5));this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.setClearColor(0x102938);container.replaceChildren(this.renderer.domElement);container.dataset.renderer='webgl';this.renderer.domElement.setAttribute('aria-label','다층 랙, 4-way 셔틀과 화물 리프트 3D');this.renderer.domElement.setAttribute('role','img');this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(43,1,.01,5000);this.scene.add(new T.HemisphereLight(0xe1f4ff,0x34424a,1.2));const sun=new T.DirectionalLight(0xffffff,1.3);sun.position.set(20,40,20);this.scene.add(sun);this.controls=new T.OrbitControls(this.camera,this.renderer.domElement);
      // Wheel-button drag pans the view; rolling the wheel still zooms.
      this.controls.mouseButtons.MIDDLE = T.MOUSE.PAN; this.controls.screenSpacePanning = true;
this.controls.enableDamping=true;this.controls.dampingFactor=.1;this.controls.maxPolarAngle=Math.PI/2.01;this.controls.minDistance=1;this.controls.maxDistance=500;this.controls.addEventListener('change',()=>this.needsRender=true);this.controls.addEventListener('start',()=>{if(!this.follow)this.mode='free';});
this.unit=this.geo(new T.BoxGeometry(1,1,1));this.palette={floor:this.mat(0x193a48),steel:this.mat(0x4d6c7a),rail:this.mat(0xb6cbd0),deck:this.mat(0xe4bf67),teal:this.mat(0x2dc4a4),cargo:this.mat(0xc99762,{transparent:true,opacity:.76}),dark:this.mat(0x24404e),pad:this.mat(0x305360,{transparent:true,opacity:.5}),reserved:this.mat(0xeec264),free:this.mat(0x419398)};this.bodyHeight=Math.max(.14,Math.min(.28,c.carLength*.22));this.build();
this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.down=e=>this.start={x:e.clientX,y:e.clientY};this.up=e=>{if(e.button||!this.start||Math.hypot(e.clientX-this.start.x,e.clientY-this.start.y)>5)return;const box=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-box.left)/box.width*2-1,1-(e.clientY-box.top)/box.height*2);this.ray.setFromCamera(this.pointer,this.camera);const hit=this.ray.intersectObjects([...this.actors.values()].filter(m=>m.body.visible).map(m=>m.body),true).find(h=>h.object.isMesh&&!h.object.material.wireframe);if(hit){let o=hit.object;while(o&&!o.userData.actor)o=o.parent;if(o){this.select(o.userData.actor);this.onSelect(this.selected);}}};this.lost=e=>{e.preventDefault();this.fallback=true;this.lastFallback=null;this.update(this.engine);};this.renderer.domElement.addEventListener('pointerdown',this.down);this.renderer.domElement.addEventListener('pointerup',this.up);this.renderer.domElement.addEventListener('webglcontextlost',this.lost);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.resize();this.setView('iso');}
geo(g){this.geometries.push(g);return g;}mat(hex,options={}){const T=root.THREE,m=new T.MeshStandardMaterial({color:new T.Color(hex).convertSRGBToLinear(),roughness:.75,metalness:.12,...options});this.materials.push(m);return m;}
box(w,h,d,x,y,z,mat,parent=this.scene){const m=new root.THREE.Mesh(this.unit,mat);m.scale.set(w,h,d);m.position.set(x,y,z);parent.add(m);return m;}
label(text,x,y,z,parent=this.scene,size=12){const T=root.THREE,canvas=document.createElement('canvas');canvas.width=640;canvas.height=80;const texture=new T.CanvasTexture(canvas),material=new T.SpriteMaterial({map:texture,transparent:true,depthTest:false}),sprite=new T.Sprite(material);this.materials.push(material);this.textures.push(texture);sprite.position.set(x,y,z);sprite.userData={ctx:canvas.getContext('2d'),texture,text:'',size,anchor:sprite.position.clone()};parent.add(sprite);this.labels.push(sprite);this.text(sprite,text);return sprite;}
text(label,text){const d=label.userData;if(d.text===text)return;d.text=text;d.ctx.clearRect(0,0,640,80);d.ctx.font='500 32px "Malgun Gothic",sans-serif';d.ctx.fillStyle='#d8f1eb';d.ctx.textAlign='center';d.ctx.textBaseline='middle';d.ctx.fillText(text,320,40,624);d.width=Math.min(624,d.ctx.measureText(text).width);d.texture.needsUpdate=true;this.needsRender=true;}
build(){const T=root.THREE,c=this.config,p=this.palette,end=c.firstBay+(c.bays-1)*c.bayPitch,deep=c.aisles*c.aislePitch,top=Model.height(c,c.levels-1)+c.levelPitch;const minX=Math.min(Model.liftPoint(c,c.numLifts-1).x-2,Model.park(c,{level:0,local:0}).x-2),maxX=end+c.bayPitch,minZ=Math.min(-4,Model.park(c,{level:0,local:Math.max(...c.layers.map(l=>l.shuttles),1)-1}).z-1),maxZ=deep+Math.max(c.carWidth,c.cargoWidth)/2+c.cargoWidth+c.gap+1;this.extent={end,deep,top,minX,maxX,minZ,maxZ};this.box(maxX-minX,.12,maxZ-minZ,(minX+maxX)/2,-.3,(minZ+maxZ)/2,p.floor);const slots=Model.slots(c),shelfOffset=(Math.max(c.carWidth,c.cargoWidth)+c.cargoWidth)/2+c.gap/2;
for(let l=0;l<c.levels;l++){const y=Model.height(c,l),group=new T.Group();this.scene.add(group);const levelLabel=this.label('F'+(l+1),end+2,y+1,deep/2,this.scene,13);levelLabel.userData.level=l;this.levels.push({group,label:levelLabel});this.box(.12,.09,deep+.6,0,y,deep/2,p.teal,group);
for(let a=0;a<c.aisles;a++){const z=(a+1)*c.aislePitch;for(const dz of [-c.carWidth*.38,c.carWidth*.38])this.box(end+1,.07,.06,(end+1)/2,y,z+dz,p.rail,group);this.box(end+1,.06,.06,(end+1)/2,y,z,p.steel,group);for(let b=0;b<c.bays;b++){const x=c.firstBay+b*c.bayPitch;this.box(.06,.05,c.carWidth+.3,x,y-.04,z,p.steel,group);for(const side of [-1,1])this.box(c.bayPitch*.9,.06,c.cargoWidth+.08,x,y+.07,z+side*shelfOffset,p.pad,group);}}
for(let n=0;n<=c.aisles;n++){const node=this.box(.28,.045,.28,0,y+.07,n*c.aislePitch,p.free,group);this.nodes.push({level:l,key:'F'+l+':N'+n,mesh:node});}
for(let i=0;i<c.layers[l].shuttles;i++){const car={level:l,local:i},pos=Model.park(c,car),feeder=pos.x/2;this.box(Math.abs(pos.x)/2,.04,.045,(pos.x+feeder)/2,y,pos.z,p.steel,group);if(i===0){const tail=Model.park(c,{level:l,local:c.layers[l].shuttles-1}).z;this.box(.045,.04,-tail,feeder,y,tail/2,p.steel,group);this.box(-feeder,.04,.045,feeder/2,y,0,p.steel,group);}const body=new T.Group();body.userData.actor='S'+(l+1)+'-'+(i+1);body.position.set(pos.x,pos.y,pos.z);this.scene.add(body);this.box(c.carLength,this.bodyHeight*.65,c.carWidth,0,this.bodyHeight*.45,0,p.deck,body);this.box(c.carLength*.8,.07,c.carWidth*.86,0,this.bodyHeight*.95,0,p.rail,body);this.box(c.carLength*.16,this.bodyHeight*.5,c.carWidth*.6,-c.carLength*.35,this.bodyHeight*.95,0,p.teal,body);for(let j=0;j<6;j++)this.box(c.carLength*.55,.035,.035,c.carLength*.08,this.bodyHeight*1.13,(j-2.5)*c.carWidth*.11,p.steel,body);
const wg=this.geo(new T.CylinderGeometry(this.bodyHeight*.23,this.bodyHeight*.23,.08,10));for(const x of [-.32,.32])for(const z of [-.48,.48]){const w=new T.Mesh(wg,p.dark);w.rotation.x=Math.PI/2;w.position.set(x*c.carLength,this.bodyHeight*.2,z*c.carWidth);body.add(w);}
this.addActor(body,'shuttle',l);}
const rows=slots.filter(s=>s.level===l),stockMesh=new T.InstancedMesh(this.unit,p.cargo,rows.length),dummy=new T.Object3D();rows.forEach((s,i)=>{dummy.position.set(s.x,y+this.bodyHeight+.1+c.cargoHeight/2,s.z+(s.side?1:-1)*shelfOffset);dummy.scale.set(0,0,0);dummy.updateMatrix();stockMesh.setMatrixAt(i,dummy.matrix);});group.add(stockMesh);this.stock.push({mesh:stockMesh,rows,shown:Array(rows.length).fill(null),offset:shelfOffset});const bufferLabel=this.label('입 0 / 출 0',-1,y+.8,-1.1,this.scene,11);bufferLabel.userData.level=l;this.levels[l].buffer=bufferLabel;this.box(1.8,.12,1.1,-.2,y+.1,-1.1,p.teal,group);}
for(let a=0;a<c.aisles;a++)for(const side of [-1,1])for(const x of [c.firstBay- c.bayPitch*.45,end+c.bayPitch*.45])this.box(.1,top,.1,x,top/2,(a+1)*c.aislePitch+side*(shelfOffset+c.cargoWidth*.48),p.steel);
for(let i=0;i<c.numLifts;i++){const pos=Model.liftPoint(c,i);for(const dx of [-.7,.7])for(const dz of [-.7,.7])this.box(.11,top+.8,.11,pos.x+dx,(top+.8)/2,pos.z+dz,p.steel);const body=new T.Group();body.position.set(pos.x,0,0);body.userData.actor='L'+(i+1);this.scene.add(body);this.box(c.cargoLength+.25,.15,c.cargoWidth+.25,0,.05,0,p.teal,body);this.addActor(body,'lift',null);}
this.groundLabel=this.label('지상 출고 0',-5,.8,-3,this.scene,12);this.box(2,.12,1.1,-5,-.05,-3,p.teal);}
addActor(body,kind,level){const T=root.THREE,c=this.config,id=body.userData.actor;const outlineMaterial=new T.MeshBasicMaterial({color:0x66ffcf,wireframe:true,transparent:true,opacity:.8});this.materials.push(outlineMaterial);const outline=this.box(kind==='lift'?c.cargoLength+.4:c.carLength*1.12,this.bodyHeight+.2,kind==='lift'?c.cargoWidth+.4:c.carWidth*1.14,0,.2,0,outlineMaterial,body);outline.visible=false;const label=this.label(id,0,this.bodyHeight+.75,0,body,11),cargo=this.box(c.cargoLength,c.cargoHeight,c.cargoWidth,0,0,0,this.palette.cargo);cargo.visible=false;this.actors.set(id,{body,label,cargo,outline,kind,level});if(!this.selected)this.selected=id;}
resize(){if(this.fallback||this.disposed)return;const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h||w===this.width&&h===this.height)return;this.width=w;this.height=h;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();if(this.mode!=='free')this.setView(this.mode);this.needsRender=true;}
setView(mode){this.mode=mode;if(this.fallback||this.disposed)return;const T=root.THREE,c=this.config,e=this.extent,focus=mode==='selected',item=this.actors.get(this.selected),center=focus?item.body.position.clone().add(new T.Vector3(0,.5,0)):new T.Vector3((e.minX+e.maxX)/2,this.level===null?e.top/2:Model.height(c,this.level),(e.minZ+e.maxZ)/2),wide=focus?6:e.maxX-e.minX+3,deep=focus?6:e.maxZ-e.minZ+3,size=Math.max(wide/Math.max(.4,this.camera.aspect),deep,focus?6:e.top*1.2,8);this.controls.target.copy(center);if(mode==='top')this.camera.position.copy(center).add(new T.Vector3(0,size*1.7,.001));else if(mode==='front')this.camera.position.copy(center).add(new T.Vector3(0,size*.18,size*1.7));else this.camera.position.copy(center).add(new T.Vector3(size*.85,size*.85,size*1.35));this.controls.update();this.lastRender=-Infinity;this.needsRender=true;}
select(id){if(!this.actors.has(id))return;this.selected=id;for(const[k,m]of this.actors)m.outline.visible=k===id;if(this.mode==='selected')this.setView('selected');this.lastTime=null;this.needsRender=true;}
setLevel(level){this.level=level===null?null:Number(level);if(this.fallback){this.lastFallback=null;return;}this.levels.forEach((f,i)=>{f.group.visible=this.level===null||this.level===i;f.label.visible=f.group.visible;f.buffer.visible=f.group.visible;});this.lastTime=null;if(this.mode!=='free')this.setView(this.mode);this.needsRender=true;}
setLabels(v){this.labelsVisible=v;this.needsRender=true;}
update(engine){if(!engine||this.disposed)return;this.engine=engine;if(this.fallback){if(this.lastFallback!==engine.time||this.lastEngine!==engine){this.container.dataset.renderer='fallback';this.container.innerHTML='<p class="fallback-note">WebGL을 사용할 수 없어 2D로 표시합니다. 계산은 계속됩니다.</p>'+root.ShuttleView.layout(this.config,engine.snapshot(),this.level??0);this.lastFallback=engine.time;this.lastEngine=engine;}return;}
this.resize();this.controls.update();const now=performance.now();if(now-this.lastRender<35)return;if(this.lastTime!==engine.time||this.lastEngine!==engine){const T=root.THREE,c=this.config,before=this.actors.get(this.selected)?.body.position.clone(),handling=new Set();
for(const actor of engine.actors){const m=this.actors.get(actor.id),p=engine.actorPose(actor),visible=m.level===null||this.level===null||this.level===m.level;m.body.visible=visible;m.body.position.set(p.x,p.y,p.z);m.body.userData.pose=p;m.cargo.visible=visible&&!!p.tu;m.outline.visible=actor.id===this.selected;
if(p.tu){let x=p.x,z=p.z,y=p.y+this.bodyHeight+.1+c.cargoHeight/2;const action=p.phase?.action,job=action?engine.jobById.get(action.job):null;if(job&&['store','retrieve'].includes(action.kind)){const offset=(Math.max(c.carWidth,c.cargoWidth)+c.cargoWidth)/2+c.gap/2,targetZ=job.slot.z+(job.slot.side?1:-1)*offset,progress=action.kind==='store'?p.progress:1-p.progress;z+=(targetZ-z)*progress;handling.add(job.tu);}if(actor.kind==='lift')y=p.y+.13+c.cargoHeight/2;m.cargo.position.set(x,y,z);}this.text(m.label,actor.id+(actor.id===this.selected?' · '+E.states[p.state]:''));}
const dummy=new T.Object3D();for(const stock of this.stock){let dirty=false;stock.rows.forEach((s,i)=>{const current=engine.slotById.get(s.id),visible=current.tu&&!handling.has(current.tu)?current.tu:null;if(stock.shown[i]===visible)return;stock.shown[i]=visible;dummy.position.set(s.x,s.y+this.bodyHeight+.1+c.cargoHeight/2,s.z+(s.side?1:-1)*stock.offset);dummy.scale.set(visible?c.cargoLength:0,visible?c.cargoHeight:0,visible?c.cargoWidth:0);dummy.updateMatrix();stock.mesh.setMatrixAt(i,dummy.matrix);dirty=true;});if(dirty)stock.mesh.instanceMatrix.needsUpdate=true;}
const reservations=new Map(engine.calendar.at(engine.time).map(r=>[r.key,r.owners]));for(const n of this.nodes)n.mesh.material=reservations.has(n.key)?this.palette.reserved:this.palette.free;for(let i=0;i<this.levels.length;i++){const f=engine.floors[i];this.text(this.levels[i].buffer,'입 '+f.ins.length+' / 출 '+f.outs.length+' · '+c.floorBuffer+'개');}this.text(this.groundLabel,'지상 출고 '+engine.output.length+'/'+c.outputBuffer);
if(this.follow&&this.mode==='selected'&&before){const delta=this.actors.get(this.selected).body.position.clone().sub(before);this.camera.position.add(delta);this.controls.target.add(delta);}this.lastTime=engine.time;this.lastEngine=engine;this.needsRender=true;}
if(this.needsRender&&this.width&&this.height){const T=root.THREE,boxes=[];this.scene.updateMatrixWorld(true);this.camera.updateMatrixWorld();for(const label of this.labels){const d=label.userData,hiddenLevel=d.level!==undefined&&this.level!==null&&this.level!==d.level;label.visible=this.labelsVisible&&!hiddenLevel&&label.parent.visible;if(!label.visible)continue;label.position.copy(d.anchor);label.updateMatrixWorld(true);const p=label.getWorldPosition(new T.Vector3()),depth=p.clone().applyMatrix4(this.camera.matrixWorldInverse).z,unit=Math.max(.001,-depth)*2*Math.tan(this.camera.fov*Math.PI/360)/this.height,h=unit*d.size*2.5;label.scale.set(h*8,h,1);const q=p.clone().project(this.camera),x=(q.x+1)*this.width/2,y=(1-q.y)*this.height/2,w=d.width/32*d.size;label.visible=q.z>=-1&&q.z<=1&&x-w/2>0&&x+w/2<this.width&&y>d.size&&y<this.height-d.size;if(label.visible){if(boxes.some(b=>Math.abs(b.x-x)<(b.w+w)/2+4&&Math.abs(b.y-y)<d.size+4))label.visible=false;else boxes.push({x,y,w});}}
this.renderer.render(this.scene,this.camera);this.lastRender=now;this.needsRender=false;}}
dispose(){this.disposed=true;this.observer?.disconnect();this.controls?.dispose();if(this.renderer){const canvas=this.renderer.domElement;canvas.removeEventListener('pointerdown',this.down);canvas.removeEventListener('pointerup',this.up);canvas.removeEventListener('webglcontextlost',this.lost);for(const a of this.geometries)a.dispose();for(const a of this.materials)a.dispose();for(const a of this.textures)a.dispose();this.renderer.dispose();this.renderer.forceContextLoss();}this.container.replaceChildren();}}
root.ShuttleScene={Scene};
})(globalThis);

