(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model'),require('./engine'));else root.ShuttleView=factory(root.ShuttleModel,root.ShuttleEngine);})(globalThis,function(Model,E){
'use strict';const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,n=1)=>v===null||!Number.isFinite(v)?'—':v.toLocaleString('ko-KR',{minimumFractionDigits:n,maximumFractionDigits:n});
const table=(heads,rows)=>'<div class="table-scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const kpi=(label,value,unit,note,featured=false)=>'<article class="kpi '+(featured?'featured':'')+'"><div class="kpi-label">'+esc(label)+'</div><div class="kpi-value">'+esc(value)+'<small>'+esc(unit)+'</small></div><p>'+esc(note)+'</p></article>';
const colors={idle:'#9aaeb8',route_wait:'#d79750',empty:'#6996af',loaded:'#169c8d',turn:'#b59b63',position:'#bbab8d',load:'#5c89ce',unload:'#927fb8',lift_move:'#51aab0',lift_load:'#72b8b1',lift_unload:'#659b88'};
function line(series,{xMax=1,xLabel='',yLabel='',height=250}={}){const W=1000,l=60,r=20,t=25,b=45,values=series.flatMap(s=>s.points.map(p=>p.y)).filter(Number.isFinite),lo=Math.min(0,...values),hi=Math.max(1,...values),px=x=>l+x/Math.max(1e-9,xMax)*(W-l-r),py=y=>height-b-(y-lo)/(hi-lo)*(height-t-b);let s='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+W+' '+height+'" role="img" aria-label="'+esc(yLabel)+'"><rect width="100%" height="100%" fill="white"/>';
for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4,y=py(v);s+='<path d="M'+l+' '+y+' H'+(W-r)+'" stroke="#e2eaee"/><text x="'+(l-8)+'" y="'+(y+4)+'" text-anchor="end" fill="#78909d" font-size="11">'+fmt(v)+'</text>';}for(let i=0;i<=5;i++)s+='<text x="'+px(xMax*i/5)+'" y="'+(height-23)+'" text-anchor="middle" fill="#78909d" font-size="11">'+fmt(xMax*i/5)+'</text>';
for(const a of series){const p=a.points.filter(p=>Number.isFinite(p.y));s+='<path d="'+p.map((q,i)=>(i?'L':'M')+px(q.x)+' '+py(q.y)).join(' ')+'" fill="none" stroke="'+a.color+'" stroke-width="2.5"/>';if(a.dots)for(const q of p)s+='<circle cx="'+px(q.x)+'" cy="'+py(q.y)+'" r="3" fill="'+a.color+'"/>';}
return s+'<text x="'+l+'" y="16" font-size="12" fill="#667f8e">'+esc(yLabel)+'</text><text x="'+(W-r)+'" y="'+(height-3)+'" text-anchor="end" font-size="11" fill="#667f8e">'+esc(xLabel)+'</text></svg>';}
function layout(c,s=null,level=0){const W=1080,H=460,end=c.firstBay+(c.bays-1)*c.bayPitch,deep=c.aisles*c.aislePitch,minX=Math.min(-9,Model.liftPoint(c,c.numLifts-1).x-2,Model.park(c,{level,local:0}).x-2),minZ=Math.min(-3,Model.park(c,{level,local:Math.max(0,c.layers[level].shuttles-1)}).z-1),scale=Math.min(900/(end-minX+3),310/(deep-minZ+3)),px=x=>80+(x-minX)*scale,pz=z=>70+(z-minZ)*scale;let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="4-way 셔틀 층별 레일과 저장 셀"><rect width="1080" height="460" rx="9" fill="#112e3d"/><text x="26" y="31" font-size="15" fill="#b8dddd">F'+(level+1)+' · X 통로 / Z 크로스레일 · '+c.bays+'베이 × '+c.aisles+'통로 × 양측</text>';
svg+='<path d="M'+px(0)+' '+pz(0)+' V'+pz(deep)+'" fill="none" stroke="#61c5bd" stroke-width="5"/>';
for(let a=0;a<c.aisles;a++){const z=(a+1)*c.aislePitch;svg+='<path d="M'+px(0)+' '+pz(z)+' H'+px(end+1)+'" stroke="#729eac" stroke-width="4"/><circle cx="'+px(0)+'" cy="'+pz(z)+'" r="5" fill="#e2b65d"/><text x="'+px(end+1.5)+'" y="'+(pz(z)+4)+'" font-size="11" fill="#b2c5cd">A'+(a+1)+'</text>';
for(let bay=0;bay<c.bays;bay++)for(const side of [-1,1]){const x=c.firstBay+bay*c.bayPitch,zz=z+side*(c.cargoWidth+c.carWidth)/2;svg+='<rect x="'+(px(x)-c.bayPitch*scale*.38)+'" y="'+(pz(zz)-scale*.24)+'" width="'+(c.bayPitch*scale*.76)+'" height="'+(scale*.48)+'" rx="1" fill="#375566"/>';}}
for(let i=0;i<c.numLifts;i++)svg+='<rect x="'+(px(-5-i*(c.cargoWidth+1))-10)+'" y="'+(pz(0)-10)+'" width="20" height="20" fill="#5bd0b1"/><text x="'+px(-5-i*(c.cargoWidth+1))+'" y="'+(pz(0)-17)+'" text-anchor="middle" font-size="10" fill="#b9dcd8">L'+(i+1)+'</text>';
const cars=s?.cars.filter(x=>x.level===level)||Array.from({length:c.layers[level].shuttles},(_,local)=>({...Model.park(c,{level,local}),id:'S'+(level+1)+'-'+(local+1),state:'idle'}));for(const car of cars)svg+='<g transform="translate('+px(car.x)+' '+pz(car.z)+')"><rect x="-8" y="-5" width="16" height="10" rx="2" fill="'+(colors[car.state]||'#63d8bd')+'"/><text y="-10" font-size="9" text-anchor="middle" fill="#d2ebea">'+esc(car.id)+'</text></g>';
return svg+'<text x="26" y="438" fill="#87a7b6" font-size="12">전체 '+c.levels+'층 · 저장 '+c.levels*c.aisles*c.bays*2+'셀 · 셔틀 '+c.layers.reduce((n,l)=>n+l.shuttles,0)+'대 · 화물 리프트 '+c.numLifts+'대</text></svg>';}
return{esc,fmt,table,kpi,colors,line,layout};
});

