// Browser runtime setup and troubleshooting completed: no connected browser is available.
'use strict';
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.STC_PLAYWRIGHT_PATH || path.join(os.tmpdir(), 'stc-depth-browser/node_modules/playwright'));
const Easy = require('../src/easy.js'), Model = require('../src/core/model.js');
const qa = path.resolve(__dirname, '../qa');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
  const passed = [], errors = [], network = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('request', r => { if (/^https?:/.test(r.url())) network.push(r.url()); });
  await page.route(/^https?:/, r => r.abort());
  const check = (name, ok) => { assert.ok(ok, name); passed.push(name); console.log('PASS ' + name); };
  const tab = async name => { await page.locator('.step[data-view=' + name + ']').click(); };
  const fill = async (key, value) => {
    const el = page.locator('#input-' + key); await el.evaluate(e => { if (e.closest('details')) e.closest('details').open = true; });
    await el.fill(String(value));
  };
  const apply = async () => { await page.locator('#calculate').click(); await page.waitForFunction(() => document.body.dataset.dirty === 'false' && !document.getElementById('results').hidden); };
  const inputFile = async (id, data) => page.locator('#' + id).setInputFiles({ name: 'test.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
  const download = async (id, name) => {
    const pending = page.waitForEvent('download'); await page.locator('#' + id).click();
    const d = await pending; const file = path.join(qa, name); await d.saveAs(file); return fs.readFileSync(file, 'utf8');
  };
  const capacity = async () => Number((await page.locator('.result-card.featured .metric-value').innerText()).replace(/,/g, '').match(/[\d.]+/)[0]);
  const noOverflow = () => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1);
  try {
    await page.goto(pathToFileURL(path.resolve(__dirname, '../../스태커크레인_간편실행.html')).href);
    check('basic inputs open first; parameters remain separate', await page.locator('#basic').isVisible() && !await page.locator('#parameters').isVisible());
    check('beginner defaults show m/min, 85% efficiency and 100% loaded performance', await page.locator('#input-vx').inputValue() === '180' && await page.locator('#summaryEfficiency').innerText() === '85%' && await page.locator('#summaryLoaded').innerText() === '100%');
    await page.screenshot({ path: path.join(qa, '01-basic-desktop.png'), fullPage: true });
    await apply(); const reference = Model.calculate(Easy.defaults);
    check('default calculation matches established model', await capacity() === Number(reference.available.toFixed(1)));
    check('SC/DC comparison and selected-operation distinction visible', (await page.locator('#cycleTable').innerText()).includes('사이클 시간') && (await page.locator('#cycleTable').innerText()).includes('효율 반영'));
    await page.screenshot({ path: path.join(qa, '02-results-desktop.png'), fullPage: true });
    await tab('parameters');
    await fill('control', '.25');
    check('parameters show changes and stale state', await page.locator('[data-field=control]').getAttribute('class').then(s => s.includes('modified')) && await page.locator('#stateBadge').innerText() === '입력 변경됨');
    await apply();
    check('shorter delay increases capacity with unchanged loaded ratio', await capacity() > Number(reference.available.toFixed(1)));
    check('previous input and throughput changes are explained', (await page.locator('#changeSummary').innerText()).includes('제어 지연') && (await page.locator('#changeSummary').innerText()).includes('0.5 → 0.25'));
    await tab('parameters'); await fill('loadedFactor', '50');
    check('loaded performance explains actual speed', (await page.locator('#loadedExplanation').innerText()).includes('90.00 m/min'));
    await page.screenshot({ path: path.join(qa, '03-parameters-desktop.png'), fullPage: true });
    await apply(); check('50% loaded performance reduces capacity', await capacity() < Number(reference.available.toFixed(1)));
    await tab('parameters'); await fill('operatingEfficiency', '.85'); await page.locator('#calculate').click();
    check('percent-vs-ratio error is clear and focuses input', (await page.locator('#error').innerText()).includes('1~100 %') && await page.locator('#input-operatingEfficiency').getAttribute('aria-invalid') === 'true');
    await fill('operatingEfficiency', '80'); await apply();
    const saved = JSON.parse(await download('saveProject', 'sample-project.json'));
    check('project stores SI values and full settings', saved.config.loadedFactor === .5 && saved.config.control === .25 && saved.config.operatingEfficiency === 80 && saved.config.vx === 3);
    await tab('parameters'); const preset = JSON.parse(await download('saveParameters', 'sample-parameters.json'));
    check('separate parameter file excludes basic geometry and demand', preset.schemaVersion === 'stc/easy-parameters@1' && !('length' in preset.parameters) && !('inbound' in preset.parameters));
    await tab('basic'); await fill('length', '75'); await fill('inbound', '30');
    await tab('parameters'); await fill('control', '-1'); await page.locator('#resetParameters').click();
    check('reset recovers invalid parameters while retaining basic inputs', await page.locator('#input-control').inputValue() === '0.5' && await page.locator('#input-length').inputValue() === '75' && await page.locator('#input-inbound').inputValue() === '30');
    await inputFile('parameterFile', preset); await page.waitForFunction(() => document.getElementById('input-control').value === '0.25');
    check('preset import retains geometry and restores parameter values', await page.locator('#input-length').inputValue() === '75' && await page.locator('#input-inbound').inputValue() === '30' && await page.locator('#input-loadedFactor').inputValue() === '50');
    await inputFile('parameterFile', { bad: true }); await page.waitForFunction(() => !document.getElementById('error').hidden);
    check('invalid parameter import leaves current settings intact', await page.locator('#input-loadedFactor').inputValue() === '50');
    await inputFile('projectFile', saved); await page.waitForFunction(() => !document.getElementById('results').hidden && document.getElementById('input-length').value === '60');
    check('project reload restores all basics and parameter state', await page.locator('#input-inbound').inputValue() === '20' && await page.locator('#input-operatingEfficiency').inputValue() === '80');
    await tab('basic'); await page.locator('#input-rackDepth').selectOption('double'); await tab('parameters'); await fill('rearStroke', '2.8'); await apply();
    await page.locator('.result-detail').evaluate(e => e.open = true);
    check('double-deep result doubles storage and exposes assumptions', (await page.locator('#storageCount').innerText()).includes('1,200') && (await page.locator('#calculationNotes').innerText()).includes('50:50'));
    await tab('parameters'); await page.locator('#group-method').evaluate(e => e.open = true); await page.locator('#input-method').selectOption('fem'); await page.locator('#input-femCase').selectOption('2'); await page.locator('#applyCase').click(); await apply();
    check('FEM CASE preset applies actual port coordinates', await page.locator('#input-outX').inputValue() === '60' && (await page.locator('#appliedParameters').innerText()).includes('FEM CASE 2'));
    const md = await download('saveMarkdown', 'sample-report.md'); check('Markdown report includes efficiency, depth and CASE', ['80% 직접 적용', '더블딥', 'CASE 2'].every(t => md.includes(t)));
    const popup = page.waitForEvent('popup'); await page.locator('#printReport').click(); const report = await popup; await report.waitForLoadState('domcontentloaded');
    check('print/PDF preview opens with correct applied efficiency', (await report.locator('body').innerText()).includes('80% 직접 적용'));
    check('print tables fit report', !await report.evaluate(() => [...document.querySelectorAll('table')].some(e => e.getBoundingClientRect().right > e.closest('section').getBoundingClientRect().right + 3)));
    await report.close();
    await inputFile('projectFile', Model.pack({ ...Easy.defaults, ports: [{ ioX: 2 }] })); await page.waitForFunction(() => !document.getElementById('error').hidden);
    check('unsupported complex legacy input is rejected explicitly', (await page.locator('#error').innerText()).includes('개별 포트'));
    await inputFile('projectFile', Easy.projectPack(Easy.defaults)); await page.waitForFunction(() => document.getElementById('input-rackDepth').value === 'single');
    check('desktop fits viewport', await noOverflow());
    await page.setViewportSize({ width: 390, height: 844 }); await tab('basic');
    check('mobile basic screen fits width', await noOverflow()); await page.screenshot({ path: path.join(qa, '04-basic-mobile.png'), fullPage: true });
    await tab('parameters'); check('mobile parameter controls fit width', await noOverflow()); await page.screenshot({ path: path.join(qa, '05-parameters-mobile.png'), fullPage: true });
    await apply(); check('mobile results fit width', await noOverflow()); await page.screenshot({ path: path.join(qa, '06-results-mobile.png'), fullPage: true });
    check('offline application has no browser errors or remote requests', errors.length === 0 && network.length === 0);
    fs.writeFileSync(path.join(qa, 'browser-results.json'), JSON.stringify({ checks: passed.length, passed, errors, network }, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
