(function(){'use strict';
const M=LiftModel,E=LiftEngine,I=LiftIO,$=id=>document.getElementById(id),esc=I.escape,f=(v,n=1)=>Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:n}):'—';
let p=M.preset(),previous=null,run=null,analysis=null,comparisons=[],worker=null,workerUrl=null,revision=0,playing=false,time=0,lastFrame=performance.now(),lastPaint=0;
const scene=new LiftScene($('scene'));
const enumFields={homeFloor:['시작/귀환 층',()=>p.floors.map(x=>[x.id,x.name])],parking:['귀환 방식',()=>[['stay','도착층 대기'],['home','매회 기준층 귀환']]],dispatch:['배차 방식',()=>[['fifo','오래된 요청 우선'],['nearest','가까운 출발층 우선']]],arrival:['요청 발생',()=>[['periodic','일정 간격'],['poisson','Poisson 무작위']]],demandMode:['수요 입력',()=>[['rates','OD · 시간대 물동량'],['history','실측 작업이력']]],speedUnit:['속도 표시',()=>[['m/min','m/min'],['m/s','m/s']]]};
const groups=[['프로젝트 · 운전',['name','moduleId','basis','lifts','homeFloor','parking','dispatch','arrival','demandMode','horizon','warmup','seed','speedUnit'],true],['플랫폼 · 적재',['platformLength','platformWidth','clearHeight','payload','maxBatch','cargoGap','batchWait'],false],['승강 속도 · 가감속',['loadedV','emptyV','loadedA','loadedD','emptyA','emptyD','upFactor','downFactor'],true],['도어 · 상하차 지연',['position','doorOpen','doorClose','interlock','control'],false],['설계 참고 계수',['availability','targetUtil'],false]];
const table=(heads,rows)=>'<table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
const options=(rows,value)=>rows.map(([v,n])=>'<option value="'+esc(v)+'"'+(v===value?' selected':'')+'>'+esc(n)+'</option>').join('');
function input(k,v,index,list,numeric=true,extra=''){return '<input data-list="'+list+'" data-i="'+index+'" data-k="'+k+'" '+(numeric?'type="number" step="any"':'type="text"')+' value="'+esc(v)+'" '+extra+'>';}function select(k,v,index,list,opts){return '<select data-list="'+list+'" data-i="'+index+'" data-k="'+k+'">'+options(opts,v)+'</select>';}function del(list,i){return '<button class="danger" data-delete="'+list+'" data-i="'+i+'">삭제</button>';}
function shown(k){if(M.fields[k]?.[1]==='speed')return p[k]*(p.speedUnit==='m/min'?60:1);if(['horizon','warmup'].includes(k))return p[k]/60;return p[k];}
function settings(){const open=new Set([...$('settings').querySelectorAll('details[open]')].map(x=>x.dataset.group));$('settings').innerHTML=groups.map(([title,keys,initial],index)=>'<details data-group="'+index+'" '+(open.size?open.has(String(index))?'open':'':initial?'open':'')+'><summary>'+title+'</summary><div class="fieldgrid">'+keys.map(k=>{if(enumFields[k])return '<label>'+enumFields[k][0]+'<select data-setting="'+k+'">'+options(enumFields[k][1](),p[k])+'</select></label>';if(!M.fields[k])return '<label class="full">'+({name:'프로젝트명',moduleId:'모듈 ID',basis:'사양·가정 근거'}[k])+(k==='basis'?'<textarea rows="3" data-setting="basis">'+esc(p.basis)+'</textarea>':'<input data-setting="'+k+'" value="'+esc(p[k])+'">')+'</label>';const q=M.fields[k],unit=q[1]==='speed'?p.speedUnit:q[1];return '<label>'+q[0]+' <span class="unit">'+unit+'</span><input type="number" step="any" data-setting="'+k+'" value="'+esc(Number.isFinite(shown(k))?Number(shown(k).toFixed(6)):'')+'"></label>';}).join('')+'</div></details>').join('');$('focusLift').innerHTML=options(Array.from({length:Math.max(1,Math.min(8,p.lifts||1))},(_,i)=>[String(i+1),'LIFT '+(i+1)]),$('focusLift').value||'1');}
function tables(){const fs=p.floors.map(x=>[x.id,x.id+' · '+x.name]),cs=p.cargo.map(x=>[x.id,x.name]);$('floorsTable').innerHTML=table(['층 ID','층명','높이 m','상차 s/개','하차 s/개','입력 버퍼','출력 버퍼','반출 s/개','연계 장비','연계 모듈 ID',''],p.floors.map((x,i)=>['<span class="id">'+esc(x.id)+'</span>',input('name',x.name,i,'floors',false),...['height','load','unload','inBuffer','outBuffer','takeaway'].map(k=>input(k,x[k],i,'floors')),select('peerType',x.peerType,i,'floors',[['none','없음'],['conveyor','컨베이어'],['stacker-crane','스태커크레인'],['rgv_linear','직선 RGV'],['rgv_loop','LOOP RGV'],['shuttle_4way','셔틀'],['agv_amr','AGV/AMR']]),input('peerId',x.peerId,i,'floors',false),del('floors',i)]));
 $('odTable').innerHTML=table(['OD ID','출발 층','도착 층','화물','물동량 개/h','우선순위','적재 상한',''],p.ods.map((x,i)=>({...x,i})).filter(x=>!$('activeOD').checked||x.rate>0||p.history.some(h=>h.flowId===x.id)).map(x=>['<span class="id">'+esc(x.id)+'</span>',select('from',x.from,x.i,'ods',fs),select('to',x.to,x.i,'ods',fs),select('cargoId',x.cargoId,x.i,'ods',cs),input('rate',x.rate,x.i,'ods'),input('priority',x.priority,x.i,'ods'),'<span>'+M.batchLimit(p,x)+' 개/회</span>',del('ods',x.i)]));
 $('cargoTable').innerHTML=table(['화물 ID','이름','형식','길이 m','폭 m','높이 m','중량 kg','색상',''],p.cargo.map((x,i)=>['<span class="id">'+esc(x.id)+'</span>',input('name',x.name,i,'cargo',false),select('kind',x.kind,i,'cargo',[['pallet','팔레트'],['box','박스'],['tote','토트']]),...['length','width','height','weight'].map(k=>input(k,x[k],i,'cargo')),input('color',x.color,i,'cargo',false),del('cargo',i)]));
 $('periodTable').innerHTML=table(['시작 min','종료 min','비율 %',''],p.periods.map((x,i)=>[input('start',x.start/60,i,'periods'),input('end',x.end/60,i,'periods'),input('factor',x.factor*100,i,'periods'),del('periods',i)]));$('stopTable').innerHTML=table(['리프트 번호','시작 min','종료 min',''],p.stops.map((x,i)=>[input('lift',x.lift,i,'stops'),input('start',x.start/60,i,'stops'),input('end',x.end/60,i,'stops'),del('stops',i)]));$('historyInfo').textContent='등록 '+p.history.length.toLocaleString()+'개 · '+(p.demandMode==='history'?'현재 작업이력 모드':'현재 OD 물동량 모드')+' · 엑셀 작업이력 시트에서도 편집할 수 있습니다.';}
function message(text){$('message').textContent=text;$('message').hidden=!text;}
function error(text){$('errors').textContent=text;$('errors').hidden=!text;}
function stopWorker(){if(worker)worker.terminate();if(workerUrl)URL.revokeObjectURL(workerUrl);worker=null;workerUrl=null;$('cancel').hidden=true;$('run').disabled=false;$('compare').disabled=false;$('compareAgain').disabled=false;}
function markDirty(rebuild=true){revision++;stopWorker();playing=false;run=null;comparisons=[];$('play').disabled=true;$('rewind').disabled=true;$('seek').disabled=true;$('play').textContent='재생';$('results').innerHTML='<p class="empty">입력이 변경되었습니다. 계산 · 시뮬레이션을 다시 실행하세요.</p>';$('comparison').innerHTML='개선안 비교를 실행하세요.';$('live').textContent='현재 입력의 배치 미리보기입니다. 계산 후 운전 이력을 재생할 수 있습니다.';const check=M.validate(p);error(check.errors.join('\n'));analysis=null;if(!check.errors.length){try{analysis=M.calculate(p);if(rebuild)scene.build(p,false);}catch(e){error(e.message);}}$('inputStatus').textContent=check.errors.length?'입력 '+check.errors.length+'개 항목 확인 필요':'입력 준비 · 실행 전';$('inputHelp').textContent='예제 기본값은 가정입니다. 현장 승인 사양으로 변경하세요.';$('subtitle').textContent=p.name+' · '+p.floors.length+'개 층 / '+p.lifts+'대 · 팔레트·박스·토트';kpis();}
function kpis(){const m=run?.metrics,vals=[['요구 물동량',analysis?f(analysis.total):'—','HU/h · 준비운전 제외 평균 수요',''],['해석 리프트 능력',f(analysis?.theory),'HU/h · 최대 적재 / 공차 근사',''],['후단 인계 처리량',f(m?.throughput),'HU/h · 시뮬레이션 측정 결과','accent'],['미투입 / 재공',m?m.backlog+' / '+m.wip:'—','개 · 운전 종료 시점','']];$('kpis').innerHTML=vals.map(([title,value,note,cl])=>'<div class="kpi '+cl+'"><span>'+title+'</span><strong>'+value+'</strong><small>'+note+'</small></div>').join('');}
function change(fn,{full=false,fit=false}={}){previous=M.clone(p);fn();markDirty();if(full){settings();tables();}if(fit&&analysis)scene.fit();}
function replace(next,text){document.activeElement?.blur();previous=M.clone(p);p=next;settings();tables();markDirty();if(analysis)scene.fit();message(text);}
function hourly(){const old=M.clone(p.periods);p.periods=[];for(let start=0;start<p.horizon;start+=3600){const end=Math.min(p.horizon,start+3600);let weighted=0,covered=0;for(const b of old){const span=Math.max(0,Math.min(end,b.end)-Math.max(start,b.start));weighted+=span*b.factor;covered+=span;}p.periods.push({start,end,factor:(weighted+(end-start-covered))/(end-start)});}}
function nextId(rows,prefix){let i=1;while(rows.some(x=>x.id===prefix+i))i++;return prefix+i;}
function tab(name){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id==='tab-'+name));if(name==='scene')scene.resize();}
function download(name,data,mime='application/json'){const blob=data instanceof Blob?data:new Blob([data],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){error(e.message);}};}
function requireRun(){if(!run)throw Error('현재 입력으로 시뮬레이션을 먼저 실행하세요.');return run;}
function start(type){const check=M.validate(p);if(check.errors.length){error(check.errors.join('\n'));return;}stopWorker();error('');playing=false;const rev=revision;workerUrl=URL.createObjectURL(new Blob([LIFT_WORKER_SOURCE],{type:'text/javascript'}));worker=new Worker(workerUrl);$('cancel').hidden=false;$('run').disabled=true;$('compare').disabled=true;$('compareAgain').disabled=true;$('inputStatus').textContent=type==='run'?'시뮬레이션 계산 중':'7개 개선안 계산 중';worker.onmessage=({data})=>{if(rev!==revision)return;if(data.type==='progress')$('inputHelp').textContent=Math.round(data.value*100)+'% 완료';else if(data.type==='error'){stopWorker();error(data.message);$('inputStatus').textContent='계산 중단';}else if(data.type==='result'){stopWorker();run=data.run;analysis=M.calculate(p);scene.setRun(run);time=0;$('seek').max=p.horizon;$('seek').value=0;$('seek').disabled=false;$('play').disabled=false;$('rewind').disabled=false;$('inputStatus').textContent='계산 완료 · 화물 보존 '+(run.metrics.conservation?'일치':'오류');$('inputHelp').textContent='후단 인계 '+run.metrics.totalCompleted+'개 / 요청 '+run.metrics.generated+'개 · 결과 해시 '+run.configHash;kpis();renderResults();paint();message('계산이 완료되었습니다. 재생을 누르거나 시간 막대를 움직여 운전 상태를 확인하세요.');}else if(data.type==='compare'){stopWorker();comparisons=data.rows;renderComparison();tab('results');$('inputStatus').textContent='개선안 비교 완료';$('inputHelp').textContent='단일 시드의 7개 조건 비교입니다. 최적해 또는 성능 보증을 의미하지 않습니다.';}};worker.onerror=e=>{stopWorker();error('계산 작업 오류: '+e.message);};worker.postMessage({type,config:M.clone(p)});}
function renderResults(){const m=run.metrics,a=analysis;const taskRates=table(['화물','측정완료','처리량 개/h'],m.byCargo.map(c=>[esc(c.name),c.completed,f(c.rate)]));const stats=table(['지표','결과'],[['측정시간',f(m.measuredSeconds/60)+' min'],['총 요청 / 총 최종 인계',m.generated+' / '+m.totalCompleted],['측정 구간 최종 인계',m.completed+' 개'],['리프트 하차 처리량',f(m.liftThroughput)+' HU/h'],['미투입 / 입력 / 탑승 / 출력',m.backlog+' / '+m.input+' / '+m.onboard+' / '+m.output],['평균 대기 / 평균 리드타임',f(m.meanWait)+' / '+f(m.meanLead)+' s'],['P95 리드타임',f(m.p95Lead)+' s'],['평균 재공 / 평균 미투입',f(m.meanWip)+' / '+f(m.meanBacklog)+' 개']] );
 $('results').innerHTML='<div class="toolbar"><button id="downloadResult">결과 CSV</button><button id="downloadJobs">화물별 운전이력 CSV</button><button id="downloadReport2">보고서 저장</button><span class="badge">화물 보존 '+(m.conservation?'일치':'오류')+'</span></div><div class="reportgrid"><div class="panel"><h3>실제 운전 결과</h3>'+stats+'</div><div class="panel"><h3>화물별 인계 처리량</h3>'+taskRates+'<h3 style="margin-top:20px">대기 물량 추이</h3><canvas class="chart" id="queueChart"></canvas></div></div><div class="sectionhead"><div><h2>리프트별 운전 점유</h2><p>작업 / 자원·출구 차단 / 계획정지 / 유휴. 준비운전을 제외한 시간 비율입니다.</p></div></div><div class="tablewrap">'+table(['리프트','점유 분포','작업','차단','정지','공차 이동','출발 횟수'],m.carRows.map(c=>[c.id,'<div class="bar"><span style="width:'+c.working*100+'%;background:#11978e"></span><span style="width:'+c.blocked*100+'%;background:#d8a340"></span><span style="width:'+c.down*100+'%;background:#ca6565"></span></div>',f(c.working*100)+'%',f(c.blocked*100)+'%',f(c.down*100)+'%',f(c.empty*100)+'%',c.trips]))+'</div><div class="sectionhead"><div><h2>층별 버퍼</h2><p>입력은 상차가 끝날 때 공간을 해제합니다. 출력 최대치는 하차 예약 공간을 포함합니다.</p></div></div><div class="tablewrap">'+table(['층','종료 입력','평균 입력','최대 입력','종료 출력','평균 출력','최대 출력(예약 포함)','미투입'],m.floorRows.map(x=>[esc(x.id),x.input,f(x.meanInput),x.maxInput,x.output,f(x.meanOutput),x.maxOutput,x.backlog]))+'</div><div class="sectionhead"><div><h2>OD별 결과</h2></div></div><div class="tablewrap">'+table(['OD','출발 → 도착','화물','요청','측정 완료','HU/h','종료 미완료','평균 리드타임 s'],m.odRows.filter(o=>o.generated).map(o=>[esc(o.id),esc(o.from+' → '+o.to),esc(o.cargoId),o.generated,o.completed,f(o.rate),o.unfinished,f(o.meanLead)]))+'</div><div class="reportgrid"><div class="panel"><h3>해석 참고값</h3>'+table(['항목','값'],[['리프트 능력 / 가용도 보정',f(a.theory)+' / '+f(a.corrected)+' HU/h'],['고정 OD 혼합 라인 상한',f(a.lineUpper)+' HU/h'],['해석 병목',esc(a.bottleneck)],['참고 필요 대수',a.required+' 대 (목표 '+f(p.targetUtil*100)+'%)'],['평균 사이클 / 적재',f(a.cycle)+' s / '+f(a.meanBatch)+' 개'],['공차 모델',esc(a.reference)]])+'</div><div class="panel"><h3>결과 해석</h3><p class="note">낮은 수요에서 관측한 처리량은 설비의 최대 능력이 아닙니다. 해석은 최대 적재와 독립 OD 공차 근사를 쓰며, 실제 부분 적재·FIFO·버퍼 정체에 따라 결과가 달라집니다.</p><p class="note">리프트 하차 완료와 후단 인계 완료를 구분합니다. 출력 버퍼에서 반출 중인 화물도 재공에 포함합니다. 총 요청 = 총 최종 인계 + 미투입 + 입력 + 탑승 + 출력.</p><p class="note">필요 대수는 리프트 작업량 기준이며 공용 상하차부·후단 반출 병목은 대수를 늘려도 해결되지 않을 수 있습니다.</p></div></div>';
 $('downloadResult').onclick=safe(()=>download('리프트_계산결과.csv',I.resultCSV(run,analysis),'text/csv;charset=utf-8'));$('downloadJobs').onclick=safe(()=>download('리프트_운전이력.csv',I.jobsCSV(run),'text/csv;charset=utf-8'));$('downloadReport2').onclick=$('saveReport').onclick;setTimeout(drawChart,0);
}
function drawChart(){const canvas=$('queueChart');if(!canvas||!run)return;const w=canvas.clientWidth||400,h=210,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const ss=run.samples,max=Math.max(5,...ss.map(s=>Math.max(s.wip,s.backlog))),left=34,right=w-10,top=25,bottom=h-28;c.strokeStyle='#dfe9ed';c.fillStyle='#88a0ad';c.font='10px Segoe UI';for(let i=0;i<=4;i++){const y=bottom-(bottom-top)*i/4;c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.stroke();c.fillText(f(max*i/4,0),2,y+3);}for(const [key,color,label,offset]of [['wip','#12978c','재공',40],['backlog','#d6a044','미투입',115]]){c.strokeStyle=color;c.lineWidth=2;c.beginPath();ss.forEach((s,i)=>{const x=left+(right-left)*s.time/run.time,y=bottom-(bottom-top)*s[key]/max;if(i)c.lineTo(x,y);else c.moveTo(x,y);});c.stroke();c.fillStyle=color;c.fillText(label,offset,13);}c.fillStyle='#7b929f';c.fillText('0',left,bottom+17);c.fillText(f(run.time/60)+' min',right-50,bottom+17);}
function renderComparison(){const good=comparisons.filter(r=>r.valid);good.sort((a,b)=>b.throughput-a.throughput||(a.p95??Infinity)-(b.p95??Infinity)||a.backlog-b.backlog);const best=good[0];$('comparison').className='tablewrap';$('comparison').innerHTML=table(['검토안','HU/h','P95 s','미투입','재공','차단비율','적용'],comparisons.map((r,i)=>[esc(r.name)+(r===best?' <span class="badge">이번 비교 최고</span>':''),r.valid?f(r.throughput):'입력 범위 초과',f(r.p95),r.backlog??'—',r.wip??'—',r.valid?f(r.blocked*100)+'%':'—',r.valid?'<button data-apply="'+i+'">이 조건 적용</button>':esc(r.errors.join('; '))]));}
function clock(t){const m=Math.floor(t/60),s=Math.floor(t%60);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
function paint(){const snap=scene.show(time);$('clock').textContent=clock(time)+' / '+clock(p.horizon);$('seek').value=time;if(snap){$('live').innerHTML=snap.poses.map(c=>'<span><b>LIFT '+c.id+'</b> '+esc(E.stateNames[c.state])+' · '+f(c.y,2)+' m · '+f(Math.abs(c.v)*(p.speedUnit==='m/min'?60:1),2)+' '+p.speedUnit+'</span>').join('')+'<span>'+snap.floors.map(x=>'<b>'+esc(x.id)+'</b> 입력 '+x.input.length+' / 출력 '+x.output.length+' / 미투입 '+x.outside).join('　')+'</span>';}else if(run){$('live').textContent='3D가 지원되지 않아 계산 결과만 제공합니다. 결과 · 개선안 탭에서 확인하세요.';}}
function animate(now){const dt=Math.min(.2,(now-lastFrame)/1000);lastFrame=now;if(playing&&run){time=Math.min(run.time,time+dt*Number($('playSpeed').value));if(time>=run.time){playing=false;$('play').textContent='재생';}if(now-lastPaint>33){lastPaint=now;paint();}}else if(scene.ready)scene.controls.update();requestAnimationFrame(animate);}
function help(){ $('help').innerHTML='<div class="helpgrid"><div class="panel"><h2>시작하기</h2><ol><li>왼쪽에서 예제를 고르고 플랫폼·승강 사양을 입력합니다.</li><li>층 · OD에서 층 높이, 상하차 시간, 버퍼, 층간 물동량을 입력합니다.</li><li>운반물 치수·중량과 필요 시 시간대 비율·계획 정지를 설정합니다.</li><li>계산 · 시뮬레이션 실행 후 재생하거나 시간 막대를 이동합니다.</li><li>결과의 미투입·차단·P95와 개선안을 비교하고 엑셀/JSON/보고서로 저장합니다.</li></ol></div><div class="panel"><h2>적용 운전 방식</h2><p>독립 승강로 1~8대, 2~20층. 모든 리프트는 같은 사양이며 모든 층을 운행합니다. 화물의 자중은 화물 허용하중과 비교하며 캐리어 중량을 다시 더하지 않습니다.</p><p>공차 접근 → 도어 열림 → 상차 → 도어 닫힘·인터록 → 적재 승강 → 도어 열림 → 하차 → 닫힘. 이동 후 정위치 시간도 별도로 포함합니다.</p><p>각 층의 입력·출력 이재부는 서로 다른 공용 자원입니다. 입력 FIFO와 출력 공간 제약을 지킵니다. 매회 기준층 귀환은 새 작업이 있어도 귀환을 완료합니다.</p></div><div class="panel"><h2>승강 시간 계산</h2><div class="formula">v_peak = min(v, √(2H / (1/a + 1/d)))<br>t = v_peak/a + t_cruise + v_peak/d<br>Q = 3600 × 리프트 대수 × 평균 적재 / 평균 사이클</div><p>짧은 층간 이동은 삼각형, 충분히 긴 이동은 사다리꼴 속도곡선입니다. 적재·공차, 상승·하강 속도를 구분합니다.</p></div><div class="panel"><h2>해석과 시뮬레이션</h2><p>해석 능력은 현재 OD 혼합 및 최대 적재 기준입니다. 도착층 대기의 공차는 이전 OD와 다음 OD를 독립적으로 섞은 근사입니다.</p><p>시뮬레이션은 실제 요청마다 배차·대기·부분 적재·버퍼·정지를 계산합니다. 해석용 가용도는 운전 결과에 다시 곱하지 않습니다. 지연된 화물도 삭제하지 않고 미투입/재공으로 남깁니다.</p><p>리드타임은 요청부터 후단 인계까지입니다. 준비운전 이후 완료한 화물을 집계하며, 준비운전 중 요청한 화물도 해당하면 포함됩니다.</p></div><div class="panel"><h2>엑셀과 프로그램 연동</h2><p>엑셀 8개 시트에 전체 조건을 저장합니다. 단위는 기본 속도 m/min, 기본 시간·시간대·정지 min, 이력 s입니다. 시트명·키·열 제목을 유지하고 확정 값을 입력하세요. 수식·매크로는 실행하지 않습니다.</p><p>통합 연동 JSON에는 층 포트 ID, 버퍼, SI 단위 설정, 화물 ID, 인계 이벤트가 포함됩니다. 기존 6종 장비와의 공통 시계 동시 운전은 별도 어댑터 연결 단계입니다.</p></div><div class="panel"><h2>현재 모델의 범위</h2><p>왕복식 캐리어 한 개/승강로, 같은 OD만 동시 적재. 혼합 목적지 중간 정차, 복층 캐리어, 연속식 수직 컨베이어, 동일 승강로 차량 간섭은 포함하지 않습니다.</p><p>저크·전력·구조·안전 인증 설계는 계산하지 않습니다. 정지표는 현재 위상에서 즉시 멈추고 재개하는 근사입니다. 운반물·플랫폼·도어는 치수 기반 개념 3D 모델입니다.</p></div><div class="panel wide"><h2>제조사 1차 자료 · 확인 2026-09-16</h2><p>기본 입력값은 제조사 특정 모델의 성능 보증값이 아닌 설명용 가정입니다. 실제 승인 사양서의 속도·가감속·이재시간으로 교체하세요.</p><ul>'+M.sources.map(s=>'<li><a target="_blank" rel="noopener" href="'+s.url+'">'+esc(s.title)+'</a> — '+esc(s.note)+'</li>').join('')+'</ul><p>Qimarox mk9의 제품 화물 하중 표기와 FAQ의 캐리어 포함 하중을 구분했습니다. 제품 페이지의 상충하는 처리량 수치를 그대로 기본 능력으로 입력하지 않고, 이동·이재 시간에서 계산하도록 구성했습니다.</p></div></div>';}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab(b.dataset.tab);if(b.dataset.tab==='results')setTimeout(drawChart,0);});
$('settings').addEventListener('change',e=>{const k=e.target.dataset.setting;if(!k)return;change(()=>{let value=e.target.value;if(M.fields[k]){value=value.trim()===''?NaN:Number(value);if(M.fields[k][1]==='speed'&&p.speedUnit==='m/min')value/=60;if(['horizon','warmup'].includes(k))value*=60;}p[k]=value;if(k==='horizon'&&p.periods.length&&Number.isFinite(value)&&value>=60&&value<=86400)hourly();},{full:['speedUnit','lifts','homeFloor','horizon','demandMode'].includes(k)});});
document.querySelector('main').addEventListener('change',e=>{const {list,i,k}=e.target.dataset;if(!list||i===undefined||!k)return;change(()=>{let v=e.target.type==='number'?(e.target.value.trim()===''?NaN:Number(e.target.value)):e.target.value;if(['periods','stops'].includes(list)&&['start','end'].includes(k))v*=60;if(list==='periods'&&k==='factor')v/=100;p[list][Number(i)][k]=v;},{full:false});if(['floors','cargo','ods'].includes(list))tables();});
document.querySelector('main').addEventListener('click',safe(e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.delete){const list=b.dataset.delete,i=Number(b.dataset.i),row=p[list][i];if(list==='floors'){if(p.floors.length<=2)throw Error('층은 최소 2개가 필요합니다.');const ids=p.ods.filter(o=>o.from===row.id||o.to===row.id).map(o=>o.id);if(p.history.some(h=>ids.includes(h.flowId)))throw Error('이 층의 OD를 참조하는 작업이력이 있습니다. 이력을 수정한 후 삭제하세요.');change(()=>{p.floors.splice(i,1);p.ods=p.ods.filter(o=>!ids.includes(o.id));if(p.homeFloor===row.id)p.homeFloor=p.floors[0].id;},{full:true});message('층과 연결 OD '+ids.length+'행을 삭제했습니다. 입력 변경 되돌리기로 복원할 수 있습니다.');}else if(list==='cargo'){if(p.ods.some(o=>o.cargoId===row.id))throw Error('OD에서 사용 중인 화물입니다. OD 화물 유형을 먼저 바꾸세요.');change(()=>p.cargo.splice(i,1),{full:true});}else{if(list==='ods'&&p.history.some(h=>h.flowId===row.id))throw Error('작업이력이 참조하는 OD입니다. 이력을 먼저 수정하세요.');change(()=>p[list].splice(i,1),{full:true});}}if(b.dataset.apply!==undefined){const r=comparisons[Number(b.dataset.apply)];if(!r?.valid)return;replace(M.clone(r.config),'개선안 '+r.name+'을 입력에 적용했습니다. 다시 실행하여 확인하세요.');}}));
$('loadPreset').onclick=()=>replace(M.preset($('preset').value),'예제 조건을 적용했습니다. 기본값은 설명용 가정입니다.');$('undo').onclick=()=>{if(!previous)return;const next=previous;previous=M.clone(p);p=next;settings();tables();markDirty();message('이전 입력 상태로 되돌렸습니다.');};
$('addFloor').onclick=safe(()=>{if(p.floors.length>=20)throw Error('최대 20층입니다.');change(()=>{p.floors.push(M.floor(nextId(p.floors,'F'),Math.max(...p.floors.map(x=>x.height))+4));p.ods=M.autoOD(p);},{full:true,fit:true});message('신규 층간 OD를 물동량 0으로 생성했습니다.');});$('autoOD').onclick=()=>{change(()=>p.ods=M.autoOD(p),{full:true});message('기존 OD를 유지하고 빠진 층간 조합을 물동량 0으로 추가했습니다.');};$('addOD').onclick=()=>change(()=>p.ods.push({id:nextId(p.ods,'OD'),from:p.floors[0].id,to:p.floors[1].id,cargoId:p.cargo[0].id,rate:0,priority:1}),{full:true});$('activeOD').onchange=tables;
$('addCargo').onclick=()=>change(()=>p.cargo.push({...M.clone(M.cargoDefaults[1]),id:nextId(p.cargo,'C'),name:'추가 화물'}),{full:true});$('autoPeriods').onclick=()=>change(hourly,{full:true});$('addPeriod').onclick=()=>change(()=>p.periods.push({start:p.periods.at(-1)?.end??0,end:p.horizon,factor:1}),{full:true});$('clearPeriods').onclick=()=>change(()=>p.periods=[],{full:true});$('addStop').onclick=()=>change(()=>p.stops.push({lift:1,start:Math.min(600,p.horizon/3),end:Math.min(900,p.horizon*2/3)}),{full:true});
$('loadJson').onclick=()=>$('fileJson').click();$('loadExcel').onclick=()=>$('fileExcel').click();$('loadHistory').onclick=()=>$('fileHistory').click();for(const [id,parse]of [['fileJson',async file=>M.unpack(JSON.parse(await file.text()))],['fileExcel',file=>I.readXlsx(file)],['fileHistory',async file=>I.importHistory(await file.text(),p)]])$(id).onchange=safe(async()=>{const file=$(id).files[0];$(id).value='';if(!file)return;if(file.size>10*1024*1024)throw Error('파일 크기는 10 MB 이하여야 합니다.');const next=await parse(file);replace(next,file.name+' 입력을 적용했습니다.');});
$('saveJson').onclick=safe(()=>download('리프트_프로젝트.json',JSON.stringify(M.pack(p),null,2)));$('saveExcel').onclick=safe(()=>download('리프트_입력조건.xlsx',I.writeXlsx(p),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));$('saveReport').onclick=safe(()=>{requireRun();download('리프트_검토보고서.html',I.report(run,analysis),'text/html;charset=utf-8');});$('savePorts').onclick=safe(()=>{requireRun();download('리프트_통합연동.json',JSON.stringify(I.interfaceData(run),null,2));});$('saveHistory').onclick=()=>download('리프트_작업이력.csv',I.historyCSV(p),'text/csv;charset=utf-8');$('clearHistory').onclick=()=>change(()=>{p.history=[];p.demandMode='rates';},{full:true});
$('run').onclick=safe(()=>start('run'));$('compare').onclick=$('compareAgain').onclick=safe(()=>start('compare'));$('cancel').onclick=()=>{stopWorker();$('inputStatus').textContent='계산 취소';$('inputHelp').textContent='입력은 유지됩니다.';};$('play').onclick=()=>{if(!run)return;if(time>=run.time)time=0;playing=!playing;$('play').textContent=playing?'일시정지':'재생';paint();};$('rewind').onclick=()=>{playing=false;time=0;$('play').textContent='재생';paint();};$('seek').oninput=()=>{playing=false;time=Number($('seek').value);$('play').textContent='재생';paint();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>scene.fit(b.dataset.view));$('focus').onclick=()=>scene.focus(Number($('focusLift').value));
settings();tables();help();markDirty();scene.fit();requestAnimationFrame(animate);window.addEventListener('resize',drawChart);
// Read-only inspection hooks also allow downstream integration to discover the plugin.
window.LiftApp={get config(){return M.clone(p);},get run(){return run;},get analysis(){return analysis;},get comparisons(){return comparisons;},scene,plugin:I.plugin};
})();
