(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model'):root.LiftModel,typeof module==='object'&&module.exports?require('./motion'):root.LiftMotion);if(typeof module==='object'&&module.exports)module.exports=api;else root.LiftEngine=api;})(globalThis,function(M,Motion){
'use strict';const EPS=1e-8;
class Heap{constructor(){this.a=[];this.seq=0;}get peek(){return this.a[0];}push(t,type,data){const e={t,type,data,seq:this.seq++};let i=this.a.length;this.a.push(e);while(i){const p=(i-1)>>1;if(!Heap.less(e,this.a[p]))break;this.a[i]=this.a[p];i=p;}this.a[i]=e;}static less(a,b){return a.t<b.t||a.t===b.t&&a.seq<b.seq;}pop(){const top=this.a[0],last=this.a.pop();if(this.a.length){let i=0;while(i*2+1<this.a.length){let j=i*2+1;if(j+1<this.a.length&&Heap.less(this.a[j+1],this.a[j]))j++;if(!Heap.less(this.a[j],last))break;this.a[i]=this.a[j];i=j;}this.a[i]=last;}return top;}}
function rng(seed){let x=seed>>>0;return()=>{x=(x+0x6D2B79F5)>>>0;let t=Math.imul(x^x>>>15,1|x);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
function intervals(rows){const out=[];for(const s of rows.slice().sort((a,b)=>a.start-b.start)){const p=out.at(-1);if(p&&s.start<=p.end)p.end=Math.max(p.end,s.end);else out.push({start:s.start,end:s.end});}return out;}
function activeAt(t,stops){for(const s of stops)if(t>=s.start-EPS&&t<s.end-EPS)return s.end;return t;}
function activeAdd(t,d,stops){if(!d)return t;let start=t;for(const s of stops){if(s.end<=start+EPS)continue;if(start<s.start){const span=s.start-start;if(d<=span+EPS)return start+d;d-=span;}start=Math.max(start,s.end);}return start+d;}
function activeElapsed(a,b,stops){return Math.max(0,b-a-stops.reduce((n,s)=>n+Math.max(0,Math.min(b,s.end)-Math.max(a,s.start)),0));}
function releases(p){if(p.demandMode==='history')return p.history.map(h=>({id:h.id,t:h.release,flowId:h.flowId})).sort((a,b)=>a.t-b.t);const out=[],random=rng(p.seed);let serial=0;for(const o of p.ods){if(!o.rate)continue;const step=()=>p.arrival==='periodic'?3600/o.rate:-Math.log(Math.max(1e-12,1-random()))*3600/o.rate;let budget=p.arrival==='periodic'?0:step();for(const b of M.bands(p)){if(!b.factor)continue;let t=b.start;while(t<b.end-EPS){const available=(b.end-t)*b.factor;if(budget>=available-EPS){budget=Math.max(0,budget-available);break;}t+=budget/b.factor;if(t<p.horizon-EPS)out.push({id:'J'+String(++serial).padStart(6,'0'),t,flowId:o.id});if(out.length>30000)throw Error('실제 요청 30,000개 한도 초과');budget=step();}}}return out.sort((a,b)=>a.t-b.t);}
const stateNames={idle:'대기',control:'배차',empty:'공차 이동',positionLoad:'상차층 정위치',waitLoad:'상차부 대기',openLoad:'상차 도어 열림',loading:'상차',closeLoad:'상차 도어 닫힘/인터록',loaded:'적재 승강',positionUnload:'하차층 정위치',waitOut:'출구 공간/이재부 대기',openUnload:'하차 도어 열림',unloading:'하차',closeUnload:'하차 도어 닫힘/인터록',returning:'기준층 귀환',positionReturn:'귀환 정위치',stopped:'계획 정지'};
class Simulation{
 constructor(input){const v=M.validate(input);if(v.errors.length)throw Error(v.errors.join('\n'));this.p=M.clone(input);this.time=0;this.heap=new Heap();this.events=[];this.items=[];this.samples=[];this.eventCount=0;this.wakes=new Set();this.od=new Map(this.p.ods.map(o=>[o.id,o]));this.floors=new Map(this.p.floors.map(f=>[f.id,{...f,external:[],queue:[],inputCount:0,output:[],reservedOut:0,loadCar:null,unloadCar:null,takeBusy:false,maxInput:0,maxOutput:0}]));const home=this.floors.get(this.p.homeFloor).height;this.cars=Array.from({length:this.p.lifts},(_,i)=>({id:i+1,y:home,state:'idle',jobs:[],segments:[{start:0,end:null,state:'idle',from:home,to:home,jobIds:[]}],stops:intervals(this.p.stops.filter(s=>s.lift===i+1))}));for(const c of this.cars)for(const s of c.stops){this.heap.push(s.start,'wake');this.heap.push(s.end,'wake');}for(const r of releases(this.p))this.heap.push(r.t,'arrival',r);for(let t=0;t<=this.p.horizon;t+=Math.max(1,this.p.horizon/360))this.heap.push(t,'sample');}
 wake(t){if(t>this.time+EPS&&t<=this.p.horizon&&!this.wakes.has(t)){this.wakes.add(t);this.heap.push(t,'wake',t);}}
 closeSegment(car,t){const s=car.segments.at(-1);if(s&&s.end===null)s.end=t;}
 wait(car,state,t){this.closeSegment(car,t);car.state=state;car.segments.push({start:t,end:null,state,from:car.y,to:car.y,jobIds:car.jobs.map(j=>j.id)});}
 phase(car,state,duration,t,to=car.y,profile=null){this.closeSegment(car,t);const end=activeAdd(t,duration,car.stops),s={start:t,end,state,from:car.y,to,profile,jobIds:car.jobs.map(j=>j.id)};car.segments.push(s);car.state=state;this.heap.push(end,'phase',{car:car.id,state,to});}
 move(car,state,to,t,loaded){const q=M.motion(this.p,car.y,to,loaded);this.phase(car,state,q.duration,t,to,q);}
 startTrip(car,jobs,t){car.jobs=jobs;car.origin=jobs[0].from;car.dest=jobs[0].to;for(const j of jobs){j.assignedAt=t;j.lift=car.id;}this.events.push({time:t,type:'DISPATCH',lift:car.id,jobIds:jobs.map(j=>j.id),from:car.origin,to:car.dest});this.phase(car,'control',this.p.control,t);}
 process(e){const t=e.t,p=this.p;if(e.type==='wake'){this.wakes.delete(e.data);return;}if(e.type==='arrival'){const o=this.od.get(e.data.flowId),j={id:e.data.id,flowId:o.id,from:o.from,to:o.to,cargoId:o.cargoId,priority:o.priority,release:t,acceptedAt:null,assignedAt:null,loadStart:null,loadedAt:null,unloadStart:null,deliveredAt:null,completedAt:null,lift:null};this.items.push(j);this.floors.get(j.from).external.push(j);this.events.push({time:t,type:'REQUEST',cargoId:j.id,flowId:j.flowId});return;}
 if(e.type==='takeaway'){const f=this.floors.get(e.data),j=f.output.shift();j.completedAt=t;f.takeBusy=false;this.events.push({time:t,type:'HANDOFF_COMPLETE',cargoId:j.id,cargoType:j.cargoId,flowId:j.flowId,floor:j.to,lift:j.lift});return;}
 if(e.type!=='phase')return;const car=this.cars[e.data.car-1],s=e.data.state;car.y=e.data.to;const a=this.floors.get(car.origin),b=this.floors.get(car.dest),jobs=car.jobs;
 if(s==='control')this.move(car,'empty',a.height,t,false);
 else if(s==='empty')this.phase(car,'positionLoad',car.segments.at(-1).profile.length>EPS?p.position:0,t);
 else if(s==='positionLoad')this.wait(car,'waitLoad',t);
 else if(s==='openLoad'){for(const j of jobs)j.loadStart=t;this.phase(car,'loading',a.load*jobs.length,t);}
 else if(s==='loading'){for(const j of jobs)j.loadedAt=t;a.inputCount-=jobs.length;this.phase(car,'closeLoad',p.doorClose+p.interlock,t);}
 else if(s==='closeLoad'){a.loadCar=null;this.move(car,'loaded',b.height,t,true);}
 else if(s==='loaded')this.phase(car,'positionUnload',p.position,t);
 else if(s==='positionUnload')this.wait(car,'waitOut',t);
 else if(s==='openUnload'){for(const j of jobs)j.unloadStart=t;this.phase(car,'unloading',b.unload*jobs.length,t);}
 else if(s==='unloading'){b.reservedOut-=jobs.length;for(const j of jobs){j.deliveredAt=t;b.output.push(j);this.events.push({time:t,type:'UNLOAD_COMPLETE',cargoId:j.id,floor:b.id,lift:car.id});}b.maxOutput=Math.max(b.maxOutput,b.output.length+b.reservedOut);car.jobs=[];this.phase(car,'closeUnload',p.doorClose+p.interlock,t);}
 else if(s==='closeUnload'){b.unloadCar=null;if(p.parking==='home')this.move(car,'returning',this.floors.get(p.homeFloor).height,t,false);else this.wait(car,'idle',t);}
 else if(s==='returning')this.phase(car,'positionReturn',car.segments.at(-1).profile.length>EPS?p.position:0,t);
 else if(s==='positionReturn')this.wait(car,'idle',t);
 }
 pump(t){const p=this.p;for(const f of this.floors.values()){while(f.external.length&&f.inputCount<f.inBuffer){const j=f.external.shift();j.acceptedAt=t;f.inputCount++;f.queue.push(j);f.maxInput=Math.max(f.maxInput,f.inputCount);}if(f.output.length&&!f.takeBusy){f.takeBusy=true;this.heap.push(t+f.takeaway,'takeaway',f.id);}}
 // Fairness is based on arrival at the relevant shared port, then shaft ID.
 const waiting=this.cars.filter(c=>['waitLoad','waitOut'].includes(c.state)).sort((a,b)=>a.segments.at(-1).start-b.segments.at(-1).start||a.id-b.id);
 for(const c of waiting){if(activeAt(t,c.stops)>t+EPS)continue;if(c.state==='waitLoad'){const f=this.floors.get(c.origin);if(f.loadCar===null){f.loadCar=c.id;this.phase(c,'openLoad',p.doorOpen,t);}}else{const f=this.floors.get(c.dest);if(f.unloadCar===null&&f.output.length+f.reservedOut+c.jobs.length<=f.outBuffer){f.unloadCar=c.id;f.reservedOut+=c.jobs.length;f.maxOutput=Math.max(f.maxOutput,f.output.length+f.reservedOut);this.phase(c,'openUnload',p.doorOpen,t);}}}
 while(true){const idle=this.cars.filter(c=>c.state==='idle'&&activeAt(t,c.stops)<=t+EPS);if(!idle.length)break;const choices=[];for(const f of this.floors.values()){const head=f.queue[0];if(!head)continue;const max=M.batchLimit(p,this.od.get(head.flowId)),jobs=[];for(const j of f.queue){if(j.flowId!==head.flowId||jobs.length>=max)break;jobs.push(j);}if(jobs.length<max&&t<head.acceptedAt+p.batchWait-EPS){this.wake(head.acceptedAt+p.batchWait);continue;}for(const c of idle)choices.push({c,f,jobs,head,cost:M.moveTime(p,c.y,f.height,false)});}if(!choices.length)break;choices.sort((a,b)=>b.head.priority-a.head.priority||(p.dispatch==='nearest'?a.cost-b.cost:0)||a.head.release-b.head.release||a.cost-b.cost||a.c.id-b.c.id);const q=choices[0];q.f.queue.splice(0,q.jobs.length);this.startTrip(q.c,q.jobs,t);}
 }
 advanceTo(until){if(!Number.isFinite(until)||until<this.time-EPS||until>this.p.horizon+EPS)throw Error('진행 시각 범위 오류');while(this.heap.peek&&this.heap.peek.t<=until+EPS){const t=this.heap.peek.t;let sample=false;do{while(this.heap.peek&&this.heap.peek.t<=t+EPS){const e=this.heap.pop();if(++this.eventCount>1000000)throw Error('이벤트 1,000,000건 초과');this.time=t;if(e.type==='sample')sample=true;else this.process(e);}this.pump(t);}while(this.heap.peek&&this.heap.peek.t<=t+EPS);if(sample){const done=this.items.filter(j=>j.completedAt!==null).length,backlog=this.items.filter(j=>j.acceptedAt===null).length;this.samples.push({time:t,generated:this.items.length,completed:done,backlog,wip:this.items.length-done-backlog});}}this.time=until;return this;}
 result(){return {version:M.VERSION,config:M.clone(this.p),configHash:M.hash(this.p),time:this.time,items:this.items,cars:this.cars.map(c=>({id:c.id,stops:c.stops,segments:c.segments})),events:this.events,samples:this.samples,eventCount:this.eventCount,floors:[...this.floors.values()].map(f=>({id:f.id,maxInput:f.maxInput,maxOutput:f.maxOutput}))};}
}
function run(p,progress){const s=new Simulation(p);for(let i=1;i<=20;i++){s.advanceTo(p.horizon*i/20);if(progress)progress(i/20);}const r=s.result();r.metrics=metrics(r);return r;}
const overlap=(a,b,w,t)=>Math.max(0,Math.min(b??t,t)-Math.max(a,w));
function metrics(r,t=r.time){const p=r.config,w=Math.min(p.warmup,t),span=t-w,items=r.items.filter(j=>j.release<=t+EPS),at=k=>j=>j[k]!==null&&j[k]<=t+EPS,completed=items.filter(at('completedAt')),measured=completed.filter(j=>j.completedAt>=w-EPS),delivered=items.filter(at('deliveredAt')),accepted=items.filter(at('acceptedAt')),loaded=items.filter(at('loadedAt')),backlog=items.length-accepted.length,input=accepted.length-loaded.length,onboard=loaded.length-delivered.length,output=delivered.length-completed.length,lead=measured.map(j=>j.completedAt-j.release).sort((a,b)=>a-b),wait=measured.map(j=>j.assignedAt-j.release),rate=n=>span?n*3600/span:0;
 const carRows=r.cars.map(c=>{let working=0,blocked=0,empty=0,loadedSeconds=0;const phaseSeconds={};for(const s of c.segments){const a=Math.max(s.start,w),b=Math.min(s.end??t,t);if(b<=a)continue;const d=activeElapsed(a,b,c.stops);phaseSeconds[s.state]=(phaseSeconds[s.state]||0)+d;if(s.state==='waitOut'||s.state==='waitLoad')blocked+=d;else if(s.state!=='idle')working+=d;if(s.state==='empty'||s.state==='returning')empty+=d;if(s.state==='loaded')loadedSeconds+=d;}const down=span-activeElapsed(w,t,c.stops);return {id:c.id,working:span?working/span:0,blocked:span?blocked/span:0,down:span?down/span:0,empty:span?empty/span:0,loaded:span?loadedSeconds/span:0,phaseSeconds,trips:c.segments.filter(s=>s.state==='control'&&s.start>=w&&s.start<=t).length};});
 const byCargo=p.cargo.map(c=>({id:c.id,name:c.name,completed:measured.filter(j=>j.cargoId===c.id).length,rate:rate(measured.filter(j=>j.cargoId===c.id).length)}));const odRows=p.ods.map(o=>{const js=items.filter(j=>j.flowId===o.id),done=measured.filter(j=>j.flowId===o.id);return {id:o.id,from:o.from,to:o.to,cargoId:o.cargoId,generated:js.length,completed:done.length,rate:rate(done.length),unfinished:js.filter(j=>!at('completedAt')(j)).length,meanLead:done.length?done.reduce((s,j)=>s+j.completedAt-j.release,0)/done.length:null};});
 const floorRows=p.floors.map(f=>{const ins=items.filter(j=>j.from===f.id&&at('acceptedAt')(j)),outs=items.filter(j=>j.to===f.id&&at('deliveredAt')(j));return {id:f.id,input:ins.filter(j=>!at('loadedAt')(j)).length,output:outs.filter(j=>!at('completedAt')(j)).length,backlog:items.filter(j=>j.from===f.id&&!at('acceptedAt')(j)).length,meanInput:span?ins.reduce((s,j)=>s+overlap(j.acceptedAt,j.loadedAt,w,t),0)/span:0,meanOutput:span?outs.reduce((s,j)=>s+overlap(j.deliveredAt,j.completedAt,w,t),0)/span:0,...(t===r.time?r.floors.find(x=>x.id===f.id):{})};});
 return {time:t,measuredSeconds:span,generated:items.length,accepted:accepted.length,totalCompleted:completed.length,completed:measured.length,throughput:rate(measured.length),liftThroughput:rate(delivered.filter(j=>j.deliveredAt>=w-EPS).length),backlog,input,onboard,output,wip:input+onboard+output,meanLead:lead.length?lead.reduce((s,x)=>s+x,0)/lead.length:null,p95Lead:lead.length?lead[Math.ceil(lead.length*.95)-1]:null,meanWait:wait.length?wait.reduce((s,x)=>s+x,0)/wait.length:null,meanWip:span?accepted.reduce((s,j)=>s+overlap(j.acceptedAt,j.completedAt,w,t),0)/span:0,meanBacklog:span?items.reduce((s,j)=>s+overlap(j.release,j.acceptedAt,w,t),0)/span:0,carRows,byCargo,odRows,floorRows,conservation:items.length===completed.length+backlog+input+onboard+output};
}
function segmentAt(car,t){let lo=0,hi=car.segments.length-1,found=0;while(lo<=hi){const m=(lo+hi)>>1;if(car.segments[m].start<=t+EPS){found=m;lo=m+1;}else hi=m-1;}return car.segments[found];}
function snapshot(r,t){t=Math.max(0,Math.min(r.time,t));const poses=r.cars.map(c=>{const s=segmentAt(c,t),dt=activeElapsed(s.start,t,c.stops),q=s.profile?Motion.at(s.profile,dt):{x:s.to,v:0,label:''},duration=s.profile?s.profile.duration:activeElapsed(s.start,s.end??r.time,c.stops),stopped=activeAt(t,c.stops)>t+EPS;return {id:c.id,y:q.x,v:stopped?0:q.v,state:stopped?'stopped':s.state,phase:s.state,progress:duration?Math.min(1,dt/duration):0,jobIds:s.jobIds,from:s.from,to:s.to,profileLabel:q.label};});const floors=r.config.floors.map(f=>({id:f.id,input:[],output:[],outside:0})),fm=new Map(floors.map(f=>[f.id,f]));for(const j of r.items){if(j.release>t)continue;if(j.completedAt!==null&&j.completedAt<=t)continue;if(j.acceptedAt===null||j.acceptedAt>t)fm.get(j.from).outside++;else if(j.loadStart===null||j.loadStart>t)fm.get(j.from).input.push(j);else if(j.deliveredAt!==null&&j.deliveredAt<=t)fm.get(j.to).output.push(j);}return {time:t,poses,floors};}
function compare(p,progress){const variants=[['기준안',()=>{}],['리프트 +1대',c=>c.lifts++],['적재·공차 속도 +20%',c=>{c.loadedV*=1.2;c.emptyV*=1.2;}],['상하차 시간 −20%',c=>c.floors.forEach(f=>{f.load*=.8;f.unload*=.8;})],['출력 버퍼 ×2',c=>c.floors.forEach(f=>f.outBuffer*=2)],['후단 반출 시간 −20%',c=>c.floors.forEach(f=>f.takeaway*=.8)],['매회 기준층 귀환',c=>c.parking='home']];return variants.map(([name,edit],i)=>{const c=M.clone(p);edit(c);const v=M.validate(c);let row={name,valid:!v.errors.length,errors:v.errors};if(!v.errors.length){const r=run(c);row={...row,config:c,throughput:r.metrics.throughput,p95:r.metrics.p95Lead,backlog:r.metrics.backlog,wip:r.metrics.wip,blocked:r.metrics.carRows.reduce((n,x)=>n+x.blocked,0)/c.lifts};}if(progress)progress((i+1)/variants.length);return row;});}
return {Heap,rng,intervals,activeAt,activeAdd,activeElapsed,releases,stateNames,Simulation,run,metrics,snapshot,segmentAt,compare};
});
