(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model'):root.LiftModel,typeof module==='object'&&module.exports?require('./engine'):root.LiftEngine,typeof module==='object'&&module.exports?require('./xlsx'):root.LiftXlsx);if(typeof module==='object'&&module.exports)module.exports=api;else root.LiftIO=api;})(globalThis,function(M,E,X){
'use strict';const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function csv(rows){return '\uFEFF'+rows.map(r=>r.map(v=>{let s=String(v??'');if(typeof v!=='number'&&/^\s*[=+@-]/.test(s))s="'"+s;return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}).join(',')).join('\r\n');}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else throw Error('CSV 따옴표 오류');}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\r'||c==='\n')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV 따옴표가 닫히지 않았습니다.');row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows;}
function importHistory(text,p){const rows=parseCSV(text);if(rows[0]?.join(',')!=='id,release_s,flowId')throw Error('CSV 헤더: id,release_s,flowId');const q=M.clone(p);q.history=rows.slice(1).map((r,i)=>{if(r.length!==3||!r[1].trim())throw Error('이력 CSV '+(i+2)+'행 오류');return {id:r[0].trim(),release:Number(r[1]),flowId:r[2].trim()};});q.demandMode='history';const v=M.validate(q);if(v.errors.length)throw Error(v.errors.join('\n'));return q;}
const specs={
 '층스테이션':{key:'floors',fields:['id','name','height','load','unload','inBuffer','outBuffer','takeaway','peerType','peerId'],headers:['층 ID','층 이름','높이 (m)','상차 (s/개)','하차 (s/개)','입력 버퍼 (개)','출력 버퍼 (개)','후단 반출 (s/개)','후단 장비 형식','후단 모듈 ID'],numeric:['height','load','unload','inBuffer','outBuffer','takeaway'],max:20},
 '운반물':{key:'cargo',fields:['id','name','kind','length','width','height','weight','color'],headers:['화물 ID','화물 이름','형식','길이 (m)','폭 (m)','높이 (m)','중량 (kg)','색상'],numeric:['length','width','height','weight'],max:12},
 'OD물동량':{key:'ods',fields:['id','from','to','cargoId','rate','priority'],headers:['OD ID','출발 층','도착 층','화물 ID','물동량 (개/h)','우선순위'],numeric:['rate','priority'],max:400},
 '시간대비율':{key:'periods',fields:['start','end','factor'],headers:['시작 (min)','종료 (min)','비율 (100%=1)'],numeric:['start','end','factor'],minutes:['start','end'],max:96},
 '계획정지':{key:'stops',fields:['lift','start','end'],headers:['리프트 번호','시작 (min)','종료 (min)'],numeric:['lift','start','end'],minutes:['start','end'],max:200},
 '작업이력':{key:'history',fields:['id','release','flowId'],headers:['작업 ID','발생 (s)','OD ID'],numeric:['release'],max:30000}
};
const labels={schemaVersion:'입력 스키마',moduleId:'모듈 ID',name:'프로젝트명',basis:'가정·근거',homeFloor:'시작/귀환 층',parking:'귀환 방식 stay/home',dispatch:'배차 fifo/nearest',arrival:'도착 periodic/poisson',demandMode:'수요 rates/history',speedUnit:'화면 속도 m/min 또는 m/s'};
const keys=Object.keys(M.preset()).filter(k=>!Array.isArray(M.preset()[k]));
function unit(k){return M.fields[k]?.[1]==='speed'?'m/min':M.fields[k]?.[1]||'문자';}
function toCell(k,v){return M.fields[k]?.[1]==='speed'?v*60:['horizon','warmup'].includes(k)?v/60:v;}
function fromCell(k,v){return M.fields[k]?.[1]==='speed'?v/60:['horizon','warmup'].includes(k)?v*60:v;}
function sheets(p){M.pack(p);const book={
 '안내':{widths:[25,120],filter:false,rows:[['항목','안내'],['파일 형식','vertical-lift/workbook@1'],['프로그램 버전',M.VERSION],['용도','왕복식 수직 리프트 전체 입력 저장/불러오기'],['단위','기본 속도 m/min, 기본 총시간·준비운전 min, 층 높이·화물 치수 m, 시간대/정지 min, 이력 s. 화면 속도 선택과 무관합니다.'],['입력','기본조건 입력값과 표 내용을 수정하세요. 키·시트명·열 제목·단위는 유지하세요. 숫자 셀에는 수식 대신 확정 값을 입력하세요.'],['화물','팔레트·박스·토트 각 1개를 HU 1개로 기록합니다. 유형 간 자동 환산하지 않습니다. maxBatch는 동일 OD만 함께 적재합니다.'],['해석','최대 적재 독립 OD 공차 근사. 가용도는 해석에만 적용, 운전의 정지는 계획정지 표로 지정. 기본 사양은 특정 제조사 보증값이 아닌 가정입니다.'],['층 설정','층 ID를 수정하면 OD 출발/도착 및 homeFloor도 함께 수정하세요. 모든 시트를 검사한 후 한 번에 적용합니다.'],['시간대','빈 표는 전체 100%. 입력 시 시작 0부터 총 운전시간까지 중복/빈틈 없이 작성. 120% 또는 숫자 1.2는 1.2배. 이력 모드는 비율을 적용하지 않습니다.'],['후단 반출','0은 무대기 인계. 양수는 화물 1개 반출에 걸리는 시간. 처리 중 화물도 출력 버퍼 공간을 차지합니다.'],['선택값','parking: stay/home; dispatch: fifo/nearest; arrival: periodic/poisson; demandMode: rates/history; kind: pallet/box/tote'],['연동값','peerType: none/conveyor/stacker-crane/rgv_linear/rgv_loop/shuttle_4way/agv_amr. peerId는 연결 대상 모듈 ID. 실제 공통 시계 연동은 후속 통합용입니다.']]},
 '기본조건':{widths:[25,37,50,20],rows:[['키','항목','입력값','단위'],...keys.map(k=>[k,M.fields[k]?.[0]||labels[k]||k,toCell(k,p[k]),unit(k)])]}
 };for(const[name,s]of Object.entries(specs))book[name]={widths:s.headers.map(()=>23),rows:[s.headers,...p[s.key].map(r=>s.fields.map(k=>s.minutes?.includes(k)?r[k]/60:r[k]))]};return book;}
function fromSheets(book){if(book.안내?.find(r=>r[0]==='파일 형식')?.[1]!=='vertical-lift/workbook@1')throw Error('리프트 엑셀 양식이 아닙니다.');const errors=[],fail=s=>{if(errors.length<35)errors.push(s);},blank=v=>v===undefined||v===null||String(v).trim()==='',number=(v,where,percent=false)=>{let n=typeof v==='number'?v:percent&&String(v).trim().endsWith('%')?Number(String(v).trim().slice(0,-1))/100:Number(v);if(blank(v)||!Number.isFinite(n)){fail(where+': 숫자가 필요합니다.');return NaN;}return n;};
 function table(name,headers,max){if(!Array.isArray(book[name])){fail(name+': 시트 없음');return [];}const [head,...rows]=book[name],idx=headers.map(x=>head?.indexOf(x));if(idx.some(i=>i<0)||head.filter(x=>!blank(x)).length!==headers.length){fail(name+': 열 제목이 양식과 다릅니다.');return [];}const out=[];rows.forEach((r,i)=>{if(r.every(blank))return;if(r.some((x,j)=>!idx.includes(j)&&!blank(x)))fail(name+' '+(i+2)+'행: 양식 외 열');out.push({line:i+2,values:idx.map(j=>r[j]??'')});});if(out.length>max)fail(name+': 최대 '+max+'행');return out;}
 const p=M.preset(),seen=new Set();for(const {line,values:r}of table('기본조건',['키','항목','입력값','단위'],keys.length)){const k=String(r[0]);if(!keys.includes(k)||seen.has(k)){fail('기본조건 '+line+'행: 키 누락/중복/오류 '+k);continue;}seen.add(k);if(r[3]!==unit(k))fail('기본조건 '+line+'행: 단위는 '+unit(k));p[k]=typeof p[k]==='number'?fromCell(k,number(r[2],'기본조건 '+line,['availability','targetUtil','upFactor','downFactor'].includes(k))):String(r[2]);}for(const k of keys)if(!seen.has(k))fail('기본조건 키 누락: '+k);
 for(const[name,s]of Object.entries(specs))p[s.key]=table(name,s.headers,s.max).map(({line,values:r})=>Object.fromEntries(s.fields.map((k,i)=>{let v=s.numeric.includes(k)?number(r[i],name+' '+line+'행 '+s.headers[i],k==='factor'):String(r[i]).trim();if(s.minutes?.includes(k))v*=60;return [k,v];})));
 if(errors.length)throw Error(errors.join('\n'));const v=M.validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));return p;
}
async function readXlsx(file){return fromSheets(await X.read(file));}function writeXlsx(p){return X.write(sheets(p));}
function getPorts(p){return p.floors.flatMap(f=>['in','out'].map(dir=>({portId:p.moduleId+':'+f.id+':'+dir,moduleId:p.moduleId,floorId:f.id,direction:dir,bufferCapacity:dir==='in'?f.inBuffer:f.outBuffer,transferTimeOwner:'vertical_lift',transferSecondsPerCargo:dir==='in'?f.load:f.unload,position:{x:0,y:f.height,z:(dir==='in'?-1:1)*(p.platformWidth/2+1)},allowedCargo:p.cargo.map(c=>({...c})),peer:dir==='out'&&f.peerType!=='none'?{deviceType:f.peerType,moduleId:f.peerId}:null,mode:'standalone-cycle-emulation'})));}
function interfaceData(r){return {schemaVersion:'logistics/vertical-lift-interface@1',deviceType:'vertical_lift',moduleVersion:M.VERSION,moduleId:r.config.moduleId,configHash:r.configHash,units:{distance:'m',time:'s',weight:'kg',quantity:'handling-unit'},timeOrigin:'simulation-start',ports:getPorts(r.config),config:M.pack(r.config),metrics:r.metrics,events:r.events.filter(e=>e.type==='HANDOFF_COMPLETE').map(e=>({...e,eventId:r.config.moduleId+':'+e.cargoId+':completed',cargoId:r.config.moduleId+':'+e.cargoId,portId:r.config.moduleId+':'+e.floor+':out',quantity:1,ownerModuleId:r.config.moduleId})),contractStatus:'포트/설정/이벤트 교환용. 공유 시계·예약·소유권 인계 어댑터는 아직 연결되지 않았습니다.'};}
function resultCSV(r,a){const m=r.metrics;return csv([['프로젝트',r.config.name],['버전',M.VERSION],['입력 해시',r.configHash],['측정시간_s',m.measuredSeconds],['최종 인계_HU/h',m.throughput],['리프트 하차_HU/h',m.liftThroughput],['해석 리프트 능력_HU/h',a.theory],['해석 라인 상한_HU/h',a.lineUpper],['요청',m.generated],['총 인계완료',m.totalCompleted],['미투입',m.backlog],['재공',m.wip],['평균 리드타임_s',m.meanLead],['P95 리드타임_s',m.p95Lead],['화물 보존',m.conservation?'일치':'오류'],[],['OD','출발','도착','화물','발생','측정 완료','HU/h','미완료','평균 리드타임_s'],...m.odRows.map(o=>[o.id,o.from,o.to,o.cargoId,o.generated,o.completed,o.rate,o.unfinished,o.meanLead]),[],['리프트','작업비율','차단비율','정지비율','공차비율'],...m.carRows.map(c=>[c.id,c.working,c.blocked,c.down,c.empty])]);}
function historyCSV(p){return csv([['id','release_s','flowId'],...p.history.map(h=>[h.id,h.release,h.flowId])]);}
function jobsCSV(r){return csv([['cargoId','OD','화물','출발','도착','리프트','발생_s','버퍼수락_s','배차_s','상차시작_s','상차완료_s','하차시작_s','하차완료_s','후단인계_s'],...r.items.map(j=>[j.id,j.flowId,j.cargoId,j.from,j.to,j.lift,j.release,j.acceptedAt,j.assignedAt,j.loadStart,j.loadedAt,j.unloadStart,j.deliveredAt,j.completedAt])]);}
function report(r,a){const f=(x,n=1)=>Number.isFinite(x)?x.toLocaleString('ko-KR',{maximumFractionDigits:n}):'—',m=r.metrics,p=r.config,table=(head,rows)=>'<table><thead><tr>'+head.map(x=>'<th>'+escape(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+escape(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';return '<!doctype html><html lang="ko"><meta charset="utf-8"><title>'+escape(p.name)+'</title><style>body{max-width:1080px;margin:auto;padding:40px;font:14px/1.7 Segoe UI,Malgun Gothic,sans-serif;color:#244354}h1{font-size:28px}h2{font-size:18px;margin-top:30px}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:9px;border:1px solid #dae4e9;text-align:left}th{background:#edf4f7}a{color:#008a88}@media print{button{display:none}body{padding:0}}</style><button onclick="print()">인쇄 / PDF 저장</button><h1>'+escape(p.name)+'</h1><p>왕복식 리프트 물동량 · v'+M.VERSION+' · 입력 해시 '+r.configHash+' · '+escape(p.basis)+'</p><h2>운전 결과</h2>'+table(['항목','값'],[['후단 인계 처리량',f(m.throughput)+' HU/h'],['리프트 하차 처리량',f(m.liftThroughput)+' HU/h'],['총 요청 / 총 인계완료',m.generated+' / '+m.totalCompleted],['미투입 / 입력 / 탑승 / 출력',m.backlog+' / '+m.input+' / '+m.onboard+' / '+m.output],['평균 / P95 리드타임',f(m.meanLead)+' / '+f(m.p95Lead)+' s'],['화물 보존',m.conservation?'일치':'오류'],['해석 능력 / 가용도 보정',f(a.theory)+' / '+f(a.corrected)+' HU/h'],['고정 OD 혼합 라인 상한 / 병목',f(a.lineUpper)+' HU/h / '+a.bottleneck]])+'<h2>층별 OD 결과</h2>'+table(['OD','층간','화물','측정완료','HU/h','미완료','평균 리드타임 s'],m.odRows.filter(o=>o.generated).map(o=>[o.id,o.from+' → '+o.to,o.cargoId,o.completed,f(o.rate),o.unfinished,f(o.meanLead)]))+'<h2>리프트 점유</h2>'+table(['리프트','작업','차단','계획정지','공차'],m.carRows.map(c=>[c.id,f(c.working*100)+'%',f(c.blocked*100)+'%',f(c.down*100)+'%',f(c.empty*100)+'%']))+'<h2>전체 기본조건</h2>'+table(['항목','값','단위'],keys.map(k=>[M.fields[k]?.[0]||labels[k]||k,toCell(k,p[k]),unit(k)]))+Object.entries(specs).filter(([,s])=>s.key!=='history').map(([name,s])=>'<h2>'+escape(name)+'</h2>'+table(s.headers,p[s.key].map(row=>s.fields.map(k=>s.minutes?.includes(k)?row[k]/60:row[k])))).join('')+'<h2>계산 정의</h2><p>최대속도 v, 가속도 a, 감속도 d, 이동거리 H에 대해 도달속도는 min(v, √(2H/(1/a+1/d))). 가속·정속·감속 구간의 시간을 합산합니다. 작업 사이클은 공차 + 제어 + 상차 정차 + 적재 승강 + 하차 정차이며, 매회 귀환 설정은 귀환 이동도 포함합니다.</p><p>해석은 최대 적재 및 '+escape(a.reference)+' 기준입니다. 시뮬레이션은 실제 FIFO 대기열·부분 적재·공용 이재부·유한 버퍼·계획정지를 반영합니다. 가용도 보정을 시뮬레이션에 다시 곱하지 않습니다. 낮은 수요에서 관측된 처리량은 최대 처리능력이 아닙니다. HU는 개별 화물 1개이며 팔레트와 박스 수량은 별도로 해석해야 합니다.</p><p>3D 위치는 동일 운전 이력과 가감속 곡선에서 재생됩니다. 도어와 상하차는 입력 시간에 따른 개념 표현입니다. 계획정지는 현재 위상에서 즉시 멈춘 후 재개하는 근사입니다. 구조·동력·안전 인증 계산은 포함하지 않습니다.</p><h2>참고자료 · 확인 2026-09-16</h2><ul>'+M.sources.map(s=>'<li><a href="'+s.url+'">'+escape(s.title)+'</a> — '+escape(s.note)+'</li>').join('')+'</ul></html>';}
const plugin={deviceType:'vertical_lift',version:M.VERSION,capabilities:{types:['reciprocating'],cargoTypes:['pallet','box','tote'],units:'SI',externalCoSimulation:false},validateConfig:M.validate,calculate:M.calculate,createModel:p=>new E.Simulation(p),getPorts,collectMetrics:E.metrics,serialize:M.pack,migrate:M.unpack,buildReport:report};
return {escape,csv,parseCSV,importHistory,specs,sheets,fromSheets,readXlsx,writeXlsx,getPorts,interfaceData,resultCSV,historyCSV,jobsCSV,report,plugin};
});
