(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./motion'):root.LiftMotion);if(typeof module==='object'&&module.exports)module.exports=api;else root.LiftModel=api;})(globalThis,function(Motion){
'use strict';
const VERSION='1.0.0',SCHEMA='vertical-lift/project@1',clone=x=>JSON.parse(JSON.stringify(x));
const sources=[
 {title:'NERAK · Vertical Reciprocating Conveyors',url:'https://www.nerak-systems.com/vertical-lifts/vertical-reciprocating-conveyors',note:'다층 상·하향 운반과 캐리어 컨베이어 구성. 실제 처리능력은 운반물 크기와 이동 높이에 의존.'},
 {title:'Qimarox · Prorunner mk1',url:'https://www.qimarox.com/product/prorunner-mk1/',note:'박스·토트 계열 왕복식. 짧은 스트로크에서 최대 승강속도에 도달하지 못할 수 있음. 공개 페이지 내 최대 처리량 표기가 서로 달라 고정 처리량으로 채택하지 않음.'},
 {title:'Qimarox · Prorunner mk9',url:'https://www.qimarox.com/product/prorunner-mk9/',note:'팔레트 왕복식, 다층 입출고. 화물 하중과 캐리어 컨베이어를 포함한 하중을 구분해야 함.'},
 {title:'Qimarox · Prorunner mk10',url:'https://www.qimarox.com/product/prorunner-mk10/',note:'고층·중량 팔레트 리프트의 참고 구조. 제조사 최대치는 조건부이며 본 프로그램의 보증값이 아님.'}
];
const fields={
 lifts:['리프트 대수','대',1,8,1],platformLength:['플랫폼 유효 길이','m',.2,8,.1],platformWidth:['플랫폼 유효 폭','m',.2,6,.1],clearHeight:['화물 유효 높이','m',.2,6,.1],payload:['화물 허용하중 (캐리어 제외)','kg',1,20000,10],maxBatch:['최대 동시 적재','개/회',1,8,1],cargoGap:['화물 사이 간격','m',0,1,.05],
 loadedV:['적재 승강속도','speed',.02,6,.1],emptyV:['공차 승강속도','speed',.02,6,.1],upFactor:['상승 속도 비율','배',.1,1,.05],downFactor:['하강 속도 비율','배',.1,1,.05],loadedA:['적재 가속도','m/s²',.02,4,.1],loadedD:['적재 감속도','m/s²',.02,4,.1],emptyA:['공차 가속도','m/s²',.02,4,.1],emptyD:['공차 감속도','m/s²',.02,4,.1],
 position:['이동 후 정위치','s/회',0,30,.1],doorOpen:['도어 열림','s/정차',0,60,.1],doorClose:['도어 닫힘','s/정차',0,60,.1],interlock:['닫힘 후 인터록 확인','s/정차',0,30,.1],control:['배차 제어 지연','s/회',0,30,.1],batchWait:['부분 적재 최대 대기','s',0,600,1],availability:['해석용 가용도','비율',.05,1,.01],targetUtil:['목표 설계 부하율','비율',.1,1,.01],horizon:['총 운전시간','min',60,86400,60],warmup:['준비운전 제외','min',0,86399,60],seed:['난수 시드','정수',0,4294967295,1]
};
const cargoDefaults=[{id:'PLT',name:'팔레트',kind:'pallet',length:1.2,width:1,height:1.4,weight:700,color:'#b88e58'},{id:'BOX',name:'박스',kind:'box',length:.6,width:.4,height:.4,weight:20,color:'#d8a76a'},{id:'TOTE',name:'토트',kind:'tote',length:.6,width:.4,height:.32,weight:30,color:'#4c9fba'}];
function floor(id,height){return {id,name:id+' 층',height,load:6,unload:6,inBuffer:8,outBuffer:8,takeaway:4,peerType:'none',peerId:''};}
function autoOD(p){const valid=new Set(p.floors.map(f=>f.id)),keep=p.ods.filter(o=>valid.has(o.from)&&valid.has(o.to)&&o.from!==o.to),pairs=new Set(keep.map(o=>o.from+'|'+o.to));let next=1;const ids=new Set(keep.map(o=>o.id));for(const a of p.floors)for(const b of p.floors)if(a.id!==b.id&&!pairs.has(a.id+'|'+b.id)){while(ids.has('OD'+next))next++;const id='OD'+next++;ids.add(id);keep.push({id,from:a.id,to:b.id,cargoId:p.cargo[0].id,rate:0,priority:1});}return keep;}
function preset(kind='pallet'){
 const p={schemaVersion:SCHEMA,moduleId:'LIFT-01',name:'왕복식 리프트 · 3층 물동량 검토',basis:'설명용 가정값. 현장 승인 사양으로 교체하세요.',lifts:1,homeFloor:'F1',parking:'stay',dispatch:'fifo',horizon:3600,warmup:300,seed:20260916,arrival:'periodic',demandMode:'rates',speedUnit:'m/min',platformLength:1.6,platformWidth:1.4,clearHeight:2.2,payload:1500,maxBatch:1,cargoGap:.1,loadedV:1,emptyV:1.2,upFactor:1,downFactor:1,loadedA:.5,loadedD:.5,emptyA:.6,emptyD:.6,position:.5,doorOpen:1,doorClose:1,interlock:.5,control:.3,batchWait:0,availability:1,targetUtil:.85,cargo:clone(cargoDefaults),floors:[floor('F1',.6),floor('F2',4.6),floor('F3',8.6)],ods:[],periods:[],stops:[],history:[]};
 p.ods=autoOD(p);for(const o of p.ods)o.rate=o.from==='F1'?35:o.to==='F1'?20:0;
 if(kind==='box'||kind==='tote'){p.name=(kind==='box'?'박스':'토트')+' · 왕복식 리프트';p.cargo=p.cargo.filter(c=>c.kind===kind);p.ods.forEach(o=>{o.cargoId=p.cargo[0].id;o.rate*=2;});Object.assign(p,{platformLength:1.4,platformWidth:1.1,clearHeight:1,payload:100,maxBatch:2,loadedV:1.5,emptyV:1.5,doorOpen:.5,doorClose:.5});p.floors.forEach(f=>{f.load=2;f.unload=2;f.takeaway=1;});}
 if(kind==='blocked'){p.name='출구 버퍼 정체 검토';p.floors[1].outBuffer=1;p.floors[1].takeaway=120;p.ods.forEach(o=>o.rate=o.from==='F1'&&o.to==='F2'?130:0);}
 if(kind==='two'){p.name='리프트 2대 · 양방향 운반';p.lifts=2;p.ods.forEach(o=>o.rate*=1.8);}
 return p;
}
function hash(p){const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);let h=2166136261;for(const c of canonical(p)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function batchLimit(p,o){const c=p.cargo.find(c=>c.id===o.cargoId),a=p.floors.find(f=>f.id===o.from),b=p.floors.find(f=>f.id===o.to);if(!c||!a||!b)return 0;const nx=Math.floor((p.platformLength+p.cargoGap+1e-9)/(c.length+p.cargoGap)),nz=Math.floor((p.platformWidth+p.cargoGap+1e-9)/(c.width+p.cargoGap));return Math.max(0,Math.min(p.maxBatch,nx*nz,Math.floor((p.payload+1e-9)/c.weight),a.inBuffer,b.outBuffer));}
function motion(p,from,to,loaded){const dir=to>=from?p.upFactor:p.downFactor;return Motion.solve(from,to,{v:(loaded?p.loadedV:p.emptyV)*dir,a:loaded?p.loadedA:p.emptyA,d:loaded?p.loadedD:p.emptyD});}
function moveTime(p,a,b,loaded){return motion(p,a,b,loaded).duration+(Math.abs(a-b)>1e-9?p.position:0);}
function bands(p){return p.periods.length?p.periods:[{start:0,end:p.horizon,factor:1}];}
function averageFactor(p,start=p.warmup,end=p.horizon){return bands(p).reduce((a,b)=>a+Math.max(0,Math.min(end,b.end)-Math.max(start,b.start))*b.factor,0)/(end-start);}
function rates(p){return p.ods.map(o=>({...o,rate:p.demandMode==='history'?p.history.filter(h=>h.flowId===o.id&&h.release>=p.warmup&&h.release<p.horizon).length*3600/(p.horizon-p.warmup):o.rate*averageFactor(p)}));}
function validate(p){
 const errors=[],warnings=[],err=s=>errors.push(s),num=(x,min,max,label,int=false)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>max||int&&!Number.isInteger(x))err(label+': '+min+'~'+max+(int?' 정수':'')+'를 입력하세요.');},id=(s,label)=>{if(typeof s!=='string'||!/^[-A-Za-z0-9_가-힣]{1,60}$/.test(s))err(label+': 영문·숫자·한글·밑줄·하이픈 1~60자 필요');},uniq=(rows,label)=>{const seen=new Set();for(const r of rows){if(!r||typeof r!=='object'){err(label+' 행 형식 오류');continue;}id(r.id,label+' ID');if(seen.has(r.id))err(label+' ID 중복: '+r.id);seen.add(r.id);}return seen;};
 if(!p||p.schemaVersion!==SCHEMA)return {errors:['리프트 프로젝트 형식이 올바르지 않습니다.'],warnings};
 for(const k of ['floors','cargo','ods','periods','stops','history'])if(!Array.isArray(p[k]))err(k+' 목록이 필요합니다.');if(errors.length)return {errors,warnings};
 id(p.moduleId,'모듈 ID');if(typeof p.name!=='string'||p.name.length>200)err('프로젝트 이름 200자 이하');if(typeof p.basis!=='string'||p.basis.length>4000)err('가정·근거 4,000자 이하');
 for(const [k,f]of Object.entries(fields))num(p[k],f[2],f[3],f[0],['lifts','maxBatch','seed'].includes(k));if(p.warmup>=p.horizon)err('준비운전은 총 운전시간보다 짧아야 합니다.');
 for(const [k,allowed]of [['parking',['stay','home']],['dispatch',['fifo','nearest']],['arrival',['periodic','poisson']],['demandMode',['rates','history']],['speedUnit',['m/s','m/min']]])if(!allowed.includes(p[k]))err(k+' 선택 오류');
 if(p.floors.length<2||p.floors.length>20||p.cargo.length<1||p.cargo.length>12||p.ods.length>400||p.periods.length>96||p.stops.length>200||p.history.length>30000)err('입력 한도: 층 2~20, 화물 12종, OD 400, 시간대 96, 정지 200, 이력 30,000행');
 const fs=uniq(p.floors,'층'),cs=uniq(p.cargo,'화물'),os=uniq(p.ods,'OD');uniq(p.history,'이력');if(errors.length)return {errors,warnings};
 if(!fs.has(p.homeFloor))err('시작/귀환 층 ID가 없습니다.');
 for(const f of p.floors){if(typeof f.name!=='string'||f.name.length>100)err(f.id+' 층명 오류');num(f.height,0,100,f.id+' 높이');num(f.load,.05,600,f.id+' 상차 s/개');num(f.unload,.05,600,f.id+' 하차 s/개');num(f.inBuffer,1,500,f.id+' 입력 버퍼',true);num(f.outBuffer,1,500,f.id+' 출력 버퍼',true);num(f.takeaway,0,3600,f.id+' 후단 반출 s/개');if(!['none','conveyor','stacker-crane','rgv_linear','rgv_loop','shuttle_4way','agv_amr'].includes(f.peerType))err(f.id+' 후단 장비 형식 오류');if(typeof f.peerId!=='string'||f.peerId.length>100)err(f.id+' 후단 ID 오류');}
 const sorted=[...p.floors].sort((a,b)=>a.height-b.height);for(let i=1;i<sorted.length;i++)if(sorted[i].height-sorted[i-1].height<.2)err('층 높이는 최소 0.2 m 이상 달라야 합니다.');
 for(const c of p.cargo){if(typeof c.name!=='string'||c.name.length>100)err(c.id+' 이름 오류');if(!['pallet','box','tote'].includes(c.kind))err(c.id+' 화물 형식 오류');for(const k of ['length','width','height'])num(c[k],.05,8,c.id+' '+k);num(c.weight,.01,20000,c.id+' 중량');if(!/^#[0-9a-f]{6}$/i.test(c.color))err(c.id+' 색상 오류');}
 for(const o of p.ods){if(!fs.has(o.from)||!fs.has(o.to)||o.from===o.to)err(o.id+': 서로 다른 유효 출발/도착 층 필요');if(!cs.has(o.cargoId))err(o.id+': 화물 ID 없음');num(o.rate,0,10000,o.id+' 물동량');num(o.priority,0,99,o.id+' 우선순위',true);if(fs.has(o.from)&&fs.has(o.to)&&cs.has(o.cargoId)){const c=p.cargo.find(c=>c.id===o.cargoId);if(!batchLimit(p,o)||c.height>p.clearHeight+1e-9)err(o.id+': 화물 치수/중량이 플랫폼 유효 치수/허용하중을 초과합니다.');}}
 let last=0;for(const b of p.periods){num(b.start,0,p.horizon,'시간대 시작');num(b.end,0,p.horizon,'시간대 종료');num(b.factor,0,10,'시간대 비율');if(Math.abs(b.start-last)>1e-6||b.end<=b.start)err('시간대는 0부터 종료까지 빈틈/중복 없이 시간순으로 입력하세요.');last=b.end;}if(p.periods.length&&Math.abs(last-p.horizon)>1e-6)err('시간대 마지막 종료는 총 운전시간과 같아야 합니다.');
 for(const s of p.stops){num(s.lift,1,p.lifts,'정지 리프트 번호',true);num(s.start,0,p.horizon,'정지 시작');num(s.end,s.start+.001,p.horizon,'정지 종료');}
 for(const h of p.history){num(h.release,0,p.horizon-1e-7,'이력 발생 시각');if(!os.has(h.flowId))err('이력 '+h.id+': OD ID가 없습니다.');}
 if(errors.length)return {errors:[...new Set(errors)],warnings};
 const expected=p.ods.reduce((n,o)=>n+o.rate,0)*p.horizon*averageFactor(p,0,p.horizon)/3600;if(p.demandMode==='rates'&&expected>25000)err('예상 요청 25,000개 초과: 수요 또는 시간을 줄이세요.');
 if(p.maxBatch>1)warnings.push('해석은 OD별 최대 적재를 가정합니다. 실제 운전은 동일 OD의 연속 대기 화물만 묶으므로 부분 적재 시 처리능력이 낮아질 수 있습니다.');
 if(p.availability<1)warnings.push('가용도는 해석 참고값에만 적용됩니다. 시뮬레이션의 휴지시간은 계획 정지표로 입력하세요.');
 warnings.push('독립 승강로의 동일 사양 리프트. 층별 입력·출력 이재부는 각각 1개 공용 자원이며 버퍼도 층별 공용입니다.','대기 화물은 층 입력 FIFO를 따릅니다. 후단 출력 공간이 없으면 리프트는 적재한 채 도착층에서 대기합니다.','상하차·도어 동작은 순차 처리하며, 가감속은 사다리꼴/삼각형 속도곡선입니다. 저크·회생전력·구조 강도는 계산하지 않습니다.');
 return {errors:[...new Set(errors)],warnings};
}
function calculate(p){const v=validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));const rows=rates(p).map(o=>({...o,batch:batchLimit(p,o)})),total=rows.reduce((a,o)=>a+o.rate,0),jobs=rows.reduce((a,o)=>a+o.rate/o.batch,0),fm=new Map(p.floors.map(f=>[f.id,f])),home=fm.get(p.homeFloor).height,door=p.doorOpen+p.doorClose+p.interlock;
 let work=0,loadedWork=0,emptyWork=0,handlingWork=0;for(const o of rows){const a=fm.get(o.from),b=fm.get(o.to),q=o.rate/o.batch;o.empty=p.parking==='home'?moveTime(p,home,a.height,false)+moveTime(p,b.height,home,false):rows.reduce((s,prev)=>s+(jobs?prev.rate/prev.batch/jobs:0)*moveTime(p,fm.get(prev.to).height,a.height,false),0);o.loaded=moveTime(p,a.height,b.height,true);o.handling=2*door+(a.load+b.unload)*o.batch;o.cycle=p.control+o.empty+o.loaded+o.handling;o.jobs=q;work+=q*o.cycle;loadedWork+=q*o.loaded;emptyWork+=q*o.empty;handlingWork+=q*o.handling;}
 const resourceRows=[{id:'리프트',kind:'lift',load:work/3600,units:p.lifts,util:work/(3600*p.lifts)}];for(const f of p.floors){const ins=rows.filter(o=>o.from===f.id),outs=rows.filter(o=>o.to===f.id);resourceRows.push({id:f.id+' 입력 이재',kind:'in',load:ins.reduce((s,o)=>s+o.jobs*(door+f.load*o.batch),0)/3600,units:1},{id:f.id+' 출력 이재',kind:'out',load:outs.reduce((s,o)=>s+o.jobs*(door+f.unload*o.batch),0)/3600,units:1},{id:f.id+' 후단 반출',kind:'takeaway',load:outs.reduce((s,o)=>s+o.rate*f.takeaway,0)/3600,units:1});}resourceRows.forEach(r=>r.util=r.load/r.units);const limiting=resourceRows.reduce((a,b)=>b.util>a.util?b:a),theory=jobs?3600*p.lifts*total/work:null,corrected=theory===null?null:theory*p.availability,lineUpper=total&&limiting.util?total/limiting.util:null;return {total,jobs,rows,cycle:jobs?work/jobs:0,meanBatch:jobs?total/jobs:0,work,loadedWork,emptyWork,handlingWork,theory,corrected,lineUpper,resourceRows,bottleneck:total?limiting.id:'수요 없음',required:work?Math.ceil(work/(3600*p.availability*p.targetUtil)):0,warnings:v.warnings,reference:p.parking==='home'?'매회 기준층 귀환':'연속 OD 독립배차 공차 근사'};}
function pack(p){const v=validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));return {schemaVersion:SCHEMA,deviceType:'vertical_lift',moduleVersion:VERSION,units:{distance:'m',speed:'m/s',acceleration:'m/s2',time:'s',weight:'kg',quantity:'handling-unit'},configHash:hash(p),config:clone(p)};}
function unpack(d){if(d?.schemaVersion!==SCHEMA||d.deviceType!=='vertical_lift'||d.moduleVersion?.split('.')[0]!=='1'||d.units?.distance!=='m'||d.units?.speed!=='m/s'||d.units?.acceleration!=='m/s2'||d.units?.time!=='s'||d.units?.weight!=='kg'||d.units?.quantity!=='handling-unit')throw Error('지원하는 리프트 프로젝트 JSON / SI 단위가 아닙니다.');if(d.configHash&&hash(d.config)!==d.configHash)throw Error('프로젝트 입력 해시가 일치하지 않습니다.');const p=clone(d.config),v=validate(p);if(v.errors.length)throw Error(v.errors.join('\n'));return p;}
return {VERSION,SCHEMA,fields,sources,cargoDefaults,floor,autoOD,preset,clone,hash,batchLimit,motion,moveTime,bands,averageFactor,rates,validate,calculate,pack,unpack};
});
