(function(root){'use strict';
class Scene{
 constructor(host){this.host=host;this.run=null;this.time=0;this.actors=[];this.carGroups=[];this.ready=false;try{const T=THREE;this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.setClearColor(0xeaf0f3);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(this.renderer.domElement);this.world=new T.Scene();this.camera=new T.PerspectiveCamera(38,1,.05,1500);this.controls=new T.OrbitControls(this.camera,this.renderer.domElement);this.controls.mouseButtons.MIDDLE=T.MOUSE.PAN;this.controls.screenSpacePanning=true;this.controls.enableDamping=true;this.controls.dampingFactor=.1;this.controls.minDistance=2;this.controls.maxDistance=600;this.controls.maxPolarAngle=Math.PI*.53;this.world.add(new T.HemisphereLight(0xf8fcff,0x91a1ae,1.1));const sun=new T.DirectionalLight(0xfff4e5,.9);sun.position.set(12,40,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:50,bottom:-50,near:.1,far:200});sun.shadow.bias=-.0004;this.world.add(sun);this.group=new T.Group();this.dynamic=new T.Group();this.world.add(this.group,this.dynamic);this.ready=true;this.controls.addEventListener('change',()=>this.draw());}catch(e){this.host.textContent='3D를 초기화하지 못했습니다: '+e.message+' · Edge/Chrome의 그래픽 가속을 확인하세요. 계산 기능은 계속 사용할 수 있습니다.';}
 this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);
 }
 mat(color,opacity=1){return new THREE.MeshStandardMaterial({color,roughness:.6,metalness:.25,transparent:opacity<1,opacity});}
 box(g,w,h,d,x,y,z,color){if(arguments.length!==8||![w,h,d,x,y,z].every(Number.isFinite))throw Error('3D 박스 치수/좌표 오류');const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof color==='number'?this.mat(color):color);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 label(text,x,y,z,w=2.4){const c=document.createElement('canvas');c.width=512;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='rgba(248,252,254,.94)';ctx.fillRect(0,0,512,100);ctx.fillStyle='#315064';ctx.font='600 34px Segoe UI,Malgun Gothic';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,50,490);const map=new THREE.CanvasTexture(c);map.encoding=THREE.sRGBEncoding;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,depthTest:false}));sprite.position.set(x,y,z);sprite.scale.set(w,w*100/512,1);this.group.add(sprite);}
 dispose(g){const gs=new Set(),ms=new Set(),ts=new Set();g.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of !o.material?[]:Array.isArray(o.material)?o.material:[o.material]){ms.add(m);if(m.map)ts.add(m.map);}});gs.forEach(x=>x.dispose());ms.forEach(x=>x.dispose());ts.forEach(x=>x.dispose());g.clear();}
 conveyor(x,y,z,length){const p=this.p,w=p.platformLength;this.box(this.group,w,.18,length,x,y-.1,z,0x647c89);this.box(this.group,.1,.14,length,x-w/2,y+.02,z,0xbac8cd);this.box(this.group,.1,.14,length,x+w/2,y+.02,z,0xbac8cd);for(let s=-length/2+.12;s<length/2;s+=.25){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,w-.15,8),this.mat(0xb5c3ca));mesh.rotation.z=Math.PI/2;mesh.position.set(x,y-.005,z+s);this.group.add(mesh);}}
 build(p,fit=true){this.p=p;this.run=null;this.time=0;if(!this.ready)return;this.dispose(this.group);this.dispose(this.dynamic);this.actors=[];this.carGroups=[];this.gates=[];const T=THREE,L=p.platformLength,W=p.platformWidth;this.pitch=L+1.4;this.width=p.lifts*this.pitch;this.top=Math.max(...p.floors.map(f=>f.height))+p.clearHeight+1;const ground=this.box(this.group,this.width+7,.16,W+12,0,-.3,0,0xd6e0e6);ground.receiveShadow=true;const grid=new T.GridHelper(Math.max(20,this.width+8),Math.ceil(Math.max(20,this.width+8)),0x9eb4c1,0xc8d6df);grid.position.y=-.205;this.group.add(grid);
 for(let i=0;i<p.lifts;i++){const x=this.x(i+1);for(const dx of [-L/2-.22,L/2+.22])for(const z of [-W/2-.22,W/2+.22])this.box(this.group,.16,this.top,.16,x+dx,this.top/2,z,0x6c8594);for(const z of [-W/2-.22,W/2+.22]){this.box(this.group,L+.6,.18,.18,x,this.top-.1,z,0x335363);this.box(this.group,L+.6,.18,.18,x,.1,z,0x335363);}this.box(this.group,.6,.45,.6,x+L/2,this.top+.1,0,0x365869);this.box(this.group,.045,this.top,.07,x-L/2-.05,this.top/2,0,0x273e4b);this.box(this.group,.045,this.top,.07,x+L/2+.05,this.top/2,0,0x273e4b);this.label('LIFT '+String(i+1).padStart(2,'0'),x,this.top+.8,0,2);
 const car=new T.Group();this.dynamic.add(car);this.box(car,L,.2,W,0,-.12,0,0x128f8c);for(let z=-W/2+.12;z<W/2;z+=.22)this.box(car,L-.1,.045,.09,0,.005,z,0xc3d6dc);this.box(car,.1,.5,W, -L/2-.05,-.05,0,0x128f8c);this.box(car,.1,.5,W, L/2+.05,-.05,0,0x128f8c);car.position.set(x,p.floors.find(f=>f.id===p.homeFloor).height,0);this.carGroups.push(car);
 for(const f of p.floors){for(const side of [-1,1]){this.conveyor(x,f.height,side*(W/2+1.25),2.5);const gate=this.box(this.group,L,.12,.12,x,f.height+.75,side*(W/2+.15),0xdfa52b);this.gates.push({mesh:gate,lift:i+1,floor:f,side});for(const dx of [-L/2-.05,L/2+.05])this.box(this.group,.06,1.5,.06,x+dx,f.height+.6,side*(W/2+.15),0xc99b39);}}
 }
 for(const f of p.floors){this.box(this.group,this.width+1,.08,.3,0,f.height-.3,-W/2-2.7,0x97afbd);this.box(this.group,this.width+1,.08,.3,0,f.height-.3,W/2+2.7,0x97afbd);this.label(f.name+' · '+f.height.toFixed(2)+' m',-this.width/2-1.7,f.height+.4,0,3);}
 this.label('공용 입력 버퍼',0,.25,-W/2-4.4,3.2);this.label('공용 출력 버퍼',0,.25,W/2+4.4,3.2);this.resize();if(fit)this.fit();this.draw();
 }
 x(id){return (id-(this.p.lifts+1)/2)*this.pitch;}
 fit(view='iso'){if(!this.ready||!this.p)return;const d=Math.max(this.top*1.8,this.width*1.3,13),target=new THREE.Vector3(0,this.top*.45,0);this.controls.target.copy(target);if(view==='front')this.camera.position.set(0,target.y,d);else if(view==='top')this.camera.position.set(0,d+this.top,.01);else this.camera.position.set(d*.7,target.y+d*.38,d);this.controls.update();this.draw();}
 focus(id){if(!this.ready)return;const y=this.carGroups[id-1]?.position.y??this.top/2,delta=new THREE.Vector3(this.x(id),y,0).sub(this.controls.target);this.camera.position.add(delta);this.controls.target.add(delta);this.controls.update();}
 setRun(r){this.run=r;this.jobMap=new Map(r.items.map(j=>[j.id,j]));this.show(0);}
 cargo(c){const g=new THREE.Group(),h=c.height;g.userData.cargo=c.id;const color=parseInt(c.color.slice(1),16);if(c.kind==='pallet'){for(const z of [-c.width*.36,0,c.width*.36])this.box(g,c.length,.07,.12,0,.035,z,0x966b3a);for(let i=0;i<5;i++)this.box(g,c.length,.055,c.width/7,0,.097,-c.width*.4+i*c.width*.2,0xc79760);this.box(g,c.length*.94,Math.max(.02,h-.13),c.width*.94,0,.13+Math.max(.02,h-.13)/2,0,0xccad7e);this.box(g,.035,Math.max(.02,h-.13),c.width*.96,0,.13+Math.max(.02,h-.13)/2,0,0xe7d3ae);}else if(c.kind==='box'){this.box(g,c.length,h,c.width,0,h/2,0,color);this.box(g,.035,h+.002,c.width+.004,0,h/2,0,0xeed4a1);}else{this.box(g,c.length,.035,c.width,0,.02,0,color);for(const x of [-c.length/2+.025,c.length/2-.025])this.box(g,.05,h,c.width,x,h/2,0,color);for(const z of [-c.width/2+.025,c.width/2-.025])this.box(g,c.length,h,.05,0,h/2,z,color);this.box(g,c.length+.04,.035,c.width+.04,0,h,0,0x7bbace);}this.dynamic.add(g);return g;}
 show(t){this.time=t;if(!this.ready||!this.run){this.draw();return null;}const p=this.p,snap=LiftEngine.snapshot(this.run,t),W=p.platformWidth,used=new Set();let index=0;const put=(job,x,y,z)=>{if(!job||used.has(job.id)||index>=220)return;used.add(job.id);const c=p.cargo.find(c=>c.id===job.cargoId);let g=this.actors[index];if(!g||g.userData.cargo!==c.id){if(g){this.dynamic.remove(g);this.dispose(g);}g=this.cargo(c);this.actors[index]=g;}g.visible=true;g.position.set(x,y,z);index++;};
 for(const pose of snap.poses){const car=this.carGroups[pose.id-1];car.position.y=pose.y;const color=pose.state==='stopped'?0xc95f60:pose.state==='waitOut'||pose.state==='waitLoad'?0xdaa144:pose.state==='loaded'?0x0fa39a:0x168d99;car.children[0].material.color.setHex(color);const ids=pose.jobIds;ids.forEach((id,i)=>{const j=this.jobMap.get(id);if(!j)return;let onboard=j.loadedAt!==null&&j.loadedAt<=t&&(j.deliveredAt===null||j.deliveredAt>t),z=0;if(pose.phase==='loading'){onboard=true;z=-(W/2+1.25)*(1-pose.progress);}if(pose.phase==='unloading'){onboard=true;z=(W/2+1.25)*pose.progress;}if(onboard){const c=p.cargo.find(c=>c.id===j.cargoId),nx=Math.max(1,Math.floor((p.platformLength+p.cargoGap)/(c.length+p.cargoGap))),col=i%nx,row=Math.floor(i/nx),rows=Math.ceil(ids.length/nx);put(j,this.x(pose.id)+(col-(Math.min(nx,ids.length)-1)/2)*(c.length+p.cargoGap),pose.y+.045,z+(row-(rows-1)/2)*(c.width+p.cargoGap));}});
 }
 for(const fs of snap.floors){const f=p.floors.find(f=>f.id===fs.id);for(const [side,list]of [[-1,fs.input],[1,fs.output]])list.slice(0,8).forEach((j,i)=>{const c=p.cargo.find(c=>c.id===j.cargoId),col=i%Math.max(1,p.lifts),row=Math.floor(i/Math.max(1,p.lifts));put(j,this.x(col+1),f.height+.05,side*(W/2+1.3+row*(c.width+.15)));});}
 for(const g of this.gates){const pose=snap.poses[g.lift-1],near=Math.abs(pose.y-g.floor.height)<.05;let open=0;if(near){if(g.side===-1){if(pose.phase==='openLoad')open=pose.progress;else if(pose.phase==='loading')open=1;else if(pose.phase==='closeLoad')open=1-pose.progress;}else{if(pose.phase==='openUnload')open=pose.progress;else if(pose.phase==='unloading')open=1;else if(pose.phase==='closeUnload')open=1-pose.progress;}}g.mesh.position.y=g.floor.height+.75+open*Math.max(1,p.clearHeight-.6);}
 this.actors.forEach((g,i)=>{if(i>=index)g.visible=false;});this.controls.update();this.draw();return snap;
 }
 resize(){if(!this.ready)return;const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.draw();}
 draw(){if(this.ready)this.renderer.render(this.world,this.camera);}
}
root.LiftScene=Scene;
})(globalThis);
