'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.CONVEYOR_PLAYWRIGHT_PATH||'playwright');
const base=path.resolve(__dirname,'..'),qa=path.join(base,'qa'),url=pathToFileURL(path.resolve(base,'../컨베이어_실행.html')).href,checks=[],errors=[],requests=[];let browser,page;
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function settled(){await page.waitForFunction(()=>document.getElementById('runStatus').textContent.startsWith('계산 완료')&&!document.body.classList.contains('busy'),{},{timeout:30000});}
async function tab(name){await page.locator('[data-tab="'+name+'"]').click();}
async function download(id){const wait=page.waitForEvent('download');await page.locator('#'+id).click();const d=await wait,stream=await d.createReadStream(),chunks=[];for await(const c of stream)chunks.push(c);return {name:d.suggestedFilename(),bytes:Buffer.concat(chunks)};}
(async()=>{browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(url);await settled();
await check('offline file launch: 4 KPIs, Worker, no remote requests',async()=>{assert.equal(await page.locator('#kpis .kpi').count(),4);assert.equal(await page.locator('#message').isVisible(),false);assert.equal(requests.length,0);await page.screenshot({path:path.join(qa,'01_overview.png')});});
await check('3D WebGL rendering is available',async()=>{assert.equal(await page.locator('#scene > canvas').count(),1);assert.ok(!(await page.locator('#sceneStatus').textContent()).includes('2D'));assert.ok(await page.locator('#scene > canvas').evaluate(c=>!!c.getContext('webgl2')||!!c.getContext('webgl')));await page.locator('.scene-card').screenshot({path:path.join(qa,'02_scene.png')});});
await check('playback moves without changing final throughput',async()=>{const before=await page.locator('#kpis').textContent();await page.locator('#play').click();await page.waitForFunction(()=>Number(document.getElementById('seek').value)>65);await page.locator('#play').click();assert.equal(await page.locator('#kpis').textContent(),before);await page.locator('#rewind').click();assert.equal(await page.locator('#seek').inputValue(),'0');await page.locator('#top').click();await page.locator('#iso').click();});
await check('all seven templates calculate and conserve cargo',async()=>{for(const id of ['straight','merge','split','cross','u','loop','h']){await page.locator('[data-preset="'+id+'"]').click();await settled();assert.equal(await page.locator('#message').isVisible(),false,id);assert.equal(await page.locator('#balance').textContent(),'화물 보존 일치');}});
await check('layout input units, stale result protections and recompute',async()=>{await tab('layout');const speed=page.locator('#edgesTable [data-index="0"][data-key="speed"]');await speed.fill('18');await speed.dispatchEvent('change');assert.equal(await page.locator('#stale').isVisible(),true);assert.equal(await page.locator('#report').isDisabled(),true);await page.locator('#run').click();await settled();assert.equal(await page.locator('#stale').isVisible(),false);await page.screenshot({path:path.join(qa,'03_layout.png')});});
await check('invalid cargo dimensions are shown, prior results remain visibly stale',async()=>{await tab('demand');const length=page.locator('#cargoTable [data-index="0"][data-key="length"]');await length.fill('3000');await length.dispatchEvent('change');await page.locator('#run').click();assert.equal(await page.locator('#message').isVisible(),true);assert.ok((await page.locator('#message').textContent()).includes('피치'));await length.fill('1200');await length.dispatchEvent('change');await page.locator('#run').click();await settled();await page.screenshot({path:path.join(qa,'04_cargo.png')});});
await check('JSON round trip and rejected foreign project',async()=>{const d=await download('saveProject'),doc=JSON.parse(d.bytes);assert.equal(doc.deviceType,'conveyor');assert.equal(doc.config.edges[0].speed,.3);await page.locator('#projectFile').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:d.bytes});await settled();await page.locator('#projectFile').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from('{}')});assert.ok((await page.locator('#message').textContent()).includes('불러오기 실패'));});
await check('report, results CSV and integration exports are generated',async()=>{await tab('analysis');const csv=await download('csvResults');assert.ok(csv.bytes.toString('utf8').includes('처리량_HU/h'));const report=await download('report');assert.ok(report.bytes.toString('utf8').includes('물동량 결과'));fs.writeFileSync(path.join(qa,'sample-report.html'),report.bytes);await tab('integration');const data=JSON.parse((await download('exportInterface')).bytes);assert.equal(data.schemaVersion,'logistics/conveyor-interface@1');assert.ok(data.events.length>0);assert.equal(data.ports.length,4);await page.screenshot({path:path.join(qa,'05_integration.png')});});
await check('scenario snapshots and sensitivity compute actual alternate runs',async()=>{await tab('analysis');await page.locator('#pin').click();assert.equal(await page.locator('#comparisons tbody tr').count(),1);await page.locator('#sensitivity').click();await page.waitForFunction(()=>document.getElementById('runStatus').textContent==='개선 조건 비교 완료',{},{timeout:60000});assert.equal(await page.locator('#sensitivityResults tbody tr').count(),5);await page.screenshot({path:path.join(qa,'06_results.png')});});
await check('history CSV switches demand mode and completes two requests',async()=>{await page.locator('[data-preset="straight"]').click();await settled();await tab('demand');await page.locator('#historyFile').setInputFiles({name:'tasks.csv',mimeType:'text/csv',buffer:Buffer.from('id,release_s,flowId\nONE,10,OD1\nTWO,12,OD1')});await page.waitForFunction(()=>document.querySelector('[data-field="demandMode"]').value==='history');await page.locator('[data-field="warmup"]').fill('0');await page.locator('[data-field="warmup"]').dispatchEvent('change');await page.locator('#run').click();await settled();await tab('simulation');assert.ok((await page.locator('#summary').textContent()).includes('2 개'));});
await check('recompute in another tab preserves a rendered 3D scene',async()=>{const count=await page.locator('#scene > canvas').evaluate(c=>{const gl=c.getContext('webgl2')||c.getContext('webgl'),pixels=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,pixels);const colors=new Set();for(let i=0;i<pixels.length;i+=64)colors.add(pixels[i]+','+pixels[i+1]+','+pixels[i+2]);return colors.size;});assert.ok(count>30,'3D canvas is blank: '+count);});
await check('mobile page fits viewport and remains usable',async()=>{await page.setViewportSize({width:390,height:844});await page.locator('#resetCamera').click();await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(qa,'07_mobile.png'),fullPage:true});});
await check('no unhandled browser exceptions',async()=>assert.deepEqual(errors,[]));
await check('WebGL disabled has usable 2D replay fallback',async()=>{const other=await chromium.launch({channel:'msedge',headless:true,args:['--disable-webgl','--disable-3d-apis']});try{const pg=await other.newPage({viewport:{width:1400,height:1000}});await pg.goto(url);await pg.waitForFunction(()=>document.getElementById('runStatus').textContent.startsWith('계산 완료'));assert.ok((await pg.locator('#sceneStatus').textContent()).includes('2D'));await pg.locator('#play').click();await pg.waitForFunction(()=>Number(document.getElementById('seek').value)>65);await pg.screenshot({path:path.join(qa,'08_fallback.png')});}finally{await other.close();}});
fs.writeFileSync(path.join(qa,'browser-check.json'),JSON.stringify({passed:checks.length,checks,errors,remoteRequests:requests,runAt:new Date().toISOString()},null,2));console.log('PASS '+checks.length+' browser checks');await browser.close();})().catch(async e=>{console.error(e);if(page)await page.screenshot({path:path.join(qa,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(qa,'browser-check.json'),JSON.stringify({passed:checks.length,checks,errors,error:String(e)},null,2));if(browser)await browser.close();process.exitCode=1;});
