(function(){
 'use strict';const Model=LoopModel,E=LoopEngine,M=LoopMotion,V=LoopView,R=LoopReport,$=id=>document.getElementById(id),{esc,fmt,table,kpi}=V;
 let draft=Model.clone(Model.defaults),config,result,engine,scene,dirty=false,tab='overview',shownDistance='m',shownSpeed='m/min',shownHandling='total',simPlaying=false,simTarget=0,motionPlaying=false,motionTime=0,motionProfile=null,lastFrame=0,lastRender=0,bulkToken=0,experimentToken=0,experimentData=null,worker=null,workerPending=null,workerReady=false,workerSequence=0,toastTimer,pendingWorkbook=null,removedOds=[],writing=false;
 const selects=['distanceUnit','speedUnit','direction','unit','handlingMode','controlMode','dispatch','parking','analysisMode','etaMode','basis','arrival','demandMode','odTableMode','periodTableMode'];
 const groups={geometryFields:['horizontal','vertical','radius'],fleetFields:['vehicles','carLength','gap','batchSize'],emptyFields:['emptyV','emptyA','emptyD'],loadedFields:['loadedV','loadedA','loadedD'],zoneFields:['curveV'],handlingFields:['position','interlock','signal','control'],approachFields:['creepDistance','creepV'],controlFields:['blocks','reaction'],demandFields:['peak','targetUtil'],factorFields:['A','Ew'],etaFields:['beta','gamma'],simulationFields:['hours','warmup','seed','jitter','timeStep']};
 const defs={stations:{target:'stationsEditor',cols:[['id','ID','text'],['name','이름','text'],['s','위치 s','distance'],['load','상차','handling'],['unload','하차','handling'],['buffer','버퍼 개','integer'],['takeaway','반출 s/개','number']]},zones:{target:'zonesEditor',cols:[['from','시작 s','distance'],['to','끝 s','distance'],['v','제한속도','speed']]},ods:{target:'odsEditor',cols:[['id','OD ID','text'],['from','출발','station'],['to','도착','station'],['rate','평균 요구량 /h','number']]},profile:{target:'profileEditor',cols:[['start','시작 min','number'],['end','끝 min','number'],['multiplier','배율','number']]}};
 const unitScale=kind=>kind==='distance'?(shownDistance==='mm'?1000:1):kind==='speed'?(shownSpeed==='m/min'?60:1):1;
 const displayUnit=kind=>kind==='distance'?shownDistance:kind==='speed'?shownSpeed:kind==='ratio'?'비율 · 0~1':kind;
 function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
 function error(e){$('error').textContent=e.message;$('error').hidden=false;}
 function clearError(){$('error').hidden=true;}
 for(const[group,keys]of Object.entries(groups))$(group).innerHTML=keys.map(key=>{const[label,unit,,,,help]=Model.fields[key];return'<div class="field"><label for="'+key+'">'+esc(label)+'<span class="unit" data-unit="'+key+'">'+esc(unit)+'</span></label><button type="button" class="help" data-help="'+key+'" title="'+esc(help)+'" aria-label="'+esc(label)+' 도움말">?</button><input id="'+key+'" type="number" step="any"></div>';}).join('');
 const help=document.createElement('dialog');help.id='helpDialog';help.innerHTML='<h2></h2><p></p><button type="button">닫기</button>';document.body.append(help);help.querySelector('button').onclick=()=>help.close();document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{const[label,u,min,max,,text]=Model.fields[b.dataset.help];help.querySelector('h2').textContent=label;help.querySelector('p').textContent=text+' 입력 범위 '+fmt(min*unitScale(u),3)+'~'+fmt(max*unitScale(u),3)+' '+displayUnit(u);help.showModal();});
 function read(check=true){const c=Model.clone(draft);for(const[key,[,u]]of Object.entries(Model.fields))c[key]=$(key).value.trim()===''?NaN:Number($(key).value)/unitScale(u);for(const key of selects)c[key]=$(key).value;c.name=$('name').value;c.basisNote=$('basisNote').value;const overhead=c.position+c.interlock+c.signal;
  for(const[key,def]of Object.entries(defs))c[key]=[...$(def.target).querySelectorAll('tbody tr')].map((row,i)=>{const x={...(draft[key][i]||{})};for(const[field,,kind]of def.cols){const input=row.querySelector('[data-key="'+field+'"]');x[field]=['text','station'].includes(kind)?input.value.trim():input.value.trim()===''?NaN:Number(input.value)/unitScale(kind);if(kind==='handling'&&shownHandling==='detail')x[field]+=overhead;}return x;});return check?Model.validate(c):c;
 }
 function write(c){writing=true;try{c={...c,...LoopTables.modes(c)};draft=Model.clone(c);shownDistance=c.distanceUnit;shownSpeed=c.speedUnit;shownHandling=c.handlingMode;for(const[key,[,u,min,max]]of Object.entries(Model.fields)){const input=$(key);input.value=Number((c[key]*unitScale(u)).toPrecision(12));input.min=min*unitScale(u);input.max=max*unitScale(u);document.querySelector('[data-unit="'+key+'"]').textContent=displayUnit(u);}for(const key of selects)$(key).value=c[key];$('name').value=c.name;$('basisNote').value=c.basisNote;editors();}finally{writing=false;}}
 function editors(){const c=draft,overhead=c.position+c.interlock+c.signal;for(const[key,def]of Object.entries(defs)){$(def.target).innerHTML=c[key].length?'<div class="table-scroll"><table><thead><tr><th>#</th>'+def.cols.map(([,label,kind])=>'<th>'+esc(label)+(['distance','speed'].includes(kind)?' ('+displayUnit(kind)+')':kind==='handling'?(shownHandling==='detail'?' 순수 s':' 총 s'):'')+'</th>').join('')+'<th></th></tr></thead><tbody>'+c[key].map((row,i)=>'<tr><td>'+(i+1)+'</td>'+def.cols.map(([field,label,kind])=>{const a=' data-key="'+field+'" aria-label="'+esc(key+' '+(i+1)+' '+label)+'"',v=kind==='handling'&&shownHandling==='detail'?row[field]-overhead:typeof row[field]==='number'?Number((row[field]*unitScale(kind)).toPrecision(12)):row[field];return'<td>'+(kind==='station'?'<select'+a+'>'+c.stations.map(s=>'<option value="'+esc(s.id)+'"'+(s.id===v?' selected':'')+'>'+esc(s.id+' · '+s.name)+'</option>').join('')+(!c.stations.some(s=>s.id===v)?'<option selected value="'+esc(v)+'">'+esc(v)+' (확인 필요)</option>':'')+'</select>':'<input'+a+' type="'+(kind==='text'?'text':'number')+'" value="'+esc(v)+'"'+(kind==='text'?' maxlength="80"':' step="any"')+'>')+'</td>';}).join('')+'<td><button type="button" data-remove="'+key+'" data-row="'+i+'">삭제</button></td></tr>').join('')+'</tbody></table></div>':'<p class="empty-state">'+(key==='profile'?'시간대 미지정 · 전체 1배':'등록된 항목이 없습니다.')+'</p>';}
  $('handlingHint').textContent=shownHandling==='total'?'정위치·인터록·신호를 포함한 총 시간입니다.':'순수 이재시간에 공통 지연 '+fmt(overhead,2)+' s를 더합니다.';$('historyStatus').textContent='작업이력 '+c.history.length+'건 · '+(c.demandMode==='history'?'CSV 모드':'OD 모드');$('historyPreview').innerHTML=table(['time_s','from','to','quantity'],c.history.slice(0,8).map(j=>[j.time,j.from,j.to,j.quantity]));$('demandTableStatus').textContent='스테이션 '+c.stations.length+'개 · 같은 번호 P/D '+LoopTables.paired(c.stations).pairs.length+'쌍 · OD '+c.ods.length+'행 · 시간대 '+c.profile.length+'행. 새 OD의 물동량을 입력한 후 계산 및 설정 적용을 누르세요.';
 }
 function stop(){simPlaying=false;motionPlaying=false;bulkToken++;$('simPlay').textContent='▶ 시뮬레이션 재생';$('motionPlay').textContent='▶ 동작 재생';$('simFinish').disabled=false;}
 function cancel(){experimentToken++;if(workerPending){worker?.terminate();worker=null;workerReady=false;workerPending.reject(Error('cancelled'));workerPending=null;$('runtime').textContent='OFFLINE · 분할 계산';}$('runExperiments').disabled=false;$('cancelExperiments').disabled=true;if(experimentData)$('experimentStatus').textContent='중단됨 · 완료된 결과 보존';}
 function markDirty(){clearError();dirty=true;document.body.dataset.dirty='true';$('dirtyNotice').hidden=false;stop();cancel();}
 function fresh(){if(dirty||!result){toast('계산 및 설정 적용으로 변경 내용을 반영하세요.');return false;}return true;}
 function apply(){try{const c=read(),r=Model.calculate(c),e=new E.Engine(c);stop();cancel();scene?.dispose();scene=null;config=c;draft=Model.clone(c);result=r;engine=e;simTarget=0;dirty=false;document.body.dataset.dirty='false';$('dirtyNotice').hidden=true;clearError();$('projectSummary').textContent=c.name+' · '+fmt(r.L,2)+' m / '+c.vehicles+'대 · '+(c.direction==='forward'?'+s':'−s')+' 방향';$('fleetMax').max=r.maxFleet;$('fleetMax').value=Math.min(Number($('fleetMax').value)||20,r.maxFleet);renderAnalysis();motionOptions();renderMotion();renderSimulation();experimentData=null;$('experimentResults').innerHTML='<p class="empty-state">대수별 실험을 시작하세요.</p>';$('experimentChart').innerHTML='';$('experimentProgress').value=0;$('exportExperiments').disabled=true;$('experimentStatus').textContent='현재 적용 조건 · 유효 대수 1~'+r.maxFleet;return true;}catch(e){markDirty();error(e);return false;}}
 function renderAnalysis(){const r=result,c=config,u=c.unit+'/h';$('analysisKpis').innerHTML=kpi('경험 보정 추정',fmt(r.current.available),u,'A × Ew × η · 실제 달성량과 구분',true)+kpi('무간섭 참고 능력',fmt(r.current.theory),u,'차량·스테이션 업무량 기준')+kpi('전체 요구 물동량',fmt(r.total),u,c.demandMode==='history'?'측정구간 이력 평균':'피크·시간대 최대 반영')+kpi('경험식 최소 대수',r.recommended??'—','대','목표 부하율 '+fmt(c.targetUtil*100,0)+'% 기준');$('analysisNotice').innerHTML='<ul>'+r.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul>';$('overviewScene').innerHTML=V.layout(c,engine.snapshot());$('trackTag').textContent=c.vehicles+'대 / 정적 한계 '+r.nMax+'대';
  $('fleetChart').innerHTML=V.line([{color:'#93aebd',points:r.rows.map(x=>({x:x.n,y:x.theory}))},{color:'#128f83',points:r.rows.map(x=>({x:x.n,y:x.available}))},{color:'#c59951',points:[{x:1,y:r.total},{x:r.maxFleet,y:r.total}]}],{xMax:r.maxFleet,xLabel:'차량 수 N',yLabel:'화물 /h'});
  $('fleetAdvice').innerHTML=table(['항목','값'],[['현재 / 정적 수용 한계',c.vehicles+' / '+r.nMax+'대'],['평균 차량 사이클',fmt(r.cycle,2)+' s'],['평균 적재 / 공차',fmt(r.loadedDistance)+' / '+fmt(r.emptyDistance)+' m'],['수요/경험 추정',fmt(r.current.ratio===null?null:r.current.ratio*100)+'%'],['목표부하 고려 부족량',fmt(r.current.shortage)+' '+u],['간섭 η(N)',fmt(r.current.eta,3)],['교통 계산 간격',fmt(r.dt,4)+' s']]);
  $('odResults').innerHTML=table(['OD','수요 /h','적재 m','공차 m','적재 s','공차 s','상차 s','하차 s','사이클 s'],r.legRows.map(x=>[x.from+'→'+x.to,fmt(x.rate),fmt(x.loadedDistance),fmt(x.emptyDistance),fmt(x.loadedTime,2),fmt(x.emptyTime,2),fmt(x.load),fmt(x.unload),fmt(x.cycle,2)]));$('stationResults').innerHTML=table(['스테이션','이재·제어 부하 %','반출 부하 %','이재 기준 능력 /h'],r.stations.map(s=>[s.id,fmt(s.work/36),fmt(s.releaseWork/36),fmt(s.capacity)]));$('fleetResults').innerHTML=table(['N','η','무간섭 /h','경험 /h','수요/능력 %'],r.rows.map(x=>[x.n,fmt(x.eta,3),fmt(x.theory),fmt(x.available),fmt(x.ratio===null?null:x.ratio*100)]));$('distanceMatrix').innerHTML=table(['출발/도착',...c.stations.map(s=>s.id)],c.stations.map(a=>[a.id,...c.stations.map(b=>fmt(Model.distance(c,a.s,b.s),3))]));
 }
 function clock(t){return[String(Math.floor(t/3600)).padStart(2,'0'),String(Math.floor(t/60)%60).padStart(2,'0'),String(Math.floor(t)%60).padStart(2,'0')].join(':');}
 function ensureScene(){if(!scene){scene=new LoopScene.Scene($('simScene'),config,i=>{$('sceneVehicle').value=i;sceneInfo();});$('sceneVehicle').innerHTML=engine.cars.map((c,i)=>'<option value="'+i+'">'+c.id+'</option>').join('');scene.setLabels($('sceneLabels').checked);scene.follow=$('sceneFollow').checked;scene.update(engine);if(scene.follow)scene.setView('selected');}scene.update(engine);$('sceneMode').textContent=scene.fallback?'2D 대체 표시':'3D · ALL RGVs';for(const id of ['viewIso','viewTop','viewFront','viewSelected','sceneLabels','sceneFollow'])$(id).disabled=!!scene.fallback;}
 function sceneInfo(){if(!engine)return;const car=engine.cars[Number($('sceneVehicle').value)||0]||engine.cars[0],p=engine.pose(car);$('sceneSelection').textContent=car.id+' · '+E.states[car.state]+' · s '+fmt(p.s,2)+' m · '+fmt(p.v*(config.speedUnit==='m/min'?60:1),2)+' '+config.speedUnit+(car.job?' · '+car.job.id+' / '+car.quantity+'개':'');}
 function renderSimulation(){if(!engine)return;const s=engine.snapshot(),c=config,u=c.unit+'/h';$('simKpis').innerHTML=kpi('최종 목적지 완료',fmt(s.throughput),u,'측정구간 실제 하차량',true)+kpi('외부 출하',fmt(s.shippingRate),u,'출고 버퍼 실제 반출량')+kpi('미배차 대기',fmt(s.waiting,0),'개','진행 '+s.active+' / 출고 버퍼 '+s.output)+kpi('P95 최초 배차 대기',fmt(s.p95Wait),'s','미배차 최장 '+fmt(s.oldest)+' s');$('simNotice').textContent=R.status(s)+' · '+c.vehicles+'대 · '+(c.controlMode==='block'?'블록 점유·예약':'간격 추종')+' · 계산 간격 '+fmt(s.dt,4)+' s · 보정계수 추가 적용 없음'+(s.gridlock?' · 교착 징후: 대기 정책·밀도·블록을 확인하세요.':'')+(s.failed?' · '+s.failed:'');$('simNotice').className='notice'+(s.failed||s.gridlock?' warning':' subtle');if(tab==='simulation')ensureScene();sceneInfo();$('simClock').textContent=clock(s.time);$('simEnd').textContent=clock(s.horizon);$('simSeek').value=s.time/s.horizon*1000;
  $('carStats').innerHTML=table(['차량','상태','작업','s m','속도 '+c.speedUnit,'작업가동 %','취급 /h','공차거리 %'],s.cars.map(x=>[x.id,E.states[x.state],x.job||'—',fmt(x.s,2),fmt(x.v*(c.speedUnit==='m/min'?60:1),2),fmt(x.busy*100),fmt(x.throughput),fmt(x.emptyRatio*100)]));$('conservation').textContent='화물 보존 '+(s.conserved?'✓ 정상':'오류')+' · 생성 '+s.created+' = 외부 출하 '+s.shipped+' + 대기 '+s.waiting+' + 진행 '+s.active+' + 출고 버퍼 '+s.output;
  $('queueChart').innerHTML=V.line([{color:'#c59951',points:engine.series.map(p=>({x:p.time/60,y:p.queue}))},{color:'#138e85',points:engine.series.map(p=>({x:p.time/60,y:p.wip}))}],{xMax:s.horizon/60,xLabel:'운전시간 min',yLabel:'미배차(황색) / WIP(녹색)'});const total=s.measuredTime*c.vehicles;$('stateChart').innerHTML=Object.keys(E.states).map(k=>{const value=s.cars.reduce((n,x)=>n+x.stateTime[k],0);return'<div class="bar"><div class="bar-label"><span>'+E.states[k]+'</span><b>'+fmt(value)+' s</b></div><div class="bar-track"><span style="background:'+V.colors[k]+';width:'+Math.min(100,total?value/total*100:0)+'%"></span></div></div>';}).join('');$('bufferStats').innerHTML=table(['버퍼','현재','예약','용량','최대','이재 점유 %'],s.stations.map(b=>[b.id,b.count,b.reserved,b.capacity,b.max,fmt(b.busy*100)]));$('trafficStats').innerHTML=table(['지표','관측값'],[['최소 실제 차체 간격',fmt(s.minGap,5)+' m'],['입력 최소 간격',fmt(c.gap,3)+' m'],['간격 조건',s.gapOK?'정상':'침범'],['평균 / 최대 대기열',fmt(s.meanQueue)+' / '+s.maxQueue],['요구량 / 관측 완료',s.throughput?fmt(result.total/s.throughput*100)+'%':'미산정']]);$('blockStats').innerHTML=c.controlMode==='block'?table(['블록','점유·예약 차량'],s.blocks.map((owner,i)=>[i+1,owner===null?'빈 블록':s.cars[owner].id])):'<p class="muted">연속 간격 추종 · 고정 블록은 사용하지 않습니다.</p>';
 }
 function motionODs(){const rows=Model.demand(config);return rows.length?rows:[{id:'경로 예시',from:config.stations[0].id,to:config.stations.at(-1).id}];}
 function motionOptions(){$('motionOd').innerHTML=motionODs().map((o,i)=>'<option value="'+i+'">'+esc(o.from+' → '+o.to)+'</option>').join('');}
 function renderMotion(){if(!config)return;const od=motionODs()[Number($('motionOd').value)||0],loaded=$('motionKind').value==='loaded',from=config.stations.find(s=>s.id===od[loaded?'from':'to']).s,to=config.stations.find(s=>s.id===od[loaded?'to':'from']).s,graphs=V.motion(config,from,to,loaded);motionProfile=graphs.profile;motionTime=0;motionPlaying=false;$('motionPlay').textContent='▶ 동작 재생';$('speedGraph').innerHTML=graphs.speed;$('positionGraph').innerHTML=graphs.position;$('accelGraph').innerHTML=graphs.acceleration;$('motionDescription').textContent=(loaded?'적재':'공차')+' · '+fmt(from,2)+' → '+fmt(to,2)+' m · 이동거리 '+fmt(motionProfile.length,2)+' m · '+fmt(motionProfile.duration,3)+' s. 이재·교통 대기 제외.';updateMotion();}
 function updateMotion(){if(!motionProfile)return;const p=M.at(motionProfile,motionTime);$('motionSeek').value=motionProfile.duration?motionTime/motionProfile.duration*1000:0;$('motionClock').textContent=fmt(motionTime,2)+' / '+fmt(motionProfile.duration,2)+' s';$('motionValues').textContent=p.label+' · 누적거리 '+fmt(p.x-motionProfile.from,3)+' m · s '+fmt(Model.physical(config,p.x),3)+' m · '+fmt(p.v*(config.speedUnit==='m/min'?60:1),3)+' '+config.speedUnit;}
 function setTab(name){tab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);if(name==='simulation')renderSimulation();}
 function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
 const filename=suffix=>(config?.name||'LoopRGV').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,60)+suffix;
 function removedCsv(rows){return R.csv([['OD ID','출발 ID','도착 ID','요구 물동량 (개/h)'],...rows.map(o=>[o.id,o.from,o.to,o.rate])]);}
 function rememberRemoved(rows){if(!rows.length)return;removedOds=Model.clone(rows);$('downloadRemovedOds').hidden=false;}
 function tableFeedback(sync){rememberRemoved(sync.removed);const messages=['스테이션 기준 갱신 · 기존 OD 물동량 유지 · 새 OD '+sync.added.length+'행(0개/h)'];if(sync.profileCreated)messages.push('시간대 '+sync.config.profile.length+'행 생성');if(sync.removed.length)messages.push('미등록 스테이션을 참조한 OD '+sync.removed.length+'행 제외 · CSV로 보관 가능');messages.push(...sync.warnings);$('demandTableStatus').textContent=messages.join(' · ');}
 function mutate(fn,tableOptions){try{const c=read(false);fn(c);const sync=tableOptions?LoopTables.reconcile(c,tableOptions):null;if(sync?.orphanedHistory.length)throw Error('작업이력에서 사용 중인 스테이션입니다. 해당 작업이력을 수정하거나 비운 후 변경하세요.');write(sync?sync.config:c);markDirty();if(sync)tableFeedback(sync);}catch(e){error(e);}}
 function syncTables(options={}){mutate(()=>{},options);}
 const newId=(prefix,list)=>{let n=1;while(list.some(x=>x.id===prefix+n))n++;return prefix+n;};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('configForm').onsubmit=e=>{e.preventDefault();apply();};
 document.addEventListener('input',e=>{if(writing)return;if(e.target.closest('#configForm,[data-panel="layout"],[data-panel="demand"]'))markDirty();});
 document.addEventListener('change',e=>{if(writing)return;const target=e.target;if(['distanceUnit','speedUnit','handlingMode'].includes(target.id)){mutate(()=>{});return;}
  if(target.closest('#stationsEditor')){const row=target.closest('tr').rowIndex-1,old=draft.stations[row]?.id,next=target.closest('tr').querySelector('[data-key="id"]').value.trim(),renames=old&&old!==next?{[old]:next}:{};syncTables({renames});return;}
  if(['hours','warmup','odTableMode','periodTableMode'].includes(target.id)){syncTables({rebuildProfile:target.id!=='odTableMode'});return;}
  if(target.closest('#profileEditor')&&target.dataset.key!=='multiplier')$('periodTableMode').value='manual';
  if(target.closest('#odsEditor')&&['from','to'].includes(target.dataset.key))$('odTableMode').value='manual';
  if(target.closest('#configForm,[data-panel="layout"],[data-panel="demand"]'))markDirty();
 });
 document.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){const key=b.dataset.remove;mutate(c=>{c[key].splice(Number(b.dataset.row),1);if(key==='ods')c.odTableMode='manual';if(key==='profile')c.periodTableMode='manual';},key==='stations'?{}:null);}});
 $('syncDemandTables').onclick=()=>syncTables({rebuildProfile:true});$('downloadRemovedOds').onclick=()=>download('LoopRGV_최근_제외OD.csv',removedCsv(removedOds),'text/csv;charset=utf-8');
 $('calculate').onclick=()=>{if(apply())toast('현재 조건을 계산과 시뮬레이션에 적용했습니다.');};$('loadPreset').onclick=()=>{write(LoopTables.reconcile(Model.preset($('preset').value)).config);if(apply())toast('설명용 예시 적용');};$('addStation').onclick=()=>mutate(c=>{if(c.stations.length>=Model.LIMITS.stations)throw Error('스테이션은 최대 '+Model.LIMITS.stations+'개입니다.');c.stations.push({id:newId('S',c.stations),name:'스테이션',s:Model.length(c)/2,load:6,unload:6,buffer:Math.max(8,c.batchSize),takeaway:0});},{});$('addZone').onclick=()=>mutate(c=>c.zones.push({from:Model.length(c)*.2,to:Model.length(c)*.3,v:.8}));$('addOd').onclick=()=>mutate(c=>{if(!c.stations.length)throw Error('스테이션을 먼저 등록하세요.');c.ods.push({id:newId('OD',c.ods),from:c.stations[0].id,to:c.stations.at(-1).id,rate:0});});$('addPeriod').onclick=()=>mutate(c=>{if(c.profile.length>=Model.LIMITS.profile)throw Error('시간대는 최대 '+Model.LIMITS.profile+'개입니다.');c.periodTableMode='manual';const last=c.profile.at(-1),start=last?.end||0,end=c.warmup+c.hours*60;if(start<end-1e-8)c.profile.push({start,end:Math.min(start+60,end),multiplier:1});else if(last&&last.end-last.start>1e-6){const finish=last.end;last.end=(last.start+last.end)/2;c.profile.push({start:last.end,end:finish,multiplier:last.multiplier});toast('마지막 시간대를 두 행으로 나눴습니다. 시작·끝과 배율을 편집하세요.');}else throw Error('기존 시간대의 시작·끝을 먼저 확인하세요.');});

 function workbookExperiment(){return Object.fromEntries(['fleetMin','fleetMax','fleetStep','repCount'].map(k=>[k,Number($(k).value)]));}
 function workbookStatus(message,failed=false){$('excelStatus').hidden=false;$('excelStatus').textContent=message;$('excelStatus').className='notice '+(failed?'error':'subtle');}
 function workbookFailure(e){workbookStatus(e.message,true);$('excelStatus').scrollIntoView({block:'center',behavior:'smooth'});}
 $('saveWorkbook').onclick=()=>{try{const c=read(),e=workbookExperiment(),blob=LoopExcel.write(c,e);download(c.name.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,60)+'_LoopRGV_입력조건.xlsx',blob,blob.type);workbookStatus('현재 입력조건과 스테이션·OD·시간대·제한속도·작업이력·실험조건을 엑셀로 저장했습니다.');}catch(e){workbookFailure(e);}};
 $('loadWorkbook').onclick=()=>{$('workbookFile').value='';$('workbookFile').click();};
 function applyWorkbook(imported,name){Model.calculate(imported.config);write(imported.config);if(!apply())throw Error($('error').textContent);for(const[k,v]of Object.entries(imported.experiment))$(k).value=v;const repair=imported.repair;rememberRemoved(repair?.removed||[]);if(repair)tableFeedback({...repair,config,profileCreated:repair.profileCreated});$('workbookReview').hidden=true;pendingWorkbook=null;workbookStatus(name+' 적용 완료 · 스테이션 '+config.stations.length+'개 · OD '+config.ods.length+'개 · 시간대 '+config.profile.length+'개'+(repair?.removed.length?' · 미등록 스테이션 OD '+repair.removed.length+'행 제외':'')+(repair?.added.length?' · 새 OD '+repair.added.length+'행(0개/h)':'')+'. 이전 실행 결과는 초기화되었습니다.');toast('엑셀 입력조건을 적용했습니다.');}
 $('workbookFile').onchange=async()=>{const f=$('workbookFile').files[0];if(!f)return;pendingWorkbook=null;$('workbookReview').hidden=true;$('loadWorkbook').disabled=true;$('saveWorkbook').disabled=true;workbookStatus('엑셀 입력값을 확인하고 있습니다…');try{const imported=await LoopExcel.read(f,{reconcile:true});Model.calculate(imported.config);if(imported.repair.removed.length){pendingWorkbook={imported,name:f.name};const missing=[...new Set(imported.repair.removed.flatMap(o=>[o.from,o.to]).filter(id=>!imported.config.stations.some(s=>s.id===id)))];workbookStatus('스테이션 기준으로 OD를 정리할 수 있습니다. 아래 내용을 확인하고 정리·적용을 누르세요. 현재 입력과 계산 결과는 유지 중입니다.');$('workbookReviewSummary').textContent='미등록 ID '+missing.length+'개: '+missing.join(', ')+' / 제외 OD '+imported.repair.removed.length+'행 · 유지 OD '+(imported.config.ods.length-imported.repair.added.length)+'행 · 새 OD '+imported.repair.added.length+'행(0개/h)';$('workbookReviewRows').innerHTML=table(['엑셀 행','OD ID','출발 ID','도착 ID','물동량 /h'],imported.repair.removed.map((o,i)=>[imported.repair.removedRowNumbers[i],o.id,o.from,o.to,o.rate]));$('workbookReview').hidden=false;$('workbookReview').scrollIntoView({block:'start'});}else applyWorkbook(imported,f.name);}catch(e){workbookFailure(e);}finally{$('loadWorkbook').disabled=false;$('saveWorkbook').disabled=false;}};
 $('applyWorkbookRepair').onclick=()=>{if(!pendingWorkbook)return;try{applyWorkbook(pendingWorkbook.imported,pendingWorkbook.name);}catch(e){workbookFailure(e);}};
 $('downloadWorkbookRemoved').onclick=()=>{if(pendingWorkbook)download('LoopRGV_제외OD_원본.csv',removedCsv(pendingWorkbook.imported.repair.removed),'text/csv;charset=utf-8');};
 $('cancelWorkbookRepair').onclick=()=>{pendingWorkbook=null;$('workbookReview').hidden=true;workbookStatus('엑셀 불러오기를 취소했습니다. 이전 입력과 계산 결과를 유지합니다.');};
 $('saveProject').onclick=()=>{try{download(filename('_LoopRGV.json'),JSON.stringify(Model.pack(read()),null,2),'application/json;charset=utf-8');}catch(e){error(e);}};$('loadProject').onclick=()=>{$('projectFile').value='';$('projectFile').click();};$('projectFile').onchange=async()=>{const f=$('projectFile').files[0];if(!f)return;try{if(f.size>10000000)throw Error('프로젝트는 10MB 이하여야 합니다.');write(LoopTables.reconcile(Model.unpack(JSON.parse(await f.text()))).config);if(apply())toast('프로젝트를 불러왔습니다.');}catch(e){error(e);}};
 $('historyTemplate').onclick=()=>download('LoopRGV_작업이력_양식.csv',R.csv([['time_s','from','to','quantity'],[0,'P1','D1',1],[60,'P2','D2',1]]),'text/csv;charset=utf-8');$('importHistory').onclick=()=>{$('historyFile').value='';$('historyFile').click();};$('historyFile').onchange=async()=>{const f=$('historyFile').files[0];if(!f)return;try{if(f.size>5000000)throw Error('CSV는 5MB 이하여야 합니다.');const c=read(false);c.history=R.parseCSV(await f.text());c.demandMode='history';write(Model.validate(c));markDirty();toast(c.history.length+'건을 읽었습니다. 설정을 적용하세요.');}catch(e){error(e);}};$('clearHistory').onclick=()=>mutate(c=>{c.history=[];c.demandMode='rate';});
 $('simPlay').onclick=()=>{if(!fresh())return;bulkToken++;$('simFinish').disabled=false;if(engine.time>=engine.horizon-1e-7)engine=new E.Engine(config);simPlaying=!simPlaying;simTarget=engine.time;$('simPlay').textContent=simPlaying?'Ⅱ 일시정지':'▶ 시뮬레이션 재생';};$('simStep').onclick=()=>{if(!fresh())return;stop();engine.advanceTo(Math.min(engine.horizon,(engine.tick+1)*engine.dt));renderSimulation();};$('simReset').onclick=()=>{if(!fresh())return;stop();engine=new E.Engine(config);renderSimulation();};$('simSeek').onchange=()=>{if(!fresh())return;stop();const target=Number($('simSeek').value)/1000*engine.horizon;if(target<engine.time)engine=new E.Engine(config);try{engine.advanceTo(target);renderSimulation();}catch(e){error(e);}};
 $('simFinish').onclick=async()=>{if(!fresh())return;stop();const token=++bulkToken;$('simFinish').disabled=true;try{while(engine.time<engine.horizon-1e-7&&token===bulkToken){engine.advanceTo(Math.min(engine.horizon,engine.time+30));if(tab==='simulation')renderSimulation();await new Promise(r=>setTimeout(r,0));}if(token===bulkToken)renderSimulation();}catch(e){error(e);renderSimulation();}finally{if(token===bulkToken)$('simFinish').disabled=false;}};
 for(const[id,view]of [['viewIso','iso'],['viewTop','top'],['viewFront','front'],['viewSelected','selected']])$(id).onclick=()=>{if(!fresh())return;ensureScene();if(view!=='selected'){$('sceneFollow').checked=false;scene.follow=false;}scene.setView(view);};$('sceneVehicle').onchange=()=>{if(!fresh())return;ensureScene();scene.select($('sceneVehicle').value);sceneInfo();};$('sceneFollow').onchange=()=>{if(!fresh())return;ensureScene();scene.follow=$('sceneFollow').checked;if(scene.follow)scene.setView('selected');};$('sceneLabels').onchange=()=>scene?.setLabels($('sceneLabels').checked);
 $('applyMotion').onclick=()=>{if(fresh())renderMotion();};$('motionPlay').onclick=()=>{if(!fresh()||!motionProfile)return;if(motionTime>=motionProfile.duration)motionTime=0;motionPlaying=!motionPlaying;$('motionPlay').textContent=motionPlaying?'Ⅱ 일시정지':'▶ 동작 재생';};$('motionSeek').oninput=()=>{if(!fresh()||!motionProfile)return;motionPlaying=false;motionTime=Number($('motionSeek').value)/1000*motionProfile.duration;updateMotion();};
 $('exportJobs').onclick=()=>{if(fresh())download(filename('_완료작업.csv'),R.csv([['job_id','from','to','quantity','arrival_s','dispatch_s','complete_s','wait_s','lead_s','measurement_window','seed'],...engine.logs.map(j=>[j.id,j.from,j.to,j.quantity,j.arrival,j.dispatch,j.complete,j.wait,j.lead,j.measured,config.seed])]),'text/csv;charset=utf-8');};$('exportReport').onclick=()=>{if(fresh())download(filename('_계산서.md'),R.markdown(result,engine.snapshot()),'text/markdown;charset=utf-8');};$('pdfReport').onclick=()=>{if(fresh())$('pdfOptions').showModal();};$('pdfCancel').onclick=()=>$('pdfOptions').close();$('pdfForm').onsubmit=e=>{e.preventDefault();if(!fresh())return;const popup=window.open('','_blank');if(!popup){error(Error('팝업이 차단되었습니다. 이 파일의 팝업을 허용하고 다시 시도하세요.'));return;}const meta=Object.fromEntries(['documentNo','recipient','author','reviewer'].map(k=>[k,$(k).value]));popup.document.open();popup.document.write(R.html(result,engine.snapshot(),meta));popup.document.close();popup.document.getElementById('printPdf').onclick=()=>popup.print();$('pdfOptions').close();};
 function setupWorker(){try{const code=['motion','model','engine'].map(id=>document.querySelector('script[data-module="'+id+'"]').textContent).join('\n')+'\nonmessage=function(e){if(e.data.type==="ping"){postMessage({type:"ready"});return;}try{const s=LoopEngine.run(e.data.config).snapshot();postMessage({type:"result",id:e.data.id,result:s});}catch(error){postMessage({type:"error",id:e.data.id,error:error.message});}};';const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{const x=e.data;if(x.type==='ready'){workerReady=true;$('runtime').textContent='OFFLINE · Worker OK';}else if(workerPending&&x.id===workerPending.id){const p=workerPending;workerPending=null;x.type==='error'?p.reject(Error(x.error)):p.resolve(x.result);}};worker.onerror=e=>{e.preventDefault();workerReady=false;worker?.terminate();worker=null;if(workerPending){workerPending.reject(Error('계산 Worker 오류'));workerPending=null;}$('runtime').textContent='OFFLINE · 분할 계산';};worker.postMessage({type:'ping'});}catch{worker=null;workerReady=false;$('runtime').textContent='OFFLINE · 분할 계산';}}
 async function trial(c,token){if(workerReady&&worker)return await new Promise((resolve,reject)=>{const id=++workerSequence;workerPending={id,resolve,reject};worker.postMessage({id,config:c});});const e=new E.Engine(c);while(e.time<e.horizon-1e-7){if(token!==experimentToken)throw Error('cancelled');e.advanceTo(Math.min(e.horizon,e.time+60));await new Promise(r=>setTimeout(r,0));}return e.snapshot();}
 function renderExperiments(){if(!experimentData)return;const rows=experimentData.counts.map(n=>{const runs=experimentData.runs.filter(r=>r.n===n);return{n,runs,flow:E.interval95(runs.map(r=>r.throughput)),wait:E.interval95(runs.map(r=>r.waiting)),p95:E.interval95(runs.map(r=>r.p95Wait))};});$('experimentChart').innerHTML=V.line([{color:'#148f83',dots:true,points:rows.filter(r=>r.flow.n).map(r=>({x:r.n,y:r.flow.mean}))},{color:'#c69d59',points:[{x:rows[0].n,y:result.total},{x:rows.at(-1).n,y:result.total}]}],{xMax:rows.at(-1).n,xLabel:'차량 수 N',yLabel:'관측 완료 /h · 요구량(황색)'});$('experimentResults').innerHTML=table(['대수','반복','완료 평균 ±95% CI /h','종료대기 평균','P95 대기 평균 s','최소 간격 m','교착 반복'],rows.map(r=>[r.n,r.flow.n,r.flow.n?fmt(r.flow.mean,2)+' ± '+fmt(r.flow.ci95,2):'—',r.wait.n?fmt(r.wait.mean):'—',r.p95.n?fmt(r.p95.mean):'—',r.runs.length?fmt(Math.min(...r.runs.map(x=>x.minGap)),4):'—',r.runs.filter(x=>x.gridlock).length]));}
 $('runExperiments').onclick=async()=>{if(!fresh())return;let counts,reps;try{const min=Number($('fleetMin').value),max=Number($('fleetMax').value),step=Number($('fleetStep').value);reps=Number($('repCount').value);if(![min,max,step].every(Number.isInteger)||min<1||max<min||max>result.maxFleet||step<1)throw Error('실험 대수는 1~'+result.maxFleet+' 범위의 정수입니다.');counts=[];for(let n=min;n<=max;n+=step)counts.push(n);if(counts.at(-1)!==max)counts.push(max);if(counts.length*reps>120)throw Error('한 번에 최대 120회 실험입니다.');for(const n of counts)Model.validate({...Model.clone(config),vehicles:n});}catch(e){error(e);return;}stop();const token=++experimentToken;experimentData={schemaVersion:'rgv-loop/experiment@1',version:Model.VERSION,config:Model.clone(config),counts,repetitions:reps,runs:[]};$('runExperiments').disabled=true;$('cancelExperiments').disabled=false;$('exportExperiments').disabled=true;try{for(let r=0;r<reps;r++)for(const n of counts){if(token!==experimentToken)return;const c={...Model.clone(config),vehicles:n,seed:(config.seed+r)>>>0},s=await trial(c,token);if(token!==experimentToken)return;experimentData.runs.push({n,repetition:r+1,seed:c.seed,throughput:s.throughput,shippingRate:s.shippingRate,waiting:s.waiting,p95Wait:s.p95Wait,minGap:s.minGap,conserved:s.conserved,gridlock:s.gridlock});$('experimentProgress').value=experimentData.runs.length/(counts.length*reps)*100;$('experimentStatus').textContent=experimentData.runs.length+' / '+counts.length*reps+'회 완료 · '+n+'대 · seed '+c.seed;$('exportExperiments').disabled=false;renderExperiments();await new Promise(r=>setTimeout(r,0));}if(token===experimentToken){const max=Math.max(...experimentData.runs.map(r=>r.throughput));$('experimentStatus').textContent=experimentData.runs.length+'회 완료 · 범위 내 관측 최대 '+fmt(max)+' '+config.unit+'/h · 수요 수준과 함께 해석하세요.';}}catch(e){if(e.message!=='cancelled')error(e);}finally{if(token===experimentToken){$('runExperiments').disabled=false;$('cancelExperiments').disabled=true;}}};$('cancelExperiments').onclick=cancel;$('exportExperiments').onclick=()=>{if(fresh()&&experimentData)download(filename('_대수실험.json'),JSON.stringify(experimentData,null,2),'application/json;charset=utf-8');};
 function frame(now){const dt=lastFrame?Math.min(.1,(now-lastFrame)/1000):0;lastFrame=now;try{if(simPlaying&&!dirty){simTarget=Math.min(engine.horizon,simTarget+dt*Number($('simSpeed').value));engine.advanceTo(simTarget);if(engine.time>=engine.horizon-1e-7){simPlaying=false;$('simPlay').textContent='▶ 다시 재생';}if(tab==='simulation'&&now-lastRender>150){renderSimulation();lastRender=now;}}
  if(tab==='simulation'&&scene&&!dirty){if(scene.fallback&&$('sceneMode').textContent!=='2D 대체 표시')ensureScene();else scene.update(engine);if(simPlaying)sceneInfo();}if(motionPlaying&&motionProfile&&!dirty){motionTime=Math.min(motionProfile.duration,motionTime+dt*2);updateMotion();if(motionTime>=motionProfile.duration){motionPlaying=false;$('motionPlay').textContent='▶ 다시 재생';}}}catch(e){stop();error(e);}requestAnimationFrame(frame);}
 write(LoopTables.reconcile(draft).config);apply();setTab('overview');setupWorker();requestAnimationFrame(frame);
})();
