(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./motion.js'));else root.LoopModel=factory(root.LoopMotion);})(globalThis,function(M){
  'use strict';
  const VERSION='0.2.2',SCHEMA='rgv-loop/project@1',clone=x=>JSON.parse(JSON.stringify(x)),mod=(x,L)=>((x%L)+L)%L;
  const LIMITS=Object.freeze({stations:200,ods:200,zones:30,profile:48,history:20000,hours:24});
  const defaults={name:'Loop RGV 설계 검토',horizontal:60,vertical:25,radius:1.2,direction:'forward',distanceUnit:'m',speedUnit:'m/min',unit:'PLT',vehicles:8,carLength:1.8,gap:.5,batchSize:1,
    emptyV:2,emptyA:.6,emptyD:.6,loadedV:1.666666666667,loadedA:.5,loadedD:.5,curveV:.75,creepDistance:0,creepV:.15,
    position:.5,interlock:.5,signal:0,control:.3,handlingMode:'total',peak:1.2,targetUtil:.8,A:1,Ew:1,etaMode:'beta',beta:.04,gamma:2,basis:'assumption',basisNote:'예시 β=0.04. 현장 실측으로 검증되지 않은 설계 가정.',analysisMode:'od',
    dispatch:'nearest',parking:'circulate',controlMode:'following',blocks:32,reaction:.2,hours:.5,warmup:3,seed:20260911,arrival:'takt',jitter:.1,timeStep:.1,demandMode:'rate',odTableMode:'paired',periodTableMode:'hourly',profile:[],history:[],zones:[],
    stations:[{id:'P1',name:'입고 1',s:10.652,load:6,unload:6,buffer:8,takeaway:0},{id:'P2',name:'입고 2',s:49.711,load:6,unload:6,buffer:8,takeaway:0},{id:'D1',name:'출고 1',s:97.647,load:6,unload:6,buffer:8,takeaway:0},{id:'D2',name:'출고 2',s:138.091,load:6,unload:6,buffer:8,takeaway:0}],
    ods:[{id:'OD1',from:'P1',to:'D1',rate:30},{id:'OD2',from:'P1',to:'D2',rate:30},{id:'OD3',from:'P2',to:'D1',rate:30},{id:'OD4',from:'P2',to:'D2',rate:30}]};
  const fields={
    horizontal:['수평 직선 길이','distance',.1,2000,1,'한쪽 직선 길이. 전체 외곽 너비는 수평 직선+2×반경입니다.'],vertical:['수직 직선 길이','distance',.1,2000,1,'한쪽 수직 직선 길이입니다.'],radius:['코너 반경','distance',.1,100,1,'4개 90° 곡선의 중심선 반경입니다.'],
    vehicles:['RGV 대수','대',1,64,1,'단일 루프에서 같은 방향으로 운행합니다. 추월하지 않습니다.'],carLength:['차체 길이','distance',.1,10,.1,'레일을 따라 점유하는 차체 길이입니다. 3D 차체 길이에도 적용됩니다.'],gap:['최소 차체 간격','distance',.05,20,.1,'앞 차량 후미와 뒤 차량 전면 사이의 최소 여유입니다.'],batchSize:['1회 최대 적재량','개/회',1,8,1,'OD 수요는 개수/h이며 생성 작업은 완전 배치입니다. CSV 한 행은 이 값 이하의 한 작업입니다.'],
    emptyV:['공차 최대속도','speed',.05,10,.1,'공차 재배치·빈 차량 순환 속도 상한입니다.'],emptyA:['공차 가속도','m/s²',.05,5,.1,'일정 가속도 상한입니다.'],emptyD:['공차 감속도','m/s²',.05,5,.1,'추종·정차·제한속도 진입의 감속 상한입니다.'],loadedV:['적재 최대속도','speed',.05,10,.1,'적재 주행 속도 상한입니다.'],loadedA:['적재 가속도','m/s²',.05,5,.1,'적재 가속도입니다.'],loadedD:['적재 감속도','m/s²',.05,5,.1,'적재 감속도입니다.'],curveV:['곡선 제한속도','speed',.05,10,.1,'모든 코너에 적용하며 직선 사양보다 높게 설정해도 가속시키지 않습니다.'],creepDistance:['정차점 저속 접근','distance',0,20,.1,'목적지 앞 이 거리에서 저속 접근. 0이면 끕니다.'],creepV:['저속 접근 속도','speed',.01,2,.05,'상·하차 정차점에 접근할 때의 제한속도입니다.'],
    position:['정위치','s/이재',0,60,.1,'상·하차 각각 총 시간에 포함됩니다.'],interlock:['인터록','s/이재',0,60,.1,'간편 입력 총 시간에 다시 더하지 않습니다.'],signal:['신호 지연','s/이재',0,60,.1,'상세 모드는 순수 이재+정위치+인터록+신호입니다.'],control:['배차 제어','s/작업',0,60,.1,'상차 위치 도착 후 상차 전에 적용합니다. 주행 중 배차 때문에 즉시 정지시키지 않습니다.'],
    peak:['피크 계수','배',1,5,.1,'OD 수요에 한 번 적용합니다. CSV에는 적용하지 않습니다.'],targetUtil:['목표 부하율','ratio',.1,1,.05,'0.8=80%. 수요/용량 지표로 설계 여유를 비교합니다.'],A:['가용도 A','ratio',.01,1,.01,'분석 차량 능력에만 적용. 시뮬레이션에는 고장 이벤트가 없습니다.'],Ew:['작업효율 E𝑤','ratio',.01,1,.01,'분석에 한 번 적용하며 간섭계수와 손실을 중복하지 않도록 근거를 기록하세요.'],beta:['간섭 β','계수',0,2,.01,'η(N)=1/(1+β(N−1)). 실측이나 설계 가정의 근거를 선택합니다.'],gamma:['간섭 γ','계수',.1,10,.1,'η(N)=(1−N/Nmax)^γ. 경험식이며 Nmax에서 0입니다.'],
    blocks:['고정 블록 수','개',4,256,1,'고정 블록 제어를 선택했을 때 1블록 1차량의 점유·진입 예약을 적용합니다.'],reaction:['추종 추가 여유','s',0,2,.05,'선행차 후미를 정지 장애물로 보는 보수 추종 제어에 속도×시간 여유를 추가합니다.'],hours:['측정 시간','h',.05,LIMITS.hours,.25,'준비운전 이후 측정시간. 시간(h) 단위입니다. 예: 8시간은 8, 30분은 0.5. 최대 24시간이며 계산 규모 한도는 별도 적용됩니다.'],warmup:['준비운전 제외','min',0,120,1,'화물과 상태는 유지하고 측정 통계에서 제외합니다.'],seed:['난수 시드','정수',0,4294967295,1,'같은 입력·버전·시드·시간간격에서 도착과 결과를 재현합니다.'],jitter:['도착 변동폭','ratio',0,.95,.05,'일정간격 도착의 ±변동 비율입니다.'],timeStep:['최대 계산 간격','s',.02,.2,.01,'고정 시간격자 기반 교통·이벤트 결합 모델. 차량 크기·블록·속도에 따라 더 작은 간격을 사용합니다.']};
  function length(c){return 2*c.horizontal+2*c.vertical+2*Math.PI*c.radius;}
  function segments(c){const H=c.horizontal,V=c.vertical,R=c.radius,q=Math.PI*R/2;let at=0;return [H,q,V,q,H,q,V,q].map((size,i)=>{const s={index:i,from:at,to:at+size,length:size,curve:i%2===1};at+=size;return s;});}
  function point(c,s){const H=c.horizontal,V=c.vertical,R=c.radius,L=length(c);s=mod(s,L);const part=segments(c).find(p=>s<p.to)||segments(c).at(-1),u=s-part.from;let x,z,tx,tz;
    if(part.index===0){x=-H/2+u;z=-V/2-R;tx=1;tz=0;}else if(part.index===2){x=H/2+R;z=-V/2+u;tx=0;tz=1;}else if(part.index===4){x=H/2-u;z=V/2+R;tx=-1;tz=0;}else if(part.index===6){x=-H/2-R;z=V/2-u;tx=0;tz=-1;}else{const angle=(part.index-3)*Math.PI/4+u/R,center={1:[H/2,-V/2],3:[H/2,V/2],5:[-H/2,V/2],7:[-H/2,-V/2]}[part.index];x=center[0]+R*Math.cos(angle);z=center[1]+R*Math.sin(angle);tx=-Math.sin(angle);tz=Math.cos(angle);}
    return{x,z,tx,tz,s,segment:part.index};}
  function travelCoord(c,s){return mod((c.direction==='forward'?1:-1)*s,length(c));}
  function physical(c,x){return mod((c.direction==='forward'?1:-1)*x,length(c));}
  function distance(c,from,to){return mod(travelCoord(c,to)-travelCoord(c,from),length(c));}
  function speedZones(c){const L=length(c),raw=[...segments(c).filter(p=>p.curve).map(p=>({from:p.from,to:p.to,v:c.curveV})),...c.zones];return raw.map(z=>c.direction==='forward'?{...z}:{from:L-z.to,to:L-z.from,v:z.v});}
  function profile(c,from,to,loaded,fullLoop=false){const L=length(c),a=travelCoord(c,from),d=fullLoop?L:distance(c,from,to),b=a+d,limits=speedZones(c).flatMap(z=>[0,L].map(k=>({from:z.from+k,to:z.to+k,v:z.v})));if(c.creepDistance>0&&d>0)limits.push({from:Math.max(a,b-c.creepDistance),to:b,v:c.creepV});return M.solve(a,b,{v:loaded?c.loadedV:c.emptyV,a:loaded?c.loadedA:c.emptyA,d:loaded?c.loadedD:c.emptyD},limits);}
  function stepSize(c){const space=c.carLength+c.gap,limit=c.controlMode==='block'?Math.min(space,length(c)/c.blocks):space;return Math.min(c.timeStep,limit/(4*Math.max(c.emptyV,c.loadedV)));}
  function number(v,min,max,name,int=false){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max||(int&&!Number.isInteger(v)))throw Error(name+': '+min+'~'+max+(int?' 정수':' 숫자')+'를 입력하세요.');}
  function validate(input){const c=clone(input);c.odTableMode??='paired';c.periodTableMode??=(c.profile?.length?'manual':'hourly');for(const [key,[label,,min,max]]of Object.entries(fields))number(c[key],min,max,label,['vehicles','batchSize','blocks','seed'].includes(key));const enums={direction:['forward','reverse'],distanceUnit:['m','mm'],speedUnit:['m/min','m/s'],unit:['PLT','BOX','TOTE'],analysisMode:['od','oneLap'],etaMode:['none','beta','power'],basis:['','assumption','measured','vendor'],dispatch:['fifo','nearest'],parking:['circulate','stay'],controlMode:['following','block'],handlingMode:['total','detail'],arrival:['takt','poisson'],demandMode:['rate','history'],odTableMode:['paired','manual'],periodTableMode:['hourly','manual']};for(const[k,values]of Object.entries(enums))if(!values.includes(c[k]))throw Error('지원하지 않는 선택: '+k);
    if(typeof c.name!=='string'||!c.name.trim()||c.name.length>160)throw Error('프로젝트명은 1~160자입니다.');if(typeof c.basisNote!=='string'||c.basisNote.length>500)throw Error('보정 근거는 500자 이내입니다.');const L=length(c),nMax=Math.floor(L/(c.carLength+c.gap));if(c.vehicles>nMax)throw Error('차량 수가 기하학적 수용 한계 '+nMax+'대를 초과합니다.');if(c.controlMode==='block'&&(L/c.blocks<c.carLength+c.gap||c.vehicles>c.blocks))throw Error('고정 블록은 차체+간격 이상 길이, 차량 수 이상 개수가 필요합니다.');
    for(const[k,min,max]of [['stations',1,LIMITS.stations],['ods',0,LIMITS.ods],['zones',0,LIMITS.zones],['profile',0,LIMITS.profile],['history',0,LIMITS.history]])if(!Array.isArray(c[k])||c[k].length<min||c[k].length>max)throw Error(k+' 항목은 '+min+'~'+max+'개입니다.');
    for(const key of ['stations','ods']){const ids=new Set();for(const row of c[key]){if(typeof row.id!=='string'||!/^[A-Za-z0-9_-]{1,30}$/.test(row.id)||ids.has(row.id))throw Error(key+' ID는 중복 없는 영문·숫자·_·-입니다.');ids.add(row.id);}}
    const overhead=c.position+c.interlock+c.signal;for(const s of c.stations){if(typeof s.name!=='string'||s.name.length>80)throw Error('스테이션 이름은 80자 이내입니다.');number(s.s,0,L,'스테이션 위치');if(s.s===L)s.s=0;number(s.load,overhead,600,'총 상차시간');number(s.unload,overhead,600,'총 하차시간');number(s.buffer,c.batchSize,10000,'출고 버퍼',true);number(s.takeaway,0,3600,'반출 간격');}
    const ids=new Set(c.stations.map(s=>s.id));const validOD=o=>{if(!ids.has(o.from)||!ids.has(o.to))throw Error('OD의 출발·도착 ID를 확인하세요.');};for(const o of c.ods){validOD(o);number(o.rate,0,10000,'OD 물동량');}for(const z of c.zones){number(z.from,0,L,'제한구간 시작');number(z.to,0,L,'제한구간 끝');number(z.v,.01,10,'제한속도');if(z.from>=z.to)throw Error('제한구간 끝은 시작보다 커야 합니다. 0점 통과 구간은 두 행으로 나누세요.');}
    const end=c.warmup+c.hours*60;for(const[p,i]of c.profile.map((p,i)=>[p,i])){number(p.start,0,end,'시간대 시작');number(p.end,0,end,'시간대 끝');number(p.multiplier,0,10,'시간대 배율');if(p.start>=p.end||(i&&p.start<c.profile[i-1].end))throw Error('시간대는 겹치지 않는 시작 순서로 입력하세요.');}for(const j of c.history){validOD(j);number(j.time,0,end*60,'작업 도착초');number(j.quantity,1,c.batchSize,'작업 수량',true);}
    for(const o of (c.demandMode==='history'?c.history:c.ods.filter(o=>o.rate>0))){const from=c.stations.find(s=>s.id===o.from),to=c.stations.find(s=>s.id===o.to);if(distance(c,from.s,to.s)<1e-10&&from.load+to.unload+c.control===0)throw Error('동일 위치 OD는 이재 또는 제어시간이 필요합니다.');}
    const expected=c.ods.reduce((s,o)=>s+o.rate,0)*c.peak*(c.profile.length?Math.max(...c.profile.map(p=>p.multiplier)):1)*end/60/c.batchSize;if(c.demandMode==='rate'&&expected>20000)throw Error('예상 작업 20,000회 한도입니다. 수요·운전시간을 줄이세요.');if(end*60/stepSize(c)*c.vehicles>20000000)throw Error('계산 규모 한도입니다. 차량 수·측정시간을 줄이거나 계산 간격을 늘리세요.');return c;}
  function demand(c){if(c.demandMode==='history'){const rows=new Map();for(const j of c.history.filter(j=>j.time>=c.warmup*60&&j.time<=c.warmup*60+c.hours*3600)){const k=j.from+'→'+j.to;const x=rows.get(k)||{id:k,from:j.from,to:j.to,rate:0,missions:0};x.rate+=j.quantity/c.hours;x.missions+=1/c.hours;rows.set(k,x);}return[...rows.values()];}const factor=c.peak*(c.profile.length?Math.max(...c.profile.map(p=>p.multiplier)):1);return c.ods.map(o=>({...o,rate:o.rate*factor,missions:o.rate*factor/c.batchSize}));}
  function eta(c,n,nMax){return c.etaMode==='none'||!c.basis?null:c.etaMode==='beta'?1/(1+c.beta*(n-1)):Math.max(0,1-n/nMax)**c.gamma;}
  function calculate(input){const c=validate(input),L=length(c),ods=demand(c).filter(o=>o.rate>0),total=ods.reduce((s,o)=>s+o.rate,0),missions=ods.reduce((s,o)=>s+o.missions,0),byId=Object.fromEntries(c.stations.map(s=>[s.id,s]));let weighted=0,ld=0,ed=0;
    const legRows=ods.map(o=>{const from=byId[o.from],to=byId[o.to],loaded=profile(c,from.s,to.s,true);let empty=0,emptyDistance=0;for(const prev of ods){const start=byId[prev.to].s,w=prev.missions/missions;empty+=w*profile(c,start,from.s,false).duration;emptyDistance+=w*distance(c,start,from.s);}const cycle=empty+loaded.duration+from.load+to.unload+c.control;if(cycle<=0)throw Error('이동·이재·제어시간이 모두 0인 OD는 계산할 수 없습니다.');weighted+=cycle*o.missions;ld+=loaded.length*o.missions;ed+=emptyDistance*o.missions;return{...o,loadedDistance:loaded.length,emptyDistance,loadedTime:loaded.duration,emptyTime:empty,load:from.load,unload:to.unload,control:c.control,cycle};});
    let cycle=missions?weighted/missions:0,loadedDistance=missions?ld/missions:0,emptyDistance=missions?ed/missions:0;
    if(c.analysisMode==='oneLap'&&missions){let travel=0;for(let i=0;i<24;i++){const a=i*L/24,b=mod(a+L/2,L);travel+=(profile(c,a,b,true).duration+profile(c,b,a,false).duration)/24;}cycle=travel+legRows.reduce((n,o)=>n+(o.load+o.unload+o.control)*o.missions/missions,0);loadedDistance=emptyDistance=L/2;}
    const stations=c.stations.map(s=>{const ins=ods.filter(o=>o.to===s.id),outs=ods.filter(o=>o.from===s.id),work=ins.reduce((n,o)=>n+o.missions*s.unload,0)+outs.reduce((n,o)=>n+o.missions*(s.load+c.control),0),releaseWork=ins.reduce((n,o)=>n+o.rate*s.takeaway,0);return{...s,work,releaseWork,capacity:work?total*3600/work:null,releaseCapacity:releaseWork?total*3600/releaseWork:null};});
    const stationLimit=Math.min(Infinity,...stations.flatMap(s=>[s.capacity,s.releaseCapacity]).filter(x=>x!==null)),nMax=Math.floor(L/(c.carLength+c.gap)),maxFleet=Math.min(64,nMax,c.controlMode==='block'?c.blocks:Infinity),perVehicle=cycle?3600/cycle*(total/missions):0;
    const rows=Array.from({length:maxFleet},(_,i)=>{const n=i+1,f=eta(c,n,nMax),raw=Math.min(n*perVehicle,stationLimit),available=f===null?null:Math.min(n*perVehicle*c.A*c.Ew*f,stationLimit);return{n,eta:f,theory:Number.isFinite(raw)?raw:0,available,ratio:available?total/available:null,shortage:available===null?null:Math.max(0,total-available*c.targetUtil)};});const current=rows[c.vehicles-1],recommended=total&&current.eta!==null?rows.find(r=>r.available>0&&r.shortage<=1e-8)?.n:null;
    const warnings=[];if(!c.basis||c.etaMode==='none')warnings.push('간섭 보정과 근거가 미선택입니다. 무간섭 능력은 참고 상한이며 달성량은 시뮬레이션으로 확인하세요.');else warnings.push('η(N)는 '+({assumption:'설계 가정',measured:'입력된 실측 근거',vendor:'벤더 근거'})[c.basis]+' 경험식입니다. 시뮬레이션 관측값에는 A·Ew·η를 다시 적용하지 않습니다.');
    if(c.vehicles>.3*nMax)warnings.push('차량 수가 정적 수용 한계의 30%를 초과합니다. 30%는 내부 검토 기준이며 규격값이 아닙니다.');if(c.parking==='stay')warnings.push('본선 위치 정차는 후속 차량을 막을 수 있습니다. 유휴 차량이 있어도 정체가 생길 수 있습니다.');warnings.push(c.analysisMode==='oneLap'?'1랩 개략 모델: 균일·독립 위치 가정으로 평균 적재 0.5랩+공차 0.5랩을 사용합니다.':'실제 OD 분석: 이전 도착지와 다음 출발지의 독립 혼합으로 공차를 근사합니다. 최근접 배차의 1/N 단축식은 사용하지 않습니다.');if(total===0)warnings.push('수요가 없어 현재 OD 혼합의 처리능력을 미평가(0)로 표시합니다.');
    return{config:c,version:VERSION,kernelVersion:M.VERSION,hash:hash(c),L,nMax,maxFleet,total,missions,cycle,loadedDistance,emptyDistance,legRows,stations,stationLimit:Number.isFinite(stationLimit)?stationLimit:0,rows,current,recommended:recommended??null,warnings,dt:stepSize(c)};}
  function hash(c){let h=2166136261;for(const ch of JSON.stringify(c)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
  function pack(c){return{schemaVersion:SCHEMA,deviceType:'rgv_loop',moduleVersion:VERSION,kernelVersion:M.VERSION,units:{distance:'m',speed:'m/s',time:'s',acceleration:'m/s²'},config:validate(c)};}
  function unpack(doc){if(doc?.schemaVersion!==SCHEMA||doc.deviceType!=='rgv_loop'||doc.moduleVersion?.split('.')[0]!=='0')throw Error('지원하는 Loop RGV 프로젝트 JSON을 선택하세요.');if(doc.units?.distance!=='m'||doc.units?.speed!=='m/s'||doc.units?.acceleration!=='m/s²'||doc.units?.time!=='s')throw Error('프로젝트 내부 SI 단위를 확인하세요.');return validate(doc.config);}
  function preset(name){const c=clone(defaults);if(name==='single'){c.name='Loop 1대 · 단일 OD';c.vehicles=1;c.ods=c.ods.slice(0,1);c.ods[0].rate=120;}if(name==='congested'){c.name='다차량 · 출고 버퍼 정체';c.vehicles=16;c.stations[2].takeaway=60;c.stations[2].buffer=2;c.ods=[{id:'OD1',from:'P1',to:'D1',rate:240}];}if(name==='block'){c.name='고정 블록 제어';c.controlMode='block';c.blocks=24;}if(name==='history'){c.name='Loop 작업이력 예제';c.warmup=0;c.demandMode='history';c.history=[{time:0,from:'P1',to:'D1',quantity:1},{time:20,from:'P2',to:'D2',quantity:1},{time:100,from:'D2',to:'P1',quantity:1}];}return c;}
  return{VERSION,SCHEMA,LIMITS,defaults,fields,clone,mod,length,segments,point,physical,travelCoord,distance,speedZones,profile,stepSize,validate,demand,eta,calculate,hash,pack,unpack,preset};
});
