(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./model.js'),require('./engine.js'));else root.LoopView=factory(root.LoopModel,root.LoopEngine);})(globalThis,function(Model,E){
 'use strict';const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,n=1)=>v===null||!Number.isFinite(v)?'—':v.toLocaleString('ko-KR',{minimumFractionDigits:n,maximumFractionDigits:n});
 const colors={idle:'#b7c8d1',circulate:'#7899a9',empty:'#709db4',loaded:'#169c8d',following:'#d4a34e',block:'#cb815a',control:'#b69c67',load:'#5688ca',unload:'#927bbd',output:'#cc6b53',dock:'#c09555'};
 const table=(heads,rows)=>'<div class="table-scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 const kpi=(label,value,unit,note,featured=false)=>'<article class="kpi '+(featured?'featured':'')+'"><div class="kpi-label">'+esc(label)+'</div><div class="kpi-value">'+esc(value)+'<small>'+esc(unit)+'</small></div><p>'+esc(note)+'</p></article>';
 function layout(c,s=null){const W=1080,H=450,scale=Math.min(870/(c.horizontal+2*c.radius+8),300/(c.vertical+2*c.radius+8)),px=x=>W/2+x*scale,pz=z=>H/2+z*scale,L=Model.length(c);const path=Array.from({length:401},(_,i)=>Model.point(c,L*i/400)).map((p,i)=>(i?'L':'M')+px(p.x).toFixed(2)+' '+pz(p.z).toFixed(2)).join(' ');let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="Loop RGV 순환 레일·차량 배치"><rect width="1080" height="450" rx="10" fill="#122a3a"/><path d="'+path+' Z" fill="none" stroke="#7395a5" stroke-width="7"/>';
 for(const part of Model.segments(c).filter(p=>p.curve)){const points=Array.from({length:15},(_,i)=>Model.point(c,part.from+part.length*i/14));svg+='<path d="'+points.map((p,i)=>(i?'L':'M')+px(p.x)+' '+pz(p.z)).join(' ')+'" fill="none" stroke="#d8aa5c" stroke-width="7"/>';}
 const labelBoxes=[],compact=c.stations.length>30;let hiddenNames=0;
 for(const st of c.stations){
  const p=Model.point(c,st.s),x=px(p.x+p.tz*3),z=pz(p.z-p.tx*3),size=compact?8:24,title=st.id+' · '+st.name+' / s '+fmt(st.s,3)+' m';
  svg+='<g data-station="'+esc(st.id)+'"><title>'+esc(title)+'</title><path d="M'+px(p.x)+' '+pz(p.z)+' L'+x+' '+z+'" stroke="#7aabac"/><rect x="'+(x-size/2)+'" y="'+(z-(compact?4:9))+'" width="'+size+'" height="'+(compact?8:18)+'" rx="2" fill="#5ccab5"/>';
  const vertical=compact&&Math.abs(p.tz)>.8,text=st.id+' · '+st.name,anchor=vertical?(p.tz>0?'start':'end'):'middle',tx=x+(vertical?(p.tz>0?10:-10):0),ty=z+(vertical?4:p.tx>=0?-17:26),width=[...text].reduce((n,ch)=>n+(ch.charCodeAt(0)>255?13:7),0),left=tx-(anchor==='middle'?width/2:anchor==='end'?width:0),box={x:left,y:ty-13,w:width,h:17};
  const overlaps=compact&&(left<15||left+width>W-15||ty<55||ty>H-35||labelBoxes.some(b=>box.x<b.x+b.w+7&&box.x+box.w+7>b.x&&box.y<b.y+b.h+5&&box.y+box.h+5>b.y));
  if(!overlaps){labelBoxes.push(box);svg+='<text data-station-label="'+esc(st.id)+'" x="'+tx+'" y="'+ty+'" text-anchor="'+anchor+'" fill="#c6e3e4" font-size="13">'+esc(text)+'</text>';}else hiddenNames++;
  svg+='</g>';
 }
 if(hiddenNames)svg+='<text x="30" y="430" fill="#94b4c4" font-size="12">스테이션 '+c.stations.length+'개 · 겹치는 이름은 생략했습니다. 각 지점에 마우스를 올리면 ID·위치를 확인할 수 있습니다.</text>';
 const cars=s?.cars||Array.from({length:c.vehicles},(_,i)=>({...Model.point(c,Model.physical(c,i*L/c.vehicles)),id:'RGV'+String(i+1).padStart(2,'0'),state:'idle'}));for(const car of cars){const color=colors[car.state]||'#60d7bd';svg+='<g transform="translate('+px(car.x)+' '+pz(car.z)+') rotate('+Math.atan2(car.tz,car.tx)*180/Math.PI+')"><rect x="-12" y="-8" width="24" height="16" rx="3" fill="'+color+'"/>'+(car.loaded?'<rect x="-7" y="-5" width="14" height="10" fill="#e5c281"/>':'')+'</g>';}
 const p=Model.point(c,0),sign=c.direction==='forward'?1:-1;svg+='<path d="M'+(px(p.x)+25*sign)+' '+(pz(p.z)+23)+' h'+(55*sign)+' m'+(-9*sign)+' -5 l'+(9*sign)+' 5 l'+(-9*sign)+' 5" fill="none" stroke="#76d6c3" stroke-width="2"/><text x="30" y="30" fill="#b4d1da" font-size="13">'+c.vehicles+' RGV · '+fmt(L,2)+' m · '+(sign>0?'+s':'−s')+' 순환</text>';return svg+'</svg>';}
 function line(series,{xMax=1,yLabel='',xLabel='시간',height=240}={}){const W=1020,l=65,r=25,t=25,b=45,values=series.flatMap(s=>s.points.map(p=>p.y)).filter(Number.isFinite),low=Math.min(0,...values),high=Math.max(1,...values),px=x=>l+x/Math.max(xMax,1e-9)*(W-l-r),py=y=>height-b-(y-low)/(high-low)*(height-t-b);let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1020 '+height+'" role="img" aria-label="'+esc(yLabel)+'"><rect width="100%" height="100%" fill="white"/>';for(let i=0;i<=4;i++){const v=low+(high-low)*i/4,y=py(v);svg+='<path d="M'+l+' '+y+' H'+(W-r)+'" stroke="#e4ebee"/><text x="'+(l-10)+'" y="'+(y+4)+'" text-anchor="end" font-size="11" fill="#78929e">'+fmt(v)+'</text>';}for(let i=0;i<=5;i++)svg+='<text x="'+px(xMax*i/5)+'" y="'+(height-22)+'" text-anchor="middle" font-size="11" fill="#78929e">'+fmt(xMax*i/5)+'</text>';for(const s of series){const pts=s.points.filter(p=>Number.isFinite(p.y));svg+='<path d="'+pts.map((p,i)=>(i?'L':'M')+px(p.x).toFixed(2)+' '+py(p.y).toFixed(2)).join(' ')+'" fill="none" stroke="'+s.color+'" stroke-width="2.3"/>';for(const p of pts)if(s.dots)svg+='<circle cx="'+px(p.x)+'" cy="'+py(p.y)+'" r="3" fill="'+s.color+'"/>'; }return svg+'<text x="'+l+'" y="15" font-size="12" fill="#647f8b">'+esc(yLabel)+'</text><text x="'+(W-r)+'" y="'+(height-2)+'" text-anchor="end" font-size="11" fill="#647f8b">'+esc(xLabel)+'</text></svg>';}
 function motion(c,from,to,loaded){const p=Model.profile(c,from,to,loaded),points=Array.from({length:501},(_,i)=>{const t=p.duration*i/500,s=(typeof LoopMotion!=='undefined'?LoopMotion:require('./motion.js')).at(p,t);return{t,...s};}),factor=c.speedUnit==='m/min'?60:1;return{profile:p,speed:line([{color:'#129a8b',points:points.map(s=>({x:s.t,y:s.v*factor}))}],{xMax:p.duration,xLabel:'시간 s',yLabel:'속도 '+c.speedUnit}),position:line([{color:'#608fac',points:points.map(s=>({x:s.t,y:s.x-p.from}))}],{xMax:p.duration,xLabel:'시간 s',yLabel:'이동거리 m'}),acceleration:line([{color:'#ae9056',points:points.map(s=>({x:s.t,y:s.a}))}],{xMax:p.duration,xLabel:'시간 s',yLabel:'가속도 m/s²'})};}
 return{esc,fmt,table,kpi,colors,layout,line,motion};
});
