'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.AGV_PLAYWRIGHT_PATH||'playwright'),base=path.resolve(__dirname,'..'),qa=path.join(base,'qa'),url=pathToFileURL(path.resolve(base,'../AGV_AMR_실행.html')).href,checks=[],errors=[],requests=[];
function compressedWorkbook(input){const zlib=require('node:zlib'),files=[],central=[];let pos=0,offset=0,total=0;while(input.readUInt32LE(pos)===0x04034b50){const size=input.readUInt32LE(pos+18),nameLen=input.readUInt16LE(pos+26),extraLen=input.readUInt16LE(pos+28),name=input.subarray(pos+30,pos+30+nameLen),body=input.subarray(pos+30+nameLen+extraLen,pos+30+nameLen+extraLen+size),data=zlib.deflateRawSync(body),crc=input.readUInt32LE(pos+14),local=Buffer.alloc(30+nameLen);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x800,6);local.writeUInt16LE(8,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(body.length,22);local.writeUInt16LE(nameLen,26);name.copy(local,30);files.push(local,data);const c=Buffer.alloc(46+nameLen);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(8,10);c.writeUInt32LE(crc,16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(body.length,24);c.writeUInt16LE(nameLen,28);c.writeUInt32LE(offset,42);name.copy(c,46);central.push(c);offset+=local.length+data.length;total+=c.length;pos+=30+nameLen+extraLen+size;}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(central.length,8);end.writeUInt16LE(central.length,10);end.writeUInt32LE(total,12);end.writeUInt32LE(offset,16);return Buffer.concat([...files,...central,end]);}
let browser,page;async function test(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function tab(name){await page.locator('[data-tab="'+name+'"]').click();}
async function finish(){await page.waitForFunction(()=>document.getElementById('simStatus').textContent==='계산 완료 · 기록 재생',{},{timeout:30000});}
async function field(key,value){const el=page.locator('[data-key="'+key+'"]');await el.evaluate(e=>{const d=e.closest('details');if(d)d.open=true;});await el.fill(String(value));await el.dispatchEvent('change');}
async function getDownload(id){const wait=page.waitForEvent('download');await page.locator('#'+id).click();const d=await wait,stream=await d.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);return {name:d.suggestedFilename(),bytes:Buffer.concat(chunks)};}
async function range(id,value){await page.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(value));}
(async()=>{browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(url);await finish();
await test('offline file:// launch / Worker / KPI / no external requests',async()=>{assert.equal(await page.locator('#overviewKpis .kpi').count(),4);assert.equal(await page.locator('body').getAttribute('data-dirty'),'false');assert.equal(await page.locator('#error').isVisible(),false);assert.equal(requests.length,0);await page.screenshot({path:path.join(qa,'01_overview.png'),fullPage:false});});
await test('WebGL 3D canvas and vehicles render',async()=>{assert.equal(await page.locator('#scene').getAttribute('data-renderer'),'webgl');assert.equal(await page.locator('#scene > canvas').count(),1);assert.equal(await page.locator('#vehicleList .vehicle-row').count(),4);await page.locator('.scene-card').screenshot({path:path.join(qa,'02_simulation.png')});});
await test('replay step / forward / backward seek restores pose and KPI',async()=>{await page.locator('#simStep').click();assert.ok(Number(await page.locator('#replayClock').getAttribute('data-time'))>0);await range('simSeek',200);const pose=await page.locator('#vehicleDetail').textContent(),count=await page.locator('#sceneCount').textContent();await range('simSeek',1600);await range('simSeek',200);assert.equal(await page.locator('#vehicleDetail').textContent(),pose);assert.equal(await page.locator('#sceneCount').textContent(),count);});
await test('play/pause and speed independent of full result',async()=>{const hash=await page.locator('body').getAttribute('data-config-hash'),kpis=await page.locator('#overviewKpis').textContent();await page.locator('#simSpeed').selectOption('20');await page.locator('#simPlay').click();await page.waitForTimeout(450);await page.locator('#simPlay').click();const t=await page.locator('#replayClock').getAttribute('data-time');assert.ok(Number(t)>200);await page.waitForTimeout(250);assert.equal(await page.locator('#replayClock').getAttribute('data-time'),t);assert.equal(await page.locator('#overviewKpis').textContent(),kpis);assert.equal(await page.locator('body').getAttribute('data-config-hash'),hash);});
await test('camera / actor selection / 2D fallback switch',async()=>{await page.locator('[data-camera="top"]').click();await page.locator('#vehicleList [data-vehicle="V2"]').click();assert.equal(await page.locator('#vehicleDetail').getAttribute('data-vehicle'),'V2');await page.locator('#followVehicle').check();await page.locator('#showEnvelope').check();await page.locator('#toggle2D').click();assert.equal(await page.locator('#sceneFallback svg').count(),1);await page.locator('#toggle2D').click();await page.locator('#followVehicle').uncheck();await page.locator('[data-camera="iso"]').click();});
await test('3D capture PNG includes report context',async()=>{const d=await getDownload('captureScene');assert.equal(d.bytes.readUInt32BE(0),0x89504E47);fs.writeFileSync(path.join(qa,'03_capture.png'),d.bytes);});
await test('JSON export/import preview roundtrip',async()=>{const d=await getDownload('saveProject'),parsed=JSON.parse(d.bytes);assert.equal(parsed.config.vehicle.loadedV,1.2);await page.locator('#projectFile').setInputFiles({name:'project.json',mimeType:'application/json',buffer:d.bytes});await page.locator('#importDialog').waitFor({state:'visible'});assert.ok((await page.locator('#importPreview').textContent()).includes('오류 0건'));await page.locator('#confirmImport').click();await finish();assert.equal(await page.locator('body').getAttribute('data-config-hash'),parsed.configHash);});
await test('native XLSX export/import previews all scenario tables',async()=>{const hash=await page.locator('body').getAttribute('data-config-hash'),d=await getDownload('saveWorkbook');assert.equal(d.bytes.readUInt32LE(0),0x04034b50);fs.writeFileSync(path.join(qa,'browser-roundtrip.xlsx'),d.bytes);await page.locator('#projectFile').setInputFiles({name:'roundtrip.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:d.bytes});await page.locator('#importDialog').waitFor({state:'visible',timeout:15000});await page.locator('#confirmImport').click();await finish();assert.equal(await page.locator('body').getAttribute('data-config-hash'),hash);});
await test('deflate-compressed XLSX import and CRC verification',async()=>{const hash=await page.locator('body').getAttribute('data-config-hash'),compressed=compressedWorkbook(fs.readFileSync(path.join(qa,'browser-roundtrip.xlsx')));await page.locator('#projectFile').setInputFiles({name:'compressed.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:compressed});await page.locator('#importDialog').waitFor({state:'visible',timeout:15000});await page.locator('#confirmImport').click();await finish();assert.equal(await page.locator('body').getAttribute('data-config-hash'),hash);});
await test('invalid import does not overwrite existing settings',async()=>{const hash=await page.locator('body').getAttribute('data-config-hash');await page.locator('#projectFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":"bad"}')});await page.locator('#error').waitFor({state:'visible'});assert.equal(await page.locator('body').getAttribute('data-config-hash'),hash);});
await test('overweight input blocks calculation / stale results guard',async()=>{await tab('demand');const el=page.locator('[data-table="od"][data-row="0"][data-field="weight"]');await el.fill('2000');await el.dispatchEvent('change');assert.equal(await page.locator('#stale').isVisible(),true);await page.locator('#calculate').click();assert.ok((await page.locator('#error').textContent()).includes('총하중'));await el.fill('500');await el.dispatchEvent('change');await page.locator('#calculate').click();await finish();});
await test('exports cannot mix new inputs with a previous run while Worker calculates',async()=>{await tab('report');await page.evaluate(()=>{window.originalQAWorker=window.Worker;window.Worker=class extends window.Worker{postMessage(message,...rest){if(message.type==='run')setTimeout(()=>super.postMessage(message,...rest),1500);else super.postMessage(message,...rest);}};});await field('demandFactor',1.1);await page.locator('#calculate').click();await page.locator('#exportReport').click();assert.ok((await page.locator('#toast').textContent()).includes('계산이 진행 중'));assert.equal(await page.locator('#stale').isVisible(),true);await finish();await page.evaluate(()=>{window.Worker=window.originalQAWorker;delete window.originalQAWorker;});await field('demandFactor',1);await page.locator('#calculate').click();await finish();});
await test('2D layout node editing updates validated dimensions',async()=>{await tab('layout');const el=page.locator('[data-table="nodes"][data-field="x"][aria-label="P1 X mm"]');await el.fill('-8000');await el.dispatchEvent('change');await page.locator('#calculate').click();await finish();const d=await getDownload('saveProject');assert.equal(JSON.parse(d.bytes).config.nodes.find(n=>n.id==='P1').x,-8);await page.screenshot({path:path.join(qa,'04_layout.png'),fullPage:false});});
await test('2D pointer drag changes node coordinates on a 250mm grid',async()=>{const circle=page.locator('#layoutCanvas [data-node="P1"] circle');await circle.scrollIntoViewIfNeeded();const box=await circle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-20,box.y+box.height/2,{steps:8});await page.mouse.up();const value=Number(await page.locator('[data-table="nodes"][aria-label="P1 X mm"]').inputValue());assert.notEqual(value,-8000);assert.equal(Math.abs(value%250),0);assert.equal(await page.locator('body').getAttribute('data-dirty'),'true');await page.locator('#calculate').click();await finish();});
await test('motion chart uses plan golden timing',async()=>{await tab('analysis');assert.ok((await page.locator('#motionSummary').textContent()).includes('42.571428571'));await page.locator('#motionDistance').fill('2000');await page.locator('#motionCalculate').click();assert.ok((await page.locator('#motionSummary').textContent()).includes('3.703280399'));await page.screenshot({path:path.join(qa,'05_analysis.png'),fullPage:false});});
await test('fleet sweep calculates real alternative results',async()=>{await tab('experiments');await page.locator('#sweepMin').fill('2');await page.locator('#sweepMax').fill('3');await page.locator('#sweepHours').fill('1');await page.locator('#runSweep').click();await page.waitForFunction(()=>!document.getElementById('runSweep').disabled&&document.querySelectorAll('#sweepTable tbody tr').length===2,{},{timeout:60000});assert.ok((await page.locator('#sweepStatus').textContent()).includes('탐색 범위'));await page.screenshot({path:path.join(qa,'06_experiments.png'),fullPage:false});});
await test('report / jobs / replay exports carry reproducible result',async()=>{await tab('report');const report=await getDownload('exportReport');assert.ok(report.bytes.toString('utf8').includes('종료 백로그'));assert.ok(report.bytes.toString('utf8').includes('재현 입력'));const jobs=await getDownload('exportJobs');assert.ok(jobs.bytes.toString('utf8').includes('completed_s'));const replay=await getDownload('exportRun'),data=JSON.parse(replay.bytes);assert.equal(data.schemaVersion,'agv-amr/run@1');assert.equal(data.audit.ok,true);fs.writeFileSync(path.join(qa,'browser-report.md'),report.bytes);});
await test('zero-demand preset renders no misleading zero-second P95',async()=>{await page.locator('#preset').selectOption('zero');await page.locator('#applyPreset').click();await finish();await tab('simulation');const values=await page.locator('#overviewKpis .kpi-value').allTextContents();assert.ok(values[0].startsWith('0'));assert.ok(values[2].includes('—'));assert.ok((await page.locator('#resultVerdict').textContent()).includes('평가 수요 없음'));});
await test('responsive 390px layout has no horizontal page overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:path.join(qa,'07_mobile.png'),fullPage:true});});
await test('no browser runtime errors',async()=>assert.deepEqual(errors,[]));
await test('WebGL unavailable falls back to replayable 2D',async()=>{const fallbackBrowser=await chromium.launch({channel:'msedge',headless:true,args:['--disable-webgl','--disable-3d-apis']});try{const fallbackPage=await fallbackBrowser.newPage({viewport:{width:1400,height:1000}});await fallbackPage.goto(url);await fallbackPage.waitForFunction(()=>document.getElementById('simStatus').textContent==='계산 완료 · 기록 재생');assert.equal(await fallbackPage.locator('#scene').getAttribute('data-renderer'),'2d');assert.equal(await fallbackPage.locator('#sceneFallback svg').count(),1);await fallbackPage.locator('#simStep').click();assert.ok(Number(await fallbackPage.locator('#replayClock').getAttribute('data-time'))>0);await fallbackPage.screenshot({path:path.join(qa,'11_no_webgl.png'),fullPage:false});}finally{await fallbackBrowser.close();}});
await page.setViewportSize({width:1600,height:1100});await page.locator('#preset').selectOption('standard');await page.locator('#applyPreset').click();await finish();await range('simSeek',180);await page.screenshot({path:path.join(qa,'08_final.png'),fullPage:false});fs.writeFileSync(path.join(qa,'browser-check.json'),JSON.stringify({passed:checks.length,checks,errors,requests,browser:await browser.version(),fileUrl:url},null,2));console.log('\n'+checks.length+' browser checks passed.');await browser.close();
})().catch(async e=>{console.error(e.stack);if(page)await page.screenshot({path:path.join(qa,'browser-failure.png'),fullPage:true}).catch(()=>{});if(browser)await browser.close();process.exitCode=1;});
